// Generated by @canonical/summon-component:svelte v0.1.0

import type { Snippet } from "svelte";
import type { SvelteHTMLElements } from "svelte/elements";

/*
	For components that render specific HTML elements with extended prop sets,
	make sure to change `"div"` to the appropriate HTML element type.
*/
type BaseProps = SvelteHTMLElements["div"];

export interface ExampleProps extends BaseProps {
  /** Content to render inside the component */
  children?: Snippet;
  // Define additional props specific to Example here
}

/*
	...or consider using appropriate interfaces directly exported from `svelte/elements`.

	For example:
	- `HTMLButtonAttributes` (provides `disabled`, `type`, etc.)
	- `HTMLAnchorAttributes` (provides `href`, `target`, etc.)
	- `HTMLInputAttributes` (provides `type`, `checked`, `value`, etc.)
	- `HTMLFormAttributes` (provides `action`, `method`, etc.)

	```typescript
	import type { HTMLButtonAttributes } from "svelte/elements";

	export interface MyButtonProps extends HTMLButtonAttributes {
		// Your custom props here
	}
	```

	See Svelte documentation on typing wrapper components:
	https://svelte.dev/docs/svelte/typescript#Typing-wrapper-components
*/
