// Generated by @canonical/summon-component:react v0.1.0

import type { Meta, StoryObj } from "@storybook/react-vite";
import JourneyWell from "./JourneyWell.js";

const meta: Meta<typeof JourneyWell> = {
  title: "Components/JourneyWell",
  component: JourneyWell,
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof JourneyWell>;

export const Default: Story = {
  args: {
    children: "Hello, JourneyWell!",
  },
};

export const WithCustomClass: Story = {
  args: {
    children: "Custom styled",
    className: "custom-class",
  },
};
