// Generated by @canonical/summon-component:react v0.1.0

import type React from "react";
import type { JourneyWellProps } from "./types.js";
import "./styles.css";

const componentCssClassName = "ds journey-well";

/**
 * JourneyWell component
 */
const JourneyWell = ({
  className,
  children,
  ...props
}: JourneyWellProps): React.ReactElement => {
  return (
    <div
      className={[componentCssClassName, className].filter(Boolean).join(" ")}
      {...props}
    >
      {children}
    </div>
  );
};

export default JourneyWell;
