// Generated by @canonical/summon-component:react v0.1.0

import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import JourneyWell from "./JourneyWell.js";

describe("JourneyWell", () => {
  it("renders children", () => {
    render(<JourneyWell>Test content</JourneyWell>);
    expect(screen.getByText("Test content")).toBeInTheDocument();
  });

  it("applies custom className", () => {
    render(<JourneyWell className="custom-class">Content</JourneyWell>);
    const element = screen.getByText("Content");
    expect(element.className).toContain("ds journey-well");
    expect(element.className).toContain("custom-class");
  });

  it("passes through additional props", () => {
    render(<JourneyWell data-testid="test-component">Content</JourneyWell>);
    expect(screen.getByTestId("test-component")).toBeInTheDocument();
  });
});
