<!-- Generated by @canonical/summon-component:svelte v0.1.0 -->

<script lang="ts" module>
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import Rule from "./Rule.svelte";

  const { Story } = defineMeta({
    title: "_work_in_progress/Components/Rule",
    component: Rule,
    tags: ["autodocs"],
    parameters: {
      // Svelte 5 Storybook autodocs do not currently pick up component docs from
      // the component source reliably, so we inject the description here instead:
      // https://github.com/storybookjs/storybook/discussions/34104#discussioncomment-16084065
      docs: {
        description: {
          component:
            "A component that separates content into logical groups. @TODO implement fixed-width behavior after implementation of the Grid @implements ds:sites.component.rule",
        },
      },
    },
  });
</script>

<Story name="Default">Basic Rule</Story>
