<!-- Generated by @canonical/summon-component:svelte v0.1.0 -->

<script lang="ts">
  import type { RuleProps } from "./types.js";
  import "./styles.css";

  const componentCssClassName = "ds rule";

  let { class: className, ...rest }: RuleProps = $props();
</script>

<hr class={[componentCssClassName, className]} {...rest} />

<!-- @component
	A component that separates content into logical groups.

	@TODO implement fixed-width behavior after implementation of the Grid
	@implements ds:sites.component.rule
-->
