<!-- Generated by @canonical/summon-component:svelte v0.29.0-experimental.0 -->

<script lang="ts" module>
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import Example from "./Example.svelte";

  const { Story } = defineMeta({
    title: "Components/Example",
    component: Example,
    tags: ["autodocs"],
    parameters: {
      // This is an example component, no need for it to be snapshotted.
      chromatic: { disableSnapshot: true },
    },
  });
</script>

<Story name="Default">
	Hello, Example!
</Story>

<Story
  name="WithCustomStyle"
  args={{
    class: "custom-style",
    id: "custom-id",
    style: "background-color: tomato;",
  }}
>
	Custom styled
</Story>
