// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import { describe, expect, it } from "vitest";
import { renderToString } from "react-dom/server";
import Section from "./Section.js";

describe("Section SSR", () => {
	it("renders without hydration errors", () => {
		const html = renderToString(<Section>Test content</Section>);
		expect(html).toContain("Test content");
		expect(html).toContain("ds section");
	});
});
