/**
 * PROTECTED — the permanent seam contract: every `create` tree is produced TWO
 * ways and diffed byte-for-byte (path set + contents, incl. the "Generated by"
 * stamp): (1) `pragma create <verb> --yes` through the kernel dispatcher, and
 * (2) summon-core `execute` with `autoPrompt`, run through `runGeneratorTask` +
 * the shared stamp — the summon bin's path. They match because both derive the
 * StampConfig from `createGeneratorStamp` (displayName + version) and run the
 * SAME `generator.generate` with the SAME answers.
 *
 * Five generators are covered: component × {react, svelte, lit}, package, and
 * application. A cross-binary subprocess guard lives in byteEquality.subprocess.test.ts.
 */

import { mkdtempSync, readdirSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { executeVerb } from "../../kernel/project/cli/dispatch.js";
import { bootRuntime } from "../../kernel/runtime/boot.js";
import type { GlobalFlags } from "../../kernel/runtime/types.js";
import type { VerbSpec } from "../../kernel/spec/types.js";
import {
  createApplicationVerb,
  createComponentVerb,
  createPackageVerb,
} from "./create.verb.js";
import type { CreateKind } from "./types.js";

const FLAGS: GlobalFlags = {
  llm: false,
  autoLlm: false,
  format: "plain",
  verbose: false,
};
const freshCwd = (): string => mkdtempSync(join(tmpdir(), "pragma-golden-"));

/** Read a directory tree into a sorted map of relative path → contents. */
function snapshot(dir: string): Map<string, string> {
  const out = new Map<string, string>();
  const walk = (d: string, base: string): void => {
    for (const entry of readdirSync(d, { withFileTypes: true }).sort((a, b) =>
      a.name.localeCompare(b.name),
    )) {
      const rel = base ? `${base}/${entry.name}` : entry.name;
      if (entry.isDirectory()) walk(join(d, entry.name), rel);
      else out.set(rel, readFileSync(join(d, entry.name), "utf-8"));
    }
  };
  walk(dir, "");
  return out;
}

const verbFor: Record<CreateKind, VerbSpec> = {
  component: createComponentVerb as VerbSpec,
  package: createPackageVerb as VerbSpec,
  application: createApplicationVerb as VerbSpec,
};

/** Producer (1): the full pragma kernel path — dispatcher runs the create verb. */
async function producePragma(
  kind: CreateKind,
  params: Record<string, unknown>,
): Promise<Map<string, string>> {
  const dir = freshCwd();
  const prev = process.cwd();
  process.chdir(dir);
  try {
    const outcome = await executeVerb(
      verbFor[kind],
      params,
      { dryRun: false, undo: false, yes: true },
      bootRuntime(FLAGS, dir),
    );
    expect(outcome.exitCode).toBe(0);
  } finally {
    process.chdir(prev);
  }
  return snapshot(dir);
}

/** Producer (2): summon-core execute + autoPrompt + the shared stamp core. */
async function produceSummon(
  kind: CreateKind,
  framework: string,
  answers: Record<string, unknown>,
): Promise<Map<string, string>> {
  const { pickGenerator } = await import("./pickGenerator.js");
  const {
    execute,
    autoPrompt,
    runGeneratorTask,
    createGeneratorStamp,
    createStampOnEffectStart,
  } = await import("@canonical/summon-core");
  const generator = pickGenerator(kind, { framework });
  const dir = freshCwd();
  await runGeneratorTask(
    execute(generator, { prompt: autoPrompt(answers), params: answers }),
    {
      cwd: dir,
      promptHandler: autoPrompt(answers),
      onEffectStart: createStampOnEffectStart(createGeneratorStamp(generator)),
      onLog: () => {},
    },
  );
  return snapshot(dir);
}

/** One golden case: the create-verb params, and the equivalent summon answers. */
interface Case {
  readonly name: string;
  readonly kind: CreateKind;
  readonly framework: string;
  readonly params: Record<string, unknown>;
  readonly answers: Record<string, unknown>;
}

const componentAnswers = {
  withStyles: true,
  withStories: true,
  withSsrTests: false,
};

const cases: Case[] = [
  {
    name: "component/react",
    kind: "component",
    framework: "react",
    params: {
      framework: "react",
      componentPath: "src/components/Button",
      ...componentAnswers,
    },
    answers: { componentPath: "src/components/Button", ...componentAnswers },
  },
  {
    name: "component/svelte",
    kind: "component",
    framework: "svelte",
    params: {
      framework: "svelte",
      componentPath: "src/lib/Button",
      ...componentAnswers,
    },
    answers: { componentPath: "src/lib/Button", ...componentAnswers },
  },
  {
    name: "component/lit",
    kind: "component",
    framework: "lit",
    params: {
      framework: "lit",
      componentPath: "src/lib/Button",
      ...componentAnswers,
    },
    answers: { componentPath: "src/lib/Button", ...componentAnswers },
  },
  {
    name: "package",
    kind: "package",
    framework: "",
    params: {
      name: "@canonical/my-lib",
      type: "library",
      description: "A library.",
      withReact: false,
      withStorybook: false,
      withCli: false,
      withPrTemplate: false,
      runInstall: false,
    },
    answers: {
      name: "@canonical/my-lib",
      type: "library",
      description: "A library.",
      withReact: false,
      withStorybook: false,
      withCli: false,
      withPrTemplate: false,
      runInstall: false,
    },
  },
  {
    name: "application",
    kind: "application",
    framework: "",
    // The pragma path receives the CLI `--with-X` params (AV-228 B8); the summon
    // path receives the generator's bare prompt names. runCreate's boundary remap
    // (`withSsr` -> `ssr`, ...) makes both produce the byte-identical tree.
    params: {
      appPath: "my-app",
      withSsr: true,
      withRouter: true,
      withForms: true,
      relay: false,
      runInstall: false,
    },
    answers: {
      appPath: "my-app",
      ssr: true,
      router: true,
      forms: true,
      relay: false,
      runInstall: false,
    },
  },
];

describe("byte-equality goldens — pragma create ≡ summon execute (PROTECTED)", () => {
  for (const testCase of cases) {
    it(`${testCase.name}: both producers write byte-identical trees`, async () => {
      const pragma = await producePragma(testCase.kind, testCase.params);
      const summon = await produceSummon(
        testCase.kind,
        testCase.framework,
        testCase.answers,
      );
      expect(pragma.size).toBeGreaterThan(0);
      expect([...pragma.keys()].sort()).toEqual([...summon.keys()].sort());
      for (const [path, content] of pragma) {
        expect(summon.get(path), `content of ${path}`).toBe(content);
      }
    });
  }
});
