/**
 * `create` behaviour: real generation + stamp, the SEC-2 path jail, the
 * lazy-React discipline, and the generator→grammar adapter parity guard.
 * The MCP plan-first/confirm parity lives in create.mcp.test.ts; the
 * byte-equality goldens in byteEquality.test.ts.
 */

import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { PragmaError } from "../../kernel/error/PragmaError.js";
import {
  executeVerb,
  type MutationFlags,
} from "../../kernel/project/cli/dispatch.js";
import { bootRuntime } from "../../kernel/runtime/boot.js";
import type { GlobalFlags } from "../../kernel/runtime/types.js";
import { createComponentVerb } from "./create.verb.js";
import { generatorToParams } from "./generatorToVerbSpec.js";

const FLAGS: GlobalFlags = {
  llm: false,
  autoLlm: false,
  format: "plain",
  verbose: false,
};
const YES: MutationFlags = { dryRun: false, undo: false, yes: true };
const freshCwd = (): string => mkdtempSync(join(tmpdir(), "pragma2-create-"));

/** Run a create verb inside `dir` (relative generator paths resolve there). */
async function runIn(
  dir: string,
  params: Record<string, unknown>,
  mutation: MutationFlags = YES,
) {
  const prev = process.cwd();
  process.chdir(dir);
  try {
    return await executeVerb(
      createComponentVerb,
      params,
      mutation,
      bootRuntime(FLAGS, dir),
    );
  } finally {
    process.chdir(prev);
  }
}

const walk = (dir: string, base = ""): string[] =>
  readdirSync(dir, { withFileTypes: true }).flatMap((e) =>
    e.isDirectory()
      ? walk(join(dir, e.name), join(base, e.name))
      : [join(base, e.name)],
  );

describe("create — real generation + stamp", () => {
  it("scaffolds a component and stamps generated files", async () => {
    const dir = freshCwd();
    const outcome = await runIn(dir, {
      framework: "react",
      componentPath: "src/components/Widget",
      withStyles: true,
      withStories: false,
      withSsrTests: false,
    });
    expect(outcome.exitCode).toBe(0);
    const main = join(dir, "src/components/Widget/Widget.tsx");
    expect(existsSync(main)).toBe(true);
    expect(readFileSync(main, "utf-8").split("\n")[0]).toBe(
      "// Generated by @canonical/summon-component:react v0.1.0",
    );
  });

  it("--dry-run writes nothing and previews effects (no Prompt lines)", async () => {
    const dir = freshCwd();
    const outcome = await runIn(
      dir,
      { framework: "react", componentPath: "src/components/Widget" },
      { dryRun: true, undo: false, yes: false },
    );
    expect(outcome.exitCode).toBe(0);
    expect(outcome.stdout).toContain("Widget.tsx");
    expect(outcome.stdout).not.toContain("Prompt");
    expect(walk(dir)).toEqual([]); // nothing written
  });

  it("--undo reverses a run", async () => {
    const dir = freshCwd();
    await runIn(dir, {
      framework: "react",
      componentPath: "src/components/Widget",
      withStyles: false,
      withStories: false,
      withSsrTests: false,
    });
    const outcome = await runIn(
      dir,
      {
        framework: "react",
        componentPath: "src/components/Widget",
        withStyles: false,
        withStories: false,
        withSsrTests: false,
      },
      { dryRun: false, undo: true, yes: true },
    );
    expect(outcome.exitCode).toBe(0);
    expect(outcome.stdout).toMatch(/Undid \d+ step/);
  });

  it("rejects an unknown framework with INVALID_INPUT", async () => {
    const dir = freshCwd();
    // coerceParam rejects the enum before run, so drive run directly via a bad
    // framework param to exercise pickGenerator's own guard too.
    const runtime = bootRuntime(FLAGS, dir);
    await expect(
      createComponentVerb.run({ framework: "vue" }, {
        ...runtime,
        interaction: { isTTY: false, transport: "cli", yes: true },
      } as never),
    ).rejects.toBeInstanceOf(PragmaError);
  });
});

describe("SEC-2 path jail (PROTECTED)", () => {
  const cases: Array<[string, string]> = [
    ["a .. escape", "../evil/Widget"],
    ["an absolute path", "/tmp/evil/Widget"],
  ];
  for (const [label, value] of cases) {
    it(`rejects ${label} with a PragmaError before any effect`, async () => {
      const dir = freshCwd();
      // The jail throws in `run`, before any effect; the projector maps it to an
      // exit code, but exercised directly here `executeVerb` propagates it.
      await expect(
        runIn(dir, { framework: "react", componentPath: value }),
      ).rejects.toBeInstanceOf(PragmaError);
      expect(walk(dir)).toEqual([]);
    });
  }

  it("rejects a symlink that escapes the workspace (realpath)", async () => {
    const root = freshCwd();
    const outside = freshCwd();
    // A symlink `link` inside the workspace pointing OUT of it.
    symlinkSync(outside, join(root, "link"));
    await expect(
      runIn(root, { framework: "react", componentPath: "link/Widget" }),
    ).rejects.toBeInstanceOf(PragmaError);
    expect(existsSync(join(outside, "Widget"))).toBe(false);
  });

  it("accepts an in-workspace path", async () => {
    const dir = freshCwd();
    mkdirSync(join(dir, "packages"), { recursive: true });
    const outcome = await runIn(dir, {
      framework: "react",
      componentPath: "packages/Widget",
      withStyles: false,
      withStories: false,
      withSsrTests: false,
    });
    expect(outcome.exitCode).toBe(0);
  });
});

describe("lazy-React discipline (PROTECTED)", () => {
  const here = dirname(fileURLToPath(import.meta.url));

  /** Walk the STATIC (relative-only) import graph from an entry .ts file. */
  function staticGraph(entry: string, seen = new Set<string>()): Set<string> {
    if (seen.has(entry) || !existsSync(entry)) return seen;
    seen.add(entry);
    const src = readFileSync(entry, "utf-8");
    const re = /(?:\bfrom\s*|(?:^|\n)\s*import\s*)["']([^"']+)["']/g;
    for (const m of src.matchAll(re)) {
      const spec = m[1];
      if (spec?.startsWith("."))
        staticGraph(
          resolve(dirname(entry), spec.replace(/\.js$/, ".ts")),
          seen,
        );
    }
    return seen;
  }

  it("the capability registry never statically reaches React/Ink or the generators", () => {
    const graph = staticGraph(resolve(here, "../index.ts"));
    // pickGenerator (which imports the heavy generators) is dynamic-only.
    expect([...graph].some((f) => f.endsWith("create/pickGenerator.ts"))).toBe(
      false,
    );
    const forbidden = [
      "react",
      "react-dom",
      "ink",
      "ink-select-input",
      "ink-text-input",
      "ink-spinner",
      "@canonical/summon-component",
      "@canonical/summon-package",
      "@canonical/summon-application",
    ];
    for (const file of graph) {
      const src = readFileSync(file, "utf-8");
      for (const pkg of forbidden) {
        const esc = pkg.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
        expect(
          new RegExp(`from\\s*["']${esc}["']`).test(src),
          `${file} statically imports ${pkg}`,
        ).toBe(false);
      }
    }
  });

  it("running create --yes never loads React or Ink", async () => {
    const dir = freshCwd();
    await runIn(dir, {
      framework: "react",
      componentPath: "src/components/Widget",
      withStyles: false,
      withStories: false,
      withSsrTests: false,
    });
    const isReactPkg = (k: string) =>
      /[\\/](react|react-dom|ink|ink-select-input|ink-text-input|ink-spinner)@\d/.test(
        k,
      ) ||
      /[\\/]node_modules[\\/](react|react-dom|ink|ink-select-input|ink-text-input|ink-spinner)[\\/]/.test(
        k,
      );
    const loaded = Object.keys(require.cache ?? {});
    expect(loaded.filter(isReactPkg)).toEqual([]);
  });
});

describe("generator→grammar adapter parity (PROTECTED)", () => {
  it("the component mirror matches the real react generator's prompts", async () => {
    const { generators } = await import("@canonical/summon-component");
    const reactGen = (generators as Record<string, { prompts: unknown[] }>)[
      "component/react"
    ];
    const params = generatorToParams(reactGen.prompts as never);
    const names = params.map((p) => p.name);
    // Every real prompt is represented (componentPath + the shared confirms).
    expect(names).toEqual([
      "componentPath",
      "withStyles",
      "withStories",
      "withSsrTests",
    ]);
    // componentPath is a positional string with file completion.
    expect(params[0]).toMatchObject({
      kind: "string",
      positional: true,
      complete: { kind: "files" },
    });
    // The shared options are booleans.
    expect(params.slice(1).every((p) => p.kind === "boolean")).toBe(true);
  });
});
