// Generated by @canonical/summon-component:react v0.1.0

import type { Meta, StoryObj } from "@storybook/react-vite";
import DefinitionsPage from "./DefinitionsPage.js";

const meta: Meta<typeof DefinitionsPage> = {
  title: "Components/DefinitionsPage",
  component: DefinitionsPage,
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof DefinitionsPage>;

export const Default: Story = {
  args: {
    children: "Hello, DefinitionsPage!",
  },
};

export const WithCustomClass: Story = {
  args: {
    children: "Custom styled",
    className: "custom-class",
  },
};
