// Generated by @canonical/summon-component:react v0.1.0

import { renderToString } from "react-dom/server";
import { describe, expect, it } from "vitest";
import DefinitionsPage from "./DefinitionsPage.js";

describe("DefinitionsPage SSR", () => {
  it("renders without hydration errors", () => {
    const html = renderToString(
      <DefinitionsPage>Test content</DefinitionsPage>,
    );
    expect(html).toContain("Test content");
    expect(html).toContain("ds definitions-page");
  });
});
