// Generated by @canonical/summon-component:react v0.1.0

import type React from "react";
import type { DefinitionsPageProps } from "./types.js";
import "./styles.css";

const componentCssClassName = "ds definitions-page";

/**
 * DefinitionsPage component
 */
const DefinitionsPage = ({
  className,
  children,
  ...props
}: DefinitionsPageProps): React.ReactElement => {
  return (
    <div
      className={[componentCssClassName, className].filter(Boolean).join(" ")}
      {...props}
    >
      {children}
    </div>
  );
};

export default DefinitionsPage;
