// Generated by @canonical/summon-component:lit v0.1.0

import { afterEach, beforeEach, describe, expect, it } from "vitest";
import "./TieredListItem.js";
import type { TieredListItem } from "./TieredListItem.js";

describe("TieredListItem component", () => {
  let elem: TieredListItem;

  beforeEach(() => {
    elem = document.createElement("ds-tiered-list-item") as TieredListItem;
    document.body.appendChild(elem);
  });

  afterEach(() => {
    elem.remove();
  });

  it("should render component", async () => {
    await customElements.whenDefined("ds-tiered-list-item");

    const container = elem.shadowRoot?.querySelector(".ds.tiered-list-item");
    expect(container).toBeTruthy();
  });

  it("should have correct tag name", () => {
    expect(elem.tagName.toLowerCase()).toBe("ds-tiered-list-item");
  });
});
