// Generated by @canonical/summon-component:lit v0.1.0

import type { Meta, StoryObj } from "@storybook/web-components-vite";
import { html } from "lit";

import "./TieredListItem.js";
import type { TieredListItem } from "./TieredListItem.js";

const meta = {
  title: "Web Components/TieredListItem",
  tags: ["autodocs"],
} satisfies Meta<TieredListItem>;

export default meta;
type Story = StoryObj<TieredListItem>;

export const Default: Story = {
  render: () =>
    html`<ds-tiered-list-item>Hello, TieredListItem!</ds-tiered-list-item>`,
};
