// Generated by @canonical/summon-component:lit v0.1.0

import { html, LitElement } from "lit";
import { customElement } from "lit/decorators.js";
import styles from "./styles.css";

const componentCssClassName = "ds tiered-list-item";

/**
 * TieredListItem web component.
 *
 * @implements ds:global.component.tiered-list-item
 */
@customElement("ds-tiered-list-item")
export class TieredListItem extends LitElement {
  static styles = styles;

  render() {
    return html`
      <div class="${componentCssClassName}">
        <div class="title"><slot name="item-title"></slot></div>
        <div class="description">
          <slot name="item-description"></slot>
        </div>
        <hr />
      </div>`;
  }
}
