// Generated by @canonical/summon-component:react v0.1.0

import type React from "react";
import useOptionAriaProperties from "#lib/utils/hooks/useOptionAriaProperties.js";
import type { OptionProps } from "./types.js";

const componentCssClassName = "ds option";

/**
 * A single plain-label option within a `SimpleChoices` group: a styled native
 * radio/checkbox paired with its label. Controlled by the parent group via
 * `checked`/`onChange`.
 * @returns {React.ReactElement} - Rendered Option
 */
const Option = ({
  name,
  type,
  option,
  checked,
  disabled,
  onChange,
}: OptionProps): React.ReactElement => {
  const ariaProps = useOptionAriaProperties(name, option.value);
  return (
    <div
      className={[componentCssClassName, "grid", disabled && "disabled"]
        .filter(Boolean)
        .join(" ")}
    >
      <input
        name={name}
        value={option.value}
        disabled={disabled}
        type={type}
        checked={checked}
        onChange={onChange}
        {...ariaProps.input}
      />
      {/* biome-ignore lint/a11y/noLabelWithoutControl : is indeed provided but undetected*/}
      <label className="p" {...ariaProps.label}>
        {option.label}
      </label>
    </div>
  );
};

export default Option;
