// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import type { ReactNode } from "react";
import type { TSectionProps } from "../TSection/types.js";

type OwnProps = {
  /** Content to render inside the component */
  children?: ReactNode;
};

// The root is the `TSection` component rather than an intrinsic tag, so the
// inherited surface comes from `TSectionProps` (itself a
// `ComponentProps<"section">` intersection) — that carries the native
// `<section>` props *and* TSection's DS-owned `title` heading, and stays
// correct if TSection ever changes its root element.
export type CategoriesSectionProps = OwnProps &
  Omit<TSectionProps, keyof OwnProps>;
