// Generated by @canonical/summon:component-webcomponents v0.1.0

import { html, LitElement } from "lit";
import { customElement, property } from "lit/decorators.js";
import styles from "./styles.css";
import type Props from "./types.js";

const componentCssClassName = "ds logo-section";

/**
 * Logo section web component.
 * A vertically stacked pattern with an optional heading and a logo grid.
 *
 * @slot logos - One or more logo items to display in the logo grid.
 * @slot description - Optional descriptive text displayed beside the heading.
 * @slot cta - Optional call-to-action content displayed beside the heading.
 *
 * @prop {string} title - Heading text for the section. Ignored in `minimal` mode.
 * @prop {string} titleHref - When set, wraps the title in an anchor tag. Ignored in `minimal` mode.
 * @prop {"default" | "minimal"} mode - `minimal` renders a plain `<div>` wrapper with only the logo block; `default` renders a full `<section>` with heading, description and CTA slots.
 *
 * @implements ds:global.component.logo-section
 */
@customElement("ds-logo-section")
export default class LogoSection extends LitElement implements Props {
  static styles = styles;

  @property({ type: String }) title = "";
  @property({ type: String, attribute: "title-href" }) titleHref = "";
  @property({ type: String, attribute: "mode" }) mode: "default" | "minimal" =
    "default";

  private get titleContent() {
    return this.titleHref
      ? html`<a href="${this.titleHref}">${this.title}</a>`
      : this.title;
  }

  render() {
    const isMinimal = this.mode === "minimal";

    if (isMinimal) {
      return html`
        <div class="${componentCssClassName}">
          ${this.renderLogoBlock()}
        </div>
      `;
    }

    return html`
      <section class="${componentCssClassName}">
        <hr />
        <div class="heading">
          <div>
            <h4 class="title">${this.titleContent}</h4>
          </div>
          <div>
            <slot name="description"></slot>
            <slot name="cta"></slot>
          </div>
        </div>
        ${this.renderLogoBlock()}
      </section>
    `;
  }

  private renderLogoBlock() {
    return html`
      <div class="logos">
        <slot name="logos"></slot>
      </div>
    `;
  }
}
