// Generated by @canonical/summon:component-webcomponents v0.1.0

export interface Props {
  /** Heading text for the section */
  title?: string;
  /** When set, wraps the title in an anchor tag. */
  titleHref?: string;
  /**
   * Layout mode of the section.
   * - `default`: Full `<section>` with heading, description, and CTA slots.
   * - `minimal`: Plain `<div>` wrapper with only the logo grid.
   * @default "default"
   */
  mode?: "default" | "minimal";
}

export default Props;
