// Generated by @canonical/summon:component-svelte v0.1.0

import { describe, expect, it } from "vitest";
import { render } from "@testing-library/svelte";
import MyComponent from "./MyComponent.svelte";

describe("MyComponent", () => {
	it("renders", () => {
		render(MyComponent);
		// Add assertions based on your component
	});

	it("applies custom class", () => {
		render(MyComponent, { props: { class: "custom-class" } });
		const element = document.querySelector(".my-component");
		expect(element).toHaveClass("custom-class");
	});
});
