// Generated by @canonical/summon:component-svelte v0.1.0

import { describe, expect, it } from "vitest";
import { render } from "svelte/server";
import MyComponent from "./MyComponent.svelte";

describe("MyComponent SSR", () => {
	it("renders on server without errors", () => {
		const { body } = render(MyComponent);
		expect(body).toContain("my-component");
	});
});
