<!-- Generated by @canonical/summon:component-svelte v0.1.0 -->

<script lang="ts" module>
	import { defineMeta } from "@storybook/addon-svelte-csf";
	import MyComponent from "./MyComponent.svelte";

	const { Story } = defineMeta({
		title: "Components/MyComponent",
		component: MyComponent,
		tags: ["autodocs"],
	});
</script>

<Story name="Default">
	<MyComponent>Hello, MyComponent!</MyComponent>
</Story>

<Story name="WithCustomClass">
	<MyComponent class="custom-class">Custom styled</MyComponent>
</Story>
