// Generated by @canonical/summon:component-svelte v0.1.0

import type { Snippet } from "svelte";
import type { HTMLAttributes } from "svelte/elements";

export interface MyComponentProps extends HTMLAttributes<HTMLDivElement> {
	/** Content to render inside the component */
	children?: Snippet;
}
