// Generated by component/webcomponents v0.1.0
// Generated by @canonical/summon:component-webcomponents v0.1.0

export { default as Hero } from "./Hero.js";
export type { HeroProps } from "./types.js";
