// Generated by component/webcomponents v0.1.0
// Generated by @canonical/summon:component-webcomponents v0.1.0

/**
 * Props for the Hero component.
 */
export interface HeroProps {
	// Define props specific to Hero here
}
