/**
 * The fish completion script (static tier). Requires fish >= 3.
 *
 * Declarative: one `complete -c` rule per fact, gated by the
 * `__<bin>_at <noun> [verb]` position probe. Default file completion is
 * suppressed (`-f`); enum values are inlined literals; file params force
 * native files back on (`-rF`); only `{kind:"entity"}` contexts exec the CLI
 * via a command substitution — fish treats substitution results as literal
 * candidates (split on newlines, never evaluated). No `eval`, no backticks.
 *
 * Static-tier coarseness (the resolver is exact): positional value rules are
 * not index-gated, and a mixed self-verb + sub-verb noun only offers its
 * sub-verbs — `__complete` answers both cases precisely.
 */

import type { CompletionModel, FlagEntry, VerbEntry } from "../types.js";
import { globalValueFlags, nounNames, verbViews, wordList } from "./shared.js";

/** A shell-safe function-name base for the bin (`pragma2` -> `__pragma2`). */
function fnBase(binName: string): string {
  return `__${binName.replace(/[^A-Za-z0-9_]/g, "_")}`;
}

/** The rule fragment completing one flag of a view (or a global flag). */
function flagRule(
  binName: string,
  fn: string,
  condition: string | undefined,
  flag: FlagEntry,
): string {
  const name = flag.flag.replace(/^--/, "");
  const parts = [`complete -c ${binName}`];
  if (condition) parts.push(`-n "${condition}"`);
  parts.push(`-l ${name}`);
  if (flag.takesValue) {
    switch (flag.source.kind) {
      case "values":
        parts.push(`-x -a "${wordList(flag.source.values, "fish values")}"`);
        break;
      case "files":
        parts.push("-rF");
        break;
      case "entity":
        parts.push(
          `-x -a "(${binName} __complete -- (${fn}_words) 2>/dev/null)"`,
        );
        break;
      case "none":
        parts.push("-x");
        break;
    }
  }
  return parts.join(" ");
}

/** The positional value rule for a view, or undefined when it offers nothing. */
function positionalRule(
  binName: string,
  fn: string,
  condition: string,
  verb: VerbEntry,
): string | undefined {
  // fish rules are not index-gated; offer the union of the verb's positional
  // sources (entity delegates to the resolver, which IS index-exact).
  const values = new Set<string>();
  let entity = false;
  let files = false;
  for (const positional of verb.positionals) {
    if (positional.source.kind === "values") {
      for (const value of positional.source.values) values.add(value);
    }
    if (positional.source.kind === "entity") entity = true;
    if (positional.source.kind === "files") files = true;
  }
  const parts = [`complete -c ${binName} -n "${condition}"`];
  if (entity) {
    parts.push(`-a "(${binName} __complete -- (${fn}_words) 2>/dev/null)"`);
  } else if (values.size > 0) {
    parts.push(
      `-a "${wordList([...values].sort(), "fish positional values")}"`,
    );
  } else if (files) {
    parts.push("-F");
  } else {
    return undefined;
  }
  return parts.join(" ");
}

/**
 * Render the fish completion script.
 *
 * @param model - The completion model.
 * @param binName - The binary to complete (function names derive from it).
 * @returns The script text.
 */
export function fishScript(model: CompletionModel, binName: string): string {
  const fn = fnBase(binName);
  const globalValueSkips = wordList(
    globalValueFlags(model).map((flag) => flag.flag),
    "fish global value flags",
  );

  const lines: string[] = [
    `# ${binName} fish completion (static tier) — generated by \`${binName} setup completions\`. Do not edit.`,
    "# Structure (nouns, verbs, flags, enum values) is inlined and never execs;",
    `# entity arguments call \`${binName} __complete\` (storeless, never-throw);`,
    "# file arguments use native completion (-rF). Requires fish >= 3.",
    `function ${fn}_words`,
    "    set -l toks (commandline -opc)",
    "    set -l cur (commandline -ct)",
    "    printf '%s\\n' $toks[2..-1] $cur",
    "end",
    `function ${fn}_at`,
    "    set -l cmd (commandline -opc)",
    "    set -l noun ''",
    "    set -l verb ''",
    "    set -l skip 0",
    "    for w in $cmd[2..-1]",
    "        if test $skip -eq 1",
    "            set skip 0",
    "            continue",
    "        end",
    "        switch $w",
    `            case ${globalValueSkips}`,
    "                set skip 1",
    "            case '-*'",
    "            case '*'",
    '                if test -z "$noun"',
    "                    set noun $w",
    '                else if test -z "$verb"',
    "                    set verb $w",
    "                end",
    "        end",
    "    end",
    '    test "$noun" = "$argv[1]"; and test "$verb" = "$argv[2]"',
    "end",
    `complete -c ${binName} -f`,
    "",
    "# nouns",
    `complete -c ${binName} -n "${fn}_at ''" -a "${wordList(nounNames(model), "fish nouns")}"`,
    "",
    "# global flags",
    ...model.globalFlags.map((flag) =>
      flagRule(
        binName,
        fn,
        flag.rootOnly === true ? `${fn}_at ''` : undefined,
        flag,
      ),
    ),
  ];

  for (const entry of model.nouns) {
    if (entry.verbs.length > 0) {
      lines.push(
        "",
        `# ${entry.noun} verbs`,
        `complete -c ${binName} -n "${fn}_at ${entry.noun}" -a "${wordList(
          entry.verbs.map((verb) => verb.label),
          "fish verbs",
        )}"`,
      );
    }
  }

  for (const view of verbViews(model)) {
    // A mixed noun's self-verb state is not expressible with the probe; its
    // sub-verbs own the second word and the resolver owns the rest.
    if (
      view.self &&
      view.verb.positionals.length === 0 &&
      view.verb.flags.length === 0 &&
      !view.verb.mutates
    ) {
      continue;
    }
    const nounEntry = model.nouns.find((entry) => entry.noun === view.noun);
    if (view.self && (nounEntry?.verbs.length ?? 0) > 0) continue;

    const condition = view.self
      ? `${fn}_at ${view.noun}`
      : `${fn}_at ${view.noun} ${view.verb.label}`;
    const rules: string[] = [];
    for (const flag of view.verb.flags) {
      rules.push(flagRule(binName, fn, condition, flag));
    }
    if (view.verb.mutates) {
      for (const flag of model.mutationFlags) {
        rules.push(flagRule(binName, fn, condition, flag));
      }
    }
    const positional = positionalRule(binName, fn, condition, view.verb);
    if (positional) rules.push(positional);
    if (rules.length > 0) {
      lines.push("", `# ${view.key}`, ...rules);
    }
  }

  lines.push("");
  return lines.join("\n");
}
