// Generated by @canonical/summon:component-webcomponents v0.1.0

import type { LitElement } from "lit";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import "./Button.js";
import type Button from "./Button.js";

/**
 * Awaits two Lit update cycles to account for slot-driven state changes.
 *
 * When slotted content is set via `textContent` or `innerHTML`, the browser
 * fires a `slotchange` event asynchronously. Our `onSlotChange` handler then
 * writes to a `@state()` field, which schedules a *second* Lit update cycle.
 * A single `await updateComplete` resolves only the first cycle — the one
 * that was already pending before `slotchange` fired — so the state update
 * from the slot handler is not yet reflected in the DOM. The second await
 * catches that cascading re-render.
 */
async function settle(el: LitElement) {
  await el.updateComplete;
  await el.updateComplete;
}

describe("Button component", () => {
  let elem: Button;

  beforeEach(() => {
    elem = document.createElement("ds-button") as Button;
    document.body.appendChild(elem);
  });

  afterEach(() => {
    elem.remove();
  });

  it("should render component", async () => {
    await customElements.whenDefined("ds-button");
    await elem.updateComplete;

    const container = elem.shadowRoot?.querySelector(".ds.button");
    expect(container).toBeTruthy();
  });

  it("should have correct tag name", () => {
    expect(elem.tagName.toLowerCase()).toBe("ds-button");
  });

  it("should apply link variant class", async () => {
    elem.variant = "link";
    await elem.updateComplete;

    const button = elem.shadowRoot?.querySelector("button");
    expect(button?.classList.contains("link")).toBe(true);
  });

  it("should derive aria-label from text content", async () => {
    elem.textContent = "Submit";
    await settle(elem);

    const button = elem.shadowRoot?.querySelector("button");
    expect(button?.getAttribute("aria-label")).toBe("Submit");
  });

  it("should prefer explicit aria-label", async () => {
    elem.textContent = "Visible label";
    elem.ariaLabel = "Accessible label";
    await settle(elem);

    const button = elem.shadowRoot?.querySelector("button");
    expect(button?.getAttribute("aria-label")).toBe("Accessible label");
  });

  it("should not render icon container when no icon is slotted", async () => {
    elem.textContent = "Action";
    await elem.updateComplete;

    const icon = elem.shadowRoot?.querySelector(".icon");
    expect(icon?.hasAttribute("hidden")).toBe(true);
  });

  it("should disable the inner button when disabled is set", async () => {
    elem.disabled = true;
    await elem.updateComplete;

    const button = elem.shadowRoot?.querySelector("button");
    expect(button?.hasAttribute("disabled")).toBe(true);
  });

  it("should render icon before content when iconPosition is start", async () => {
    elem.innerHTML = '<span slot="icon">*</span>Action';
    elem.iconPosition = "start";
    await settle(elem);

    const button = elem.shadowRoot?.querySelector("button");
    expect(button?.firstElementChild?.classList.contains("icon")).toBe(true);
  });

  it("should render icon after content when iconPosition is end", async () => {
    elem.innerHTML = '<span slot="icon">*</span>Action';
    elem.iconPosition = "end";
    await settle(elem);

    const button = elem.shadowRoot?.querySelector("button");
    expect(button?.lastElementChild?.classList.contains("icon")).toBe(true);
  });
});
