// Generated by component/webcomponents v0.1.0
// Generated by @canonical/summon:component-webcomponents v0.1.0

import { afterEach, beforeEach, describe, expect, it } from "vitest";
import "./Button.js";
import type Button from "./Button.js";

describe("Button component", () => {
  let elem: Button;

  beforeEach(() => {
    elem = document.createElement("ds-button") as Button;
    document.body.appendChild(elem);
  });

  afterEach(() => {
    elem.remove();
  });

  it("should render component", async () => {
    await customElements.whenDefined("ds-button");
    await elem.updateComplete;

    const container = elem.shadowRoot?.querySelector(".ds.button");
    expect(container).toBeTruthy();
  });

  it("should have correct tag name", () => {
    expect(elem.tagName.toLowerCase()).toBe("ds-button");
  });

  it("should reflect importance as attribute", async () => {
    elem.importance = "primary";
    await elem.updateComplete;

    expect(elem.getAttribute("importance")).toBe("primary");
  });

  it("should reflect anticipation as attribute", async () => {
    elem.anticipation = "constructive";
    await elem.updateComplete;

    expect(elem.getAttribute("anticipation")).toBe("constructive");
  });

  it("should apply link variant class", async () => {
    elem.variant = "link";
    await elem.updateComplete;

    const button = elem.shadowRoot?.querySelector("button");
    expect(button?.classList.contains("link")).toBe(true);
  });

  it("should derive aria-label from text content", async () => {
    elem.textContent = "Submit";
    elem.requestUpdate();
    await elem.updateComplete;

    const button = elem.shadowRoot?.querySelector("button");
    expect(button?.getAttribute("aria-label")).toBe("Submit");
  });

  it("should prefer explicit aria-label", async () => {
    elem.textContent = "Visible label";
    elem.ariaLabel = "Accessible label";
    await elem.updateComplete;

    const button = elem.shadowRoot?.querySelector("button");
    expect(button?.getAttribute("aria-label")).toBe("Accessible label");
  });

  it("should not render icon container when no icon is slotted", async () => {
    elem.textContent = "Action";
    await elem.updateComplete;

    const icon = elem.shadowRoot?.querySelector(".icon");
    expect(icon?.hasAttribute("hidden")).toBe(true);
  });

  it("should render icon before content when iconPosition is start", async () => {
    elem.innerHTML = '<span slot="icon">*</span>Action';
    elem.iconPosition = "start";
    await elem.updateComplete;

    const button = elem.shadowRoot?.querySelector("button");
    expect(button?.firstElementChild?.classList.contains("icon")).toBe(true);
  });

  it("should render icon after content when iconPosition is end", async () => {
    elem.innerHTML = '<span slot="icon">*</span>Action';
    elem.iconPosition = "end";
    await elem.updateComplete;

    const button = elem.shadowRoot?.querySelector("button");
    expect(button?.lastElementChild?.classList.contains("icon")).toBe(true);
  });
});
