// Generated by component/webcomponents v0.1.0
// Generated by @canonical/summon:component-webcomponents v0.1.0

import { html, LitElement } from "lit";
import { customElement, property, state } from "lit/decorators.js";
import { ifDefined } from "lit/directives/if-defined.js";
import styles from "./styles.css";
import type { ButtonProps } from "./types.js";

const componentCssClassName = "ds button";

/**
 * Button web component.
 *
 * @implements ds:global.component.button
 */
@customElement("ds-button")
export default class Button extends LitElement implements ButtonProps {
  static styles = styles;

  @state()
  private hasIcon = false;

  @property({ type: String, reflect: true })
  importance?: ButtonProps["importance"];

  @property({ type: String, reflect: true })
  anticipation?: ButtonProps["anticipation"];

  @property({ type: String, reflect: true })
  variant?: ButtonProps["variant"];

  @property({ type: String, attribute: "icon-position", reflect: true })
  iconPosition: ButtonProps["iconPosition"] = "start";

  @property({ type: String, attribute: "aria-label" })
  ariaLabel: string | null = null;

  @property({ type: Boolean })
  disabled = false;

  @property({ type: String })
  type: ButtonProps["type"] = "button";

  private onIconSlotChange(e: Event): void {
    this.hasIcon = (e.target as HTMLSlotElement).assignedElements().length > 0;
  }

  private deriveAriaLabel(): string | undefined {
    if (this.ariaLabel) {
      return this.ariaLabel;
    }

    const derived = this.textContent?.trim();
    return derived ? derived : undefined;
  }

  render() {
    const classes = [componentCssClassName, this.variant]
      .filter(Boolean)
      .join(" ");

    const ariaLabel = this.deriveAriaLabel();

    const iconSlot = html`
			<span class="icon" ?hidden=${!this.hasIcon}>
				<slot name="icon" @slotchange=${this.onIconSlotChange}></slot>
			</span>
		`;

    return html`
			<button
				class="${classes}"
				?disabled=${this.disabled}
				type="${this.type}"
				aria-label=${ifDefined(ariaLabel)}
			>
				${
          this.iconPosition === "end"
            ? html`<slot></slot>${iconSlot}`
            : html`${iconSlot}<slot></slot>`
        }
			</button>
		`;
  }
}
