// Generated by @canonical/summon-component:react v0.1.0

import { renderToString } from "react-dom/server";
import { FormProvider, useForm } from "react-hook-form";
import { describe, expect, it } from "vitest";
import NumberField from "./NumberField.js";

function SSRHost() {
  const methods = useForm();
  return (
    <FormProvider {...methods}>
      <NumberField name="qty" label="Quantity" />
    </FormProvider>
  );
}

// Proves the field renders to static HTML under a form provider.
describe("NumberField SSR", () => {
  it("renders the labelled number field to static HTML", () => {
    const html = renderToString(<SSRHost />);
    expect(html).toContain("Quantity");
    expect(html).toContain('type="number"');
    expect(html).toContain("ds input number chrome");
  });
});
