// Generated by @canonical/summon-component:react v0.1.0

import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { FormProvider, useForm } from "react-hook-form";
import { describe, expect, it, vi } from "vitest";
import { renderWithForm } from "../../../testing/renderWithForm.js";
import NumberField from "./NumberField.js";

// NumberField = NumberInput bound to react-hook-form + field chrome, so it is
// tested through a FormProvider.
describe("NumberField", () => {
  it("renders the label, description, and a number input", () => {
    renderWithForm(
      <NumberField name="qty" label="Quantity" description="How many?" />,
    );
    expect(screen.getByText("Quantity")).toBeInTheDocument();
    expect(screen.getByText("How many?")).toBeInTheDocument();
    expect(screen.getByLabelText("Quantity")).toHaveAttribute("type", "number");
  });

  it("forwards min/max/step onto the underlying input", () => {
    renderWithForm(
      <NumberField name="qty" label="Quantity" min={0} max={9} step={3} />,
    );
    const input = screen.getByLabelText("Quantity");
    expect(input).toHaveAttribute("min", "0");
    expect(input).toHaveAttribute("max", "9");
    expect(input).toHaveAttribute("step", "3");
  });

  it("registers the value as a NUMBER (valueAsNumber), not a string", async () => {
    const onSubmit = vi.fn();
    function Host() {
      const methods = useForm();
      return (
        <FormProvider {...methods}>
          <form onSubmit={methods.handleSubmit(onSubmit)}>
            <NumberField name="qty" label="Quantity" />
            <button type="submit">submit</button>
          </form>
        </FormProvider>
      );
    }
    render(<Host />);
    fireEvent.change(screen.getByLabelText("Quantity"), {
      target: { value: "7" },
    });
    fireEvent.click(screen.getByRole("button", { name: "submit" }));
    // RHF's handleSubmit is async; wait for it to fire with the coerced value.
    await waitFor(() => expect(onSubmit).toHaveBeenCalled());
    const submitted = onSubmit.mock.calls[0][0] as { qty: unknown };
    expect(submitted.qty).toBe(7);
    expect(typeof submitted.qty).toBe("number");
  });
});
