// Generated by @canonical/summon-component:react v0.1.0

import { fireEvent, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import { renderWithForm } from "../../../testing/renderWithForm.js";
import NumberField from "./NumberField.js";

// NumberField = NumberInput bound to react-hook-form + field chrome, so it is
// tested through a FormProvider.
describe("NumberField", () => {
  it("renders the label, description, and a number input", () => {
    renderWithForm(
      <NumberField name="qty" label="Quantity" description="How many?" />,
    );
    expect(screen.getByText("Quantity")).toBeInTheDocument();
    expect(screen.getByText("How many?")).toBeInTheDocument();
    expect(screen.getByLabelText("Quantity")).toHaveAttribute("type", "number");
  });

  it("forwards min/max/step onto the underlying input", () => {
    renderWithForm(
      <NumberField name="qty" label="Quantity" min={0} max={9} step={3} />,
    );
    const input = screen.getByLabelText("Quantity");
    expect(input).toHaveAttribute("min", "0");
    expect(input).toHaveAttribute("max", "9");
    expect(input).toHaveAttribute("step", "3");
  });

  it("registers the field value with the form", () => {
    renderWithForm(<NumberField name="qty" label="Quantity" />);
    const input = screen.getByLabelText("Quantity");
    fireEvent.change(input, { target: { value: "7" } });
    expect(input).toHaveValue(7);
  });
});
