// Generated by @canonical/summon-component:react v0.1.0

import bindField from "#lib/common/bindField/index.js";
import withWrapper from "#lib/common/Wrapper/withWrapper.js";
import { NumberInput } from "#lib/subcomponent/NumberInput/index.js";
import type { NumberFieldProps } from "./types.js";

/**
 * NumberInput bound to react-hook-form, wrapped with field chrome (label,
 * description, error) and middleware/conditional-display support. Collects a
 * numeric value with optional min/max/step and prefix/suffix units.
 */
export default withWrapper<NumberFieldProps>(
  // `valueAsNumber` so RHF stores a number, not the string the native
  // `<input type="number">` reports (the consumer's registerProps still win).
  bindField<NumberFieldProps>(NumberInput, "native", {
    registerDefaults: { valueAsNumber: true },
  }),
);
