// Generated by @canonical/summon-component:react v0.1.0

import type { InputProps } from "../../common/types.js";
import type { NumberInputProps } from "../../subcomponent/NumberInput/index.js";

/** Props for the react-hook-form-bound Number field (presentational + binding). */
export type NumberFieldProps = InputProps<NumberInputProps>;
