// Generated by @canonical/summon-component:react v0.1.0

import { renderToString } from "react-dom/server";
import { describe, expect, it } from "vitest";
import Cards from "./Cards.js";

describe("Cards SSR", () => {
  it("renders to a static HTML string on the server", () => {
    const html = renderToString(<Cards>Test content</Cards>);
    expect(html).toContain("Test content");
    expect(html).toContain("ds cards");
  });
});
