// Generated by @canonical/summon-application:application/react v0.1.0

import { HeadProvider } from "@canonical/react-head";
import type { ServerEntrypointProps } from "@canonical/react-ssr/renderer";
import { createStaticRouter } from "@canonical/router-core";
import { Outlet, RouterProvider } from "@canonical/router-react";
import { RelayEnvironmentProvider } from "react-relay";
import type { RecordMap } from "relay-runtime/store/RelayStoreTypes.js";
import { createEnvironment } from "#relay/environment.js";
import { appRoutes, middleware, notFoundRoute } from "../routes.js";
import "#styles/app.css";

interface InitialData extends Record<string, unknown> {
  readonly url?: string;
  /** Colour-scheme preference resolved from the request cookie, if any. */
  readonly theme?: "light" | "dark";
  /**
   * Relay hydration payload from the server's prepare step: the serialised
   * record map of the route's executed query. `__INITIAL_DATA__` is an
   * app-level namespaced map owned by `JSXRenderer` (P-2 D8); `relay` is its
   * first data namespace (`router` stays reserved).
   */
  readonly relay?: {
    readonly records?: RecordMap;
  };
}

export default function EntryServer(props: ServerEntrypointProps<InitialData>) {
  const initialData = props.initialData ?? {};
  const url = initialData.url ?? "/";
  const router = createStaticRouter(appRoutes, url, {
    middleware: [...middleware],
    notFound: notFoundRoute,
  });

  // A fresh Relay environment per server render, so no store state leaks
  // between requests — seeded from the prepare step's serialised records
  // (the same bytes the client hydrates from, so data-driven hydration
  // mismatch is excluded by construction). With a warm store the page's
  // queries render without fetching; nothing fetches through this
  // environment otherwise (Stage 2 injects a live executor for @defer).
  const relayEnvironment = createEnvironment({
    records: initialData.relay?.records,
  });

  // Paint the cookie-resolved theme on <html> for a flash-free first render —
  // the same element `usePreferredTheme` toggles on the client, and one React
  // does not hydrate (only `#root` is), so there is no mismatch to reconcile.
  return (
    <html lang={props.lang} className={initialData.theme}>
      <head>
        {props.otherHeadElements}
        {props.scriptElements}
        {props.linkElements}
      </head>
      <body>
        <div id="root">
          <HeadProvider>
            <RelayEnvironmentProvider environment={relayEnvironment}>
              <RouterProvider router={router}>
                <Outlet fallback={<p>Loading…</p>} />
              </RouterProvider>
            </RelayEnvironmentProvider>
          </HeadProvider>
        </div>
      </body>
    </html>
  );
}

export type { InitialData };
