/** Display labels for keys that render differently from their identifier */
export const KEY_LABELS = {
  a: "A",
  b: "B",
  c: "C",
  d: "D",
  e: "E",
  f: "F",
  g: "G",
  h: "H",
  i: "I",
  j: "J",
  k: "K",
  l: "L",
  m: "M",
  n: "N",
  o: "O",
  p: "P",
  q: "Q",
  r: "R",
  s: "S",
  t: "T",
  u: "U",
  v: "V",
  w: "W",
  x: "X",
  y: "Y",
  z: "Z",
  f1: "F1",
  f2: "F2",
  f3: "F3",
  f4: "F4",
  f5: "F5",
  f6: "F6",
  f7: "F7",
  f8: "F8",
  f9: "F9",
  f10: "F10",
  f11: "F11",
  f12: "F12",
  tab: "Tab",
  space: "Space",
  backspace: "Backspace",
  delete: "Del",
  escape: "Esc",
  shift: "Shift",
  ctrl: "Ctrl",
  alt: "Alt",
  cmd: "Cmd",
  option: "Option",
  meta: "Meta",
  capslock: "Caps Lock",
  enter: "↵",
  up: "↑",
  down: "↓",
  left: "←",
  right: "→",
  home: "Home",
  end: "End",
  pageup: "PgUp",
  pagedown: "PgDn",
} as const;

/** Accessible labels for keys whose label is a symbol */
export const ARIA_LABELS: Partial<Record<keyof typeof KEY_LABELS, string>> = {
  enter: "Enter",
  up: "Up",
  down: "Down",
  left: "Left",
  right: "Right",
} as const;
