// Generated by @canonical/summon-component:react v0.1.0

import type { Meta, StoryObj } from "@storybook/react-vite";
import Component from "./DropdownButton.js";

const meta: Meta<typeof Component> = {
  title: "Components/DropdownButton",
  component: Component,
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof Component>;

export const Default: Story = {
  args: {
    children: "DropdownButton",
    options: [
      { label: "Option A", value: "a" },
      { label: "Option B", value: "b" },
    ],
  },
};
