// Generated by @canonical/summon-component:react v0.1.0

import { renderToString } from "react-dom/server";
import { describe, expect, it } from "vitest";
import DropdownButton from "./DropdownButton.js";

describe("DropdownButton SSR", () => {
  it("renders without hydration errors", () => {
    const html = renderToString(
      <DropdownButton options={[{ label: "A", value: "a" }]}>
        Test content
      </DropdownButton>,
    );
    expect(html).toContain("Test content");
    expect(html).toContain("ds dropdown-button");
  });
});
