// Generated by @canonical/summon-component:react v0.1.0

import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import DropdownButton from "./DropdownButton.js";

describe("DropdownButton", () => {
  const options = [{ label: "Option A", value: "a" }];

  it("renders children", () => {
    render(<DropdownButton options={options}>Test content</DropdownButton>);
    expect(screen.getByText("Test content")).toBeInTheDocument();
  });

  it("applies custom className", () => {
    const { container } = render(
      <DropdownButton className="custom-class" options={options}>
        Content
      </DropdownButton>,
    );
    const wrapper = container.querySelector(".ds.dropdown-button");
    expect(wrapper).toBeInTheDocument();
    expect(wrapper?.className).toContain("custom-class");
  });

  it("passes through additional props", () => {
    render(<DropdownButton options={options}>Content</DropdownButton>);
    expect(screen.getByText("Content")).toBeInTheDocument();
    expect(screen.getByRole("dialog", { hidden: true })).toBeInTheDocument();
  });
});
