// Generated by @canonical/summon-component:react v0.1.0

import type React from "react";
import "./styles.css";
import Icon from "../Icon/Icon.js";
import Props from "./types.js";
import { useState } from "react";
import Popover from "lib/Popover/Popover.js";
import Button from "lib/Button/Button.js";

const componentCssClassName = "ds dropdown-button";

/**
 * DropdownButton component
 *
 * @implements ds:global.component.dropdown_button
 */
const DropdownButton = ({
  id,
  className,
  children,
  options,
  style,
  ...props
}: Props): React.ReactElement => {
  	// Derive aria-label from children if not explicitly provided
	const ariaLabel =
    props["aria-label"] ||
    (typeof children === "string" ? children : undefined);

	const [isOpen, setIsOpen] = useState(false);
	const icon = <Icon icon="chevron-down" />;

	return (
		<Popover content="I'm the popover">
			<Button icon={icon} iconPosition="end">
					{children}
			</Button>
		</Popover>
	);
};

export default DropdownButton;
