<!-- Generated by @canonical/summon-component:svelte v0.29.0-experimental.0 -->

<script lang="ts">
  import type { ExampleProps } from "./types.js";
  import "./styles.css";

  const componentCssClassName = "ds example";

  let { class: className, children, ...rest }: ExampleProps = $props();
</script>

<div
	class={[componentCssClassName, className]}
	data-testid="example"
	{...rest}
>
	{@render children?.()}
</div>
