// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import { describe, expect, it } from "vitest";
import { render, screen } from "@testing-library/react";
import Category from "./Category.js";

describe("Category", () => {
	it("renders children", () => {
		render(<Category>Test content</Category>);
		expect(screen.getByText("Test content")).toBeInTheDocument();
	});

	it("applies custom className", () => {
		render(<Category className="custom-class">Content</Category>);
		const element = screen.getByText("Content");
		expect(element.className).toContain("ds category");
		expect(element.className).toContain("custom-class");
	});

	it("passes through additional props", () => {
		render(<Category data-testid="test-component">Content</Category>);
		expect(screen.getByTestId("test-component")).toBeInTheDocument();
	});
});
