// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import type { Meta, StoryObj } from "@storybook/react";
import Category from "./Category.js";

const meta: Meta<typeof Category> = {
	title: "Components/Category",
	component: Category,
	tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof Category>;

export const Default: Story = {
	args: {
		children: "Hello, Category!",
	},
};

export const WithCustomClass: Story = {
	args: {
		children: "Custom styled",
		className: "custom-class",
	},
};
