// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import { renderToString } from "react-dom/server";
import { describe, expect, it } from "vitest";
import Category from "./Category.js";

describe("Category SSR", () => {
  it("renders without hydration errors", () => {
    const html = renderToString(<Category items={[]}>Test content</Category>);
    expect(html).toContain("Test content");
    expect(html).toContain("ds category");
  });
});
