// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import type React from "react";
import type { CategoryProps } from "./types.js";
import "./styles.css";

const componentCssClassName = "ds category";

/**
 * Category component
 */
const Category = ({
  className,
  children,
  title,
  items = [],
  ...props
}: CategoryProps): React.ReactNode => {
  return (
    <div
      className={[componentCssClassName, className].filter(Boolean).join(" ")}
      {...props}
    >
      <h3>{title}</h3>
      <ul>
        {items.map((item) => (
          <li key={item}>{item}</li>
        ))}
      </ul>
    </div>
  );
};

export default Category;
