// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import Category from "./Category.js";

describe("Category", () => {
  // TODO(#662): the component accepts `children` but silently drops them.
  // Unskip once the children-vs-props API is settled.
  it.skip("renders children", () => {
    render(<Category items={[]}>Test content</Category>);
    expect(screen.getByText("Test content")).toBeInTheDocument();
  });

  it("applies custom className", () => {
    render(
      <Category items={[]} className="custom-class">
        Content
      </Category>,
    );
    // The root element carries the classes; children may render in a descendant.
    const element = document.querySelector(".custom-class") as HTMLElement;
    expect(element.className).toContain("ds category");
    expect(element.className).toContain("custom-class");
  });

  it("passes through additional props", () => {
    render(
      <Category items={[]} data-testid="test-component">
        Content
      </Category>,
    );
    expect(screen.getByTestId("test-component")).toBeInTheDocument();
  });
});
