// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import Category from "./Category.js";

describe("Category", () => {
  it("renders the title and items", () => {
    render(<Category title="Cloud" items={["OpenStack", "MAAS"]} />);
    expect(screen.getByText("Cloud")).toBeInTheDocument();
    expect(screen.getByText("OpenStack")).toBeInTheDocument();
    expect(screen.getByText("MAAS")).toBeInTheDocument();
  });

  it("applies custom className", () => {
    const { container } = render(
      <Category items={[]} className="custom-class" />,
    );
    expect(container.firstChild).toHaveClass("ds", "category", "custom-class");
  });

  it("passes through additional props", () => {
    render(<Category items={[]} data-testid="test-component" />);
    expect(screen.getByTestId("test-component")).toBeInTheDocument();
  });
});
