// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import type { HTMLAttributes, ReactNode } from "react";

export interface CategoryProps extends HTMLAttributes<HTMLDivElement> {
  /** Content to render inside the component */
  children?: ReactNode;
  /** Category title */
  title?: string;
  /** List of items to display */
  items: string[];
}
