// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import type { HTMLAttributes } from "react";

/**
 * The component renders its title and items; it accepts no children.
 */
export interface CategoryProps
  extends Omit<HTMLAttributes<HTMLDivElement>, "children"> {
  /** Category title */
  title?: string;
  /** List of items to display */
  items: string[];
}
