/**
 * Generates ICON_MANIFEST — a content-hash manifest for the icons in
 * `icons/` — and writes a hashed copy of each SVG to `dist/icons/` for
 * cache-safe self-hosting.
 *
 * Filenames are stable across releases (`search.svg` never changes name even
 * when its glyph does), so a consumer who self-hosts `icons/` verbatim behind
 * long-lived cache headers can serve a stale icon indefinitely after a
 * `ds-assets` update. Hashing each file's contents into its distributed
 * filename (`search.a1b2c3d4.svg`) makes the filename itself the cache key,
 * at the granularity of the actual change — updating one icon only
 * invalidates that icon's URL, not the whole set. See docs/ICONS.md.
 *
 * The hashing itself is `buildAssetManifest` (src/build/), which is also
 * exported from `@canonical/ds-assets/build` so consumers can apply the same
 * content-addressing to their own custom icons. This script layers ds-assets-
 * specific concerns on top: ordering the manifest by `ICON_NAMES` (for a
 * stable, meaningful git diff) and emitting it as a typed `.ts` module.
 *
 * Run via `bun run build:icons-manifest` (wired into `build:package`, so a
 * normal `bun run build` keeps `dist/icons/` and the committed
 * `src/icons/manifest.generated.ts` in sync automatically). Also runnable
 * directly to regenerate the manifest after editing an icon by hand.
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { buildAssetManifest } from "../src/build/buildAssetManifest.js";
import { ICON_NAMES } from "../src/icons/constants.js";

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const manifestPath = join(packageRoot, "src", "icons", "manifest.generated.ts");

const hashedFileNames = buildAssetManifest({
  sourceDir: join(packageRoot, "icons"),
  outDir: join(packageRoot, "dist", "icons"),
});

const manifestEntries = ICON_NAMES.map((iconName) => {
  const hashedFileName = hashedFileNames[iconName];
  if (!hashedFileName) {
    throw new Error(
      `buildAssetManifest produced no entry for "${iconName}" — is icons/${iconName}.svg missing?`,
    );
  }
  return [iconName, hashedFileName] as const;
});

const manifestSource = `// AUTO-GENERATED by scripts/build-icon-manifest.ts — do not edit by hand.
// Regenerate with \`bun run build:icons-manifest\` after changing an icon.
import type { IconName } from "./types.js";

/**
 * Maps each icon name to its content-hashed distributed filename (the file
 * actually shipped in \`dist/icons/\`). \`Icon\` (in
 * \`@canonical/react-ds-global\`) reads this by default, so self-hosting
 * \`dist/icons/\` verbatim gets correct per-file cache invalidation with no
 * extra configuration. See docs/ICONS.md.
 */
const ICON_MANIFEST: Record<IconName, string> = {
${manifestEntries.map(([name, fileName]) => `  "${name}": "${fileName}",`).join("\n")}
};

export default ICON_MANIFEST;
`;

writeFileSync(manifestPath, manifestSource);

console.log(
  `Generated manifest and hashed copies for ${manifestEntries.length} icons.`,
);
