/**
 * Generates a content-hash manifest for the icons in `icons/`, and writes a
 * hashed copy of each SVG to `dist/icons/` for cache-safe self-hosting.
 *
 * Filenames are stable across releases (`search.svg` never changes name even
 * when its glyph does), so a consumer who self-hosts `icons/` verbatim behind
 * long-lived cache headers can serve a stale icon indefinitely after a
 * `ds-assets` update. Hashing each file's contents into its distributed
 * filename (`search.a1b2c3d4.svg`) makes the filename itself the cache key,
 * at the granularity of the actual change — updating one icon only
 * invalidates that icon's URL, not the whole set. See docs/ICONS.md.
 *
 * Run via `bun run build:icons-manifest` (wired into `build:package`, so a
 * normal `bun run build` keeps `dist/icons/` and the committed
 * `src/icons/manifest.generated.ts` in sync automatically). Also runnable
 * directly to regenerate the manifest after editing an icon by hand.
 */
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { ICON_NAMES } from "../src/icons/constants.js";

/** Matches the default hash length bundlers (Vite, webpack) use for their
 * own emitted assets — short enough to keep filenames readable, long enough
 * that collisions are not a practical concern for a set of this size. */
const HASH_LENGTH = 8;

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const iconsDir = join(packageRoot, "icons");
const distIconsDir = join(packageRoot, "dist", "icons");
const manifestPath = join(packageRoot, "src", "icons", "manifest.generated.ts");

mkdirSync(distIconsDir, { recursive: true });

const manifestEntries = ICON_NAMES.map((iconName) => {
  const contents = readFileSync(join(iconsDir, `${iconName}.svg`));
  const hash = createHash("sha256")
    .update(contents)
    .digest("hex")
    .slice(0, HASH_LENGTH);
  const hashedFileName = `${iconName}.${hash}.svg`;

  writeFileSync(join(distIconsDir, hashedFileName), contents);

  return [iconName, hashedFileName] as const;
});

const manifestSource = `// AUTO-GENERATED by scripts/build-icon-manifest.ts — do not edit by hand.
// Regenerate with \`bun run build:icons-manifest\` after changing an icon.
import type { IconName } from "./types.js";

/**
 * Maps each icon name to its content-hashed distributed filename (the file
 * actually shipped in \`dist/icons/\`). \`Icon\` (in
 * \`@canonical/react-ds-global\`) reads this by default, so self-hosting
 * \`dist/icons/\` verbatim gets correct per-file cache invalidation with no
 * extra configuration. See docs/ICONS.md.
 */
export const ICON_MANIFEST: Record<IconName, string> = {
${manifestEntries.map(([name, fileName]) => `  "${name}": "${fileName}",`).join("\n")}
};
`;

writeFileSync(manifestPath, manifestSource);

console.log(
  `Generated manifest and hashed copies for ${manifestEntries.length} icons.`,
);
