// Generated by @canonical/summon-component:react v0.1.0

import { renderToString } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { NumberInput } from "./NumberInput.js";

// Proves the presentational input renders to static HTML with no client runtime
// / form context — the server-rendered floor for progressive enhancement.
describe("NumberInput SSR", () => {
  it("renders a number input to static HTML without a form context", () => {
    const html = renderToString(<NumberInput name="qty" min={0} />);
    expect(html).toContain("<input");
    expect(html).toContain('type="number"');
    expect(html).toContain('name="qty"');
    expect(html).toContain("ds input number chrome");
  });
});
