// Generated by @canonical/summon-component:react v0.1.0

import { forwardRef, type ReactElement } from "react";
import type { NumberInputProps } from "./types.js";
import "./styles.css";

const componentCssClassName = "ds input number chrome";

/**
 * Presentational number input — pure markup, no react-hook-form. A native
 * numeric entry (`type="number"`) with optional prefix/suffix slots for units
 * or symbols (e.g. `$`, `kg`).
 *
 * Usable standalone (controlled via `value`/`onChange`, or uncontrolled) or via
 * the field tier, which spreads react-hook-form's `register()` result onto it.
 * @returns {ReactElement} - Rendered NumberInput
 */
export const NumberInput = forwardRef<HTMLInputElement, NumberInputProps>(
  function NumberInput(
    { id, className, style, prefix, suffix, ...nativeProps },
    ref,
  ): ReactElement {
    return (
      <div
        id={id}
        style={style}
        className={[componentCssClassName, className].filter(Boolean).join(" ")}
      >
        {prefix && <span className="prefix">{prefix}</span>}
        <input className="p" type="number" ref={ref} {...nativeProps} />
        {suffix && <span className="suffix">{suffix}</span>}
      </div>
    );
  },
);

export default NumberInput;
