// Generated by @canonical/summon-component:react v0.1.0

import type React from "react";

type NativeNumberProps = Omit<
  React.InputHTMLAttributes<HTMLInputElement>,
  "type" | "prefix"
>;

type AdditionalNumberProps = {
  /** Prefix element, rendered inside `span.prefix` (e.g. a currency symbol). */
  prefix?: React.ReactNode;

  /** Suffix element, rendered inside `span.suffix` (e.g. a unit). */
  suffix?: React.ReactNode;
};

/** Props for the presentational Number input (no react-hook-form). */
export type NumberInputProps = NativeNumberProps & AdditionalNumberProps;
