// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import { renderToString } from "react-dom/server";
import { describe, expect, it } from "vitest";
import CategoriesSection from "./CategoriesSection.js";
import fixtures from "./fixtures.js";

describe("CategoriesSection SSR", () => {
  it("renders without hydration errors", () => {
    const html = renderToString(<CategoriesSection />);
    expect(html).toContain(fixtures[0].title);
    expect(html).toContain("ds categories-section");
  });
});
