// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import CategoriesSection from "./CategoriesSection.js";
import fixtures from "./fixtures.js";

describe("CategoriesSection", () => {
  it("renders the category fixtures", () => {
    render(<CategoriesSection />);
    for (const category of fixtures) {
      expect(screen.getByText(category.title)).toBeInTheDocument();
    }
  });

  it("applies custom className", () => {
    const { container } = render(
      <CategoriesSection className="custom-class" />,
    );
    expect(container.firstChild).toHaveClass(
      "ds",
      "categories-section",
      "custom-class",
    );
  });

  it("passes through additional props", () => {
    render(<CategoriesSection data-testid="test-component" />);
    expect(screen.getByTestId("test-component")).toBeInTheDocument();
  });
});
