// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import type React from "react";
import type { CategoriesSectionProps } from "./types.js";
import "./styles.css";
import { TSection } from "../TSection/index.js";
import { Category } from "./common/index.js";
import fixtures from "./fixtures.js";

const componentCssClassName = "ds categories-section";

/**
 * CategoriesSection component
 */
const CategoriesSection = ({
  className,
  children,
  title,
  ...props
}: CategoriesSectionProps): React.ReactNode => {
  return (
    <TSection
      className={[componentCssClassName, className].filter(Boolean).join(" ")}
      title={title}
      {...props}
    >
      {fixtures.map((category) => (
        <Category key={category.id} {...category} />
      ))}
    </TSection>
  );
};

export default CategoriesSection;
