/**
 * The `token add-config` write body (lazily imported, off the fast path).
 *
 * A store-backed mutation: it counts the design tokens in the active graph (so
 * the plan reports how many tokens the config will cover) and derives the
 * terrazzo token-source globs from the configured design-system packages, then
 * returns a Task that writes `tokens.config.mjs`. The store read happens in the
 * async setup; the file write is the Task's single `WriteFile` effect, so a
 * plan-only preview (`mutation.preview`) describes the write without performing
 * it. Ported from the old shell's `token add-config` (terrazzo `defineConfig`).
 */

import { resolve } from "node:path";
import { $, exists, gen, type Task, writeFile } from "@canonical/task";
import type { PragmaRuntime } from "../../kernel/runtime/types.js";

/** The default token source when no design-system packages are configured. */
const DEFAULT_TOKEN_SOURCE =
  "node_modules/@canonical/ds-global/tokens/**/*.json";

/** The result of generating a terrazzo tokens config. */
export interface AddConfigResult {
  /** The absolute path written. */
  readonly path: string;
  /** How many `ds:Token` entities the active graph holds. */
  readonly tokenCount: number;
  /** The token-source globs written into the config. */
  readonly sources: readonly string[];
  /** Whether a `tokens.config.mjs` already existed (it is overwritten). */
  readonly alreadyExisted: boolean;
}

/** Count the `ds:Token` entities in the booted store (best-effort). */
async function countTokens(rt: PragmaRuntime): Promise<number> {
  try {
    const result = (await rt.query.sparql(
      "SELECT (COUNT(DISTINCT ?token) AS ?count) WHERE { ?token a ds:Token }",
    )) as { type?: string; bindings?: { count?: string }[] };
    const raw = result.bindings?.[0]?.count;
    return raw ? Number(raw) : 0;
  } catch {
    return 0;
  }
}

/** Derive the terrazzo token-source globs from the configured packages. */
async function resolveSources(rt: PragmaRuntime): Promise<string[]> {
  const { config } = await rt.loadConfig();
  const packages = config.packages ?? [];
  if (packages.length === 0) return [DEFAULT_TOKEN_SOURCE];
  return packages.map((pkg) => {
    const name = typeof pkg === "string" ? pkg : pkg.name;
    return `node_modules/${name}/tokens/**/*.json`;
  });
}

/** Render the terrazzo `tokens.config.mjs` content. */
function generateConfig(sources: readonly string[]): string {
  const sourceList = sources
    .map((source) => `    ${JSON.stringify(source)}`)
    .join(",\n");
  return `// tokens.config.mjs — generated by \`pragma token add-config\`
import { defineConfig } from "@canonical/terrazzo";

export default defineConfig({
  tokens: [
${sourceList},
  ],
  outDir: "./tokens/",
  plugins: [],
});
`;
}

/**
 * Build the Task that writes `tokens.config.mjs` for the terrazzo pipeline.
 *
 * @param rt - The runtime (its store is booted by the projector for needsStore).
 * @returns A Task yielding the write outcome.
 * @note Impure — reads the store + config; the write is the Task's effect.
 */
export async function runAddConfig(
  rt: PragmaRuntime,
): Promise<Task<AddConfigResult>> {
  const tokenCount = await countTokens(rt);
  const sources = await resolveSources(rt);
  const path = resolve(rt.cwd, "tokens.config.mjs");
  const content = generateConfig(sources);

  return gen(function* () {
    const alreadyExisted = yield* $(exists(path));
    yield* $(writeFile(path, content));
    return { path, tokenCount, sources, alreadyExisted };
  });
}
