// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

export type { ViewContentLayoutProps } from "./types.js";
export { ViewContentLayout } from "./ViewContentLayout.js";
