// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import { ViewContentLayout } from "./ViewContentLayout";

describe("ViewContentLayout", () => {
  it("renders children", () => {
    render(<ViewContentLayout>Test content</ViewContentLayout>);
    expect(screen.getByText("Test content")).toBeInTheDocument();
  });

  it("applies custom className", () => {
    render(
      <ViewContentLayout className="custom-class">Content</ViewContentLayout>,
    );
    const element = screen.getByText("Content");
    expect(element).toHaveClass("view-content-layout");
    expect(element).toHaveClass("custom-class");
  });

  it("passes through additional props", () => {
    render(
      <ViewContentLayout data-testid="test-component">
        Content
      </ViewContentLayout>,
    );
    expect(screen.getByTestId("test-component")).toBeInTheDocument();
  });
});
