// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import type { ViewContentLayoutProps } from "./types";
import "./styles.css";

/**
 * ViewContentLayout component
 */
export const ViewContentLayout = ({
  className,
  children,
  ...props
}: ViewContentLayoutProps): JSX.Element => {
  return (
    <div
      className={`ds view-content-layout${className ? ` ${className}` : ""}`}
      {...props}
    >
      {children}
    </div>
  );
};
