// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import type { Meta, StoryObj } from "@storybook/react";
import { ViewContentLayout } from "./ViewContentLayout.js";

const meta: Meta<typeof ViewContentLayout> = {
	title: "Components/ViewContentLayout",
	component: ViewContentLayout,
	tags: ["autodocs"],
	parameters: {
		layout: "fullscreen",
	},
};

export default meta;
type Story = StoryObj<typeof ViewContentLayout>;

export const Default: Story = {
	args: {
		children: "Hello, ViewContentLayout!",
	},
};

export const WithCustomClass: Story = {
	args: {
		children: "Custom styled",
		className: "custom-class",
	},
};
