// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import { renderToString } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { ViewContentLayout } from "./ViewContentLayout";

describe("ViewContentLayout SSR", () => {
  it("renders without hydration errors", () => {
    const html = renderToString(
      <ViewContentLayout>Test content</ViewContentLayout>,
    );
    expect(html).toContain("Test content");
    expect(html).toContain("view-content-layout");
  });
});
