// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import type { Meta, StoryObj } from "@storybook/react";
import * as decorators from "../../storybook/decorators.js";
import { ViewContentLayout } from "./ViewContentLayout.js";

const meta: Meta<typeof ViewContentLayout> = {
	title: "Components/ViewContentLayout",
	component: ViewContentLayout,
	tags: ["autodocs"],
	parameters: {
		layout: "fullscreen",
	},
};

export default meta;
type Story = StoryObj<typeof ViewContentLayout>;

const ExampleCard = () => (
	<div
		style={{
			border: "1px solid #ccc",
			minHeight: "300px",
			backgroundColor: "#f9f9f9",
		}}
	>
		This is an example card inside the ViewLayout.
	</div>
);

export const Default: Story = {
	args: {
		// children: "Hello, ViewContentLayout!",
		children: [...Array(3)].map((_, index) => <ExampleCard key={index} />),
	},
	// decorators: [decorators.threeColumnGrid()],
};

export const Fluid: Story = {
	args: {
		children: [...Array(8)].map((_, index) => <ExampleCard key={index} />),
	},
	// decorators: [decorators.fluidGrid()],
};
