// Generated by @canonical/summon-component:react v0.1.0

import { describe, expect, it } from "vitest";
import { render, screen } from "@testing-library/react";
import LensBreadcrumbs from "./LensBreadcrumbs.js";

describe("LensBreadcrumbs", () => {
	it("renders children", () => {
		render(<LensBreadcrumbs>Test content</LensBreadcrumbs>);
		expect(screen.getByText("Test content")).toBeInTheDocument();
	});

	it("applies custom className", () => {
		render(<LensBreadcrumbs className="custom-class">Content</LensBreadcrumbs>);
		const element = screen.getByText("Content");
		expect(element.className).toContain("ds lens-breadcrumbs");
		expect(element.className).toContain("custom-class");
	});

	it("passes through additional props", () => {
		render(<LensBreadcrumbs data-testid="test-component">Content</LensBreadcrumbs>);
		expect(screen.getByTestId("test-component")).toBeInTheDocument();
	});
});
