// Generated by @canonical/summon-component:lit v0.1.0

import { afterEach, beforeEach, describe, expect, it } from "vitest";
import "./LogoSection.js";
import type LogoSection from "./LogoSection.js";

describe("LogoSection component", () => {
  let elem: LogoSection;

  beforeEach(async () => {
    elem = document.createElement("ds-logo-section") as LogoSection;
    document.body.appendChild(elem);
    await customElements.whenDefined("ds-logo-section");
    await elem.updateComplete;
  });

  afterEach(() => {
    elem.remove();
  });

  it("should have correct tag name", () => {
    expect(elem.tagName.toLowerCase()).toBe("ds-logo-section");
  });

  describe("default mode", () => {
    it("renders a <section> element", () => {
      expect(
        elem.shadowRoot?.querySelector("section.ds.logo-section"),
      ).toBeTruthy();
    });

    it("renders a top rule", () => {
      expect(elem.shadowRoot?.querySelector("hr")).toBeTruthy();
    });

    it("renders the title text", async () => {
      elem.title = "Our partners";
      await elem.updateComplete;
      expect(
        elem.shadowRoot?.querySelector(".title")?.textContent?.trim(),
      ).toBe("Our partners");
    });

    it("renders title as a link when titleHref is set", async () => {
      elem.title = "Our partners";
      elem.titleHref = "https://example.com";
      await elem.updateComplete;
      const link = elem.shadowRoot?.querySelector(".title .link");
      expect(link?.getAttribute("href")).toBe("https://example.com");
      expect(link?.textContent).toBe("Our partners");
    });

    it("does not render description text when description is empty", async () => {
      await elem.updateComplete;
      const secondCol = elem.shadowRoot?.querySelector(".description");
      expect(secondCol?.textContent?.trim()).toBe("");
    });

    it("renders description as a link when descriptionHref is set", async () => {
      elem.description = "Learn more";
      elem.descriptionHref = "https://example.com/about";
      await elem.updateComplete;
      const link = elem.shadowRoot?.querySelector(".description .link");
      expect(link?.getAttribute("href")).toBe("https://example.com/about");
      expect(link?.textContent?.trim()).toBe("Learn more");
    });

    it("exposes a logos slot", () => {
      expect(elem.shadowRoot?.querySelector("slot[name='logos']")).toBeTruthy();
    });

    it("exposes a cta slot", () => {
      expect(elem.shadowRoot?.querySelector("slot[name='cta']")).toBeTruthy();
    });
  });

  describe("default prop values", () => {
    it("defaults mode to 'default'", () => {
      expect(elem.mode).toBe("default");
    });

    it("defaults title to empty string", () => {
      expect(elem.title).toBe("");
    });

    it("defaults description to empty string", () => {
      expect(elem.description).toBe("");
    });
  });

  describe("minimal mode", () => {
    beforeEach(async () => {
      elem.mode = "minimal";
      await elem.updateComplete;
    });

    it("renders a <div> instead of <section>", () => {
      expect(
        elem.shadowRoot?.querySelector("div.ds.logo-section"),
      ).toBeTruthy();
      expect(elem.shadowRoot?.querySelector("section")).toBeNull();
    });

    it("does not render the heading block", () => {
      expect(elem.shadowRoot?.querySelector(".heading")).toBeNull();
    });

    it("does not render title even when set", async () => {
      elem.title = "Our partners";
      await elem.updateComplete;
      expect(elem.shadowRoot?.querySelector("h4")).toBeNull();
    });

    it("exposes a logos slot", () => {
      expect(elem.shadowRoot?.querySelector("slot[name='logos']")).toBeTruthy();
    });
  });
});
