// Generated by @canonical/summon-component-lit v0.1.0

import type { Meta, StoryObj } from "@storybook/web-components-vite";
import { html } from "lit";

import "./LogoSection.js";
import type LogoSection from "./LogoSection.js";

const meta = {
  title: "Web Components/LogoSection",
  tags: ["autodocs"],
  decorators: [
    (story) => html`
			<ds-site-layout>
				${story()}
			</ds-site-layout>
		`,
  ],
} satisfies Meta<LogoSection>;

export default meta;
type Story = StoryObj<LogoSection>;

export const Default: Story = {
  render: () => html`
		<ds-logo-section
			title="The quick brown fox jumps over the lazy dog"
			description="The quick brown fox jumps over the lazy dog"
			description-href="#"
		>
			<img slot="logos" src="https://assets.ubuntu.com/v1/38fdfd23-Dell-logo.png" alt="Dell Technologies" loading="lazy">
			<img slot="logos" src="https://assets.ubuntu.com/v1/cd5f636a-hp-logo.png" alt="Hewlett Packard" loading="lazy">
			<img slot="logos" src="https://assets.ubuntu.com/v1/f90702cd-lenovo-logo.png" alt="Lenovo" loading="lazy">
			<img slot="logos" src="https://assets.ubuntu.com/v1/2ef3c028-amazon-web-services-logo.png" alt="Amazon Web Services" loading="lazy">
			<img slot="logos" src="https://assets.ubuntu.com/v1/cb7ef8ac-ibm-cloud-logo.png" alt="IBM Cloud" loading="lazy">
			<img slot="logos" src="https://assets.ubuntu.com/v1/210f44e4-microsoft-azure-new-logo.png" alt="Microsoft Azure" loading="lazy">
			<img slot="logos" src="https://assets.ubuntu.com/v1/a554a818-google-cloud-logo.png" alt="Google Cloud" loading="lazy">
			<img slot="logos" src="https://assets.ubuntu.com/v1/b3e692f4-oracle-new-logo.png" alt="Oracle" loading="lazy">

		</ds-logo-section>
	`,
};

export const Minimal: Story = {
  render: () => html`
		<ds-logo-section
			title="The quick brown fox jumps over the lazy dog"
			description="The quick brown fox jumps over the lazy dog"
			mode="minimal"
		>
			<img slot="logos" src="https://assets.ubuntu.com/v1/38fdfd23-Dell-logo.png" alt="Dell Technologies" loading="lazy">
			<img slot="logos" src="https://assets.ubuntu.com/v1/cd5f636a-hp-logo.png" alt="Hewlett Packard" loading="lazy">
			<img slot="logos" src="https://assets.ubuntu.com/v1/f90702cd-lenovo-logo.png" alt="Lenovo" loading="lazy">
			<img slot="logos" src="https://assets.ubuntu.com/v1/2ef3c028-amazon-web-services-logo.png" alt="Amazon Web Services" loading="lazy">
			<img slot="logos" src="https://assets.ubuntu.com/v1/cb7ef8ac-ibm-cloud-logo.png" alt="IBM Cloud" loading="lazy">
			<img slot="logos" src="https://assets.ubuntu.com/v1/210f44e4-microsoft-azure-new-logo.png" alt="Microsoft Azure" loading="lazy">
			<img slot="logos" src="https://assets.ubuntu.com/v1/a554a818-google-cloud-logo.png" alt="Google Cloud" loading="lazy">
			<img slot="logos" src="https://assets.ubuntu.com/v1/b3e692f4-oracle-new-logo.png" alt="Oracle" loading="lazy">
		</ds-logo-section>
	`,
};
