// Generated by @canonical/summon-component:lit v0.1.0

export interface Props {
  /** Heading text for the section. Ignored in `minimal` mode. */
  title?: string;
  /** When set, wraps the title in an anchor tag. Ignored in `minimal` mode. */
  titleHref?: string;
  /** Descriptive text displayed beside the heading. Ignored in `minimal` mode. */
  description?: string;
  /** When set, wraps the description in an anchor tag. Ignored in `minimal` mode. */
  descriptionHref?: string;
  /**
   * Layout mode of the section.
   * - `default`: Full `<section>` with heading, description, and CTA slots.
   * - `minimal`: Plain `<div>` wrapper with only the logo grid.
   * @default "default"
   */
  mode?: "default" | "minimal";
}

export default Props;
