/**
 * PROTECTED — the summon bin's half of the byte-equality conformance suite.
 *
 * The fixture, the answers, the expected path set and the comparison all come
 * from `@canonical/summon-core/testing`; this file supplies only THIS bin's
 * execution composition, and `packages/cli/pragma` supplies its own against the
 * same fixture. That is what makes the suite a conformance suite rather than
 * two tests that happen to agree.
 *
 * The composition below is the one `registerFromBarrel`'s action handler
 * performs, and it is not the same as pragma's: this bin calls
 * `generator.generate` DIRECTLY over answers it defaulted itself, where pragma
 * goes through summon-core's `execute`. Two paths into one core is exactly the
 * shape a stamp or answer divergence hides in, so the reproduction here is
 * deliberate rather than a shortcut through `execute`.
 *
 * Both compositions are checked against the SAME written-down `CONFORMANCE_TREE`
 * the core ships, so a failure names which composition moved rather than only
 * that the two disagree — and neither can pass by agreeing with the other on a
 * tree they both got wrong.
 */

import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  answerPromptWithDefaults,
  autoPrompt,
  createGeneratorStamp,
  createStampOnEffectStart,
  execute,
  type GeneratorDefinition,
  runGeneratorTask,
} from "@canonical/summon-core";
import {
  assertByteEqual,
  CONFORMANCE_ANSWERS,
  CONFORMANCE_TREE,
  conformanceGenerator,
  snapshotTree,
} from "@canonical/summon-core/testing";
import { describe, expect, it } from "vitest";

const freshCwd = (): string => mkdtempSync(join(tmpdir(), "summon-conf-"));

/**
 * Fill in a generator's prompt defaults for answers the caller did not give.
 *
 * A verbatim reproduction of `registerFromBarrel`'s `applyDefaults`, which is a
 * module-private helper of the action handler. Reproduced rather than exported:
 * the point of the case is that the bin's OWN defaulting agrees with
 * summon-core's, so importing the core's would assume what is under test.
 */
function applyDefaults(
  prompts: GeneratorDefinition["prompts"],
  answers: Record<string, unknown>,
): Record<string, unknown> {
  const result = { ...answers };
  for (const prompt of prompts) {
    if (!(prompt.name in result) && prompt.default !== undefined) {
      result[prompt.name] = prompt.default;
    }
  }
  return result;
}

/** The summon bin's composition: defaults → generate → runGeneratorTask. */
async function produceViaSummonBin(): Promise<Map<string, string>> {
  const dir = freshCwd();
  const answers = applyDefaults(conformanceGenerator.prompts, {
    ...CONFORMANCE_ANSWERS,
  });
  await runGeneratorTask(conformanceGenerator.generate(answers), {
    cwd: dir,
    promptHandler: answerPromptWithDefaults,
    onEffectStart: createStampOnEffectStart(
      createGeneratorStamp(conformanceGenerator),
    ),
    onLog: () => {},
  });
  return snapshotTree(dir);
}

/** The `execute` composition — the one pragma's kernel drives. */
async function produceViaExecute(): Promise<Map<string, string>> {
  const dir = freshCwd();
  const answers = { ...CONFORMANCE_ANSWERS };
  await runGeneratorTask(
    execute(conformanceGenerator, {
      prompt: autoPrompt(answers),
      params: answers,
    }),
    {
      cwd: dir,
      promptHandler: autoPrompt(answers),
      onEffectStart: createStampOnEffectStart(
        createGeneratorStamp(conformanceGenerator),
      ),
      onLog: () => {},
    },
  );
  return snapshotTree(dir);
}

describe("byte-equality conformance — the summon bin's seam (PROTECTED)", () => {
  it("produces the shared fixture's exact tree, through this bin's composition", async () => {
    const viaBin = await produceViaSummonBin();
    expect(() => assertByteEqual(viaBin, CONFORMANCE_TREE)).not.toThrow();
  });

  it("agrees with the `execute` composition pragma's kernel drives", async () => {
    const viaExecute = await produceViaExecute();
    expect(() => assertByteEqual(viaExecute, CONFORMANCE_TREE)).not.toThrow();
  });

  it("stamps with the generator's DISPLAY name, and leaves JSON unstamped", async () => {
    // The stamp identity is the one thing a bin can derive for itself, so it is
    // the one thing worth naming rather than only diffing. JSON has no comment
    // syntax, so a bin that stamps unconditionally diverges on that file alone.
    const tree = await produceViaSummonBin();
    const source = tree.get("src/widget-factory/index.ts") ?? "";
    expect(source.split("\n").at(0)).toBe(
      "// Generated by @canonical/summon-core:conformance v1.0.0",
    );
    expect(tree.get("src/widget-factory/NOTES.md")?.split("\n").at(0)).toBe(
      "<!-- Generated by @canonical/summon-core:conformance v1.0.0 -->",
    );
    expect(tree.get("src/widget-factory/config.json")?.startsWith("{")).toBe(
      true,
    );
  });
});
