/**
 * PROTECTED — the summon bin's half of the byte-equality conformance suite.
 *
 * The fixture, the answers, the expected path set and the comparison all come
 * from `@canonical/summon-core/testing`; this file supplies only THIS bin's
 * execution composition, and `packages/cli/pragma` supplies its own against the
 * same fixture. That is what makes the suite a conformance suite rather than
 * two tests that happen to agree.
 *
 * The composition below is the one `registerFromBarrel`'s action handler
 * performs, and it is not the same as pragma's: this bin calls
 * `generator.generate` DIRECTLY over answers `applyDefaults` filled in, where
 * pragma drives `executeVerb` over a `VerbSpec` with the stamp on
 * `shapeEffect` (`packages/cli/pragma/src/capabilities/create/
 * byteEquality.test.ts` owns that one). Two paths into one core is exactly the
 * shape a stamp or answer divergence hides in.
 *
 * The defaulting is IMPORTED from `registration/applyDefaults.ts` rather than
 * reproduced: a copy here would stay green through the drift in the production
 * copy that this suite exists to catch on the answer side.
 *
 * There is deliberately no case driving summon-core's own `execute` here. The
 * core runs that composition itself, in its own third-consumer case, and a copy
 * of it in this package would exercise no code this package owns — the kit's
 * index says so in as many words.
 */

import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  answerPromptWithDefaults,
  createGeneratorStamp,
  createStampOnEffectStart,
  runGeneratorTask,
} from "@canonical/summon-core";
import {
  assertByteEqual,
  CONFORMANCE_ANSWERS,
  CONFORMANCE_TREE,
  conformanceGenerator,
  snapshotTree,
} from "@canonical/summon-core/testing";
import { describe, expect, it } from "vitest";
import { applyDefaults } from "./registration/applyDefaults.js";

const freshCwd = (): string => mkdtempSync(join(tmpdir(), "summon-conf-"));

/**
 * The summon bin's composition: defaults → generate → runGeneratorTask.
 *
 * `withNotes` is deliberately WITHHELD from the supplied answers. Its value in
 * `CONFORMANCE_ANSWERS` is also its prompt default and it gates a whole file,
 * so the shared tree only comes out right if `applyDefaults` puts it back —
 * which is what makes this case measure the bin's defaulting instead of
 * passing straight through it. The other two answers are supplied, as a real
 * invocation supplies its flags.
 *
 * @returns The produced tree, keyed by relative POSIX path.
 * @note Impure — writes a fresh temp tree and reads it back.
 */
async function produceViaSummonBin(): Promise<Map<string, string>> {
  const dir = freshCwd();
  const { withNotes: _withheld, ...supplied } = CONFORMANCE_ANSWERS;
  const answers = applyDefaults(conformanceGenerator.prompts, supplied);
  expect(answers).toEqual({ ...CONFORMANCE_ANSWERS });
  await runGeneratorTask(conformanceGenerator.generate(answers), {
    cwd: dir,
    promptHandler: answerPromptWithDefaults,
    onEffectStart: createStampOnEffectStart(
      createGeneratorStamp(conformanceGenerator),
    ),
    onLog: () => {},
  });
  return snapshotTree(dir);
}

/**
 * One produced file's bytes, or a throw naming the path that is absent.
 *
 * The tree is this test's own output, not an external payload, so a `?? ""`
 * here would report a content mismatch against an empty string where the real
 * failure is a seam that stopped writing the file (cs:code.fallback.defensive).
 *
 * @param tree - The snapshot `produceViaSummonBin` returned.
 * @param path - The POSIX-relative path `CONFORMANCE_TREE` declares.
 * @returns The file's bytes as text.
 */
function readProduced(tree: Map<string, string>, path: string): string {
  const source = tree.get(path);
  if (source === undefined) {
    throw new Error(`the produced tree is missing ${path}`);
  }
  return source;
}

describe("byte-equality conformance — the summon bin's seam (PROTECTED)", () => {
  it("produces the shared fixture's exact tree, through this bin's composition", async () => {
    const viaBin = await produceViaSummonBin();
    expect(() => assertByteEqual(viaBin, CONFORMANCE_TREE)).not.toThrow();
  });

  it("stamps with the generator's DISPLAY name, and leaves JSON unstamped", async () => {
    // The stamp identity is the one thing a bin can derive for itself, so it is
    // the one thing worth naming rather than only diffing. JSON has no comment
    // syntax, so a bin that stamps unconditionally diverges on that file alone.
    const tree = await produceViaSummonBin();
    expect(
      readProduced(tree, "src/widget-factory/index.ts").split("\n").at(0),
    ).toBe("// Generated by @canonical/summon-core:conformance v1.0.0");
    expect(
      readProduced(tree, "src/widget-factory/NOTES.md").split("\n").at(0),
    ).toBe("<!-- Generated by @canonical/summon-core:conformance v1.0.0 -->");
    expect(
      readProduced(tree, "src/widget-factory/config.json").startsWith("{"),
    ).toBe(true);
  });
});
