<!-- Generated by @canonical/summon:component-svelte v0.1.0 -->

<script lang="ts">
  import { CollapsedItems, ExpandedItems } from "./common/index.js";
  import type { BreadcrumbsProps, PossiblyCollapsedSegment } from "./types.js";
  import "./styles.css";

  const componentCssClassName = "ds breadcrumbs";

  const {
    class: className,
    segments,
    minNumExpanded = 1,
    ...rest
  }: BreadcrumbsProps = $props();

  const maxNumCollapsed = $derived(
    minNumExpanded === "all"
      ? 0
      : Math.max(0, segments.length - Math.max(0, minNumExpanded)),
  );
  let containerWidth = $state<number>();
  let segmentWidths = $state<number[]>([]);

  const [collapsed, expanded] = $derived.by(
    (): [
      collapsed: PossiblyCollapsedSegment[],
      expanded: PossiblyCollapsedSegment[],
    ] => {
      if (
        // Bail out if we don't want to collapse any segments before reading `containerWidth` or `segmentWidths`
        // This way `$derived` won't rerun unnecessarily when the widths change
        maxNumCollapsed === 0 ||
        // We have not measured the container width yet
        containerWidth === undefined
      ) {
        // No segments are collapsed
        return [[], segments];
      }

      let expandedWidth = segmentWidths
        // When the number of segments passed as a prop decreases, the widths of the unmounted `li`s are not removed from the `segmentWidths`,
        // This makes sure, that we use the widths of the segments that are actually rendered in any given moment
        .slice(0, segments.length)
        .reduce((acc, width) => acc + width, 0);

      const collapsed: PossiblyCollapsedSegment[] = [];
      let i = 0;
      // Move the segments from the start one by one to the collapsed list until we can fit the rest in the `containerWidth` or we have collapsed the maximum number of segments
      while (
        i < segments.length &&
        expandedWidth >= containerWidth &&
        i < maxNumCollapsed
      ) {
        collapsed.push({ ...segments[i], collapsed: true });
        expandedWidth -= segmentWidths[i];
        i++;
      }

      // The rest of the segments are expanded
      const expanded = segments.slice(i);

      return [collapsed, expanded];
    },
  );
</script>

<nav
  aria-label="Breadcrumbs"
  class={[componentCssClassName, className]}
  {...rest}
>
  <ol>
    {#if collapsed.length > 0}
      <CollapsedItems segments={collapsed} hasCurrent={expanded.length === 0} />
    {/if}
    <ExpandedItems
      segments={[...collapsed, ...expanded]}
      bind:segmentWidths
      bind:containerWidth
      canCollapseMore={collapsed.length < maxNumCollapsed}
    />
  </ol>
</nav>

<!-- @component
`Breadcrumbs` is a navigation component used to display the current page's location within a navigational hierarchy. It allows users to easily navigate back to previous pages or sections.

## Example Usage
```svelte
<Breadcrumbs
  segments={[
    { label: "Project", href: "/launchpad" },
    { label: "Repository", href: "/launchpad/launchpad-ui" },
    {
      label: "Merge proposals",
      href: "/launchpad/launchpad-ui/merge-proposals",
    },
    {
      label: "475346: update ibugtarget for template",
      href: "/launchpad/launchpad-ui/merge-proposals/475346",
    },
  ]}
  minNumExpanded={2}
/>
```
-->
