// Generated by @canonical/summon:component-svelte v0.1.0

import type { SvelteHTMLElements } from "svelte/elements";

export interface Segment {
  label: string;
  href?: string;
}

export interface BreadcrumbsProps
  extends Omit<SvelteHTMLElements["nav"], "children"> {
  /**
   * Breadcrumb segments.
   */
  segments: Segment[];
  /**
   * The number of segments, from the end, that should never be collapsed.
   * If set to `all` or a number greater or equal to the total number of segments, no segments will be collapsed.
   *
   * @default 1
   */
  minNumExpanded?: "all" | number;
}

export interface PossiblyHiddenSegment extends Segment {
  hidden?: boolean;
}
