// Generated by @canonical/summon-application:application/react v0.1.0

import {
  type AnyRoute,
  group,
  type NavigationContext,
  type RouteMiddleware,
  type RouteParamValues,
  redirect,
  route,
  wrapper,
} from "@canonical/router-core";
import type { ReactElement, ReactNode } from "react";
import accountRoutes from "#domains/account/routes.js";
import componentsRoutes from "#domains/components/routes.js";
import { LensFilterProvider } from "#domains/lenses/definitions/lensFilterContext.js";
import definitionsRoutes from "#domains/lenses/definitions/routes.js";
import journeysRoutes from "#domains/lenses/journeys/routes.js";
import lensRoutes from "#domains/lenses/routes.js";
import standardsRoutes from "#domains/lenses/standards/routes.js";
import marketingRoutes from "#domains/marketing/routes.js";
import playgroundRoutes from "#domains/playground/routes.js";
import Shell from "#lib/Shell/index.js";

const protectedPaths = new Set(["/account"]);

function hasDemoAuth(search: unknown): boolean {
  const authValue = (search as Record<string, unknown>)?.auth;

  return authValue === "1";
}

export function getAuthRedirectHref(input: string | URL): string | null {
  // Absolute URLs are used as-is; relative paths resolve against a dummy base.
  const url =
    input instanceof URL ? input : new URL(input, "https://router.local");

  if (
    !protectedPaths.has(url.pathname) ||
    hasDemoAuth({ auth: url.searchParams.get("auth") })
  ) {
    return null;
  }

  return `/login?from=${encodeURIComponent(url.pathname)}`;
}

export function withAuth(loginPath: string): RouteMiddleware {
  return ((currentRoute: AnyRoute) => {
    if (!protectedPaths.has(currentRoute.url)) {
      return currentRoute;
    }

    const currentPrefetch = currentRoute.prefetch;

    return {
      ...currentRoute,
      prefetch: (
        params: unknown,
        search: unknown,
        context: NavigationContext,
      ) => {
        if (!hasDemoAuth(search)) {
          const from = currentRoute.render(
            (params ?? {}) as RouteParamValues | Record<string, never>,
          );

          redirect(`${loginPath}?from=${encodeURIComponent(from)}`, 302);
        }

        if (currentPrefetch) {
          return currentPrefetch(params, search, context);
        }
      },
    };
  }) as RouteMiddleware;
}

/**
 * Every public route mounts inside the DocsShell — the one shell instance
 * of `layout.shell` (P-4.1). The wrapper is deliberately just the Shell:
 * the frame owns rail/strip/canvas/footer, routes own only their canvas.
 *
 * The one addition (AV-274): the Definitions lens's filter provider sits
 * ABOVE the Shell. It has to. The Shell renders the mode strip, and a
 * route claims the strip's sockets with static `meta` — so the strip's
 * Controls are mounted BY THE FRAME, as siblings of the canvas rather than
 * descendants of the page. No prop path exists from the explorer up to
 * them, so the shared filter has to cross that boundary through context,
 * and the provider must therefore enclose both the strip and the canvas.
 *
 * Non-Definitions routes pay effectively nothing: the provider is one
 * `useState` holding a no-op filter that nothing reads, since the other
 * lenses claim no sockets. The alternative — widening `StripSlotsEntry` so
 * every claim can carry live state — would make every future lens pay for
 * this one's requirement, which is the larger cost.
 */
const publicLayout = wrapper<ReactElement>({
  id: "public-layout",
  component: ({ children }: { children: ReactNode }) => (
    <LensFilterProvider>
      <Shell>{children}</Shell>
    </LensFilterProvider>
  ),
});

const notFoundRoute = route({
  url: "/not-found",
  component: () => (
    <section>
      <h1>Page not found</h1>
      <p>The page you are looking for does not exist.</p>
    </section>
  ),
});

const [guide, home] = group(publicLayout, [
  marketingRoutes.guide,
  marketingRoutes.home,
] as const);

const [account, login] = group(publicLayout, [
  accountRoutes.account,
  accountRoutes.login,
] as const);

const [playground] = group(publicLayout, [
  playgroundRoutes.playground,
] as const);

// The v1 lens set (owner-ruled order): Home · Components · Definitions ·
// Standards · Guides. Home is marketingRoutes.home above; the Components
// lens is live (catalog + entity, P-5) from `#domains/components`; the
// Definitions lens is live (the explorer triptych + term view, P-5) from
// `#domains/lenses/definitions`; the Standards lens is live (the
// category-grouped index + reading pages, P-5) from
// `#domains/lenses/standards`; Guides stays a stub until P-5 builds its
// views.
const [
  components,
  definitions,
  standards,
  journeys,
  guides,
  componentEntity,
  definitionsTerm,
  standardEntity,
  journeysJob,
] = group(publicLayout, [
  componentsRoutes.components,
  definitionsRoutes.definitions,
  standardsRoutes.standards,
  journeysRoutes.journeys,
  lensRoutes.guides,
  componentsRoutes.componentEntity,
  definitionsRoutes.definitionsTerm,
  standardsRoutes.standardEntity,
  journeysRoutes.journeysJob,
] as const);

const appRoutes = {
  guide,
  home,
  account,
  login,
  playground,
  components,
  definitions,
  standards,
  journeys,
  guides,
  componentEntity,
  definitionsTerm,
  standardEntity,
  journeysJob,
} as const;

export type AppRoutes = typeof appRoutes;

declare module "@canonical/router-react" {
  interface RouterRegister {
    routes: AppRoutes;
  }
}

export const middleware = [withAuth("/login")] as const;

export { appRoutes, notFoundRoute };
