import { pure } from "@canonical/task";
import { describe, expect, it } from "vitest";
import applyStamp from "./applyStamp.js";
import runTaskWithStamp from "./runTaskWithStamp.js";
import type StampConfig from "../types/StampConfig.js";

const stamp: StampConfig = { generator: "test-gen", version: "1.0.0" };

// =============================================================================
// applyStamp
// =============================================================================

describe("applyStamp", () => {
  it("stamps TypeScript files with single-line comment", () => {
    expect(applyStamp("file.ts", "const x = 1;", stamp)).toBe(
      "// Generated by test-gen v1.0.0\n\nconst x = 1;",
    );
  });

  it("stamps TSX files with single-line comment", () => {
    expect(applyStamp("Component.tsx", "<div />", stamp)).toBe(
      "// Generated by test-gen v1.0.0\n\n<div />",
    );
  });

  it("stamps JavaScript files with single-line comment", () => {
    expect(applyStamp("app.js", "console.log(1);", stamp)).toBe(
      "// Generated by test-gen v1.0.0\n\nconsole.log(1);",
    );
  });

  it("stamps CSS files with block comment (preferBlock)", () => {
    expect(applyStamp("styles.css", "body {}", stamp)).toBe(
      "/* Generated by test-gen v1.0.0 */\n\nbody {}",
    );
  });

  it("stamps SCSS files with single-line comment", () => {
    expect(applyStamp("styles.scss", "$color: red;", stamp)).toBe(
      "// Generated by test-gen v1.0.0\n\n$color: red;",
    );
  });

  it("stamps HTML files with HTML comment", () => {
    expect(applyStamp("page.html", "<div></div>", stamp)).toBe(
      "<!-- Generated by test-gen v1.0.0 -->\n\n<div></div>",
    );
  });

  it("stamps SVG files with HTML comment", () => {
    expect(applyStamp("icon.svg", "<svg></svg>", stamp)).toBe(
      "<!-- Generated by test-gen v1.0.0 -->\n\n<svg></svg>",
    );
  });

  it("stamps Svelte files with HTML comment", () => {
    expect(applyStamp("App.svelte", "<script></script>", stamp)).toBe(
      "<!-- Generated by test-gen v1.0.0 -->\n\n<script></script>",
    );
  });

  it("stamps MDX files with JSX comment", () => {
    expect(applyStamp("doc.mdx", "# Hello", stamp)).toBe(
      "{/* Generated by test-gen v1.0.0 */}\n\n# Hello",
    );
  });

  it("stamps SQL files with double-dash comment", () => {
    expect(applyStamp("query.sql", "SELECT 1;", stamp)).toBe(
      "-- Generated by test-gen v1.0.0\n\nSELECT 1;",
    );
  });

  it("stamps YAML files with hash comment", () => {
    expect(applyStamp("config.yaml", "key: value", stamp)).toBe(
      "# Generated by test-gen v1.0.0\n\nkey: value",
    );
  });

  it("stamps YML files with hash comment", () => {
    expect(applyStamp("ci.yml", "name: CI", stamp)).toBe(
      "# Generated by test-gen v1.0.0\n\nname: CI",
    );
  });

  it("stamps shell scripts with hash comment", () => {
    expect(applyStamp("setup.sh", "echo hi", stamp)).toBe(
      "# Generated by test-gen v1.0.0\n\necho hi",
    );
  });

  it("stamps Python files with hash comment", () => {
    expect(applyStamp("main.py", "print(1)", stamp)).toBe(
      "# Generated by test-gen v1.0.0\n\nprint(1)",
    );
  });

  it("stamps Go files with single-line comment", () => {
    expect(applyStamp("main.go", "package main", stamp)).toBe(
      "// Generated by test-gen v1.0.0\n\npackage main",
    );
  });

  it("stamps Rust files with single-line comment", () => {
    expect(applyStamp("lib.rs", "fn main() {}", stamp)).toBe(
      "// Generated by test-gen v1.0.0\n\nfn main() {}",
    );
  });

  it("stamps Markdown files with HTML comment", () => {
    expect(applyStamp("README.md", "# Title", stamp)).toBe(
      "<!-- Generated by test-gen v1.0.0 -->\n\n# Title",
    );
  });

  it("returns content unchanged for JSON (no comment syntax)", () => {
    const content = '{ "key": "value" }';
    expect(applyStamp("package.json", content, stamp)).toBe(content);
  });

  it("returns content unchanged for unknown extension", () => {
    const content = "binary data";
    expect(applyStamp("file.dat", content, stamp)).toBe(content);
  });

  it("returns content unchanged for extensionless files", () => {
    const content = "some content";
    expect(applyStamp("Makefile", content, stamp)).toBe(content);
  });

  it("handles shebang — places stamp after shebang line", () => {
    const content = "#!/bin/bash\necho hello";
    expect(applyStamp("script.sh", content, stamp)).toBe(
      "#!/bin/bash\n# Generated by test-gen v1.0.0\n\necho hello",
    );
  });

  it("handles shebang in .ts files", () => {
    const content = "#!/usr/bin/env bun\nconsole.log('hi');";
    expect(applyStamp("cli.ts", content, stamp)).toBe(
      "#!/usr/bin/env bun\n// Generated by test-gen v1.0.0\n\nconsole.log('hi');",
    );
  });

  it("handles shebang-only file (no newline) — stamps normally", () => {
    // When there's no newline after shebang, indexOf("\n") returns -1
    // so the code falls through to prepend the stamp normally
    const content = "#!/bin/bash";
    expect(applyStamp("script.sh", content, stamp)).toBe(
      "# Generated by test-gen v1.0.0\n\n#!/bin/bash",
    );
  });

  it("handles empty content", () => {
    expect(applyStamp("file.ts", "", stamp)).toBe(
      "// Generated by test-gen v1.0.0\n\n",
    );
  });

  it("handles compound extension (.test.ts) — uses final extension", () => {
    expect(applyStamp("app.test.ts", "test()", stamp)).toBe(
      "// Generated by test-gen v1.0.0\n\ntest()",
    );
  });

  it("handles uppercase extensions via lowercase normalization", () => {
    expect(applyStamp("README.MD", "# Title", stamp)).toBe(
      "<!-- Generated by test-gen v1.0.0 -->\n\n# Title",
    );
  });

  it("includes generator name and version in stamp text", () => {
    const customStamp: StampConfig = {
      generator: "@canonical/summon-component",
      version: "0.3.2",
    };
    expect(applyStamp("file.ts", "code", customStamp)).toBe(
      "// Generated by @canonical/summon-component v0.3.2\n\ncode",
    );
  });
});

// =============================================================================
// runTaskWithStamp
// =============================================================================

describe("runTaskWithStamp", () => {
  it("runs a pure task without stamp option", async () => {
    const result = await runTaskWithStamp(pure(42));
    expect(result).toBe(42);
  });

  it("runs a pure task with stamp option (no WriteFile effects to stamp)", async () => {
    const result = await runTaskWithStamp(pure("done"), {
      stamp,
    });
    expect(result).toBe("done");
  });
});
