import * as path from "node:path";
import type StampConfig from "../types/StampConfig.js";

const COMMENT_STYLES: Record<
  string,
  {
    single?: string;
    blockStart?: string;
    blockEnd?: string;
    preferBlock?: boolean;
  }
> = {
  ".ts": { single: "//" },
  ".tsx": { single: "//" },
  ".js": { single: "//" },
  ".jsx": { single: "//" },
  ".mjs": { single: "//" },
  ".cjs": { single: "//" },
  ".css": { blockStart: "/*", blockEnd: "*/", preferBlock: true },
  ".scss": { single: "//" },
  ".sass": { single: "//" },
  ".less": { single: "//" },
  ".html": { blockStart: "<!--", blockEnd: "-->" },
  ".htm": { blockStart: "<!--", blockEnd: "-->" },
  ".xml": { blockStart: "<!--", blockEnd: "-->" },
  ".svg": { blockStart: "<!--", blockEnd: "-->" },
  ".vue": { blockStart: "<!--", blockEnd: "-->" },
  ".svelte": { blockStart: "<!--", blockEnd: "-->" },
  ".yaml": { single: "#" },
  ".yml": { single: "#" },
  ".toml": { single: "#" },
  ".sh": { single: "#" },
  ".bash": { single: "#" },
  ".zsh": { single: "#" },
  ".py": { single: "#" },
  ".rb": { single: "#" },
  ".go": { single: "//" },
  ".rs": { single: "//" },
  ".java": { single: "//" },
  ".kt": { single: "//" },
  ".swift": { single: "//" },
  ".c": { single: "//" },
  ".cpp": { single: "//" },
  ".h": { single: "//" },
  ".php": { single: "//" },
  ".md": { blockStart: "<!--", blockEnd: "-->" },
  ".mdx": { blockStart: "{/*", blockEnd: "*/}" },
  ".sql": { single: "--" },
  ".json": {},
};

/**
 * Apply a stamp to file content based on file extension.
 * Returns the original content if the file type doesn't support comments.
 */
export default function applyStamp(
  filePath: string,
  content: string,
  stamp: StampConfig,
): string {
  const ext = path.extname(filePath).toLowerCase();
  const style = COMMENT_STYLES[ext];

  if (!style) {
    return content;
  }

  const stampText = `Generated by ${stamp.generator} v${stamp.version}`;
  let stampLine: string;

  if (style.single && !style.preferBlock) {
    stampLine = `${style.single} ${stampText}`;
  } else if (style.blockStart && style.blockEnd) {
    stampLine = `${style.blockStart} ${stampText} ${style.blockEnd}`;
  } else {
    return content;
  }

  // Handle shebang - place stamp after it
  if (content.startsWith("#!")) {
    const firstNewline = content.indexOf("\n");
    if (firstNewline !== -1) {
      const shebang = content.slice(0, firstNewline + 1);
      const rest = content.slice(firstNewline + 1);
      return `${shebang}${stampLine}\n\n${rest}`;
    }
  }

  return `${stampLine}\n\n${content}`;
}
