/**
 * The one generator both bins run to prove their execution seams agree.
 *
 * It is deliberately small and deliberately awkward. Every effect it emits is
 * there to reach a part of the seam that a plain "write one file" fixture would
 * leave untested:
 *
 * - `mkdir` of a nested path, so directory creation is on the wire rather than
 *   implied by a write.
 * - A `.ts` file, which the stamp transform PREFIXES with `Generated by <name>
 *   v<version>` — the identity that must be identical across bins, and the one
 *   a bin can get wrong on its own by deriving the stamp itself.
 * - A `.md` file behind a conditional prompt, whose comment style is a BLOCK
 *   comment, so a stamp implementation that only handles line comments diverges
 *   here instead of silently agreeing.
 * - A `.json` file, which the stamp transform leaves ALONE (JSON has no comment
 *   syntax), so a bin that stamps everything diverges.
 * - A multi-byte character in the content, so a byte count taken in UTF-16 code
 *   units disagrees with one taken in UTF-8 bytes.
 *
 * Kept free of `@canonical/summon-core`'s own execute/run layers: the fixture is
 * DATA, and each consumer drives it through its own seam, comparing against the
 * written-down `CONFORMANCE_TREE`. That is what makes a disagreement
 * attributable to one binary rather than to the pair.
 */

import { mkdir, sequence_, type Task, when, writeFile } from "@canonical/task";
import type GeneratorDefinition from "../../types/GeneratorDefinition.js";

/** Build the file body the conformance generator writes for a module. */
function buildModuleSource(moduleName: string, summary: string): string {
  return `export const name = ${JSON.stringify(moduleName)};\nexport const summary = ${JSON.stringify(summary)};\n`;
}

/**
 * The conformance fixture generator.
 *
 * `displayName` differs from `name` on purpose: `createGeneratorStamp` prefers
 * the display name, so a consumer that stamps with the registry name instead
 * produces a different first line and this suite says so.
 */
export const conformanceGenerator: GeneratorDefinition = {
  meta: {
    name: "conformance/module",
    displayName: "@canonical/summon-core:conformance",
    description: "The shared byte-equality conformance fixture.",
    version: "1.0.0",
  },
  prompts: [
    {
      name: "moduleName",
      type: "text",
      message: "Module name?",
      default: "module",
      positional: true,
    },
    {
      name: "summary",
      type: "text",
      message: "Summary?",
      default: "A module.",
    },
    {
      name: "withNotes",
      type: "confirm",
      message: "Write NOTES.md?",
      default: true,
    },
  ],
  generate: (answers: Record<string, unknown>): Task<void> => {
    const moduleName = String(answers.moduleName);
    const summary = String(answers.summary);
    const dir = `src/${moduleName}`;
    return sequence_([
      mkdir(dir),
      writeFile(`${dir}/index.ts`, buildModuleSource(moduleName, summary)),
      when(
        answers.withNotes === true,
        writeFile(`${dir}/NOTES.md`, `# ${moduleName}\n\n${summary}\n`),
      ),
      writeFile(
        `${dir}/config.json`,
        `${JSON.stringify({ name: moduleName, summary }, null, 2)}\n`,
      ),
    ]);
  },
};
