/**
 * The fixed inputs of the byte-equality conformance suite, and the tree they
 * must produce.
 *
 * Held apart from the generator so a consumer drives the SAME answers against
 * the SAME expected bytes without inventing either — the whole point of the
 * suite is that no binary is measured against its own idea of the answer.
 */

/**
 * The answer set the conformance generator is run with.
 *
 * Every value reaches a different part of the seam: `moduleName` drives both
 * the template and the directory a file lands in, `summary` carries a
 * MULTI-BYTE character (an em dash, three UTF-8 bytes) so a byte count taken in
 * UTF-16 code units disagrees with one taken in bytes, and `withNotes` gates a
 * second file so a conditional prompt is exercised rather than assumed.
 */
export const CONFORMANCE_ANSWERS = {
  moduleName: "widget-factory",
  summary: "A module — with an em dash in its summary.",
  withNotes: true,
} as const;

/**
 * The exact tree {@link ./conformanceGenerator.conformanceGenerator} produces
 * under {@link CONFORMANCE_ANSWERS} — relative path → bytes, stamps included.
 *
 * WRITTEN DOWN, not derived. A suite that produced the reference tree with the
 * same code it was testing would agree with itself no matter what either
 * binary did, including writing nothing at all. Because this is a literal, a
 * binary whose seam drifts stops matching it IN ITS OWN PROCESS, so neither
 * bin needs to reach the other to catch a divergence.
 *
 * Three files, three different stamp outcomes: a line comment (`.ts`), a block
 * comment (`.md`), and no stamp at all (`.json` has no comment syntax).
 */
export const CONFORMANCE_TREE: ReadonlyMap<string, string> = new Map([
  [
    "src/widget-factory/NOTES.md",
    "<!-- Generated by @canonical/summon-core:conformance v1.0.0 -->\n\n# widget-factory\n\nA module — with an em dash in its summary.\n",
  ],
  [
    "src/widget-factory/config.json",
    '{\n  "name": "widget-factory",\n  "summary": "A module — with an em dash in its summary."\n}\n',
  ],
  [
    "src/widget-factory/index.ts",
    '// Generated by @canonical/summon-core:conformance v1.0.0\n\nexport const name = "widget-factory";\nexport const summary = "A module — with an em dash in its summary.";\n',
  ],
]);
