/**
 * The byte-equality conformance kit — one generator, one answer set, one
 * comparison, run by every binary that executes summon generators.
 *
 * WHY IT LIVES HERE. `pragma create <verb>` and `summon <generator>` produce
 * files through two different front ends over one core. The guarantee that
 * matters to a user is that the FILES ARE THE SAME — same paths, same bytes,
 * same `Generated by` stamp — and that guarantee is only as good as the fixture
 * both sides are measured against. Shipping the fixture from the core means
 * neither bin can quietly measure itself against its own.
 *
 * WHAT "BOTH BINS" MEANS HERE, precisely. Neither bin can dispatch the other's
 * generators: pragma's `create` is bound to three declared generator packages
 * and refuses anything else, and the summon bin ships only its own `init` and
 * `example` builtins. So this suite is run by both bins' EXECUTION SEAMS over
 * one fixture, not by both CLI entry points over one command. That is the
 * strongest claim the shape of the two products supports, and it is the claim
 * that catches the failure this exists for: a bin deriving the stamp, the
 * answers, or the run options itself and drifting.
 *
 * @experimental A TESTING surface, not a product API. It exists so consumers
 * can hold themselves to the seam contract; its shape may change with the
 * fixture whenever a new part of the seam needs covering, and no compatibility
 * is offered across versions.
 */

export { conformanceGenerator } from "./conformanceGenerator.js";
export { CONFORMANCE_ANSWERS, CONFORMANCE_TREE } from "./constants.js";
export { assertByteEqual, snapshotTree } from "./snapshotTree.js";
