// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import { renderToString } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { SettingsView } from "./SettingsView.js";

describe("SettingsView SSR", () => {
  it("renders without hydration errors", () => {
    const html = renderToString(<SettingsView>Test content</SettingsView>);
    expect(html).toContain("Test content");
    expect(html).toContain("settings-view");
  });
});
