// Generated by @canonical/summon-component:react v0.1.0

import type React from "react";
import type { PropertiesSectionProps } from "./types.js";
import "./styles.css";

const componentCssClassName = "ds properties-section";

/**
 * PropertiesSection component
 */
const PropertiesSection = ({
  className,
  children,
  ...props
}: PropertiesSectionProps): React.ReactElement => {
  return (
    <div
      className={[componentCssClassName, className].filter(Boolean).join(" ")}
      {...props}
    >
      {children}
    </div>
  );
};

export default PropertiesSection;
