// Generated by @canonical/summon-component:react v0.1.0

import { renderToString } from "react-dom/server";
import { describe, expect, it } from "vitest";
import PropertiesSection from "./PropertiesSection.js";

describe("PropertiesSection SSR", () => {
  it("renders without hydration errors", () => {
    const html = renderToString(
      <PropertiesSection>Test content</PropertiesSection>,
    );
    expect(html).toContain("Test content");
    expect(html).toContain("ds properties-section");
  });
});
