// Generated by @canonical/summon-component:react v0.1.0

import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import PropertiesSection from "./PropertiesSection.js";

describe("PropertiesSection", () => {
  it("renders children", () => {
    render(<PropertiesSection>Test content</PropertiesSection>);
    expect(screen.getByText("Test content")).toBeInTheDocument();
  });

  it("applies custom className", () => {
    render(
      <PropertiesSection className="custom-class">Content</PropertiesSection>,
    );
    const element = screen.getByText("Content");
    expect(element.className).toContain("ds properties-section");
    expect(element.className).toContain("custom-class");
  });

  it("passes through additional props", () => {
    render(
      <PropertiesSection data-testid="test-component">
        Content
      </PropertiesSection>,
    );
    expect(screen.getByTestId("test-component")).toBeInTheDocument();
  });
});
