// Generated by @canonical/summon-component:lit v0.1.0

export interface ListItem {
  text: string;
  ticked?: boolean;
}

/**
 * Props for the List component.
 */
export interface ListProps {
  /** list type variant */
  listType: "ordered" | "unordered" | "bulletless" | "inline" | "inline-middot";
  /** items array */
  items: Array<Partial<ListItem>>;
  /** whether to show a horizontal divider between items */
  divider: boolean;
}
