// Generated by @canonical/summon-component:react v0.1.0

import type React from "react";

type NativeRadioProps = React.InputHTMLAttributes<HTMLInputElement>;

/** Props for the presentational Radio input (no react-hook-form). */
export type RadioInputProps = NativeRadioProps;
