// Generated by @canonical/summon-component:react v0.1.0

import { renderToString } from "react-dom/server";
import { describe, expect, it } from "vitest";
import CatalogItem from "./CatalogItem.js";

describe("CatalogItem SSR", () => {
  it("renders without hydration errors", () => {
    const html = renderToString(<CatalogItem>Test content</CatalogItem>);
    expect(html).toContain("Test content");
    expect(html).toContain("ds catalog-item");
  });
});
