// Generated by @canonical/summon-component:react v0.1.0

import type React from "react";
import type { CatalogItemProps } from "./types.js";
import "./styles.css";

const componentCssClassName = "ds catalog-item";

/**
 * CatalogItem component
 */
const CatalogItem = ({
  className,
  children,
  ...props
}: CatalogItemProps): React.ReactElement => {
  return (
    <div
      className={[componentCssClassName, className].filter(Boolean).join(" ")}
      {...props}
    >
      {children}
    </div>
  );
};

export default CatalogItem;
