// Generated by @canonical/summon-component:react v0.1.0

import type { Meta, StoryObj } from "@storybook/react-vite";
import CatalogItem from "./CatalogItem.js";

const meta: Meta<typeof CatalogItem> = {
  title: "Components/CatalogItem",
  component: CatalogItem,
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof CatalogItem>;

export const Default: Story = {
  args: {
    children: "Hello, CatalogItem!",
  },
};

export const WithCustomClass: Story = {
  args: {
    children: "Custom styled",
    className: "custom-class",
  },
};
