// Generated by summon webapp
// Feature module: router

/**
 * Router configuration for my-webapp
 */
import { Routes, Route } from 'react-router-dom';

export const AppRoutes = () => (
  <Routes>
    <Route path="/" element={<div>Home</div>} />
    <Route path="/about" element={<div>About</div>} />
    <Route path="*" element={<div>Not Found</div>} />
  </Routes>
);
