// Generated by @canonical/summon-component:react v0.1.0

import type { Meta, StoryObj } from "@storybook/react-vite";
import ComponentEntityPage from "./ComponentEntityPage.js";

const meta: Meta<typeof ComponentEntityPage> = {
  title: "Components/ComponentEntityPage",
  component: ComponentEntityPage,
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof ComponentEntityPage>;

export const Default: Story = {
  args: {
    children: "Hello, ComponentEntityPage!",
  },
};

export const WithCustomClass: Story = {
  args: {
    children: "Custom styled",
    className: "custom-class",
  },
};
