// Generated by @canonical/summon-component:react v0.1.0

import { renderToString } from "react-dom/server";
import { describe, expect, it } from "vitest";
import ComponentEntityPage from "./ComponentEntityPage.js";

describe("ComponentEntityPage SSR", () => {
  it("renders without hydration errors", () => {
    const html = renderToString(
      <ComponentEntityPage>Test content</ComponentEntityPage>,
    );
    expect(html).toContain("Test content");
    expect(html).toContain("ds component-entity-page");
  });
});
