<!-- Generated by @canonical/summon-component:svelte v0.34.0 -->

<script lang="ts" module>
	import { defineMeta } from "@storybook/addon-svelte-csf";
	import Button from "./Button.svelte";

	const { Story } = defineMeta({
		title: "Components/Button",
		component: Button,
		tags: ["autodocs"],
	});
</script>

<Story name="Default">
	Hello, Button!
</Story>

<Story
  name="WithCustomClass"
  args={{
    class: "custom-class",
    id: "custom-id",
    style: "background-color: tomato;",
  }}
>
	Custom styled
</Story>
