<!-- Generated by @canonical/summon-component:svelte v0.29.0-experimental.0 -->

<script lang="ts" module>
  import { MODIFIER_FAMILIES } from "@canonical/ds-types";
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import { fn } from "storybook/test";
  import Button from "./Button.svelte";

  const { Story } = defineMeta({
    title: "Components/Button",
    component: Button,
    tags: ["autodocs"],
    argTypes: {
      // Importance is never blank — primary is the default hierarchy.
      importance: {
        control: "select",
        options: [...MODIFIER_FAMILIES.importance],
      },
      anticipation: {
        control: "select",
        options: [undefined, ...MODIFIER_FAMILIES.anticipation],
      },
      variant: {
        control: "select",
        options: [undefined, "link"],
      },
    },
    args: {
      onclick: fn(),
      importance: "primary",
    },
  });
</script>

<Story name="Default">
  Button
</Story>

<!-- Importance modifiers express the visual hierarchy of an action. -->
<Story name="Importance" asChild>
  <div style="display: flex; gap: 0.5rem;">
    <Button>Default</Button>
    {#each MODIFIER_FAMILIES.importance as importance (importance)}
      <Button {importance}>{importance}</Button>
    {/each}
  </div>
</Story>

<!-- Anticipation modifiers express the expected consequence of an action. -->
<Story name="Anticipation" asChild>
  <div style="display: flex; gap: 0.5rem;">
    <Button>Default</Button>
    {#each MODIFIER_FAMILIES.anticipation as anticipation (anticipation)}
      <Button {anticipation}>{anticipation}</Button>
    {/each}
  </div>
</Story>

<!-- Link variant renders as inline text with underline. -->
<Story name="LinkVariant" args={{ variant: "link" }}>
  Learn more
</Story>

<!-- Button with icon and label. -->
<Story name="WithIcon" args={{ anticipation: "destructive" }}>
  {#snippet template(args)}
    <Button {...args}>
      {#snippet icon()}
        <svg viewBox="0 0 16 16" fill="currentColor" aria-hidden="true">
          <path
            d="M2 4h12M5 4V2h6v2M6 7v5M10 7v5M4 4l1 10h6l1-10"
            stroke="currentColor"
            stroke-width="1.5"
            fill="none"
          />
        </svg>
      {/snippet}
      Delete
    </Button>
  {/snippet}
</Story>

<!-- Disabled button using design-tokens disabled state variables. -->
<Story name="Disabled" args={{ disabled: true }}>
  Disabled
</Story>
