<!-- Generated by @canonical/summon-component:svelte v0.29.0-experimental.0 -->

<script lang="ts">
  import type { ButtonProps } from "./types.js";
  import "./styles.css";

  const componentCssClassName = "ds button";

  let {
    class: className,
    children,
    importance = "primary",
    anticipation,
    variant,
    icon,
    ...rest
  }: ButtonProps = $props();

  $effect(() => {
    if (
      import.meta.env?.DEV &&
      icon &&
      !children &&
      !rest["aria-label"] &&
      !rest["aria-labelledby"]
    ) {
      console.warn(
        "Button: icon-only buttons need an explicit `aria-label` or `aria-labelledby` to be accessible.",
      );
    }
  });
</script>

<button
  class={[
    componentCssClassName,
    // The `.p` baseline utility supplies the body-text tier (font, snapped
    // line-height) and the padding-block nudges that align the button box
    // to the baseline grid — so the box height tracks the text inside.
    "p",
    importance,
    anticipation,
    variant,
    className,
  ]}
  {...rest}
>
  {#if icon}
    <span class="icon">{@render icon()}</span>
  {/if}
  {#if children}
    <span class="label">{@render children()}</span>
  {/if}
</button>

<!-- @component
`Button` triggers actions within an interface, typically involving
data transformation or manipulation. It provides clear visual
indicators of the primary actions users can perform.

## Example Usage
```svelte
<Button importance="primary" onclick={() => save()}>
  Save
</Button>
```
-->
