// AUTO-GENERATED from libphonenumber metadata. Do not edit by hand.

import masks, { type MaskKey } from "./masks.js";
import type { CountryData } from "./types.js";

/** Resolve a mask key to its format string. */
const m = (k: MaskKey): string => masks[k];

/**
 * All ISO 3166-1 alpha-2 countries with dial code and a best-effort national-
 * number display mask (derived from libphonenumber). Masks are cosmetic only;
 * the submitted value is always raw digits / E.164.
 */
const countries: CountryData[] = [
  { code: "AC", name: "Ascension Island", dialCode: "+247" },
  { code: "AD", name: "Andorra", dialCode: "+376", format: m("m1") },
  {
    code: "AE",
    name: "United Arab Emirates",
    dialCode: "+971",
    format: m("m2"),
  },
  { code: "AF", name: "Afghanistan", dialCode: "+93", format: m("m2") },
  { code: "AG", name: "Antigua & Barbuda", dialCode: "+1" },
  { code: "AI", name: "Anguilla", dialCode: "+1" },
  { code: "AL", name: "Albania", dialCode: "+355", format: m("m2") },
  { code: "AM", name: "Armenia", dialCode: "+374", format: m("m3") },
  { code: "AO", name: "Angola", dialCode: "+244", format: m("m1") },
  { code: "AR", name: "Argentina", dialCode: "+54", format: m("m4") },
  { code: "AS", name: "American Samoa", dialCode: "+1" },
  { code: "AT", name: "Austria", dialCode: "+43", format: m("m5") },
  { code: "AU", name: "Australia", dialCode: "+61", format: m("m6") },
  { code: "AW", name: "Aruba", dialCode: "+297", format: m("m7") },
  { code: "AX", name: "\u00c5land Islands", dialCode: "+358" },
  { code: "AZ", name: "Azerbaijan", dialCode: "+994", format: m("m8") },
  {
    code: "BA",
    name: "Bosnia & Herzegovina",
    dialCode: "+387",
    format: m("m9"),
  },
  { code: "BB", name: "Barbados", dialCode: "+1" },
  { code: "BD", name: "Bangladesh", dialCode: "+880", format: m("m10") },
  { code: "BE", name: "Belgium", dialCode: "+32", format: m("m8") },
  { code: "BF", name: "Burkina Faso", dialCode: "+226", format: m("m11") },
  { code: "BG", name: "Bulgaria", dialCode: "+359", format: m("m1") },
  { code: "BH", name: "Bahrain", dialCode: "+973", format: m("m12") },
  { code: "BI", name: "Burundi", dialCode: "+257", format: m("m11") },
  { code: "BJ", name: "Benin", dialCode: "+229", format: m("m13") },
  { code: "BL", name: "St. Barth\u00e9lemy", dialCode: "+590" },
  { code: "BM", name: "Bermuda", dialCode: "+1" },
  { code: "BN", name: "Brunei", dialCode: "+673", format: m("m7") },
  { code: "BO", name: "Bolivia", dialCode: "+591", format: m("m14") },
  { code: "BQ", name: "Caribbean Netherlands", dialCode: "+599" },
  { code: "BR", name: "Brazil", dialCode: "+55", format: m("m15") },
  { code: "BS", name: "Bahamas", dialCode: "+1" },
  { code: "BT", name: "Bhutan", dialCode: "+975", format: m("m11") },
  { code: "BW", name: "Botswana", dialCode: "+267", format: m("m6") },
  { code: "BY", name: "Belarus", dialCode: "+375", format: m("m16") },
  { code: "BZ", name: "Belize", dialCode: "+501", format: m("m17") },
  { code: "CA", name: "Canada", dialCode: "+1" },
  { code: "CC", name: "Cocos (Keeling) Islands", dialCode: "+61" },
  { code: "CD", name: "Congo - Kinshasa", dialCode: "+243", format: m("m18") },
  {
    code: "CF",
    name: "Central African Republic",
    dialCode: "+236",
    format: m("m11"),
  },
  {
    code: "CG",
    name: "Congo - Brazzaville",
    dialCode: "+242",
    format: m("m2"),
  },
  { code: "CH", name: "Switzerland", dialCode: "+41", format: m("m19") },
  {
    code: "CI",
    name: "C\u00f4te d\u2019Ivoire",
    dialCode: "+225",
    format: m("m20"),
  },
  { code: "CK", name: "Cook Islands", dialCode: "+682", format: m("m21") },
  { code: "CL", name: "Chile", dialCode: "+56", format: m("m22") },
  { code: "CM", name: "Cameroon", dialCode: "+237", format: m("m11") },
  { code: "CN", name: "China", dialCode: "+86", format: m("m23") },
  { code: "CO", name: "Colombia", dialCode: "+57", format: m("m24") },
  { code: "CR", name: "Costa Rica", dialCode: "+506", format: m("m25") },
  { code: "CU", name: "Cuba", dialCode: "+53", format: m("m24") },
  { code: "CV", name: "Cape Verde", dialCode: "+238", format: m("m26") },
  { code: "CW", name: "Cura\u00e7ao", dialCode: "+599", format: m("m7") },
  { code: "CX", name: "Christmas Island", dialCode: "+61" },
  { code: "CY", name: "Cyprus", dialCode: "+357", format: m("m27") },
  { code: "CZ", name: "Czechia", dialCode: "+420", format: m("m28") },
  { code: "DE", name: "Germany", dialCode: "+49", format: m("m29") },
  { code: "DJ", name: "Djibouti", dialCode: "+253", format: m("m11") },
  { code: "DK", name: "Denmark", dialCode: "+45", format: m("m11") },
  { code: "DM", name: "Dominica", dialCode: "+1" },
  { code: "DO", name: "Dominican Republic", dialCode: "+1" },
  { code: "DZ", name: "Algeria", dialCode: "+213", format: m("m30") },
  { code: "EC", name: "Ecuador", dialCode: "+593", format: m("m6") },
  { code: "EE", name: "Estonia", dialCode: "+372", format: m("m6") },
  { code: "EG", name: "Egypt", dialCode: "+20", format: m("m16") },
  { code: "EH", name: "Western Sahara", dialCode: "+212" },
  { code: "ER", name: "Eritrea", dialCode: "+291", format: m("m31") },
  { code: "ES", name: "Spain", dialCode: "+34", format: m("m1") },
  { code: "ET", name: "Ethiopia", dialCode: "+251", format: m("m2") },
  { code: "FI", name: "Finland", dialCode: "+358", format: m("m27") },
  { code: "FJ", name: "Fiji", dialCode: "+679", format: m("m22") },
  { code: "FK", name: "Falkland Islands", dialCode: "+500" },
  { code: "FM", name: "Micronesia", dialCode: "+691", format: m("m7") },
  { code: "FO", name: "Faroe Islands", dialCode: "+298", format: m("m32") },
  { code: "FR", name: "France", dialCode: "+33", format: m("m8") },
  { code: "GA", name: "Gabon", dialCode: "+241", format: m("m11") },
  { code: "GB", name: "United Kingdom", dialCode: "+44", format: m("m5") },
  { code: "GD", name: "Grenada", dialCode: "+1" },
  { code: "GE", name: "Georgia", dialCode: "+995", format: m("m1") },
  { code: "GF", name: "French Guiana", dialCode: "+594", format: m("m8") },
  { code: "GG", name: "Guernsey", dialCode: "+44" },
  { code: "GH", name: "Ghana", dialCode: "+233", format: m("m2") },
  { code: "GI", name: "Gibraltar", dialCode: "+350", format: m("m33") },
  { code: "GL", name: "Greenland", dialCode: "+299", format: m("m34") },
  { code: "GM", name: "Gambia", dialCode: "+220", format: m("m7") },
  { code: "GN", name: "Guinea", dialCode: "+224", format: m("m8") },
  { code: "GP", name: "Guadeloupe", dialCode: "+590", format: m("m8") },
  { code: "GQ", name: "Equatorial Guinea", dialCode: "+240", format: m("m1") },
  { code: "GR", name: "Greece", dialCode: "+30", format: m("m35") },
  { code: "GT", name: "Guatemala", dialCode: "+502", format: m("m22") },
  { code: "GU", name: "Guam", dialCode: "+1" },
  { code: "GW", name: "Guinea-Bissau", dialCode: "+245", format: m("m1") },
  { code: "GY", name: "Guyana", dialCode: "+592", format: m("m7") },
  {
    code: "HK",
    name: "Hong Kong SAR China",
    dialCode: "+852",
    format: m("m36"),
  },
  { code: "HN", name: "Honduras", dialCode: "+504", format: m("m37") },
  { code: "HR", name: "Croatia", dialCode: "+385", format: m("m1") },
  { code: "HT", name: "Haiti", dialCode: "+509", format: m("m38") },
  { code: "HU", name: "Hungary", dialCode: "+36", format: m("m39") },
  { code: "ID", name: "Indonesia", dialCode: "+62", format: m("m40") },
  { code: "IE", name: "Ireland", dialCode: "+353", format: m("m6") },
  { code: "IL", name: "Israel", dialCode: "+972", format: m("m41") },
  { code: "IM", name: "Isle of Man", dialCode: "+44" },
  { code: "IN", name: "India", dialCode: "+91", format: m("m42") },
  {
    code: "IO",
    name: "British Indian Ocean Territory",
    dialCode: "+246",
    format: m("m7"),
  },
  { code: "IQ", name: "Iraq", dialCode: "+964", format: m("m16") },
  { code: "IR", name: "Iran", dialCode: "+98", format: m("m5") },
  { code: "IS", name: "Iceland", dialCode: "+354", format: m("m1") },
  { code: "IT", name: "Italy", dialCode: "+39", format: m("m43") },
  { code: "JE", name: "Jersey", dialCode: "+44" },
  { code: "JM", name: "Jamaica", dialCode: "+1" },
  { code: "JO", name: "Jordan", dialCode: "+962", format: m("m44") },
  { code: "JP", name: "Japan", dialCode: "+81", format: m("m25") },
  { code: "KE", name: "Kenya", dialCode: "+254", format: m("m45") },
  { code: "KG", name: "Kyrgyzstan", dialCode: "+996", format: m("m46") },
  { code: "KH", name: "Cambodia", dialCode: "+855", format: m("m6") },
  { code: "KI", name: "Kiribati", dialCode: "+686" },
  { code: "KM", name: "Comoros", dialCode: "+269", format: m("m26") },
  { code: "KN", name: "St. Kitts & Nevis", dialCode: "+1" },
  { code: "KP", name: "North Korea", dialCode: "+850", format: m("m16") },
  { code: "KR", name: "South Korea", dialCode: "+82", format: m("m47") },
  { code: "KW", name: "Kuwait", dialCode: "+965", format: m("m33") },
  { code: "KY", name: "Cayman Islands", dialCode: "+1" },
  { code: "KZ", name: "Kazakhstan", dialCode: "+7" },
  { code: "LA", name: "Laos", dialCode: "+856", format: m("m18") },
  { code: "LB", name: "Lebanon", dialCode: "+961", format: m("m39") },
  { code: "LC", name: "St. Lucia", dialCode: "+1" },
  { code: "LI", name: "Liechtenstein", dialCode: "+423", format: m("m1") },
  { code: "LK", name: "Sri Lanka", dialCode: "+94", format: m("m2") },
  { code: "LR", name: "Liberia", dialCode: "+231", format: m("m2") },
  { code: "LS", name: "Lesotho", dialCode: "+266", format: m("m12") },
  { code: "LT", name: "Lithuania", dialCode: "+370", format: m("m3") },
  { code: "LU", name: "Luxembourg", dialCode: "+352", format: m("m9") },
  { code: "LV", name: "Latvia", dialCode: "+371", format: m("m39") },
  { code: "LY", name: "Libya", dialCode: "+218", format: m("m48") },
  { code: "MA", name: "Morocco", dialCode: "+212", format: m("m49") },
  { code: "MC", name: "Monaco", dialCode: "+377", format: m("m39") },
  { code: "MD", name: "Moldova", dialCode: "+373", format: m("m33") },
  { code: "ME", name: "Montenegro", dialCode: "+382", format: m("m39") },
  { code: "MF", name: "St. Martin", dialCode: "+590" },
  { code: "MG", name: "Madagascar", dialCode: "+261", format: m("m50") },
  { code: "MH", name: "Marshall Islands", dialCode: "+692", format: m("m51") },
  { code: "MK", name: "North Macedonia", dialCode: "+389", format: m("m39") },
  { code: "ML", name: "Mali", dialCode: "+223", format: m("m11") },
  { code: "MM", name: "Myanmar (Burma)", dialCode: "+95", format: m("m16") },
  { code: "MN", name: "Mongolia", dialCode: "+976", format: m("m46") },
  { code: "MO", name: "Macao SAR China", dialCode: "+853", format: m("m12") },
  { code: "MP", name: "Northern Mariana Islands", dialCode: "+1" },
  { code: "MQ", name: "Martinique", dialCode: "+596", format: m("m8") },
  { code: "MR", name: "Mauritania", dialCode: "+222", format: m("m11") },
  { code: "MS", name: "Montserrat", dialCode: "+1" },
  { code: "MT", name: "Malta", dialCode: "+356", format: m("m12") },
  { code: "MU", name: "Mauritius", dialCode: "+230", format: m("m52") },
  { code: "MV", name: "Maldives", dialCode: "+960", format: m("m16") },
  { code: "MW", name: "Malawi", dialCode: "+265", format: m("m8") },
  { code: "MX", name: "Mexico", dialCode: "+52", format: m("m5") },
  { code: "MY", name: "Malaysia", dialCode: "+60", format: m("m53") },
  { code: "MZ", name: "Mozambique", dialCode: "+258", format: m("m1") },
  { code: "NA", name: "Namibia", dialCode: "+264", format: m("m1") },
  { code: "NC", name: "New Caledonia", dialCode: "+687", format: m("m54") },
  { code: "NE", name: "Niger", dialCode: "+227", format: m("m39") },
  { code: "NF", name: "Norfolk Island", dialCode: "+672", format: m("m55") },
  { code: "NG", name: "Nigeria", dialCode: "+234", format: m("m56") },
  { code: "NI", name: "Nicaragua", dialCode: "+505", format: m("m12") },
  { code: "NL", name: "Netherlands", dialCode: "+31", format: m("m35") },
  { code: "NO", name: "Norway", dialCode: "+47", format: m("m3") },
  { code: "NP", name: "Nepal", dialCode: "+977", format: m("m57") },
  { code: "NR", name: "Nauru", dialCode: "+674", format: m("m7") },
  { code: "NU", name: "Niue", dialCode: "+683", format: m("m7") },
  { code: "NZ", name: "New Zealand", dialCode: "+64", format: m("m1") },
  { code: "OM", name: "Oman", dialCode: "+968", format: m("m27") },
  { code: "PA", name: "Panama", dialCode: "+507", format: m("m16") },
  { code: "PE", name: "Peru", dialCode: "+51", format: m("m1") },
  { code: "PF", name: "French Polynesia", dialCode: "+689", format: m("m8") },
  { code: "PG", name: "Papua New Guinea", dialCode: "+675", format: m("m12") },
  { code: "PH", name: "Philippines", dialCode: "+63", format: m("m58") },
  { code: "PK", name: "Pakistan", dialCode: "+92", format: m("m28") },
  { code: "PL", name: "Poland", dialCode: "+48", format: m("m1") },
  {
    code: "PM",
    name: "St. Pierre & Miquelon",
    dialCode: "+508",
    format: m("m1"),
  },
  { code: "PR", name: "Puerto Rico", dialCode: "+1" },
  {
    code: "PS",
    name: "Palestinian Territories",
    dialCode: "+970",
    format: m("m6"),
  },
  { code: "PT", name: "Portugal", dialCode: "+351", format: m("m2") },
  { code: "PW", name: "Palau", dialCode: "+680", format: m("m7") },
  { code: "PY", name: "Paraguay", dialCode: "+595", format: m("m22") },
  { code: "QA", name: "Qatar", dialCode: "+974", format: m("m12") },
  { code: "RE", name: "R\u00e9union", dialCode: "+262", format: m("m8") },
  { code: "RO", name: "Romania", dialCode: "+40", format: m("m2") },
  { code: "RS", name: "Serbia", dialCode: "+381", format: m("m59") },
  { code: "RU", name: "Russia", dialCode: "+7", format: m("m60") },
  { code: "RW", name: "Rwanda", dialCode: "+250", format: m("m1") },
  { code: "SA", name: "Saudi Arabia", dialCode: "+966", format: m("m16") },
  { code: "SB", name: "Solomon Islands", dialCode: "+677", format: m("m59") },
  { code: "SC", name: "Seychelles", dialCode: "+248", format: m("m31") },
  { code: "SD", name: "Sudan", dialCode: "+249", format: m("m2") },
  { code: "SE", name: "Sweden", dialCode: "+46", format: m("m61") },
  { code: "SG", name: "Singapore", dialCode: "+65", format: m("m62") },
  { code: "SH", name: "St. Helena", dialCode: "+290" },
  { code: "SI", name: "Slovenia", dialCode: "+386", format: m("m33") },
  { code: "SJ", name: "Svalbard & Jan Mayen", dialCode: "+47" },
  { code: "SK", name: "Slovakia", dialCode: "+421", format: m("m1") },
  { code: "SL", name: "Sierra Leone", dialCode: "+232", format: m("m27") },
  { code: "SM", name: "San Marino", dialCode: "+378", format: m("m63") },
  { code: "SN", name: "Senegal", dialCode: "+221", format: m("m8") },
  { code: "SO", name: "Somalia", dialCode: "+252", format: m("m2") },
  { code: "SR", name: "Suriname", dialCode: "+597", format: m("m51") },
  { code: "SS", name: "South Sudan", dialCode: "+211", format: m("m1") },
  {
    code: "ST",
    name: "S\u00e3o Tom\u00e9 & Pr\u00edncipe",
    dialCode: "+239",
    format: m("m7"),
  },
  { code: "SV", name: "El Salvador", dialCode: "+503", format: m("m64") },
  { code: "SX", name: "Sint Maarten", dialCode: "+1" },
  { code: "SY", name: "Syria", dialCode: "+963", format: m("m1") },
  { code: "SZ", name: "Eswatini", dialCode: "+268", format: m("m65") },
  { code: "TA", name: "Tristan da Cunha", dialCode: "+290" },
  { code: "TC", name: "Turks & Caicos Islands", dialCode: "+1" },
  { code: "TD", name: "Chad", dialCode: "+235", format: m("m11") },
  { code: "TG", name: "Togo", dialCode: "+228", format: m("m11") },
  { code: "TH", name: "Thailand", dialCode: "+66", format: m("m6") },
  { code: "TJ", name: "Tajikistan", dialCode: "+992", format: m("m14") },
  { code: "TK", name: "Tokelau", dialCode: "+690" },
  { code: "TL", name: "Timor-Leste", dialCode: "+670", format: m("m12") },
  { code: "TM", name: "Turkmenistan", dialCode: "+993", format: m("m66") },
  { code: "TN", name: "Tunisia", dialCode: "+216", format: m("m39") },
  { code: "TO", name: "Tonga", dialCode: "+676", format: m("m67") },
  { code: "TR", name: "T\u00fcrkiye", dialCode: "+90", format: m("m68") },
  { code: "TT", name: "Trinidad & Tobago", dialCode: "+1" },
  { code: "TV", name: "Tuvalu", dialCode: "+688", format: m("m59") },
  { code: "TW", name: "Taiwan", dialCode: "+886", format: m("m5") },
  { code: "TZ", name: "Tanzania", dialCode: "+255", format: m("m14") },
  { code: "UA", name: "Ukraine", dialCode: "+380", format: m("m1") },
  { code: "UG", name: "Uganda", dialCode: "+256", format: m("m46") },
  { code: "US", name: "United States", dialCode: "+1", format: m("m69") },
  { code: "UY", name: "Uruguay", dialCode: "+598", format: m("m70") },
  { code: "UZ", name: "Uzbekistan", dialCode: "+998", format: m("m30") },
  { code: "VA", name: "Vatican City", dialCode: "+39" },
  { code: "VC", name: "St. Vincent & Grenadines", dialCode: "+1" },
  { code: "VE", name: "Venezuela", dialCode: "+58", format: m("m57") },
  { code: "VG", name: "British Virgin Islands", dialCode: "+1" },
  { code: "VI", name: "U.S. Virgin Islands", dialCode: "+1" },
  { code: "VN", name: "Vietnam", dialCode: "+84", format: m("m5") },
  { code: "VU", name: "Vanuatu", dialCode: "+678", format: m("m7") },
  { code: "WF", name: "Wallis & Futuna", dialCode: "+681", format: m("m8") },
  { code: "WS", name: "Samoa", dialCode: "+685", format: m("m59") },
  { code: "XK", name: "Kosovo", dialCode: "+383", format: m("m1") },
  { code: "YE", name: "Yemen", dialCode: "+967", format: m("m1") },
  { code: "YT", name: "Mayotte", dialCode: "+262" },
  { code: "ZA", name: "South Africa", dialCode: "+27", format: m("m16") },
  { code: "ZM", name: "Zambia", dialCode: "+260", format: m("m1") },
  { code: "ZW", name: "Zimbabwe", dialCode: "+263", format: m("m63") },
];

export default countries;
