// Generated by @canonical/summon-component:react v0.1.0

import { renderToString } from "react-dom/server";
import { describe, expect, it } from "vitest";
import JourneyInspector from "./JourneyInspector.js";

describe("JourneyInspector SSR", () => {
  it("renders without hydration errors", () => {
    const html = renderToString(
      <JourneyInspector>Test content</JourneyInspector>,
    );
    expect(html).toContain("Test content");
    expect(html).toContain("ds journey-inspector");
  });
});
