// Generated by @canonical/summon-component:react v0.1.0

import type React from "react";
import type { JourneyInspectorProps } from "./types.js";
import "./styles.css";

const componentCssClassName = "ds journey-inspector";

/**
 * JourneyInspector component
 */
const JourneyInspector = ({
  className,
  children,
  ...props
}: JourneyInspectorProps): React.ReactElement => {
  return (
    <div
      className={[componentCssClassName, className].filter(Boolean).join(" ")}
      {...props}
    >
      {children}
    </div>
  );
};

export default JourneyInspector;
