// Generated by @canonical/summon-component:react v0.1.0

import type { Meta, StoryObj } from "@storybook/react-vite";
import JourneyInspector from "./JourneyInspector.js";

const meta: Meta<typeof JourneyInspector> = {
  title: "Components/JourneyInspector",
  component: JourneyInspector,
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof JourneyInspector>;

export const Default: Story = {
  args: {
    children: "Hello, JourneyInspector!",
  },
};

export const WithCustomClass: Story = {
  args: {
    children: "Custom styled",
    className: "custom-class",
  },
};
