// Generated by @canonical/summon-component:react v0.1.0

import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import JourneyInspector from "./JourneyInspector.js";

describe("JourneyInspector", () => {
  it("renders children", () => {
    render(<JourneyInspector>Test content</JourneyInspector>);
    expect(screen.getByText("Test content")).toBeInTheDocument();
  });

  it("applies custom className", () => {
    render(
      <JourneyInspector className="custom-class">Content</JourneyInspector>,
    );
    const element = screen.getByText("Content");
    expect(element.className).toContain("ds journey-inspector");
    expect(element.className).toContain("custom-class");
  });

  it("passes through additional props", () => {
    render(
      <JourneyInspector data-testid="test-component">Content</JourneyInspector>,
    );
    expect(screen.getByTestId("test-component")).toBeInTheDocument();
  });
});
