<script lang="ts" module>
  // Generated by @canonical/summon:component-svelte v0.1.0
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import Link from "./Link.svelte";

  const { Story } = defineMeta({
    title: "Components/Link",
    tags: ["autodocs"],
    component: Link,
    args: {
      href: "https://ubuntu.com",
    },
  });
</script>

<Story name="Default">Link</Story>
