<!-- Generated by @canonical/summon:component-svelte v0.1.0 -->

<script lang="ts">
  import type { LinkProps } from "./types";
  import "./styles.css";

  const componentCssClassName = "ds link";

  let { class: className, children, soft, ...rest }: LinkProps = $props();
</script>

<a class={[componentCssClassName, className, { soft }]} {...rest}>
  {@render children?.()}
</a>

<!-- @component
`Link` is a styled anchor element.

## Example Usage
```svelte
<Link href="https://ubuntu.com" target="_blank" rel="noopener">
  Canonical
</Link>
```
-->
