// Generated by @canonical/summon:component-svelte v0.1.0

import type { HTMLAnchorAttributes } from "svelte/elements";

export interface LinkProps extends HTMLAnchorAttributes {
  /**
   * Whether the link should be styled softly, inheriting the color of its parent.
   */
  soft?: boolean;
}
