// Generated by @canonical/summon-component-lit v0.1.0

import { html, LitElement } from "lit";
import { customElement, property, state } from "lit/decorators.js";
import { ifDefined } from "lit/directives/if-defined.js";
import styles from "./styles.css";
import type { ButtonProps } from "./types.js";

const componentCssClassName = "ds button";

/**
 * Buttons trigger actions within an interface, typically involving
 * data transformation or manipulation. They provide clear visual
 * indicators of the primary actions users can perform.
 *
 * @implements ds:global.component.button
 */
@customElement("ds-button")
export default class Button extends LitElement implements ButtonProps {
  static shadowRootOptions = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };

  static styles = styles;

  @state()
  private hasIcon = false;

  @state()
  private slottedText = "";

  @property({ type: String, reflect: true })
  variant?: ButtonProps["variant"];

  @property({ type: String, attribute: "icon-position", reflect: true })
  iconPosition: ButtonProps["iconPosition"] = "start";

  @property({ type: String, attribute: "aria-label" })
  ariaLabel: string | null = null;

  @property({ type: Boolean })
  disabled = false;

  @property({ type: String })
  type: ButtonProps["type"] = "button";

  private onSlotChange(e: Event): void {
    const slot = e.target as HTMLSlotElement;
    if (slot.name === "icon") {
      this.hasIcon = slot.assignedElements().length > 0;
    } else {
      this.slottedText = slot
        .assignedNodes({ flatten: true })
        .map((node) => node.textContent ?? "")
        .join("")
        .trim();
    }
  }

  private deriveAriaLabel(): string | undefined {
    if (this.ariaLabel) {
      return this.ariaLabel;
    }

    return this.slottedText || undefined;
  }

  render() {
    const classes = [componentCssClassName, this.variant]
      .filter(Boolean)
      .join(" ");

    const ariaLabel = this.deriveAriaLabel();

    const iconSlot = html`
			<span class="icon" ?hidden=${!this.hasIcon}>
				<slot name="icon" @slotchange=${this.onSlotChange}></slot>
			</span>
		`;

    return html`
			<button
        id="button"
        part="button"
				class="${classes}"
				?disabled=${this.disabled}
				type="${this.type}"
				aria-label=${ifDefined(ariaLabel)}
			>
				${
          this.iconPosition === "end"
            ? html`<slot @slotchange=${this.onSlotChange}></slot>${iconSlot}`
            : html`${iconSlot}<slot @slotchange=${this.onSlotChange}></slot>`
        }
			</button>
		`;
  }
}
