// Generated by @canonical/summon:component-webcomponents v0.1.0

import type { Meta, StoryObj } from "@storybook/web-components-vite";
import { html } from "lit";
import { ifDefined } from "lit/directives/if-defined.js";

import "./Button.js";
import type Button from "./Button.js";

type StoryArgs = Button & {
  importance?: "primary" | "secondary" | "tertiary";
  anticipation?: "constructive" | "caution" | "destructive";
  label?: string;
};

const meta = {
  title: "Web Components/Button",
  tags: ["autodocs"],
  argTypes: {
    importance: {
      control: "select",
      options: [undefined, "primary", "secondary", "tertiary"],
    },
    anticipation: {
      control: "select",
      options: [undefined, "constructive", "caution", "destructive"],
    },
    variant: {
      control: "select",
      options: [undefined, "link"],
    },
    iconPosition: {
      control: "radio",
      options: ["start", "end"],
    },
    disabled: {
      control: "boolean",
    },
  },
  render: (args) => html`
    <ds-button
      class=${ifDefined([args.importance, args.anticipation].filter(Boolean).join(" ") || undefined)}
      variant=${ifDefined(args.variant)}
      icon-position=${ifDefined(args.iconPosition)}
      ?disabled=${args.disabled}
    >${args.label ?? "Button"}</ds-button>
  `,
} satisfies Meta<StoryArgs>;

export default meta;
type Story = StoryObj<StoryArgs>;

export const Default: Story = {
  args: {
    label: "Button",
  },
};

export const Primary: Story = {
  args: {
    label: "Primary",
    importance: "primary",
  },
};

export const Constructive: Story = {
  args: {
    label: "Constructive",
    anticipation: "constructive",
  },
};

export const Link: Story = {
  args: {
    label: "Learn more",
    variant: "link",
  },
};

export const IconStart: Story = {
  args: {
    label: "Create",
    iconPosition: "start",
  },
  render: (args) => html`
    <ds-button
      class=${ifDefined([args.importance, args.anticipation].filter(Boolean).join(" ") || undefined)}
      variant=${ifDefined(args.variant)}
      icon-position=${ifDefined(args.iconPosition)}
      ?disabled=${args.disabled}
    >
      <svg slot="icon" viewBox="0 0 16 16" fill="currentColor" aria-hidden="true">
        <path d="M8 1v14M1 8h14" stroke="currentColor" stroke-width="2" />
      </svg>
      ${args.label ?? "Create"}
    </ds-button>
  `,
};

export const IconEnd: Story = {
  args: {
    label: "Continue",
    iconPosition: "end",
  },
  render: (args) => html`
    <ds-button
      class=${ifDefined([args.importance, args.anticipation].filter(Boolean).join(" ") || undefined)}
      variant=${ifDefined(args.variant)}
      icon-position=${ifDefined(args.iconPosition)}
      ?disabled=${args.disabled}
    >
      <svg slot="icon" viewBox="0 0 16 16" fill="currentColor" aria-hidden="true">
        <path d="M1 8h12M9 4l4 4-4 4" stroke="currentColor" stroke-width="2" fill="none" />
      </svg>
      ${args.label ?? "Continue"}
    </ds-button>
  `,
};
