// Generated by @canonical/summon-component:lit v0.1.0

/**
 * Props for the Button component.
 */
export interface ButtonProps {
  /**
   * Button variant.
   */
  variant?: "link";

  /**
   * Position of the icon relative to the label.
   * Icon content should be provided using a named slot: slot="icon".
   */
  iconPosition?: "start" | "end";

  /**
   * Accessible label for the internal button element.
   * If not provided, a label is derived from slotted text content.
   */
  ariaLabel?: string | null;

  /**
   * Native button disabled state.
   */
  disabled?: boolean;

  /**
   * Native button type.
   */
  type?: "button" | "submit" | "reset";
}
