/**
 * Static shell-completion script templates.
 *
 * The static tier: each script inlines the nouns, per-noun verbs, and global
 * flags so a shell completes `pragma2` without invoking it. The richer dynamic
 * tier (entity names, config-derived values) is the separate `__complete`
 * resolver a later PR wires these scripts to call.
 */

import type { CompletionModel } from "./complete.js";

/** The verb `case`/branch bodies shared by the shell templates. */
function nounCases(model: CompletionModel): { noun: string; verbs: string }[] {
  return model.nouns
    .filter((noun) => (model.verbs[noun]?.length ?? 0) > 0)
    .map((noun) => ({
      noun,
      verbs: (model.verbs[noun] ?? []).join(" "),
    }));
}

/** Render the bash completion script. */
export function bashScript(model: CompletionModel): string {
  const nouns = model.nouns.join(" ");
  const globals = model.globalFlags.join(" ");
  const cases = nounCases(model)
    .map(({ noun, verbs }) => `      ${noun}) verbs="${verbs}" ;;`)
    .join("\n");

  return [
    "# pragma2 bash completion (static tier) — generated by `pragma2 setup completions`",
    "_pragma2() {",
    // biome-ignore lint/suspicious/noTemplateCurlyInString: bash parameter expansion, not a JS template
    '  local cur="${COMP_WORDS[COMP_CWORD]}"',
    `  local nouns="${nouns}"`,
    `  local globals="${globals}"`,
    '  if [ "$COMP_CWORD" -eq 1 ]; then',
    '    COMPREPLY=($(compgen -W "$nouns $globals" -- "$cur"))',
    "    return",
    "  fi",
    "  local verbs=''",
    // biome-ignore lint/suspicious/noTemplateCurlyInString: bash parameter expansion, not a JS template
    '  case "${COMP_WORDS[1]}" in',
    cases,
    "  esac",
    '  COMPREPLY=($(compgen -W "$verbs $globals" -- "$cur"))',
    "}",
    "complete -F _pragma2 pragma2",
    "",
  ].join("\n");
}

/** Render the zsh completion script. */
export function zshScript(model: CompletionModel): string {
  const nouns = model.nouns.join(" ");
  const globals = model.globalFlags.join(" ");
  const cases = nounCases(model)
    .map(({ noun, verbs }) => `      ${noun}) verbs="${verbs}" ;;`)
    .join("\n");

  return [
    "#compdef pragma2",
    "# pragma2 zsh completion (static tier)",
    "_pragma2() {",
    `  local nouns="${nouns}"`,
    `  local globals="${globals}"`,
    "  if (( CURRENT == 2 )); then",
    // biome-ignore lint/suspicious/noTemplateCurlyInString: zsh word-splitting expansion, not a JS template
    "    compadd -- ${=nouns} ${=globals}",
    "    return",
    "  fi",
    "  local verbs=''",
    // biome-ignore lint/suspicious/noTemplateCurlyInString: zsh parameter expansion, not a JS template
    '  case "${words[2]}" in',
    cases,
    "  esac",
    // biome-ignore lint/suspicious/noTemplateCurlyInString: zsh word-splitting expansion, not a JS template
    "  compadd -- ${=verbs} ${=globals}",
    "}",
    "compdef _pragma2 pragma2",
    "",
  ].join("\n");
}

/** Render the fish completion script. */
export function fishScript(model: CompletionModel): string {
  const lines: string[] = [
    "# pragma2 fish completion (static tier)",
    `complete -c pragma2 -n __fish_use_subcommand -a "${model.nouns.join(" ")}"`,
  ];
  for (const noun of model.nouns) {
    const verbs = model.verbs[noun] ?? [];
    if (verbs.length > 0) {
      lines.push(
        `complete -c pragma2 -n "__fish_seen_subcommand_from ${noun}" -a "${verbs.join(" ")}"`,
      );
    }
  }
  for (const flag of model.globalFlags) {
    lines.push(`complete -c pragma2 -l "${flag.replace(/^--/, "")}"`);
  }
  lines.push("");
  return lines.join("\n");
}
