// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import type React from "react";
import type { ChatSectionProps } from "./types.js";
import "./styles.css";
import { TSection } from "../TSection/index.js";

const componentCssClassName = "ds chat-section";

/**
 * ChatSection component
 */
const ChatSection = ({
  className,
  children,
  title,
  ...props
}: ChatSectionProps): React.ReactNode => {
  return (
    <TSection
      className={[componentCssClassName, className].filter(Boolean).join(" ")}
      {...props}
      title={title}
    >
      <div className="form">
        <textarea placeholder="Type your message here..." />
      </div>
    </TSection>
  );
};

export default ChatSection;
