// Generated by @canonical/summon-component:react v0.1.0

import { describe, expect, it } from "vitest";
import { render, screen } from "@testing-library/react";
import Footer from "./Footer.js";

describe("Footer", () => {
	it("renders children", () => {
		render(<Footer>Test content</Footer>);
		expect(screen.getByText("Test content")).toBeInTheDocument();
	});

	it("applies custom className", () => {
		render(<Footer className="custom-class">Content</Footer>);
		const element = screen.getByText("Content");
		expect(element.className).toContain("ds footer");
		expect(element.className).toContain("custom-class");
	});

	it("passes through additional props", () => {
		render(<Footer data-testid="test-component">Content</Footer>);
		expect(screen.getByTestId("test-component")).toBeInTheDocument();
	});
});
