// Generated by @canonical/summon-component:react v0.1.0

import type { Meta, StoryObj } from "@storybook/react-vite";
import Footer from "./Footer.js";

const meta: Meta<typeof Footer> = {
	title: "Components/SideNavigation/Footer",
	component: Footer,
	tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof Footer>;

export const Default: Story = {
	args: {
		children: "Hello, Footer!",
	},
};

export const WithCustomClass: Story = {
	args: {
		children: "Custom styled",
		className: "custom-class",
	},
};
