// Generated by @canonical/summon-component:react v0.1.0

import type React from "react";
import type { FooterProps } from "./types.js";
import "./styles.css";

const componentCssClassName = "ds footer";

/**
 * Footer component
 */
const Footer = ({
	className,
	children,
	...props
}: FooterProps): React.ReactElement => {
	return (
		<div
			className={[componentCssClassName, className].filter(Boolean).join(" ")}
			{...props}
		>
			{children}
		</div>
	);
};

export default Footer;
