// Generated by @canonical/summon-component:react v0.1.0

import { render, screen } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";
import type { FooterItem } from "../../types.js";
import Footer from "./Footer.js";

describe("Footer", () => {
  it("renders children", () => {
    render(<Footer>Test content</Footer>);
    expect(screen.getByText("Test content")).toBeInTheDocument();
  });

  it("applies custom className", () => {
    render(<Footer className="custom-class">Content</Footer>);
    const element = screen.getByText("Content");
    expect(element.className).toContain("ds footer");
    expect(element.className).toContain("custom-class");
  });

  it("passes through additional props", () => {
    render(<Footer data-testid="test-component">Content</Footer>);
    expect(screen.getByTestId("test-component")).toBeInTheDocument();
  });

  describe("items (closed footer-items vocabulary)", () => {
    const items: FooterItem[] = [
      { kind: "account", url: "/account", label: "Ada Lovelace" },
      { kind: "notifications", url: "/notifications", slot: <span>3</span> },
      { kind: "logout", onClick: vi.fn() },
    ];

    it("renders each item with its default or given label", () => {
      render(<Footer items={items} />);
      expect(
        screen.getByRole("link", { name: "Ada Lovelace" }),
      ).toHaveAttribute("href", "/account");
      expect(
        screen.getByRole("link", { name: /^Notifications/ }),
      ).toHaveAttribute("href", "/notifications");
      expect(
        screen.getByRole("button", { name: "Log out" }),
      ).toBeInTheDocument();
    });

    it("renders navigable items as links and action items as buttons", () => {
      render(<Footer items={items} />);
      expect(
        screen.getByRole("link", { name: "Ada Lovelace" }),
      ).toBeInTheDocument();
      expect(
        screen.getByRole("button", { name: "Log out" }),
      ).toBeInTheDocument();
    });

    it("calls onClick for an action item", () => {
      const onClick = vi.fn();
      render(<Footer items={[{ kind: "logout", onClick }]} />);
      screen.getByRole("button", { name: "Log out" }).click();
      expect(onClick).toHaveBeenCalledOnce();
    });

    it("renders the trailing slot", () => {
      render(<Footer items={items} />);
      expect(screen.getByText("3")).toBeInTheDocument();
    });

    it("takes precedence over root and children", () => {
      render(
        <Footer items={[{ kind: "logout" }]} root={{ key: "root", items: [] }}>
          Fallback
        </Footer>,
      );
      expect(
        screen.getByRole("button", { name: "Log out" }),
      ).toBeInTheDocument();
      expect(screen.queryByText("Fallback")).not.toBeInTheDocument();
    });

    it("hides the footer's logout item and shows the certificate icon for a certificate user", () => {
      const { container } = render(<Footer items={items} certificateUser />);
      expect(
        screen.queryByRole("button", { name: "Log out" }),
      ).not.toBeInTheDocument();
      expect(
        container.querySelector("use[href$='certificate.svg#certificate']"),
      ).toBeInTheDocument();
    });
  });
});
