// Generated by @canonical/summon-component:react v0.1.0

import { describe, expect, it } from "vitest";
import { renderToString } from "react-dom/server";
import Footer from "./Footer.js";

describe("Footer SSR", () => {
	it("renders without hydration errors", () => {
		const html = renderToString(<Footer>Test content</Footer>);
		expect(html).toContain("Test content");
		expect(html).toContain("ds footer");
	});
});
