// Generated by @canonical/summon:component-webcomponents v0.1.0

import { html, LitElement } from "lit";
import { customElement } from "lit/decorators.js";
import styles from "./styles.css";
import type { HeroProps } from "./types.js";

const componentCssClassName = "ds hero";

/**
 * Hero web component.
 *
 * @implements ds:global.component.hero
 */
@customElement("ds-hero")
export default class Hero extends LitElement implements HeroProps {
  static styles = styles;

  render() {
    return html`
			<div class="${componentCssClassName}">
        <slot></slot>
        <slot name="image"></slot>
			</div>
		`;
  }
}
