// Generated by @canonical/summon:component-webcomponents v0.1.0

/**
 * Props for the Hero component.
 */
export type HeroProps = {
  /** Heading text for the section. */
  title?: string;
  /** Descriptive text displayed beside the heading. */
  description?: string;
};
