import { existsSync } from "node:fs";
import { resolve } from "node:path";
import { detectPackageManager, PM_COMMANDS } from "../../../pm.js";

export interface AddConfigResult {
  readonly configPath: string;
  readonly configContent: string;
  readonly tokenSources: readonly string[];
  readonly alreadyExists: boolean;
  readonly installHint: string;
}

/**
 * Resolve the tokens config to generate.
 *
 * Returns data only — the caller writes the file.
 */
export default function resolveAddConfig(cwd: string): AddConfigResult {
  const configPath = resolve(cwd, "tokens.config.mjs");
  const alreadyExists = existsSync(configPath);

  const tokenSources = ["node_modules/@canonical/ds-global/tokens/**/*.json"];

  const configContent = generateConfigContent(tokenSources);

  const pm = detectPackageManager();
  const installHint = `Recommended: ${PM_COMMANDS[pm].install("@canonical/terrazzo-lsp")}`;

  return {
    configPath,
    configContent,
    tokenSources,
    alreadyExists,
    installHint,
  };
}

function generateConfigContent(sources: readonly string[]): string {
  const sourcesStr = sources.map((s) => `    "${s}"`).join(",\n");
  return `// tokens.config.mjs — generated by pragma tokens add-config
import { defineConfig } from "@canonical/terrazzo";

export default defineConfig({
  tokens: [
${sourcesStr},
  ],
  outDir: "./tokens/",
  plugins: [],
});
`;
}
