// Generated by summon webapp
// Tests for my-webapp

import { describe, it, expect } from 'vitest';

describe('MyWebapp', () => {
  it('should pass a basic test', () => {
    expect(true).toBe(true);
  });

  describe('App Store', () => {
    it('should initialize with count of 0', async () => {
      const { useAppStore } = await import('../src/state');
      const { count } = useAppStore.getState();
      expect(count).toBe(0);
    });

    it('should increment count', async () => {
      const { useAppStore } = await import('../src/state');
      const { increment } = useAppStore.getState();
      increment();
      expect(useAppStore.getState().count).toBe(1);
    });

    it('should decrement count', async () => {
      const { useAppStore } = await import('../src/state');
      const store = useAppStore.getState();
      store.reset();
      store.decrement();
      expect(useAppStore.getState().count).toBe(-1);
    });
  });

  describe('API Client', () => {
    it('should be configured with base URL', async () => {
      const { api } = await import('../src/api');
      expect(api).toBeDefined();
    });
  });

});
