// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import type { Meta, StoryObj } from "@storybook/react-vite";
import { SettingsView } from "./SettingsView.js";

const meta: Meta<typeof SettingsView> = {
  title: "Components/SettingsView",
  component: SettingsView,
  tags: ["autodocs"],
  parameters: {
    grid: "responsive",
  },
};

export default meta;
type Story = StoryObj<typeof SettingsView>;

export const Default: Story = {
  args: {
    children: "Hello, SettingsView!",
  },
};

export const WithCustomClass: Story = {
  args: {
    children: "Custom styled",
    className: "custom-class",
  },
};
