// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import type { SettingsViewProps } from "./types";
import "./styles.css";

/**
 * SettingsView component
 */
export const SettingsView = ({
	className,
	children,
	title,
	...props
}: SettingsViewProps): JSX.Element => {
	return (
		<div
			className={`settings-view${className ? ` ${className}` : ""}`}
			{...props}
		>
			<h2>{title}</h2>
			<div className="content">
				{children}
				<div className="setting">
					<label htmlFor="setting1">Setting 1.0</label>
					<input type="text" name="setting1" />
				</div>
				<div className="setting">
					<label htmlFor="setting1">Setting 1.0</label>
					<input type="text" name="setting1" />
				</div>
			</div>
		</div>
	);
};
