// Generated by @canonical/summon-component:react v0.1.0

import bindField from "#lib/common/bindField/index.js";
import withWrapper from "#lib/common/Wrapper/withWrapper.js";
import { PasswordInput } from "#lib/subcomponent/PasswordInput/index.js";
import type { PasswordFieldProps } from "./types.js";

/**
 * PasswordInput bound to react-hook-form, wrapped with field chrome (label,
 * description, error) and middleware/conditional-display support. Collects a
 * secret value, masked by default, with a reveal/mask toggle.
 *
 * `import { PasswordField } from "@canonical/react-ds-global-form";`
 */
export default withWrapper<PasswordFieldProps>(
  bindField<PasswordFieldProps>(PasswordInput, "native"),
);
