// Generated by @canonical/summon-component:react v0.1.0

import { renderToString } from "react-dom/server";
import { FormProvider, useForm } from "react-hook-form";
import { describe, expect, it } from "vitest";
import PasswordField from "./PasswordField.js";

function SSRHost() {
  const methods = useForm();
  return (
    <FormProvider {...methods}>
      <PasswordField name="password" label="Password" />
    </FormProvider>
  );
}

// Proves the field renders to static HTML (masked) under a form provider.
describe("PasswordField SSR", () => {
  it("renders the labelled masked field to static HTML", () => {
    const html = renderToString(<SSRHost />);
    expect(html).toContain("Password");
    expect(html).toContain('type="password"');
    expect(html).toContain("ds input password chrome");
  });
});
