// Generated by @canonical/summon-component:react v0.1.0

import { fireEvent, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import { renderWithForm } from "../../../testing/renderWithForm.js";
import PasswordField from "./PasswordField.js";

// PasswordField = PasswordInput bound to react-hook-form + field chrome, so it
// is tested through a FormProvider.
describe("PasswordField", () => {
  it("renders the label, description, and a masked input", () => {
    renderWithForm(
      <PasswordField
        name="password"
        label="Password"
        description="At least 8 characters"
      />,
    );
    expect(screen.getByText("Password")).toBeInTheDocument();
    expect(screen.getByText("At least 8 characters")).toBeInTheDocument();
    expect(screen.getByLabelText("Password")).toHaveAttribute(
      "type",
      "password",
    );
  });

  it("reveals the value when the toggle is pressed", () => {
    renderWithForm(<PasswordField name="password" label="Password" />);
    const input = screen.getByLabelText("Password");
    expect(input).toHaveAttribute("type", "password");
    fireEvent.click(screen.getByRole("button", { name: "Show password" }));
    expect(input).toHaveAttribute("type", "text");
  });

  it("registers the field value with the form", () => {
    renderWithForm(<PasswordField name="password" label="Password" />);
    const input = screen.getByLabelText("Password");
    fireEvent.change(input, { target: { value: "hunter2" } });
    expect(input).toHaveValue("hunter2");
  });
});
