// Generated by @canonical/summon-component:react v0.1.0

import type { InputProps } from "../../common/types.js";
import type { PasswordInputProps } from "../../subcomponent/PasswordInput/index.js";

/** Props for the react-hook-form-bound Password field (presentational + binding). */
export type PasswordFieldProps = InputProps<PasswordInputProps>;
