// Generated by @canonical/summon-component:react v0.1.0

import type { Meta, StoryObj } from "@storybook/react-vite";
import JourneyRail from "./JourneyRail.js";

const meta: Meta<typeof JourneyRail> = {
  title: "Components/JourneyRail",
  component: JourneyRail,
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof JourneyRail>;

export const Default: Story = {
  args: {
    children: "Hello, JourneyRail!",
  },
};

export const WithCustomClass: Story = {
  args: {
    children: "Custom styled",
    className: "custom-class",
  },
};
