// Generated by @canonical/summon-component:react v0.1.0

import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import JourneyRail from "./JourneyRail.js";

describe("JourneyRail", () => {
  it("renders children", () => {
    render(<JourneyRail>Test content</JourneyRail>);
    expect(screen.getByText("Test content")).toBeInTheDocument();
  });

  it("applies custom className", () => {
    render(<JourneyRail className="custom-class">Content</JourneyRail>);
    const element = screen.getByText("Content");
    expect(element.className).toContain("ds journey-rail");
    expect(element.className).toContain("custom-class");
  });

  it("passes through additional props", () => {
    render(<JourneyRail data-testid="test-component">Content</JourneyRail>);
    expect(screen.getByTestId("test-component")).toBeInTheDocument();
  });
});
