// Generated by @canonical/summon-component:react v0.1.0

import type React from "react";
import type { JourneyRailProps } from "./types.js";
import "./styles.css";

const componentCssClassName = "ds journey-rail";

/**
 * JourneyRail component
 */
const JourneyRail = ({
  className,
  children,
  ...props
}: JourneyRailProps): React.ReactElement => {
  return (
    <div
      className={[componentCssClassName, className].filter(Boolean).join(" ")}
      {...props}
    >
      {children}
    </div>
  );
};

export default JourneyRail;
