// Generated by @canonical/summon-component:react v0.1.0

import { renderToString } from "react-dom/server";
import { describe, expect, it } from "vitest";
import JourneyRail from "./JourneyRail.js";

describe("JourneyRail SSR", () => {
  it("renders without hydration errors", () => {
    const html = renderToString(<JourneyRail>Test content</JourneyRail>);
    expect(html).toContain("Test content");
    expect(html).toContain("ds journey-rail");
  });
});
