// Generated by summon webapp
// Tests for my-app

import { describe, it, expect } from 'vitest';

describe('MyApp', () => {
  it('should pass a basic test', () => {
    expect(true).toBe(true);
  });



});
