// Generated by @canonical/summon-component:react v0.1.0

import type { Meta, StoryObj } from "@storybook/react-vite";
import HierarchyWell from "./HierarchyWell.js";

const meta: Meta<typeof HierarchyWell> = {
  title: "Components/HierarchyWell",
  component: HierarchyWell,
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof HierarchyWell>;

export const Default: Story = {
  args: {
    children: "Hello, HierarchyWell!",
  },
};

export const WithCustomClass: Story = {
  args: {
    children: "Custom styled",
    className: "custom-class",
  },
};
