// Generated by @canonical/summon-component:react v0.1.0

import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import HierarchyWell from "./HierarchyWell.js";

describe("HierarchyWell", () => {
  it("renders children", () => {
    render(<HierarchyWell>Test content</HierarchyWell>);
    expect(screen.getByText("Test content")).toBeInTheDocument();
  });

  it("applies custom className", () => {
    render(<HierarchyWell className="custom-class">Content</HierarchyWell>);
    const element = screen.getByText("Content");
    expect(element.className).toContain("ds hierarchy-well");
    expect(element.className).toContain("custom-class");
  });

  it("passes through additional props", () => {
    render(<HierarchyWell data-testid="test-component">Content</HierarchyWell>);
    expect(screen.getByTestId("test-component")).toBeInTheDocument();
  });
});
