// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import type { Meta, StoryObj } from "@storybook/react";
import IconSection from "./IconSection.js";
import * as decorators from "../../../storybook/decorators.js";

const meta: Meta<typeof IconSection> = {
  title: "Components/IconSection",
  component: IconSection,
  tags: ["autodocs"],
  decorators: [decorators.grid()],
};

export default meta;
type Story = StoryObj<typeof IconSection>;

export const Default: Story = {
  args: {
    children: "Hello, IconSection!",
  },
};

export const WithCustomClass: Story = {
  args: {
    children: "Custom styled",
    className: "custom-class",
  },
};
