// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import IconSection from "./IconSection.js";

describe("IconSection", () => {
  it("renders the icon set", () => {
    const { container } = render(<IconSection />);
    expect(container.querySelectorAll(".icon-wrapper").length).toBeGreaterThan(
      0,
    );
  });

  it("applies custom className", () => {
    const { container } = render(<IconSection className="custom-class" />);
    expect(container.firstChild).toHaveClass(
      "ds",
      "icon-section",
      "custom-class",
    );
  });

  it("passes through additional props", () => {
    render(<IconSection data-testid="test-component" />);
    expect(screen.getByTestId("test-component")).toBeInTheDocument();
  });
});
