// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import type React from "react";
import type { IconSectionProps } from "./types.js";
import "./styles.css";
import { Section } from "../Section/index.js";
import { Icon } from "../../Icon/index.js";

const componentCssClassName = "ds icon-section";

const iconSelection: string[] = [
  "arrow-down",
  "arrow-left",
  "arrow-right",
  "arrow-up",
  "blueprint",
  "bug",
  "checkmark",
  "chevron-down",
  "chevron-right",
  "close",
  "code",
  "copy",
  "debug",
  "delete",
  "download",
  "edit",
  "error",
  "external-link",
  "file",
  "filter",
  "folder",
  "help",
  "home",
  "information",
  "link",
  "menu",
  "notifications",
  "plus",
  "search",
  "security",
];

/**
 * IconSection component
 */
const IconSection = ({
  className,
  children,
  ...props
}: IconSectionProps): React.ReactElement => {
  return (
    <Section
      className={[componentCssClassName, className].filter(Boolean).join(" ")}
      {...props}
    >
      {iconSelection.map((icon) => (
        <div class="icon-wrapper">
          <Icon icon={icon} />
        </div>
      ))}
    </Section>
  );
};

export default IconSection;
