// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import type { HTMLAttributes } from "react";

/**
 * The component renders a fixed icon grid; it accepts no children.
 */
export type IconSectionProps = Omit<HTMLAttributes<HTMLDivElement>, "children">;
