// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import type { ComponentProps, ReactNode } from "react";

type OwnProps = {
  /** Content to render inside the component */
  children?: ReactNode;
  /**
   * The section heading, rendered into the section's `<h2>`.
   *
   * `title` is DS-owned here and deliberately shadows the native `title`
   * attribute: it is consumed as the heading and never forwarded to the DOM,
   * so a `TSection` cannot also carry a native `title` tooltip.
   * @default "Section title"
   */
  title?: string;
};

export type TSectionProps = OwnProps &
  Omit<ComponentProps<"section">, keyof OwnProps>;
