<!-- Generated by @canonical/summon:component-svelte v0.1.0 -->

<script lang="ts" module>
  const roundedValueFormatter = new Intl.NumberFormat("en-US", {
    notation: "compact",
    compactDisplay: "short",
    minimumFractionDigits: 0,
    maximumFractionDigits: 1,
  });
</script>

<script lang="ts">
  import type { BadgeProps } from "./types";
  import "./styles.css";

  const componentCssClassName = "ds badge";

  const {
    class: className,
    value,
    variant = "capped",
    severity,
    ...rest
  }: BadgeProps = $props();

  const displayValue = $derived.by(() => {
    const nonNegativeInt = Math.round(Math.max(value, 0));

    if (variant === "capped") {
      return nonNegativeInt > 999 ? "999+" : nonNegativeInt;
    }

    return roundedValueFormatter.format(nonNegativeInt);
  });
</script>

<span class={[componentCssClassName, className, severity]} {...rest}>
  {displayValue}
</span>

<!-- @component
`Badge` is a visual indicator for numeric values. It is static and not interactive.

## Example Usage
```svelte
<Badge value={42} severity="caution" />
<Badge value={2351} variant="rounded" />
```
-->
