<script lang="ts" module>
  // Generated by @canonical/summon:component-svelte v0.1.0
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import { MODIFIER_FAMILIES } from "../../modifier-families/index.js";
  import Badge from "./Badge.svelte";

  const { Story } = defineMeta({
    title: "Components/Badge",
    component: Badge,
    tags: ["autodocs"],
    argTypes: {
      value: { control: { type: "number", min: 0, step: 1 } },
    },
  });
</script>

<Story name="Default" args={{ value: 42 }} />

<Story
  name="Capped"
  argTypes={{ value: { table: { disable: true } } }}
  args={{ variant: "capped" }}
>
  {#snippet template(args)}
    <div class="row">
      {#each [0, 42, 999, 2100] as value (value)}
        <Badge {...args} {value} />
      {/each}
    </div>
  {/snippet}
</Story>

<Story
  name="Rounded"
  argTypes={{ value: { table: { disable: true } } }}
  args={{ variant: "rounded" }}
>
  {#snippet template(args)}
    <div class="row">
      {#each [0, 42, 999, 2100, 10_000, 251_110, 8_899_500, 1_111_111_111, 98_123_456_789_890] as value (value)}
        <Badge {...args} {value} />
      {/each}
    </div>
  {/snippet}
</Story>

<Story
  name="Severities"
  argTypes={{ severity: { table: { disable: true } } }}
  args={{ value: 42 }}
>
  {#snippet template(args)}
    {#each MODIFIER_FAMILIES.severity as severity (severity)}
      <div class="row">
        <Badge {...args} {severity} />
        {severity || "default"}
      </div>
    {/each}
  {/snippet}
</Story>
