// Generated by @canonical/summon:component-svelte v0.1.0

import type { SvelteHTMLElements } from "svelte/elements";
import type { ModifierFamily } from "../../modifier-families/index.js";

export interface BadgeProps
  extends Omit<SvelteHTMLElements["span"], "children">,
    ModifierFamily<"severity"> {
  /**
   * The non-negative integer value displayed within the badge. Negative values will be clamped to 0. Floats will be rounded.
   */
  value: number;
  /**
   * - `capped` should be used whenever the amount of items is only relevant for small values. If the `value` is larger than 999, it will be displayed as `999+`.
   * - `rounded` should be used whenever differences between large amounts of items are relevant. Values larger than 999 will be displayed as `1K`, `2.5M`, etc.
   *
   * @default "capped"
   */
  variant?: "capped" | "rounded";
}
