// Generated by @canonical/summon-component:react v0.1.0

import type React from "react";
import type { SideNavigationProps } from "./types.js";
import "./styles.css";
import { Header, Content, Footer} from "./common/index.js";

const componentCssClassName = "ds side-navigation";

/**
 * SideNavigation component
 */
const SideNavigation = ({
	className,
	children,
	...props
}: SideNavigationProps): React.ReactElement => {
	return (
		<div
			className={[componentCssClassName, className].filter(Boolean).join(" ")}
			{...props}
		>
      <Header>
        TEST
      </Header>
      <Content>
			{children}
      </Content>
      <Footer>
        TEST
      </Footer>

		</div>
	);
};

export default SideNavigation;
