// Generated by @canonical/summon-component:react v0.1.0

import { describe, expect, it } from "vitest";
import { renderToString } from "react-dom/server";
import SideNavigation from "./SideNavigation.js";

describe("SideNavigation SSR", () => {
	it("renders without hydration errors", () => {
		const html = renderToString(<SideNavigation>Test content</SideNavigation>);
		expect(html).toContain("Test content");
		expect(html).toContain("ds side-navigation");
	});
});
