<!-- Generated by @canonical/summon-component:svelte v0.1.0 -->

<script lang="ts" module>
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import {
    ACTION_KEYS,
    FUNCTION_KEYS,
    MODIFIER_KEYS,
    NAVIGATION_KEYS,
  } from "./constants.js";
  import KeyboardKey from "./KeyboardKey.svelte";
  import type { Key } from "./types.js";

  const { Story } = defineMeta({
    title: "Components/KeyboardKey",
    component: KeyboardKey,
    tags: ["autodocs"],
    argTypes: {
      keyValue: { control: { type: "select" } },
    },
    parameters: {
      // Svelte 5 Storybook autodocs do not currently pick up component docs from
      // the component source reliably, so we inject the description here instead:
      // https://github.com/storybookjs/storybook/discussions/34104#discussioncomment-16084065
      docs: {
        description: {
          component:
            'The KeyboardKey component renders a single keyboard key as a styled kbd element. It maps a key identifier (letters, digits, modifiers, function keys, navigation keys, and action keys) to its display label and presents it as a compact, inline visual indicator. Use it to represent keyboard shortcuts, key bindings, or individual keys within instructional or reference content. It is non-interactive and purely informational.\n\n`import { KeyboardKey } from "@canonical/svelte-ds-app-wpe";`',
        },
      },
    },
  });

  const modifierKeys = Object.keys(MODIFIER_KEYS) as Key[];
  const actionKeys = Object.keys(ACTION_KEYS) as Key[];
  const navigationKeys = Object.keys(NAVIGATION_KEYS) as Key[];
  const functionKeys = Object.keys(FUNCTION_KEYS) as Key[];
</script>

<!-- Render inside a baseline-aligned paragraph so the inline <kbd> keys sit on
     the text baseline, as they would in real usage. -->

<Story name="Default" args={{ keyValue: "enter" }}>
  {#snippet template(args)}
    <div class="surface story-surface">
      <p class="p"><KeyboardKey {...args} /></p>
    </div>
  {/snippet}
</Story>

<Story name="ModifierKeys" argTypes={{ keyValue: { table: { disable: true } } }}>
  {#snippet template()}
    <div class="surface story-surface">
      <p class="p">
        <span style="display: inline-flex; gap: var(--dimension-100);">
          {#each modifierKeys as key (key)}
            <KeyboardKey keyValue={key} />
          {/each}
        </span>
      </p>
    </div>
  {/snippet}
</Story>

<Story name="ActionKeys" argTypes={{ keyValue: { table: { disable: true } } }}>
  {#snippet template()}
    <div class="surface story-surface">
      <p class="p">
        <span style="display: inline-flex; gap: var(--dimension-100);">
          {#each actionKeys as key (key)}
            <KeyboardKey keyValue={key} />
          {/each}
        </span>
      </p>
    </div>
  {/snippet}
</Story>

<Story
  name="NavigationKeys"
  argTypes={{ keyValue: { table: { disable: true } } }}
>
  {#snippet template()}
    <div class="surface story-surface">
      <p class="p">
        <span style="display: inline-flex; gap: var(--dimension-100);">
          {#each navigationKeys as key (key)}
            <KeyboardKey keyValue={key} />
          {/each}
        </span>
      </p>
    </div>
  {/snippet}
</Story>

<Story name="FunctionKeys" argTypes={{ keyValue: { table: { disable: true } } }}>
  {#snippet template()}
    <div class="surface story-surface">
      <p class="p">
        <span style="display: inline-flex; gap: var(--dimension-100);">
          {#each functionKeys as key (key)}
            <KeyboardKey keyValue={key} />
          {/each}
        </span>
      </p>
    </div>
  {/snippet}
</Story>

<style>
  /* KeyboardKey carries `.surface`, so it renders on the NEXT layer of whatever
     surface it sits in. Render the stories on a painted `.surface` so the key
     steps up to the surface+1 ("like inputs") fill and reads correctly, as it
     would in an app. The inner `.p` keeps the inline <kbd> keys on the baseline. */
  .story-surface {
    background: var(--surface-color-background);
    color: var(--surface-color-text);
    padding: var(--dimension-200);
  }
</style>
