// Generated by @canonical/summon-component:svelte v0.1.0

import type { SvelteHTMLElements } from "svelte/elements";
import type { KEY_LABELS } from "./constants.js";

/** Valid keyboard key identifiers, derived from KEY_LABELS */
export type Key = keyof typeof KEY_LABELS;

type BaseProps = Omit<SvelteHTMLElements["kbd"], "children">;

export interface KeyboardKeyProps extends BaseProps {
  /** The keyboard key to display */
  keyValue: Key;
}
