// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import { renderToString } from "react-dom/server";
import { describe, expect, it } from "vitest";
import ChatSection from "./ChatSection.js";

describe("ChatSection SSR", () => {
  it("renders without hydration errors", () => {
    const html = renderToString(<ChatSection />);
    expect(html).toContain("Type your message here...");
    expect(html).toContain("ds chat-section");
  });
});
