// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import ChatSection from "./ChatSection.js";

describe("ChatSection", () => {
  it("renders the message form", () => {
    render(<ChatSection />);
    expect(
      screen.getByPlaceholderText("Type your message here..."),
    ).toBeInTheDocument();
  });

  it("applies custom className", () => {
    const { container } = render(<ChatSection className="custom-class" />);
    expect(container.firstChild).toHaveClass(
      "ds",
      "chat-section",
      "custom-class",
    );
  });

  it("passes through additional props", () => {
    render(<ChatSection data-testid="test-component" />);
    expect(screen.getByTestId("test-component")).toBeInTheDocument();
  });
});
