// Generated by @canonical/summon-component:react v0.1.0

import type React from "react";
import type { ShellProps } from "./types.js";
import "./styles.css";

const componentCssClassName = "ds shell";

/**
 * Shell component
 */
const Shell = ({
  className,
  children,
  ...props
}: ShellProps): React.ReactElement => {
  return (
    <div
      className={[componentCssClassName, className].filter(Boolean).join(" ")}
      {...props}
    >
      {children}
    </div>
  );
};

export default Shell;
