// Generated by @canonical/summon-component:react v0.1.0

import { createStaticRouter } from "@canonical/router-core";
import { RouterProvider } from "@canonical/router-react";
import { renderToString } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { appRoutes, notFoundRoute } from "../../routes.js";
import Shell from "./Shell.js";

describe("Shell SSR", () => {
  it("server-renders the whole frame with children in the canvas", () => {
    const html = renderToString(
      <RouterProvider
        router={createStaticRouter(appRoutes, "/", { notFound: notFoundRoute })}
      >
        <Shell>Test content</Shell>
      </RouterProvider>,
    );
    expect(html).toContain("ds shell");
    expect(html).toContain('data-region="primary-nav"');
    expect(html).toContain('data-region="mode-strip"');
    expect(html).toContain('data-region="canvas"');
    expect(html).toContain('data-region="footer"');
    expect(html).toContain("Test content");
  });
});
