// Generated by @canonical/summon-component:react v0.1.0

import { renderToString } from "react-dom/server";
import { describe, expect, it } from "vitest";
import Shell from "./Shell.js";

describe("Shell SSR", () => {
  it("renders without hydration errors", () => {
    const html = renderToString(<Shell>Test content</Shell>);
    expect(html).toContain("Test content");
    expect(html).toContain("ds shell");
  });
});
