// Generated by @canonical/summon-component:react v0.1.0

import type { Meta, StoryObj } from "@storybook/react-vite";
import Shell from "./Shell.js";

const meta: Meta<typeof Shell> = {
  title: "Components/Shell",
  component: Shell,
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof Shell>;

export const Default: Story = {
  args: {
    children: "Hello, Shell!",
  },
};

export const WithCustomClass: Story = {
  args: {
    children: "Custom styled",
    className: "custom-class",
  },
};
