// Generated by @canonical/summon-component:react v0.1.0

import type { HTMLAttributes, ReactNode } from "react";

export interface ShellProps extends HTMLAttributes<HTMLDivElement> {
  /** Content to render inside the component */
  children?: ReactNode;
}
