// Generated by package v0.1.0
/**
 * @canonical/svelte-ds-app-wpe
 *
 * WPE-specific components for the Pragma design system.
 * This package provides Svelte UI components for the Workplace V2 application.
 */

export * from "./components/index.js";
