// Generated by @canonical/summon-component:react v0.1.0

import type { Meta, StoryObj } from "@storybook/react-vite";
import {
  LayoutSlot,
  layoutDecorators,
  mockCards,
} from "#storybook/layouts/story-utils.js";
import ContentLayout from "../ContentLayout/ContentLayout.js";
import ViewLayout from "../ViewLayout/ViewLayout.js";
import ApplicationLayout from "./ApplicationLayout.js";

const meta: Meta<typeof ApplicationLayout> = {
  title: "Layouts/ApplicationLayout",
  component: ApplicationLayout,
  tags: ["autodocs"],
  parameters: { layout: "fullscreen" },
  decorators: layoutDecorators,
};

export default meta;
type Story = StoryObj<typeof ApplicationLayout>;

/** Navigation rail (min-content) + content area (1fr). */
export const Default: Story = {
  args: {
    navigation: (
      <LayoutSlot name="navigation" style={{ inlineSize: "16rem" }} />
    ),
    children: <LayoutSlot name="default" />,
  },
};

/** Without the navigation slot, the content takes the full width. */
export const WithoutNavigation: Story = {
  args: {
    children: <LayoutSlot name="default" />,
  },
};

/**
 * The full layout grammar — ApplicationLayout > ViewLayout > ContentLayout.
 * Dashed rectangles mark slots; solid ones are example content (cards) on
 * the ContentLayout grid. Every placeholder is a nested surface, so depth
 * reads as shade.
 */
export const Composed: Story = {
  args: {
    navigation: (
      <LayoutSlot name="navigation" style={{ inlineSize: "16rem" }} />
    ),
    children: (
      <ViewLayout
        aside={<LayoutSlot name="aside" style={{ inlineSize: "20rem" }} />}
      >
        <ContentLayout>{mockCards(8)}</ContentLayout>
      </ViewLayout>
    ),
  },
};
