// Generated by @canonical/summon-component:react v0.1.0

import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import ApplicationLayout from "./ApplicationLayout.js";

describe("ApplicationLayout", () => {
  it("renders children in the content region", () => {
    const { container } = render(
      <ApplicationLayout>Test content</ApplicationLayout>,
    );
    const content = container.querySelector(".content");
    expect(content).toHaveTextContent("Test content");
  });

  it("applies the base and custom class to the root", () => {
    const { container } = render(
      <ApplicationLayout className="custom-class">Content</ApplicationLayout>,
    );
    const el = container.firstElementChild;
    expect(el?.className).toContain("ds application-layout");
    expect(el?.className).toContain("custom-class");
  });

  it("renders the navigation slot in the navigation region", () => {
    const { container } = render(
      <ApplicationLayout navigation={<span>Nav</span>}>
        Content
      </ApplicationLayout>,
    );
    const navigation = container.querySelector(".navigation");
    expect(navigation).toHaveTextContent("Nav");
    expect(screen.getByText("Content")).toBeInTheDocument();
  });

  it("omits the navigation region when the slot is not provided", () => {
    const { container } = render(
      <ApplicationLayout>Content</ApplicationLayout>,
    );
    expect(container.querySelector(".navigation")).toBeNull();
  });

  it("passes through additional props", () => {
    render(
      <ApplicationLayout data-testid="test-component">
        Content
      </ApplicationLayout>,
    );
    expect(screen.getByTestId("test-component")).toBeInTheDocument();
  });
});
