// Generated by @canonical/summon-component:react v0.1.0

import type React from "react";
import type { ApplicationLayoutProps } from "./types.js";
import "./styles.css";

const componentCssClassName = "ds application-layout";

/**
 * ApplicationLayout — the application shell.
 *
 * Divides the viewport between a leading navigation rail (named slot,
 * `min-content`) and the main content area (default slot, `1fr`), per the
 * ontology instance `apps.layout.application_layout`.
 */
const ApplicationLayout = ({
  className,
  children,
  navigation,
  ...props
}: ApplicationLayoutProps): React.ReactElement => {
  return (
    <div
      className={[componentCssClassName, className].filter(Boolean).join(" ")}
      {...props}
    >
      {navigation != null && <div className="navigation">{navigation}</div>}
      <div className="content">{children}</div>
    </div>
  );
};

export default ApplicationLayout;
