// Generated by @canonical/summon-component:react v0.1.0

import type { Meta, StoryObj } from "@storybook/react-vite";
import {
  LayoutSlot,
  layoutDecorators,
} from "../../storybook/layouts/story-utils.js";
import ApplicationLayout from "./ApplicationLayout.js";

const meta: Meta<typeof ApplicationLayout> = {
  title: "Layouts/ApplicationLayout",
  component: ApplicationLayout,
  parameters: { layout: "fullscreen" },
  decorators: layoutDecorators,
};

export default meta;
type Story = StoryObj<typeof ApplicationLayout>;

/** Navigation rail (min-content) + content area (1fr). */
export const Default: Story = {
  args: {
    navigation: (
      <LayoutSlot name="navigation" style={{ inlineSize: "16rem" }} />
    ),
    children: <LayoutSlot name="default" />,
  },
};

/** Without the navigation slot, the content takes the full width. */
export const WithoutNavigation: Story = {
  args: {
    children: <LayoutSlot name="default" />,
  },
};
