// AUTO-GENERATED by buildAssetManifest — do not edit by hand.
const assetManifest = {
  "brand-mark": "brand-mark.dd17fe85.svg",
  "service-status": "service-status.73e7af3a.svg",
} as const;

export default assetManifest;
