// Generated by @canonical/summon-component:react v0.1.0

import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import TermRail from "./TermRail.js";

describe("TermRail", () => {
  it("renders children", () => {
    render(<TermRail>Test content</TermRail>);
    expect(screen.getByText("Test content")).toBeInTheDocument();
  });

  it("applies custom className", () => {
    render(<TermRail className="custom-class">Content</TermRail>);
    const element = screen.getByText("Content");
    expect(element.className).toContain("ds term-rail");
    expect(element.className).toContain("custom-class");
  });

  it("passes through additional props", () => {
    render(<TermRail data-testid="test-component">Content</TermRail>);
    expect(screen.getByTestId("test-component")).toBeInTheDocument();
  });
});
