/**
 * Default component type for navigation items.
 * Framework-agnostic — consumers supply a concrete type
 * (e.g. React.ComponentType) via the generic parameter.
 */
export type DefaultComponent = unknown;

/**
 * Navigation item - Public API (WD405)
 *
 * A unified type for navigation items across the design system.
 * Used by Breadcrumbs, SiteNavigation, FileTree, MegaMenu, etc.
 *
 * @template C - Custom component type for rendering the item
 */
export interface Item<C = DefaultComponent> {
  /**
   * Unique identifier for the item when a URL is not provided.
   * e.g. 'section-header' for a non-navigable grouping item.
   */
  key?: string;

  /**
   * Navigation URL for the item, used for navigable links.
   * e.g. '/dashboard' for directing to the dashboard page.
   */
  url?: string;

  /**
   * Display text for the item in the navigation UI.
   * e.g. 'Dashboard' as the visible label.
   */
  label?: string;

  /**
   * Flag indicating whether the item is interactive or disabled.
   * e.g. true to prevent clicks on unavailable features.
   */
  disabled?: boolean;

  /**
   * CSS class name for custom styling of the item.
   * e.g. 'nav-item-active' to highlight the current page.
   */
  className?: string;

  /**
   * Array of child items for nested navigation structures.
   * e.g. Submenu items under a parent like 'Settings'.
   */
  items?: Item<C>[];

  /**
   * Enum value determining the type of display for items.
   * e.g. 'list' for rendering as a simple list.
   */
  displayItemsType?: "default" | "custom";

  /**
   * Custom component for rendering the item itself.
   * e.g. A specialized renderer for complex items.
   */
  Component?: C;
}

/**
 * Annotated navigation item - Private API (WD405)
 *
 * Internal type with parent reference and depth annotations.
 * Generated by annotateTree() helper.
 *
 * @template C - Custom component type for rendering the item
 */
export interface _Item<C = DefaultComponent> extends Item<C> {
  /**
   * URL (or key) of the parent item in the navigation hierarchy.
   * e.g. '/parent' for a child item under '/parent', or null for the root.
   */
  parentUrl: string | null;

  /**
   * Integer representing the nesting level in the tree.
   * e.g. 0 for top-level items, 1 for their children, 2 for grandchildren.
   */
  depth: number;

  /**
   * Array of annotated child items, if any.
   * e.g. Prepared sub-items with their own parentUrl and depth.
   */
  items?: _Item<C>[];
}

/**
 * Index for quick lookup of items by URL or key - Private API (WD405)
 *
 * A dictionary for O(1) lookup of prepared items.
 *
 * @template C - Custom component type for rendering the item
 */
export type _Index<C = DefaultComponent> = {
  [url: string]: _Item<C>;
};
