/**
 * Navigation item - Public API (WD405)
 *
 * A unified type for navigation items across the design system.
 * Used by Breadcrumbs, SiteNavigation, FileTree, MegaMenu, etc.
 *
 * Only fields consumed by the shared navigation utilities belong here.
 * Styling and rendering customization (CSS classes, custom renderers)
 * belong on the item types that components declare by extending this
 * one (e.g. BreadcrumbItem, MenuItem), using each framework's own idioms.
 */
export interface Item {
  /**
   * Unique identifier for the item when a URL is not provided.
   * e.g. 'section-header' for a non-navigable grouping item.
   */
  key?: string;

  /**
   * Navigation URL for the item, used for navigable links.
   * e.g. '/dashboard' for directing to the dashboard page.
   */
  url?: string;

  /**
   * Display text for the item in the navigation UI.
   * e.g. 'Dashboard' as the visible label.
   */
  label?: string;

  /**
   * Flag indicating whether the item is interactive or disabled.
   * e.g. true to prevent clicks on unavailable features.
   */
  disabled?: boolean;

  /**
   * Array of child items for nested navigation structures.
   * e.g. Submenu items under a parent like 'Settings'.
   */
  items?: Item[];
}

/**
 * Annotated navigation item - Private API (WD405)
 *
 * Internal type with parent reference and depth annotations.
 * Generated by annotateTree() helper.
 *
 * Generic over the **whole item type** `T` it annotates, so an enhanced item
 * (extra fields beyond the base WD405 `Item`, e.g. `icon`/`slot`) survives
 * annotation with its fields intact and fully typed.
 *
 * @template T - The item type being annotated (defaults to the base `Item`)
 */
export type _Item<T extends Item = Item> = Omit<T, "items"> & {
  /**
   * URL (or key) of the parent item in the navigation hierarchy.
   * e.g. '/parent' for a child item under '/parent', or null for the root.
   */
  parentUrl: string | null;

  /**
   * Integer representing the nesting level in the tree.
   * e.g. 0 for top-level items, 1 for their children, 2 for grandchildren.
   */
  depth: number;

  /**
   * Array of annotated child items, if any.
   * e.g. Prepared sub-items with their own parentUrl and depth.
   *
   * `T`'s own `items` is omitted before intersecting so this annotated form
   * (`_Item<T>[]`) is the one surfaced when iterating children — otherwise the
   * intersection would expose `T`'s base element type.
   */
  items?: _Item<T>[];
};

/**
 * Index for quick lookup of items by URL or key - Private API (WD405)
 *
 * A dictionary for O(1) lookup of prepared items.
 *
 * @template T - The item type being annotated (defaults to the base `Item`)
 */
export type _Index<T extends Item = Item> = {
  [url: string]: _Item<T>;
};
