/**
 * Navigation item - Public API (WD405)
 *
 * A unified type for navigation items across the design system.
 * Used by Breadcrumbs, SiteNavigation, FileTree, MegaMenu, etc.
 *
 * Only fields consumed by the shared navigation utilities belong here.
 * Styling and rendering customization (CSS classes, custom renderers)
 * belong on the item types that components declare by extending this
 * one (e.g. BreadcrumbItem, MenuItem), using each framework's own idioms.
 */
export interface Item {
  /**
   * Unique identifier for the item when a URL is not provided.
   * e.g. 'section-header' for a non-navigable grouping item.
   */
  key?: string;

  /**
   * Navigation URL for the item, used for navigable links.
   * e.g. '/dashboard' for directing to the dashboard page.
   */
  url?: string;

  /**
   * Display text for the item in the navigation UI.
   * e.g. 'Dashboard' as the visible label.
   */
  label?: string;

  /**
   * Flag indicating whether the item is interactive or disabled.
   * e.g. true to prevent clicks on unavailable features.
   */
  disabled?: boolean;

  /**
   * Array of child items for nested navigation structures.
   * e.g. Submenu items under a parent like 'Settings'.
   */
  items?: Item[];
}

/**
 * Annotated navigation item - Private API (WD405)
 *
 * Internal type with parent reference and depth annotations.
 * Generated by annotateTree() helper.
 *
 * Generic over the **whole item type** `T` it annotates, so an enhanced item
 * (extra fields beyond the base WD405 `Item`, e.g. `icon`/`slot`) survives
 * annotation with its fields intact and fully typed.
 *
 * Distributes over union item types: `_Item<A | B>` annotates each member
 * separately (`_Item<A> | _Item<B>`-shaped), so a discriminated union of entry
 * kinds (e.g. a menu item vs a separator) keeps its discriminant and
 * member-specific fields after annotation. A plain `Omit<A | B, "items">`
 * would collapse the union to its common keys. Children remain the **whole**
 * union: a tree of `A | B` entries has `_Item<A | B>[]` children on every
 * member, whichever member the parent is.
 *
 * Instantiate `_Item` with the tree's FULL entry union: `_Item<OneMember>`
 * re-types `items` with just that member, statically hiding the other entry
 * kinds a heterogeneous tree's children can hold at runtime.
 *
 * @template T - The item type being annotated (defaults to the base `Item`)
 */
export type _Item<T extends Item = Item> = _DistributiveOmit<T, "items"> & {
  /**
   * URL (or key) of the parent item in the navigation hierarchy.
   * e.g. '/parent' for a child item under '/parent', or null for the root.
   */
  parentUrl: string | null;

  /**
   * Integer representing the nesting level in the tree.
   * e.g. 0 for top-level items, 1 for their children, 2 for grandchildren.
   */
  depth: number;

  /**
   * Array of annotated child items, if any.
   * e.g. Prepared sub-items with their own parentUrl and depth.
   *
   * `T`'s own `items` is omitted before intersecting so this annotated form
   * (`_Item<T>[]`) is the one surfaced when iterating children — otherwise the
   * intersection would expose `T`'s base element type. `T` here is the whole
   * (possibly union) entry type, so children stay heterogeneous regardless of
   * which member the parent is.
   */
  items?: _Item<T>[];
};

/**
 * An `Omit` that distributes over union types: `_DistributiveOmit<A | B, K>`
 * is `Omit<A, K> | Omit<B, K>`, where the plain `Omit<A | B, K>` would first
 * collapse the union to its common keys. Intersecting the annotation fields
 * with the distributed union then distributes too, keeping `_Item<A | B>`
 * member-shaped. The conditional is only on the `Omit` half — the annotation
 * fields above stay a concrete object type, so generic code can access
 * `parentUrl`/`depth`/`items` without resolving the conditional.
 */
type _DistributiveOmit<T, K extends PropertyKey> = T extends unknown
  ? Omit<T, K>
  : never;

/**
 * Index for quick lookup of items by URL or key - Private API (WD405)
 *
 * A dictionary for O(1) lookup of prepared items.
 *
 * @template T - The item type being annotated (defaults to the base `Item`)
 */
export type _Index<T extends Item = Item> = {
  [url: string]: _Item<T>;
};
