// Generated by @canonical/summon-component:react v0.1.0

import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import ContentLayout from "./ContentLayout.js";

describe("ContentLayout", () => {
  it("renders children as direct grid items", () => {
    const { container } = render(
      <ContentLayout>
        <span>Card A</span>
        <span>Card B</span>
      </ContentLayout>,
    );
    const el = container.firstElementChild;
    expect(el?.children).toHaveLength(2);
    expect(screen.getByText("Card A")).toBeInTheDocument();
    expect(screen.getByText("Card B")).toBeInTheDocument();
  });

  it("applies the base and custom class to the root", () => {
    const { container } = render(
      <ContentLayout className="custom-class">Content</ContentLayout>,
    );
    const el = container.firstElementChild;
    expect(el?.className).toContain("ds content-layout");
    expect(el?.className).toContain("custom-class");
  });

  it("uses the fixed-responsive grid preset by default", () => {
    const { container } = render(<ContentLayout>Content</ContentLayout>);
    const el = container.firstElementChild;
    expect(el?.className).toContain("grid");
    expect(el?.className).toContain("responsive");
    expect(el?.className).not.toContain("intrinsic");
  });

  it("switches to the intrinsic grid preset via the grid prop", () => {
    const { container } = render(
      <ContentLayout grid="intrinsic">Content</ContentLayout>,
    );
    const el = container.firstElementChild;
    expect(el?.className).toContain("grid");
    expect(el?.className).toContain("intrinsic");
    expect(el?.className).not.toContain("responsive");
  });

  it("passes through additional props", () => {
    render(<ContentLayout data-testid="test-component">Content</ContentLayout>);
    expect(screen.getByTestId("test-component")).toBeInTheDocument();
  });
});
