// Generated by @canonical/summon-component:react v0.1.0

import { renderToString } from "react-dom/server";
import { describe, expect, it } from "vitest";
import ContentLayout from "./ContentLayout.js";

describe("ContentLayout SSR", () => {
  it("renders without hydration errors", () => {
    const html = renderToString(<ContentLayout>Test content</ContentLayout>);
    expect(html).toContain("Test content");
    expect(html).toContain("ds content-layout");
  });
});
