// Generated by @canonical/summon-component:react v0.1.0

import type { Meta, StoryObj } from "@storybook/react-vite";
import { layoutDecorators, mockCards } from "#storybook/layouts/story-utils.js";
import ContentLayout from "./ContentLayout.js";

const meta: Meta<typeof ContentLayout> = {
  title: "Layouts/ContentLayout",
  component: ContentLayout,
  tags: ["autodocs"],
  parameters: { layout: "fullscreen" },
  decorators: layoutDecorators,
};

export default meta;
type Story = StoryObj<typeof ContentLayout>;

/** Cards (example content in the default slot) on the intrinsic grid. */
export const Default: Story = {
  args: {
    children: mockCards(10),
  },
};

/** Many cards — resize the canvas to see the auto-fill columns reflow. */
export const Fluid: Story = {
  args: {
    children: mockCards(24),
  },
};
