// Generated by @canonical/summon-component:react v0.1.0

import type { Meta, StoryObj } from "@storybook/react-vite";
import { layoutDecorators, mockCards } from "#storybook/layouts/story-utils.js";
import ContentLayout from "./ContentLayout.js";

const meta: Meta<typeof ContentLayout> = {
  title: "Layouts/ContentLayout",
  component: ContentLayout,
  tags: ["autodocs"],
  parameters: { layout: "fullscreen" },
  decorators: layoutDecorators,
};

export default meta;
type Story = StoryObj<typeof ContentLayout>;

/** Fixed-responsive grid (the default). */
export const Default: Story = {
  args: {
    children: mockCards(10),
  },
  render: (args) => (
    <>
      <p>
        Fixed-responsive grid (default): breakpoint-driven columns — 4 below
        768px, 8 to 1279px, 12 from 1280px. Each card spans one column.
      </p>
      <ContentLayout {...args} />
    </>
  ),
};

/** Intrinsic grid — opt in via grid="intrinsic". */
export const Intrinsic: Story = {
  args: {
    grid: "intrinsic",
    children: mockCards(24),
  },
  render: (args) => (
    <>
      <p>
        Intrinsic grid: fluid auto-fill in groups of four minmax(--grid-col-min,
        1fr) columns — the column count follows the available width, not
        breakpoints. Resize the canvas to see the cards reflow.
      </p>
      <ContentLayout {...args} />
    </>
  ),
};
