// Generated by @canonical/summon-component:react v0.1.0

import type React from "react";
import type { ContentLayoutProps } from "./types.js";
import "./styles.css";

const componentCssClassName = "ds content-layout";

/**
 * ContentLayout — the responsive content grid of a view.
 *
 * Lays its children (default slot) on the design system's intrinsic grid
 * (fluid auto-fill in groups of four columns), per the ontology instance
 * `apps.layout.content_layout`. Children are grid items; span them via
 * `grid-column`/`grid-row` where a card needs more room.
 */
const ContentLayout = ({
  className,
  children,
  ...props
}: ContentLayoutProps): React.ReactElement => {
  return (
    <div
      className={[componentCssClassName, className].filter(Boolean).join(" ")}
      {...props}
    >
      {children}
    </div>
  );
};

export default ContentLayout;
