// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import { GridCard } from "./GridCard.js";

describe("GridCard", () => {
  // TODO(#662): the component accepts `children` but silently drops them.
  // Unskip once the children-vs-props API is settled.
  it.skip("renders children", () => {
    render(<GridCard>Test content</GridCard>);
    expect(screen.getByText("Test content")).toBeInTheDocument();
  });

  it("applies custom className", () => {
    render(<GridCard className="custom-class">Content</GridCard>);
    // The root element carries the classes; children may render in a descendant.
    const element = document.querySelector(".custom-class") as HTMLElement;
    expect(element).toHaveClass("grid-card");
    expect(element).toHaveClass("custom-class");
  });

  it("passes through additional props", () => {
    render(<GridCard data-testid="test-component">Content</GridCard>);
    expect(screen.getByTestId("test-component")).toBeInTheDocument();
  });
});
