/**
 * Generate the embedded fallback pack.
 *
 * Builds a pack from `src/kernel/runtime/graphpack/embedded/sample.ttl` into a
 * throwaway cache, then inlines the four artifact files as escaped JS strings
 * in `pack.generated.ts`. Inlining (rather than shipping file assets) is what
 * lets the embedded pack survive `bun build --compile` with no asset step.
 *
 * Run after editing `sample.ttl`: `bun run scripts/genEmbedded.ts`.
 */

import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { buildPack } from "../src/kernel/runtime/graphpack/build.js";
import {
  DATA_FILE,
  INDEX_FILE,
  MANIFEST_FILE,
  SCHEMA_FILE,
} from "../src/kernel/runtime/graphpack/types.js";

const here = fileURLToPath(new URL(".", import.meta.url));
const embeddedDir = join(here, "../src/kernel/runtime/graphpack/embedded");
const sourcePath = join(embeddedDir, "sample.ttl");
const outPath = join(embeddedDir, "pack.generated.ts");
// The index string lives in its OWN module so the storeless `__complete` path
// (entitySource) imports only it — never the n-quads/schema/manifest strings.
const indexOutPath = join(embeddedDir, "pack.index.generated.ts");

// Build into an isolated cache so we never touch the developer's real cache.
const cacheHome = mkdtempSync(join(tmpdir(), "pragma-genembedded-"));
process.env.XDG_CACHE_HOME = cacheHome;

const PREFIXES = {
  ex: "https://pragma.canonical.com/sample#",
  rdf: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
  rdfs: "http://www.w3.org/2000/01/rdf-schema#",
  owl: "http://www.w3.org/2002/07/owl#",
  xsd: "http://www.w3.org/2001/XMLSchema#",
};

try {
  const content = readFileSync(sourcePath, "utf-8");
  const { dir, contentHash } = await buildPack(
    [{ path: "sample.ttl", content }],
    {
      name: "pragma-sample",
      version: "0.31.0",
      sourceRef: "embedded:sample.ttl",
      prefixes: PREFIXES,
    },
  );

  const read = (file: string): string => readFileSync(join(dir, file), "utf-8");
  const dataNq = read(DATA_FILE);
  const schemaJson = read(SCHEMA_FILE);
  const indexJson = read(INDEX_FILE);
  const manifestJson = read(MANIFEST_FILE);

  const header = `// AUTO-GENERATED by scripts/genEmbedded.ts — do not edit by hand.
// Regenerate after changing sample.ttl: \`bun run scripts/genEmbedded.ts\`.
`;
  const module = `${header}export const dataNq = ${JSON.stringify(dataNq)};
export const schemaJson = ${JSON.stringify(schemaJson)};
export const manifestJson = ${JSON.stringify(manifestJson)};
`;
  writeFileSync(outPath, module);
  writeFileSync(
    indexOutPath,
    `${header}export const indexJson = ${JSON.stringify(indexJson)};\n`,
  );
  console.log(`Generated embedded pack ${contentHash} → ${outPath}`);
  console.log(`Generated embedded index → ${indexOutPath}`);
} finally {
  rmSync(cacheHome, { recursive: true, force: true });
}
