// Generated by @canonical/summon-component:react v0.1.0

import { describe, expect, it } from "vitest";
import { renderToString } from "react-dom/server";
import Content from "./Content.js";

describe("Content SSR", () => {
	it("renders without hydration errors", () => {
		const html = renderToString(<Content>Test content</Content>);
		expect(html).toContain("Test content");
		expect(html).toContain("ds content");
	});
});
