// Generated by @canonical/summon-component:react v0.1.0

import type { Meta, StoryObj } from "@storybook/react-vite";
import Content from "./Content.js";

const meta: Meta<typeof Content> = {
	title: "Components/SideNavigation/Content",
	component: Content,
	tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof Content>;

export const Default: Story = {
	args: {
		children: "Hello, Content!",
	},
};

export const WithCustomClass: Story = {
	args: {
		children: "Custom styled",
		className: "custom-class",
	},
};
