// Generated by @canonical/summon-component:react v0.1.0

import type React from "react";
import type { ContentProps } from "./types.js";
import "./styles.css";

const componentCssClassName = "ds content";

/**
 * Content component
 */
const Content = ({
	className,
	children,
	...props
}: ContentProps): React.ReactElement => {
	return (
		<div
			className={[componentCssClassName, className].filter(Boolean).join(" ")}
			{...props}
		>
			{children}
		</div>
	);
};

export default Content;
