// Generated by @canonical/summon-component:lit v0.1.0

import { html, LitElement } from "lit";
import { customElement, property } from "lit/decorators.js";
import styles from "./styles.css";
import type { NavigationProps, NavLink } from "./types.js";

const componentCssClassName = "ds navigation";

/**
 * Navigation web component.
 *
 * @implements ds:global.component.navigation
 */
@customElement("ds-navigation")
export default class Navigation extends LitElement implements NavigationProps {
  static styles = styles;

  @property({ type: String }) brand = "";
  @property({ type: Array }) links: NavLink[] = [];

  render() {
    return html`
      <nav class="${componentCssClassName}">
        <a href="/" class="banner">
          <div class="logo">
            <img src="https://assets.ubuntu.com/v1/29985a98-ubuntu-logo32.png" alt="" width="16" height="16">
          </div>
          <span class="text">${this.brand}</span>
        </a>
        <ul class="links">
          ${this.links.map(
            (link) => html`<li><a href="${link.href}">${link.label}</a></li>`,
          )}
        </ul>
      </nav>
    `;
  }
}
