// Generated by @canonical/summon-component:lit v0.1.0

import type { Meta, StoryObj } from "@storybook/web-components-vite";
import { html } from "lit";

import "./Navigation.js";
import type Navigation from "./Navigation.js";

const meta = {
  title: "Web Components/Navigation",
  tags: ["autodocs"],
  parameters: {
    layout: "fullscreen",
  },
} satisfies Meta<Navigation>;

export default meta;
type Story = StoryObj<Navigation>;

export const Default: Story = {
  render: () => html`
    <ds-navigation
      brand="Ubuntu Server"
      .links=${[{ label: "Hyperscale", href: "/server/hyperscale" }, { label: "Docs", href: "#" }]}
    ></ds-navigation>`,
};
