// Generated by @canonical/summon-component:react v0.1.0

import { renderToString } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { PasswordInput } from "./PasswordInput.js";

// Proves the presentational input renders to static HTML with no client runtime
// / form context — masked (type=password) on the server floor.
describe("PasswordInput SSR", () => {
  it("renders a masked input to static HTML without a form context", () => {
    const html = renderToString(<PasswordInput name="secret" />);
    expect(html).toContain("<input");
    expect(html).toContain('type="password"');
    expect(html).toContain("ds input password chrome");
  });

  it("renders the reveal toggle in the suffix position by default", () => {
    const html = renderToString(<PasswordInput name="secret" />);
    expect(html).toContain("reveal-toggle");
    expect(html).toContain('data-state="masked"');
  });
});
