// Generated by @canonical/summon-component:react v0.1.0

import { forwardRef, type ReactElement, useId, useState } from "react";
import type { PasswordInputProps } from "./types.js";
import "./styles.css";

const componentCssClassName = "ds input password chrome";

/**
 * Presentational password input — pure markup, no react-hook-form. The entered
 * value is masked by default; a dedicated reveal/mask toggle (eye) sits in the
 * suffix position. There is no prefix. A distinct component from Text rather
 * than a `type="password"` content-type, because the reveal control is a named,
 * semantic part of the anatomy.
 *
 * Usable standalone (controlled via `value`/`onChange`, or uncontrolled) or via
 * the field tier, which spreads react-hook-form's `register()` result onto it.
 * @returns {ReactElement} - Rendered PasswordInput
 */
export const PasswordInput = forwardRef<HTMLInputElement, PasswordInputProps>(
  function PasswordInput(
    {
      id,
      className,
      style,
      revealable = true,
      revealLabel = "Show password",
      maskLabel = "Hide password",
      ...nativeProps
    },
    ref,
  ): ReactElement {
    const [revealed, setRevealed] = useState(false);
    const inputId = useId();
    const resolvedId = id ?? inputId;

    return (
      <div
        style={style}
        className={[componentCssClassName, className].filter(Boolean).join(" ")}
      >
        <input
          id={resolvedId}
          className="p"
          type={revealed ? "text" : "password"}
          ref={ref}
          {...nativeProps}
        />
        {revealable && (
          <button
            type="button"
            className="suffix reveal-toggle"
            aria-label={revealed ? maskLabel : revealLabel}
            aria-controls={resolvedId}
            aria-pressed={revealed}
            onClick={() => setRevealed((r) => !r)}
          >
            <span
              className="reveal-icon"
              data-state={revealed ? "revealed" : "masked"}
            />
          </button>
        )}
      </div>
    );
  },
);

export default PasswordInput;
