// Generated by @canonical/summon-component:react v0.1.0

import type { Meta, StoryObj } from "@storybook/react-vite";
import { PasswordInput } from "./PasswordInput.js";

const meta: Meta<typeof PasswordInput> = {
  title: "subcomponents/PasswordInput",
  component: PasswordInput,
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof PasswordInput>;

export const Default: Story = {
  args: { name: "password", defaultValue: "hunter2" },
};

export const NotRevealable: Story = {
  args: { name: "password", defaultValue: "hunter2", revealable: false },
};

export const Disabled: Story = {
  args: { name: "password", defaultValue: "hunter2", disabled: true },
};
