// Generated by @canonical/summon-component:react v0.1.0

import type React from "react";

type NativePasswordProps = Omit<
  React.InputHTMLAttributes<HTMLInputElement>,
  "type" | "prefix"
>;

type AdditionalPasswordProps = {
  /** Whether the reveal/mask (eye) toggle is offered. Defaults to `true`. */
  revealable?: boolean;

  /** Accessible label for the toggle while the value is masked. */
  revealLabel?: string;

  /** Accessible label for the toggle while the value is revealed. */
  maskLabel?: string;
};

/** Props for the presentational Password input (no react-hook-form). */
export type PasswordInputProps = NativePasswordProps & AdditionalPasswordProps;
