/**
 * The verbatim guarantee, pinned through the REFERENCE producer: a generator
 * that templates one file and carries another lands the templated file
 * STAMPED and the carried file byte-identical to its source content —
 * exactly the split `copy()` used to provide, now through the one WriteFile
 * shape a compiled binary can perform.
 */

import { sequence_ } from "@canonical/task";
import { describe, expect, it } from "vitest";
import { produceReference } from "../../testing/conformance/produceReference.js";
import type GeneratorDefinition from "../../types/GeneratorDefinition.js";
import template from "../tasks/template.js";
import rawFile from "./rawFile.js";

const CARRIED = "// relay artifact — must land byte-identical\nconst x = 1;\n";

const generator: GeneratorDefinition = {
  meta: {
    name: "fixture/raw",
    displayName: "fixture-raw",
    description: "A raw-file fixture",
    version: "0.0.1",
  },
  prompts: [{ name: "title", type: "text", message: "Title:", default: "T" }],
  generate: (answers) =>
    sequence_([
      template({
        source: "/fixture/templates/readme.md.ejs",
        content: "# <%= title %>\n",
        dest: "out/readme.ts",
        vars: answers,
      }),
      rawFile({
        source: "/fixture/templates/artifact.ts",
        content: CARRIED,
        dest: "out/artifact.ts",
      }),
    ]),
};

describe("rawFile through the conformance reference (PROTECTED)", () => {
  it("templated output is stamped; carried output is verbatim", async () => {
    const snapshot = await produceReference({
      generator,
      answers: { title: "Hello" },
    });
    expect([...snapshot.keys()]).toEqual(["out/artifact.ts", "out/readme.ts"]);
    const templated = snapshot.get("out/readme.ts") ?? "";
    const carried = snapshot.get("out/artifact.ts") ?? "";
    // The templated .ts file carries the generated-by stamp…
    expect(templated).toContain("Generated by fixture-raw");
    expect(templated).toContain("# Hello");
    // …the carried file is BYTE-IDENTICAL to its loaded content: no stamp.
    expect(carried).toBe(CARRIED);
  }, 60_000);
});
