import { dryRun } from "@canonical/task";
import { describe, expect, it } from "vitest";
import createGeneratorStamp from "../../stamp/createGeneratorStamp.js";
import createStampOnEffectStart from "../../stamp/createStampOnEffectStart.js";
import rawFile from "./rawFile.js";

describe("rawFile", () => {
  it("is a verbatim WriteFile of the carried content", () => {
    const task = rawFile({
      source: "/pkg/templates/src/app.css",
      content: ".x{}",
      dest: "my-app/src/app.css",
    });
    const { effects } = dryRun(task);
    expect(effects).toHaveLength(1);
    const effect = effects[0] as {
      _tag: string;
      path: string;
      content: string;
      verbatim?: boolean;
      undo?: unknown;
    };
    expect(effect._tag).toBe("WriteFile");
    expect(effect.path).toBe("my-app/src/app.css");
    expect(effect.content).toBe(".x{}");
    expect(effect.verbatim).toBe(true);
    // Reversible like any write: the default delete-undo is attached.
    expect(effect.undo).toBeDefined();
  });

  it("the stamping transform SKIPS it — carried bytes land unchanged", () => {
    const stamp = createGeneratorStamp({
      meta: { name: "g", displayName: "g", description: "g", version: "1" },
      prompts: [],
      generate: () => rawFile({ source: "s", content: "", dest: "d" }),
    });
    const onEffectStart = createStampOnEffectStart(stamp);

    // A verbatim write is untouched…
    const { effects } = dryRun(
      rawFile({ source: "/t/x.ts", content: "const x = 1;\n", dest: "x.ts" }),
    );
    const verbatimEffect = effects[0] as { content: string };
    onEffectStart(effects[0] as never);
    expect(verbatimEffect.content).toBe("const x = 1;\n");

    // …while a plain WriteFile of the same content IS stamped.
    const plain = {
      _tag: "WriteFile",
      path: "x.ts",
      content: "const x = 1;\n",
    };
    onEffectStart(plain as never);
    expect(plain.content).toContain("Generated by");
  });
});
