// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import type { Meta } from "@storybook/react-vite";
import { CategoriesSection } from "#lib/_work_in_progress/CategoriesSection/index.js";
import { ChatSection } from "#lib/_work_in_progress/ChatSection/index.js";
import { DescriptionSection } from "#lib/_work_in_progress/DescriptionSection/index.js";
import { IconSection } from "#lib/_work_in_progress/IconSection/index.js";

const meta: Meta = {
  title: "_work_in_progress/other/GridTrial",
  parameters: {
    layout: "fullscreen",
    grid: "responsive",
  },
};

export default meta;
// type Story = StoryObj<typeof DescriptionSection>;

export const Default = () => {
  // some logic
  return (
    <>
      <ChatSection title="What can we help you with ?" />
      <DescriptionSection title="Fast track">
        <p>
          Sed ut perspiciatis unde omnis iste natus error sit voluptatem
          accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae
          ab illo inventore veritatis et quasi architecto beatae vitae dicta
          sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit
          aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos
          qui ratione voluptatem sequi nesciunt.
        </p>
      </DescriptionSection>
      <CategoriesSection>Hello, CategoriesSection!</CategoriesSection>
      <IconSection title="Icons" />
      <div style={{ minHeight: "200px" }}>#</div>
    </>
  );
};
