// Generated by component/lit v0.1.0
// Generated by @canonical/summon:component-lit v0.1.0

import { afterEach, beforeEach, describe, expect, it } from "vitest";
import "./TieredList.js";
import type TieredList from "./TieredList.js";

describe("TieredList component", () => {
  let elem: TieredList;

  beforeEach(() => {
    elem = document.createElement("ds-tiered-list") as TieredList;
    document.body.appendChild(elem);
  });

  afterEach(() => {
    elem.remove();
  });

  it("should render component", async () => {
    await customElements.whenDefined("ds-tiered-list");

    const container = elem.shadowRoot?.querySelector(".ds.tiered-list");
    expect(container).toBeTruthy();
  });

  it("should have correct tag name", () => {
    expect(elem.tagName.toLowerCase()).toBe("ds-tiered-list");
  });
});
