// Generated by component/lit v0.1.0
// Generated by @canonical/summon:component-lit v0.1.0

import { html, LitElement } from "lit";
import { customElement, property, state } from "lit/decorators.js";
import { classMap } from "lit/directives/class-map.js";
import styles from "./styles.css";
import type { TieredListProps } from "./types.js";

const componentCssClassName = "ds tiered-list";

/**
 * TieredList web component.
 *
 * @implements ds:global.component.tiered-list
 */
@customElement("ds-tiered-list")
export default class TieredList extends LitElement implements TieredListProps {
  static styles = styles;

  @property({ type: String }) title = "";
  @property({ type: Boolean }) isDescriptionFullWidthOnDesktop = false;
  @property({ type: Boolean }) isListFullWidthOnTablet = false;
  @property({ type: String })
  padding: "deep" | "shallow" | "default" = "default";

  @state() private _hasCTA = false;

  private _onCtaSlotChanged(e: Event) {
    const slot = e.target as HTMLSlotElement;
    this._hasCTA = slot.assignedElements().length > 0;
  }

  render() {
    const sectionClasses = {
      [componentCssClassName]: true,
      "full-width-description-on-desktop": this.isDescriptionFullWidthOnDesktop,
      "full-width-list-on-tablet": this.isListFullWidthOnTablet,
      [`is-${this.padding}`]: this.padding !== "default",
    };

    return html`
      <section class=${classMap(sectionClasses)}>
        <hr />
        <div class="header">
          <div class="title">
            <h2>${this.title}</h2>
          </div>
          <div class="description">
            <slot name="description"></slot>
          </div>
        </div>
        <div class="body">
          <slot name="items"></slot>
        </div>
        <hr ?hidden=${!this._hasCTA} />
        <div class="cta" ?hidden=${!this._hasCTA}>
          <div class="p-cta-block">
            <slot name="cta" @slotchange=${this._onCtaSlotChanged}></slot>
          </div>
        </div>
      </section>
    `;
  }
}
