// Generated by component/lit v0.1.0
// Generated by @canonical/summon:component-lit v0.1.0

/**
 * Props for the TieredList component.
 */
export interface TieredListProps {
  /** Heading text for the section. */
  title: string;
  /** Whether the description element should be full-width on desktop */
  isDescriptionFullWidthOnDesktop?: boolean;
  /** Whether the list element should be full-width on tablet */
  isListFullWidthOnTablet?: boolean;
  /** Padding variant for the section */
  padding?: "deep" | "shallow" | "default";
}
