name: Setup environment
description: Installs build tools and dependencies
inputs:
  bun-version:
    default: '1.3.9'
    description: Version of Bun to use
  node-version:
    # Node is required for Storybook and Lerna (Bun is used as package manager only)
    # Storybook 10 supports Node 20.16+, 22.19+, or 24+
    default: '24'
    description: Version of Node to use
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}

      # "prepare" hook on `bun install` runs `bun run build`
      # - name: Install dependencies
      #   shell: bash
      #   run: bun install --frozen-lockfile
      # NOTE: --frozen-lockfile disabled for now due to a known Bun bug where bun install
      # always writes the lockfile internally, causing false positives with --frozen-lockfile
      # even when bun.lock content is unchanged. Tracked in:
      # https://github.com/oven-sh/bun/issues/16692
      # https://github.com/oven-sh/bun/issues/19088
    - name: Install dependencies
      shell: bash
      run: bun install && git diff --exit-code bun.lock

      # Workaround for https://github.com/oven-sh/bun/issues/19782
      # Workspace bin symlinks aren't created on first install. Remove after fix is merged.
    - name: Re-link workspace binaries
      shell: bash
      run: bun install
