// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import type { ViewLayoutProps } from "./types";
import "./styles.css";

/**
 * ViewLayout component
 */
export const ViewLayout = ({
	className,
	children,
	...props
}: ViewLayoutProps): JSX.Element => {
	return (
		<div
			className={`view-layout${className ? ` ${className}` : ""}`}
			{...props}
		>
			{children}
		</div>
	);
};
