// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import { renderToString } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { ViewLayout } from "./ViewLayout.js";

describe("ViewLayout SSR", () => {
  it("renders without hydration errors", () => {
    const html = renderToString(<ViewLayout>Test content</ViewLayout>);
    expect(html).toContain("Test content");
    expect(html).toContain("view-layout");
  });
});
