// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import type { Meta, StoryObj } from "@storybook/react";
import { ViewLayout } from "./ViewLayout.js";

const meta: Meta<typeof ViewLayout> = {
	title: "Components/ViewLayout",
	component: ViewLayout,
	tags: ["autodocs"],
	parameters: {
		layout: "fullscreen",
	},
};

export default meta;
type Story = StoryObj<typeof ViewLayout>;

export const Default: Story = {
	args: {
		children: "Hello, ViewLayout!",
	},
};

export const WithCustomClass: Story = {
	args: {
		children: "Custom styled",
		className: "custom-class",
	},
};
