/**
 * PROTECTED — the permanent seam contract: every `create` tree is produced TWO
 * ways and diffed byte-for-byte (path set + contents, incl. the "Generated by"
 * stamp): (1) `pragma create <verb> --yes` through the kernel dispatcher, and
 * (2) summon-core `execute` with `autoPrompt`, run through `runGeneratorTask` +
 * the shared stamp. They match because both derive the StampConfig from
 * `createGeneratorStamp` (displayName + version) and run the SAME
 * `generator.generate` with the SAME answers.
 *
 * Two suites live here, and they answer different questions.
 *
 * The GOLDENS below cover the five generators this distribution actually binds
 * — component × {react, svelte, lit}, package, application — over the real
 * `create` verbs. They are about THIS product's output.
 *
 * The CONFORMANCE case at the end drives the fixture generator
 * `@canonical/summon-core/testing` ships, with the answers and the expected
 * path set that module declares. `packages/cli/summon` runs the same fixture
 * through its own composition, so the two bins are measured against ONE thing
 * neither of them owns. Read that module's docblock for what "both bins" can
 * and cannot mean here: neither bin can dispatch the other's generators, so
 * the claim is about the two execution seams, not the two CLI entry points.
 *
 * A cross-binary subprocess guard lives in byteEquality.subprocess.test.ts.
 */

import { mkdtempSync, readdirSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  assertByteEqual,
  CONFORMANCE_ANSWERS,
  CONFORMANCE_TREE,
  conformanceGenerator,
  snapshotTree,
} from "@canonical/summon-core/testing";
import { describe, expect, it } from "vitest";
import { executeVerb } from "../../kernel/project/cli/dispatch.js";
import { bootRuntime } from "../../kernel/runtime/boot.js";
import type { GlobalFlags } from "../../kernel/runtime/types.js";
import type { VerbSpec } from "../../kernel/spec/types.js";
import { createVerbs } from "./create.verb.js";
import type { CreateKind } from "./types.js";

const FLAGS: GlobalFlags = {
  llm: false,
  autoLlm: false,
  format: "plain",
  verbose: false,
};
const freshCwd = (): string => mkdtempSync(join(tmpdir(), "pragma-golden-"));

/** Read a directory tree into a sorted map of relative path → contents. */
function snapshot(dir: string): Map<string, string> {
  const out = new Map<string, string>();
  const walk = (d: string, base: string): void => {
    for (const entry of readdirSync(d, { withFileTypes: true }).sort((a, b) =>
      a.name.localeCompare(b.name),
    )) {
      const rel = base ? `${base}/${entry.name}` : entry.name;
      if (entry.isDirectory()) walk(join(d, entry.name), rel);
      else out.set(rel, readFileSync(join(d, entry.name), "utf-8"));
    }
  };
  walk(dir, "");
  return out;
}

/** Producer (1): the full pragma kernel path — dispatcher runs the create verb. */
async function producePragma(
  kind: CreateKind,
  params: Record<string, unknown>,
): Promise<Map<string, string>> {
  const dir = freshCwd();
  const prev = process.cwd();
  process.chdir(dir);
  try {
    const outcome = await executeVerb(
      createVerbs[kind] as VerbSpec,
      params,
      { dryRun: false, undo: false, yes: true },
      bootRuntime(FLAGS, dir),
    );
    expect(outcome.exitCode).toBe(0);
  } finally {
    process.chdir(prev);
  }
  return snapshot(dir);
}

/** Producer (2): summon-core execute + autoPrompt + the shared stamp core. */
async function produceSummon(
  kind: CreateKind,
  framework: string,
  answers: Record<string, unknown>,
): Promise<Map<string, string>> {
  const { pickGenerator } = await import("./pickGenerator.js");
  const {
    execute,
    autoPrompt,
    runGeneratorTask,
    createGeneratorStamp,
    createStampOnEffectStart,
  } = await import("@canonical/summon-core");
  const generator = pickGenerator(kind, { framework });
  const dir = freshCwd();
  await runGeneratorTask(
    execute(generator, { prompt: autoPrompt(answers), params: answers }),
    {
      cwd: dir,
      promptHandler: autoPrompt(answers),
      onEffectStart: createStampOnEffectStart(createGeneratorStamp(generator)),
      onLog: () => {},
    },
  );
  return snapshot(dir);
}

/** One golden case: the create-verb params, and the equivalent summon answers. */
interface Case {
  readonly name: string;
  readonly kind: CreateKind;
  readonly framework: string;
  readonly params: Record<string, unknown>;
  readonly answers: Record<string, unknown>;
}

const componentAnswers = {
  withStyles: true,
  withStories: true,
  withSsrTests: false,
};

const cases: Case[] = [
  {
    name: "component/react",
    kind: "component",
    framework: "react",
    params: {
      framework: "react",
      componentPath: "src/components/Button",
      ...componentAnswers,
    },
    answers: { componentPath: "src/components/Button", ...componentAnswers },
  },
  {
    name: "component/svelte",
    kind: "component",
    framework: "svelte",
    params: {
      framework: "svelte",
      componentPath: "src/lib/Button",
      ...componentAnswers,
    },
    answers: { componentPath: "src/lib/Button", ...componentAnswers },
  },
  {
    name: "component/lit",
    kind: "component",
    framework: "lit",
    params: {
      framework: "lit",
      componentPath: "src/lib/Button",
      ...componentAnswers,
    },
    answers: { componentPath: "src/lib/Button", ...componentAnswers },
  },
  {
    name: "package",
    kind: "package",
    framework: "",
    params: {
      name: "@canonical/my-lib",
      type: "library",
      description: "A library.",
      withReact: false,
      withStorybook: false,
      withCli: false,
      withPrTemplate: false,
      runInstall: false,
    },
    answers: {
      name: "@canonical/my-lib",
      type: "library",
      description: "A library.",
      withReact: false,
      withStorybook: false,
      withCli: false,
      withPrTemplate: false,
      runInstall: false,
    },
  },
  {
    name: "application",
    kind: "application",
    framework: "",
    // The pragma path receives the CLI `--with-X` params (AV-228 B8); the summon
    // path receives the generator's bare prompt names. runCreate's boundary remap
    // (`withSsr` -> `ssr`, ...) makes both produce the byte-identical tree.
    params: {
      appPath: "my-app",
      withSsr: true,
      withRouter: true,
      withForms: true,
      withRelay: false,
      runInstall: false,
    },
    answers: {
      appPath: "my-app",
      ssr: true,
      router: true,
      forms: true,
      relay: false,
      runInstall: false,
    },
  },
];

describe("byte-equality goldens — pragma create ≡ summon execute (PROTECTED)", () => {
  for (const testCase of cases) {
    it(`${testCase.name}: both producers write byte-identical trees`, async () => {
      const pragma = await producePragma(testCase.kind, testCase.params);
      const summon = await produceSummon(
        testCase.kind,
        testCase.framework,
        testCase.answers,
      );
      expect(pragma.size).toBeGreaterThan(0);
      expect([...pragma.keys()].sort()).toEqual([...summon.keys()].sort());
      for (const [path, content] of pragma) {
        expect(summon.get(path), `content of ${path}`).toBe(content);
      }
    });
  }
});

describe("byte-equality conformance — the shared fixture (PROTECTED)", () => {
  it("produces the summon-core conformance tree through the kernel's execute seam", async () => {
    // The same kit `packages/cli/summon/src/conformance.test.ts` runs, against
    // the same written-down tree. Neither bin can pass by measuring itself
    // against its own idea of what the generator should emit: the paths, the
    // bytes and the stamp identity all come from the core.
    const {
      execute,
      autoPrompt,
      runGeneratorTask,
      createGeneratorStamp,
      createStampOnEffectStart,
    } = await import("@canonical/summon-core");
    const answers = { ...CONFORMANCE_ANSWERS };
    const dir = freshCwd();
    await runGeneratorTask(
      execute(conformanceGenerator, {
        prompt: autoPrompt(answers),
        params: answers,
      }),
      {
        cwd: dir,
        promptHandler: autoPrompt(answers),
        onEffectStart: createStampOnEffectStart(
          createGeneratorStamp(conformanceGenerator),
        ),
        onLog: () => {},
      },
    );
    const produced = snapshotTree(dir);
    expect(() => assertByteEqual(produced, CONFORMANCE_TREE)).not.toThrow();
  });
});
