/**
 * PROTECTED — the permanent seam contract: every `create` tree is produced TWO
 * ways and diffed byte-for-byte (path set + contents, incl. the "Generated by"
 * stamp): (1) `pragma create <verb> --yes` through the kernel dispatcher, and
 * (2) summon-core `execute` with `autoPrompt`, run through `runGeneratorTask` +
 * the shared stamp. They match because both derive the StampConfig from
 * `createGeneratorStamp` (displayName + version) and run the SAME
 * `generator.generate` with the SAME answers.
 *
 * Two suites live here, and they answer different questions.
 *
 * The GOLDENS below cover the five generators this distribution actually binds
 * — component × {react, svelte, lit}, package, application — over the real
 * `create` verbs. They are about THIS product's output.
 *
 * The CONFORMANCE cases at the end drive the fixture generator
 * `@canonical/summon-core/testing` ships, with the answers and the expected
 * path set that module declares, through PRAGMA's seam — `executeVerb` over a
 * locally-built `VerbSpec` that reproduces `runCreate`'s wiring, so the bytes
 * come out of the kernel's own dispatch and effect seam. `packages/cli/summon`
 * runs the same fixture through ITS composition, so the two bins are measured
 * against ONE thing neither of them owns. Read that module's docblock for what
 * "both bins" can and cannot mean here: neither bin can dispatch the other's
 * generators, so the claim is about the two execution seams, not the two CLI
 * entry points.
 *
 * A cross-binary subprocess guard lives in byteEquality.subprocess.test.ts.
 */

import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  assertByteEqual,
  CONFORMANCE_ANSWERS,
  CONFORMANCE_TREE,
  conformanceGenerator,
  snapshotTree,
} from "@canonical/summon-core/testing";
import { describe, expect, it } from "vitest";
import { executeVerb } from "../../kernel/project/cli/dispatch.js";
import { bootRuntime } from "../../kernel/runtime/boot.js";
import type { GlobalFlags } from "../../kernel/runtime/types.js";
import type { VerbSpec } from "../../kernel/spec/types.js";
import { createFormatters } from "./create.render.js";
import { createVerbs } from "./create.verb.js";
import type { CreateKind } from "./types.js";

const FLAGS: GlobalFlags = {
  llm: false,
  autoLlm: false,
  format: "plain",
  verbose: false,
};
const freshCwd = (): string => mkdtempSync(join(tmpdir(), "pragma-golden-"));

/** Producer (1): the full pragma kernel path — dispatcher runs the create verb. */
async function producePragma(
  kind: CreateKind,
  params: Record<string, unknown>,
): Promise<Map<string, string>> {
  const dir = freshCwd();
  const prev = process.cwd();
  process.chdir(dir);
  try {
    const outcome = await executeVerb(
      createVerbs[kind] as VerbSpec,
      params,
      { dryRun: false, undo: false, yes: true },
      bootRuntime(FLAGS, dir),
    );
    expect(outcome.exitCode).toBe(0);
  } finally {
    process.chdir(prev);
  }
  return snapshotTree(dir);
}

/** Producer (2): summon-core execute + autoPrompt + the shared stamp core. */
async function produceSummon(
  kind: CreateKind,
  framework: string,
  answers: Record<string, unknown>,
): Promise<Map<string, string>> {
  const { pickGenerator } = await import("./pickGenerator.js");
  const {
    execute,
    autoPrompt,
    runGeneratorTask,
    createGeneratorStamp,
    createStampOnEffectStart,
  } = await import("@canonical/summon-core");
  const generator = pickGenerator(kind, { framework });
  const dir = freshCwd();
  await runGeneratorTask(
    execute(generator, { prompt: autoPrompt(answers), params: answers }),
    {
      cwd: dir,
      promptHandler: autoPrompt(answers),
      onEffectStart: createStampOnEffectStart(createGeneratorStamp(generator)),
      onLog: () => {},
    },
  );
  return snapshotTree(dir);
}

/** One golden case: the create-verb params, and the equivalent summon answers. */
interface Case {
  readonly name: string;
  readonly kind: CreateKind;
  readonly framework: string;
  readonly params: Record<string, unknown>;
  readonly answers: Record<string, unknown>;
}

const componentAnswers = {
  withStyles: true,
  withStories: true,
  withSsrTests: false,
};

const cases: Case[] = [
  {
    name: "component/react",
    kind: "component",
    framework: "react",
    params: {
      framework: "react",
      componentPath: "src/components/Button",
      ...componentAnswers,
    },
    answers: { componentPath: "src/components/Button", ...componentAnswers },
  },
  {
    name: "component/svelte",
    kind: "component",
    framework: "svelte",
    params: {
      framework: "svelte",
      componentPath: "src/lib/Button",
      ...componentAnswers,
    },
    answers: { componentPath: "src/lib/Button", ...componentAnswers },
  },
  {
    name: "component/lit",
    kind: "component",
    framework: "lit",
    params: {
      framework: "lit",
      componentPath: "src/lib/Button",
      ...componentAnswers,
    },
    answers: { componentPath: "src/lib/Button", ...componentAnswers },
  },
  {
    name: "package",
    kind: "package",
    framework: "",
    params: {
      name: "@canonical/my-lib",
      type: "library",
      description: "A library.",
      withReact: false,
      withStorybook: false,
      withCli: false,
      withPrTemplate: false,
      runInstall: false,
    },
    answers: {
      name: "@canonical/my-lib",
      type: "library",
      description: "A library.",
      withReact: false,
      withStorybook: false,
      withCli: false,
      withPrTemplate: false,
      runInstall: false,
    },
  },
  {
    name: "application",
    kind: "application",
    framework: "",
    // The pragma path receives the CLI `--with-X` params (AV-228 B8); the summon
    // path receives the generator's bare prompt names. runCreate's boundary remap
    // (`withSsr` -> `ssr`, ...) makes both produce the byte-identical tree.
    params: {
      appPath: "my-app",
      withSsr: true,
      withRouter: true,
      withForms: true,
      withRelay: false,
      runInstall: false,
    },
    answers: {
      appPath: "my-app",
      ssr: true,
      router: true,
      forms: true,
      relay: false,
      runInstall: false,
    },
  },
];

describe("byte-equality goldens — pragma create ≡ summon execute (PROTECTED)", () => {
  for (const testCase of cases) {
    it(`${testCase.name}: both producers write byte-identical trees`, async () => {
      const pragma = await producePragma(testCase.kind, testCase.params);
      const summon = await produceSummon(
        testCase.kind,
        testCase.framework,
        testCase.answers,
      );
      expect(pragma.size).toBeGreaterThan(0);
      expect([...pragma.keys()].sort()).toEqual([...summon.keys()].sort());
      for (const [path, content] of pragma) {
        expect(summon.get(path), `content of ${path}`).toBe(content);
      }
    });
  }
});

/**
 * Producer (3): the shared fixture through PRAGMA's execution seam.
 *
 * pragma's `create` is bound to three declared generator packages and refuses
 * anything else, so the kernel cannot DISPATCH the core's fixture generator —
 * there is no `create conformance` noun and there must not be one. What the
 * kernel can do, and what this does, is run the fixture over the same seam a
 * real `create` runs on: a `VerbSpec` whose `run` reproduces `runCreate`'s
 * non-interactive wiring, driven by `executeVerb`. The tree below is therefore
 * written by pragma's mutation dispatch, its {@link runEffectSeam} composition
 * and its Task interpretation — NOT by summon-core's own runner, which is what
 * this case used to call and what made it a third copy of the core's own test.
 *
 * The reproduction's one load-bearing detail is the stamp's SLOT.
 * `create.verb.ts` puts it on `shapeEffect`, never `onEffectStart`: the stamp
 * is what the written bytes ARE, so a `--dry-run` must apply it, while the
 * wizard's progress render must not run on a plan. Conflating the two was a
 * real bug once. Reproducing it here on `onEffectStart` would have this case
 * measuring a composition pragma does not have, so it reproduces the slot the
 * verb actually uses.
 *
 * @returns The tree pragma's seam wrote, keyed by relative path.
 * @note Impure — writes a fresh temp tree and reads it back.
 */
async function producePragmaConformance(): Promise<Map<string, string>> {
  const {
    execute,
    autoPrompt,
    createGeneratorStamp,
    createStampOnEffectStart,
  } = await import("@canonical/summon-core");
  const answers = { ...CONFORMANCE_ANSWERS };
  const stamp = createGeneratorStamp(conformanceGenerator);
  const dir = freshCwd();
  const conformanceVerb: VerbSpec = {
    path: ["conformance"],
    summary: "Run the shared conformance fixture through pragma's create seam.",
    params: [],
    output: { formatters: createFormatters },
    capability: {
      needsStore: false,
      mutates: true,
      destructive: false,
      interactive: true,
      mcp: { expose: false, reason: "a test fixture, never a shipped verb" },
    },
    run: (_params, rt) => {
      const prompt = autoPrompt(answers);
      rt.exec = {
        cwd: rt.cwd,
        promptHandler: prompt,
        shapeEffect: createStampOnEffectStart(stamp),
        onLog: () => {},
      };
      return execute(conformanceGenerator, {
        prompt,
        params: answers,
      }) as never;
    },
  };
  const outcome = await executeVerb(
    conformanceVerb,
    {},
    { dryRun: false, undo: false, yes: true },
    bootRuntime(FLAGS, dir),
  );
  expect(outcome.exitCode).toBe(0);
  return snapshotTree(dir);
}

describe("byte-equality conformance — the shared fixture (PROTECTED)", () => {
  it("produces the summon-core conformance tree through pragma's own seam", async () => {
    // The same kit `packages/cli/summon/src/conformance.test.ts` runs, against
    // the same written-down tree. Neither bin can pass by measuring itself
    // against its own idea of what the generator should emit: the paths, the
    // bytes and the stamp identity all come from the core.
    const produced = await producePragmaConformance();
    expect(() => assertByteEqual(produced, CONFORMANCE_TREE)).not.toThrow();
  });

  it("carries the stamp through `shapeEffect`, the slot `create` wires", async () => {
    // Named rather than only diffed, because it is the ONE part of the seam
    // pragma derives for itself. `runEffectSeam` composes `shapeEffect` before
    // the UI half, so a kernel that stopped reading `shapeEffect` writes the
    // same paths with unstamped bytes — a difference the path set cannot see.
    const produced = await producePragmaConformance();
    expect(produced.get("src/widget-factory/index.ts")?.split("\n").at(0)).toBe(
      "// Generated by @canonical/summon-core:conformance v1.0.0",
    );
  });
});
