/**
 * `create` behaviour: real generation + stamp, the SEC-2 path jail, the
 * lazy-React discipline, and the pins on the BUILD-DERIVED create surface.
 * The MCP plan-first/confirm parity lives in create.mcp.test.ts; the
 * byte-equality goldens in byteEquality.test.ts; the fork proof in
 * forkGenerator.subprocess.test.ts.
 */

import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  symlinkSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import conf from "../../../pragma.conf.js";
import { PragmaError } from "../../kernel/error/PragmaError.js";
import {
  executeVerb,
  type MutationFlags,
} from "../../kernel/project/cli/dispatch.js";
import { bootRuntime } from "../../kernel/runtime/boot.js";
import type { GlobalFlags } from "../../kernel/runtime/types.js";
import {
  createVerbs,
  isModuleNotFound,
  toGeneratorAnswers,
} from "./create.verb.js";
import { createModule } from "./index.js";
import { CREATE_SURFACE } from "./surface.generated.js";
import type { CreateKind, NounSurface } from "./types.js";

const FLAGS: GlobalFlags = {
  llm: false,
  autoLlm: false,
  format: "plain",
  verbose: false,
};
const YES: MutationFlags = { dryRun: false, undo: false, yes: true };
const freshCwd = (): string => mkdtempSync(join(tmpdir(), "pragma-create-"));

/** Run a create verb inside `dir` (relative generator paths resolve there). */
async function runIn(
  dir: string,
  params: Record<string, unknown>,
  mutation: MutationFlags = YES,
) {
  const prev = process.cwd();
  process.chdir(dir);
  try {
    return await executeVerb(
      createVerbs.component,
      params,
      mutation,
      bootRuntime(FLAGS, dir),
    );
  } finally {
    process.chdir(prev);
  }
}

const walk = (dir: string, base = ""): string[] =>
  readdirSync(dir, { withFileTypes: true }).flatMap((e) =>
    e.isDirectory()
      ? walk(join(dir, e.name), join(base, e.name))
      : [join(base, e.name)],
  );

describe("create — real generation + stamp", () => {
  it("scaffolds a component and stamps generated files", async () => {
    const dir = freshCwd();
    const outcome = await runIn(dir, {
      framework: "react",
      componentPath: "src/components/Widget",
      withStyles: true,
      withStories: false,
      withSsrTests: false,
    });
    expect(outcome.exitCode).toBe(0);
    const main = join(dir, "src/components/Widget/Widget.tsx");
    expect(existsSync(main)).toBe(true);
    expect(readFileSync(main, "utf-8").split("\n")[0]).toBe(
      "// Generated by @canonical/summon-component:react v0.1.0",
    );
  });

  it("--dry-run writes nothing and previews effects (no Prompt lines)", async () => {
    const dir = freshCwd();
    const outcome = await runIn(
      dir,
      { framework: "react", componentPath: "src/components/Widget" },
      { dryRun: true, undo: false, yes: false },
    );
    expect(outcome.exitCode).toBe(0);
    expect(outcome.stdout).toContain("Widget.tsx");
    expect(outcome.stdout).not.toContain("Prompt");
    expect(walk(dir)).toEqual([]); // nothing written
  });

  it("--undo reverses a run", async () => {
    const dir = freshCwd();
    await runIn(dir, {
      framework: "react",
      componentPath: "src/components/Widget",
      withStyles: false,
      withStories: false,
      withSsrTests: false,
    });
    const outcome = await runIn(
      dir,
      {
        framework: "react",
        componentPath: "src/components/Widget",
        withStyles: false,
        withStories: false,
        withSsrTests: false,
      },
      { dryRun: false, undo: true, yes: true },
    );
    expect(outcome.exitCode).toBe(0);
    expect(outcome.stdout).toMatch(/Undid \d+ step/);
  });

  it("rejects an unknown framework with INVALID_INPUT", async () => {
    const dir = freshCwd();
    // coerceParam rejects the enum before run, so drive run directly via a bad
    // framework param to exercise pickGenerator's own guard too.
    const runtime = bootRuntime(FLAGS, dir);
    await expect(
      createVerbs.component.run({ framework: "vue" }, {
        ...runtime,
        interaction: { isTTY: false, transport: "cli", yes: true },
      } as never),
    ).rejects.toBeInstanceOf(PragmaError);
  });
});

describe("SEC-2 path jail (PROTECTED)", () => {
  const cases: Array<[string, string]> = [
    ["a .. escape", "../evil/Widget"],
    ["an absolute path", "/tmp/evil/Widget"],
  ];
  for (const [label, value] of cases) {
    it(`rejects ${label} with a PragmaError before any effect`, async () => {
      const dir = freshCwd();
      // The jail throws in `run`, before any effect; the projector maps it to an
      // exit code, but exercised directly here `executeVerb` propagates it.
      await expect(
        runIn(dir, { framework: "react", componentPath: value }),
      ).rejects.toBeInstanceOf(PragmaError);
      expect(walk(dir)).toEqual([]);
    });
  }

  it("rejects a symlink that escapes the workspace (realpath)", async () => {
    const root = freshCwd();
    const outside = freshCwd();
    // A symlink `link` inside the workspace pointing OUT of it.
    symlinkSync(outside, join(root, "link"));
    await expect(
      runIn(root, { framework: "react", componentPath: "link/Widget" }),
    ).rejects.toBeInstanceOf(PragmaError);
    expect(existsSync(join(outside, "Widget"))).toBe(false);
  });

  it("accepts an in-workspace path", async () => {
    const dir = freshCwd();
    mkdirSync(join(dir, "packages"), { recursive: true });
    const outcome = await runIn(dir, {
      framework: "react",
      componentPath: "packages/Widget",
      withStyles: false,
      withStories: false,
      withSsrTests: false,
    });
    expect(outcome.exitCode).toBe(0);
  });
});

describe("lazy-React discipline (PROTECTED)", () => {
  const here = dirname(fileURLToPath(import.meta.url));

  /** Walk the STATIC (relative-only) import graph from an entry .ts file. */
  function staticGraph(entry: string, seen = new Set<string>()): Set<string> {
    if (seen.has(entry) || !existsSync(entry)) return seen;
    seen.add(entry);
    const src = readFileSync(entry, "utf-8");
    const re = /(?:\bfrom\s*|(?:^|\n)\s*import\s*)["']([^"']+)["']/g;
    for (const m of src.matchAll(re)) {
      const spec = m[1];
      if (spec?.startsWith("."))
        staticGraph(
          resolve(dirname(entry), spec.replace(/\.js$/, ".ts")),
          seen,
        );
    }
    return seen;
  }

  it("the capability registry never statically reaches React/Ink or the generators", () => {
    const graph = staticGraph(resolve(here, "../index.ts"));
    // pickGenerator (which imports the heavy generators) is dynamic-only.
    expect([...graph].some((f) => f.endsWith("create/pickGenerator.ts"))).toBe(
      false,
    );
    // …and so is the generated VALUE module it imports them through. The DATA
    // module is on the graph and must stay import-free, which the assertion
    // below pins.
    expect(
      [...graph].some((f) => f.endsWith("create/generators.generated.ts")),
    ).toBe(false);
    // DERIVED from the declaration, not spelled by hand: the forbidden set is
    // exactly the generator packages THIS distribution declares, plus the
    // runtime they pull. A fork that swaps its packages gets its own packages
    // forbidden with no edit here — strictly stronger than a fixed list, which
    // would go quiet the moment the declaration changed.
    const declared = conf.generators.map((generator) => generator.name);
    expect(declared.length).toBeGreaterThan(0);
    const forbidden = [
      "react",
      "react-dom",
      "ink",
      "ink-select-input",
      "ink-text-input",
      "ink-spinner",
      ...declared,
      // The generators pull summon-core, and summon-core is what costs the
      // fast paths (+43 MB RSS once it loads). Dropping the `type` from one of
      // the `import type … from "@canonical/summon-core"` lines in this
      // directory is a one-word regression nothing else catches.
      "@canonical/summon-core",
    ];
    for (const file of graph) {
      // Type-only imports are erased before runtime, so they load nothing —
      // strip them before asking what the file actually pulls in.
      const src = readFileSync(file, "utf-8").replace(
        /\bimport\s+type\b[^;]*;/g,
        "",
      );
      for (const pkg of forbidden) {
        const esc = pkg.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
        expect(
          new RegExp(`from\\s*["']${esc}["']`).test(src),
          `${file} statically imports ${pkg}`,
        ).toBe(false);
      }
    }
  });

  it("running create --yes never loads React or Ink", async () => {
    const dir = freshCwd();
    await runIn(dir, {
      framework: "react",
      componentPath: "src/components/Widget",
      withStyles: false,
      withStories: false,
      withSsrTests: false,
    });
    const isReactPkg = (k: string) =>
      /[\\/](react|react-dom|ink|ink-select-input|ink-text-input|ink-spinner)@\d/.test(
        k,
      ) ||
      /[\\/]node_modules[\\/](react|react-dom|ink|ink-select-input|ink-text-input|ink-spinner)[\\/]/.test(
        k,
      );
    const loaded = Object.keys(require.cache ?? {});
    expect(loaded.filter(isReactPkg)).toEqual([]);
  });
});

describe("derived create surface (PROTECTED)", () => {
  const dir = dirname(fileURLToPath(import.meta.url));

  // The surface is GENERATED from `pragma.conf.ts` + the live generators, so
  // there is no hand-written mirror left to drift. What can still go wrong is a
  // derivation quietly producing the wrong thing, and every check below pins it
  // against something OUTSIDE itself: the declaration read as source text, a
  // literal expectation, the live generator maps, the embedded manifest, and —
  // for the flag set — the FROZEN COVENANT. Staleness of the committed bytes is
  // NOT checkable from in here; see the note on the first case.

  it("the generated value module imports exactly the declared packages", () => {
    // Read as SOURCE TEXT and compared to the DECLARATION — input against
    // output, not the derivation against itself. This is what catches a codegen
    // bug that writes a specifier the declaration does not name (or drops one):
    // the binary would then link a package the distribution never declared.
    //
    // A regenerate-and-compare staleness guard was tried here and DELETED as
    // vacuous: `testing/perf/globalSetup.ts` rebuilds `dist/pragma` whenever
    // anything under `src/`, `scripts/`, `pragma.conf.ts` or `package.json` is
    // newer, and that build regenerates these modules — so by the time any test
    // body runs, the committed bytes on disk are always fresh and the guard
    // could not fail. Measured: hand-editing a prompt default and an import
    // specifier both passed. What keeps the committed bytes honest is the
    // `git status` after a gate run, and the covenant conformance below.
    const source = readFileSync(
      resolve(dir, "generators.generated.ts"),
      "utf-8",
    );
    const specifiers = [
      ...source.matchAll(/import \{ generators as \w+ \} from "([^"]+)";/g),
    ].map((match) => match.at(1));
    expect(specifiers.length).toBeGreaterThan(0);
    expect(specifiers.sort()).toEqual(
      conf.generators.map((generator) => generator.name).sort(),
    );
  });

  it("the generated DATA module has no import at all", () => {
    // `create.verb.ts` reads it on the `--help` and `__complete` fast paths. One
    // value import here would drag a generator — and summon-core, +43 MB RSS —
    // onto every invocation. The lazy-React graph walk cannot see this, because
    // it only forbids NAMED packages; a relative import would slip through.
    const source = readFileSync(resolve(dir, "surface.generated.ts"), "utf-8");
    expect(source).not.toMatch(/^import /m);
  });

  it("the derived path param is exactly the argument each noun jails (SEC-2)", () => {
    // A LITERAL expectation for THIS distribution's three nouns, against a
    // build that now refuses to leave a positional unjailed at all: a
    // positional text prompt the heuristic did not select and the declaration
    // did not name (`pathParam`) is a codegen error, so `undefined` here can
    // only mean "no positional", never "the jail was silently dropped".
    // `package` has no positional — it writes into a subdirectory derived from
    // `--name`, which `cwdJail.test.ts` covers separately.
    const derived = Object.fromEntries(
      Object.entries(CREATE_SURFACE).map(
        ([kind, noun]: [string, NounSurface]) => [kind, noun.pathParam],
      ),
    );
    expect(derived).toEqual({
      component: "componentPath",
      package: undefined,
      application: "appPath",
    });
  });

  it("the axis collapses the declared package's real generator keys", () => {
    const component: NounSurface = CREATE_SURFACE.component;
    expect(component.axis).toBe("framework");
    expect(component.keyPrefix).toBe("component");
    expect([...(component.axisValues ?? [])]).toEqual([
      "react",
      "svelte",
      "lit",
    ]);
  });

  it("the CLI-grammar overlays are applied, and only where declared", () => {
    // `runInstall` is a DELIBERATE divergence from the generators, which default
    // it TRUE: the grammar has no `--no-` form, so a default-true boolean could
    // never be turned off. It is declared per noun (`optIn`), not inferred.
    for (const kind of ["package", "application"] as const) {
      expect(
        createVerbs[kind].params.find((p) => p.name === "runInstall"),
        kind,
      ).toMatchObject({ kind: "boolean", default: false });
    }
    // The include-flag rename (`--with-X`) is declared too: application's four
    // booleans are exposed prefixed, and the bare names must NOT survive.
    const names = createVerbs.application.params.map((p) => p.name);
    for (const flag of ["withSsr", "withRouter", "withForms", "withRelay"]) {
      expect(names).toContain(flag);
    }
    for (const bare of ["ssr", "router", "forms", "relay"]) {
      expect(names).not.toContain(bare);
    }
    // `componentPath` drops its ParamSpec default so the SELECTED framework's
    // own prompt default applies — and stays optional despite having none here.
    const componentPath = createVerbs.component.params.find(
      (p) => p.name === "componentPath",
    ) as Record<string, unknown> | undefined;
    expect(componentPath).toMatchObject({
      kind: "string",
      positional: true,
      complete: { kind: "files" },
      required: false,
    });
    expect(componentPath?.default).toBeUndefined();
  });

  it("the include-flag aliases round-trip a param bag to generator prompt names", () => {
    expect(
      toGeneratorAnswers("application", {
        withSsr: true,
        withRelay: false,
        appPath: "x",
      }),
    ).toEqual({ ssr: true, relay: false, appPath: "x" });
    // A noun with no declared aliases passes its bag through untouched.
    expect(toGeneratorAnswers("package", { name: "@a/b" })).toEqual({
      name: "@a/b",
    });
  });
});

describe("bundling backstop — an unresolvable generator module (PROTECTED)", () => {
  it("detects a module-resolution failure but not a genuine runtime error", () => {
    // bun --compile's unresolved-specifier error (the shipped-binary case).
    expect(
      isModuleNotFound({
        name: "ResolveMessage",
        message: "Cannot find module './pickGenerator.js'",
      }),
    ).toBe(true);
    // node ESM's resolution error.
    expect(
      isModuleNotFound(
        Object.assign(new Error("x"), { code: "ERR_MODULE_NOT_FOUND" }),
      ),
    ).toBe(true);
    // A REAL runtime bug in a source build must still propagate (not be masked
    // as "run from source").
    expect(
      isModuleNotFound(new TypeError("cannot read properties of undefined")),
    ).toBe(false);
    expect(isModuleNotFound(null)).toBe(false);
    expect(isModuleNotFound("nope")).toBe(false);
  });
});

describe("declared generator bindings (PROTECTED)", () => {
  // The create surface's generator facts are written down in `pragma.conf.ts`
  // and reach code only through the build-written `generators.generated.ts` /
  // `surface.generated.ts`. What is checkable against something OUTSIDE those
  // modules — the live generator maps and the embedded manifest — is checked
  // here.

  it("every declared noun resolves to the generator it names", async () => {
    const { pickGenerator } = await import("./pickGenerator.js");
    // `meta.name` is the generator's OWN identity, so a swapped key or an axis
    // value the package does not carry turns this red — which `toBeDefined()`
    // on a non-nullable return could not. Derived from the declaration, so a
    // fork's nouns are checked the same way.
    const nouns = Object.keys(CREATE_SURFACE) as CreateKind[];
    expect(nouns.length).toBeGreaterThan(0);
    for (const kind of nouns) {
      const noun: NounSurface = CREATE_SURFACE[kind];
      if (noun.axis !== undefined && noun.axisValues !== undefined) {
        for (const value of noun.axisValues) {
          expect(pickGenerator(kind, { [noun.axis]: value }).meta.name).toBe(
            `${noun.keyPrefix}/${value}`,
          );
        }
      } else {
        expect(pickGenerator(kind, {}).meta.name).toBe(noun.key);
      }
    }
  });

  it("no create verb publishes an availability caveat", () => {
    // The INVERSE of the assertion this replaces, and deliberately LITERAL
    // rather than derived from a bit: the bit it used to read
    // (`readsEmbeddedTemplates`) is gone because it became universally true.
    // Every noun runs from the shipped binary — `compiledCreate.subprocess
    // .test.ts` proves each byte for byte — so a summary that withdraws itself,
    // or a doc explaining a refusal, is a claim the binary contradicts.
    for (const verb of createModule.verbs) {
      const kind = verb.path.at(1);
      expect(verb.summary, kind).not.toContain("Source-run only");
      expect(verb.doc ?? "", kind).not.toContain("UNSUPPORTED");
      expect(verb.doc ?? "", kind).not.toContain("source checkout");
    }
  });

  it("the --framework enum offers the declared frameworks and defaults to one of them", () => {
    const framework = createVerbs.component.params.find(
      (p) => p.name === "framework",
    );
    // A `values: []` enum with a `default` would leave every `--framework`
    // rejected while `--help` still advertises a default — the hazard this names.
    // (That every value resolves is the test above.)
    expect(framework?.kind).toBe("enum");
    const values = (framework as { values: readonly string[] }).values;
    expect(values.length).toBeGreaterThan(0);
    expect(values).toContain(framework?.default);
  });

  it("embeds every key under a declared package's scope, and no other", async () => {
    const { TEMPLATES } = await import("./templates.embedded.generated.js");
    const keys = Object.keys(TEMPLATES);
    // The manifest is package-scoped, so an entry outside every declared
    // package's scope is dead weight no loader can ever key. Non-empty first:
    // `.filter()` over an empty list is vacuous.
    expect(keys.length).toBeGreaterThan(0);
    const scopes = conf.generators.map((generator) => `${generator.name}/`);
    expect(scopes.length).toBeGreaterThan(0);
    expect(
      keys.filter((key) => !scopes.some((scope) => key.startsWith(scope))),
    ).toEqual([]);
  });

  it("create surfaces exactly the three declared nouns", () => {
    // A LITERAL surface pin, and literal is the point: the surface is a
    // deliberate SUBSET of what the declared packages ship (the application
    // package also ships `domain`, `route` and `wrapper`). The DECLARATION
    // decides which of them this distribution exposes, not the package — so an
    // upstream release adding a generator must not silently widen this
    // distribution's surface, and deriving the expectation from the same
    // declaration the build reads would agree with itself by construction.
    expect(createModule.verbs.map((v) => v.path[1])).toEqual([
      "component",
      "package",
      "application",
    ]);
  });
});
