// AUTO-GENERATED by scripts/build.ts — do not edit by hand.
// Regenerate: `bun run scripts/build.ts`. The `create` surface, derived from
// `pragma.conf.ts`'s `generators` declaration and the live generators it names:
// each noun's prompt mirror, framework axis, path param, summary and examples.
// ZERO IMPORTS, deliberately — `create.verb.ts` reads this on the `--help` and
// `__complete` fast paths, which must load neither a generator nor summon-core.
/** Noun → its derived create surface. */
export const CREATE_SURFACE = {
  "component": {
    "package": "@canonical/summon-component",
    "key": "component/react",
    "axis": "framework",
    "axisValues": [
      "react",
      "svelte",
      "lit"
    ],
    "axisDoc": "Component framework.",
    "keyPrefix": "component",
    "summary": "Scaffold a React, Svelte, or Lit component.",
    "useWhen": "Scaffolding a new component (React, Svelte, or Lit)",
    "examples": [
      {
        "cmd": "create component src/components/Button --framework react",
        "note": "React component with tests, stories, and styles"
      },
      {
        "cmd": "create component src/lib/Card --framework svelte --dry-run",
        "note": "preview the files without writing"
      }
    ],
    "prompts": [
      {
        "name": "componentPath",
        "type": "text",
        "message": "Component path:",
        "default": "src/components/MyComponent",
        "positional": true
      },
      {
        "name": "withStyles",
        "type": "confirm",
        "message": "Include styles?",
        "default": true
      },
      {
        "name": "withStories",
        "type": "confirm",
        "message": "Include Storybook stories?",
        "default": true
      },
      {
        "name": "withSsrTests",
        "type": "confirm",
        "message": "Include SSR tests?",
        "default": true
      }
    ],
    "docs": {
      "framework": "Component framework.",
      "componentPath": "Component path (its final segment is the PascalCase component name)."
    },
    "pathParam": "componentPath",
    "aliases": {},
    "optIn": [],
    "noDefault": [
      "componentPath"
    ]
  },
  "package": {
    "package": "@canonical/summon-package",
    "key": "package",
    "summary": "Scaffold a new npm package for the monorepo.",
    "useWhen": "Scaffolding a new npm package with proper monorepo configuration",
    "examples": [
      {
        "cmd": "create package --name @canonical/my-lib --type library"
      },
      {
        "cmd": "create package --name @canonical/my-tool --run-install"
      }
    ],
    "prompts": [
      {
        "name": "name",
        "type": "text",
        "message": "Package name:",
        "default": "@canonical/my-package"
      },
      {
        "name": "type",
        "type": "select",
        "message": "Package type:",
        "default": "tool-ts",
        "choices": [
          {
            "label": "tool-ts - TypeScript tool (runs from src/, no build)",
            "value": "tool-ts"
          },
          {
            "label": "library - Publishable library (dist/ build output)",
            "value": "library"
          },
          {
            "label": "css - CSS package (src/index.css, no build)",
            "value": "css"
          }
        ]
      },
      {
        "name": "description",
        "type": "text",
        "message": "Package description:",
        "default": ""
      },
      {
        "name": "withReact",
        "type": "confirm",
        "message": "Include React dependencies?",
        "default": false
      },
      {
        "name": "withStorybook",
        "type": "confirm",
        "message": "Include Storybook setup?",
        "default": false
      },
      {
        "name": "withCli",
        "type": "confirm",
        "message": "Include CLI binary entry point?",
        "default": false
      },
      {
        "name": "withPrTemplate",
        "type": "confirm",
        "message": "Include a .github/PULL_REQUEST_TEMPLATE.md?",
        "default": false
      },
      {
        "name": "runInstall",
        "type": "confirm",
        "message": "Run package manager install after creation?",
        "default": true
      }
    ],
    "docs": {},
    "aliases": {},
    "optIn": [
      "runInstall"
    ],
    "noDefault": []
  },
  "application": {
    "package": "@canonical/summon-application",
    "key": "application/react",
    "summary": "Scaffold a full React application with SSR and routing.",
    "useWhen": "Scaffolding a new React application with SSR, routing, and optional Relay",
    "examples": [
      {
        "cmd": "create application my-app"
      },
      {
        "cmd": "create application my-app --with-relay"
      }
    ],
    "prompts": [
      {
        "name": "appPath",
        "type": "text",
        "message": "Application directory name:",
        "default": "my-app",
        "positional": true
      },
      {
        "name": "ssr",
        "type": "confirm",
        "message": "Include SSR?",
        "default": true
      },
      {
        "name": "router",
        "type": "confirm",
        "message": "Include router?",
        "default": true
      },
      {
        "name": "forms",
        "type": "confirm",
        "message": "Include form components?",
        "default": true
      },
      {
        "name": "relay",
        "type": "confirm",
        "message": "Include a Relay (GraphQL) data layer with a local mock schema?",
        "default": false
      },
      {
        "name": "runInstall",
        "type": "confirm",
        "message": "Install dependencies now?",
        "default": true
      }
    ],
    "docs": {},
    "pathParam": "appPath",
    "aliases": {
      "withSsr": "ssr",
      "withRouter": "router",
      "withForms": "forms",
      "withRelay": "relay"
    },
    "optIn": [
      "runInstall"
    ],
    "noDefault": []
  }
} as const;
