// Generated by @canonical/summon-component:react v0.1.0

import type { ComponentProps, ReactNode } from "react";

type OwnProps = {
  /** View content (default slot). Typically a ContentLayout. */
  children?: ReactNode;
  /**
   * Contextual aside (named slot), rendered in the trailing `min-content`
   * column — a detail panel, filters, help. Slot-agnostic: pass any
   * ReactNode; the slot owns its inline size.
   */
  aside?: ReactNode;
};

export type ViewLayoutProps = OwnProps &
  Omit<ComponentProps<"div">, keyof OwnProps>;
