// Generated by @canonical/summon-component:react v0.1.0

import type React from "react";
import type { ViewLayoutProps } from "./types.js";
import "./styles.css";

const componentCssClassName = "ds view-layout";

/**
 * ViewLayout — a single view within the application shell.
 *
 * Divides its space between the view content (default slot, `1fr`) and an
 * optional contextual aside (named slot, `min-content`), per the ontology
 * instance `apps.layout.view_layout`.
 */
const ViewLayout = ({
  className,
  children,
  aside,
  ...props
}: ViewLayoutProps): React.ReactElement => {
  return (
    <div
      className={[componentCssClassName, className].filter(Boolean).join(" ")}
      {...props}
    >
      <div className="content">{children}</div>
      {aside != null && <div className="aside">{aside}</div>}
    </div>
  );
};

export default ViewLayout;
