// Generated by @canonical/summon-component:react v0.1.0

import { renderToString } from "react-dom/server";
import { describe, expect, it } from "vitest";
import ViewLayout from "./ViewLayout.js";

describe("ViewLayout SSR", () => {
  it("renders without hydration errors", () => {
    const html = renderToString(
      <ViewLayout aside={<span>Aside</span>}>Test content</ViewLayout>,
    );
    expect(html).toContain("Test content");
    expect(html).toContain("Aside");
    expect(html).toContain("ds view-layout");
  });
});
