// Generated by @canonical/summon-component-lit v0.1.0

import { html, LitElement } from "lit";
import { customElement } from "lit/decorators.js";
import styles from "./styles.css";
import type { SiteLayoutProps } from "./types.js";

const componentCssClassName = "ds site-layout";

/**
 * SiteLayout web component.
 *
 * @implements ds:global.component.site-layout
 */
@customElement("ds-site-layout")
export default class SiteLayout extends LitElement implements SiteLayoutProps {
  static styles = styles;

  render() {
    return html`
			<div class="${componentCssClassName}">
			<slot></slot>
			</div>
		`;
  }
}
