// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import type { ApplicationLayoutProps } from "./types";
import "./styles.css";
import { InnerGridDemo } from "../InnerGridDemo/index.js";

/**
 * ApplicationLayout component
 */
export const ApplicationLayout = ({
	className,
	children,
	...props
}: ApplicationLayoutProps): JSX.Element => {
	return (
		<div
			className={`application-layout${className ? ` ${className}` : ""}`}
			{...props}
		>
			<aside className="sidebar">Sidebar content</aside>
			<InnerGridDemo className="content">{children}</InnerGridDemo>
			<aside className="pane">pane</aside>
		</div>
	);
};
