// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import { describe, expect, it } from "vitest";
import { renderToString } from "react-dom/server";
import { ApplicationLayout } from "./ApplicationLayout";

describe("ApplicationLayout SSR", () => {
	it("renders without hydration errors", () => {
		const html = renderToString(<ApplicationLayout>Test content</ApplicationLayout>);
		expect(html).toContain("Test content");
		expect(html).toContain("application-layout");
	});
});
