// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import IconSection from "./IconSection.js";

describe("IconSection", () => {
  // TODO(#662): the component accepts `children` but silently drops them.
  // Unskip once the children-vs-props API is settled.
  it.skip("renders children", () => {
    render(<IconSection>Test content</IconSection>);
    expect(screen.getByText("Test content")).toBeInTheDocument();
  });

  it("applies custom className", () => {
    render(<IconSection className="custom-class">Content</IconSection>);
    // The root element carries the classes; children may render in a descendant.
    const element = document.querySelector(".custom-class") as HTMLElement;
    expect(element.className).toContain("ds icon-section");
    expect(element.className).toContain("custom-class");
  });

  it("passes through additional props", () => {
    render(<IconSection data-testid="test-component">Content</IconSection>);
    expect(screen.getByTestId("test-component")).toBeInTheDocument();
  });
});
