// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import { renderToString } from "react-dom/server";
import { describe, expect, it } from "vitest";
import IconSection from "./IconSection.js";

describe("IconSection SSR", () => {
  it("renders without hydration errors", () => {
    const html = renderToString(<IconSection>Test content</IconSection>);
    // TODO(#662): also assert children render once the children-vs-props API
    // is settled — the component currently drops children.
    expect(html).toContain("ds icon-section");
  });
});
