// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import type React from "react";
import type { DescriptionSectionProps } from "./types.js";
import "./styles.css";
import { Section } from "../Section/index.js";

const componentCssClassName = "ds description-section";

/**
 * DescriptionSection component
 */
const DescriptionSection = ({
  className,
  children,
  title,
  ...props
}: DescriptionSectionProps): React.ReactElement => {
  return (
    <Section
      className={[componentCssClassName, className].filter(Boolean).join(" ")}
      {...props}
      title={title}
    >
      {children}
    </Section>
  );
};

export default DescriptionSection;
