// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import { renderToString } from "react-dom/server";
import { describe, expect, it } from "vitest";
import DescriptionSection from "./DescriptionSection.js";

describe("DescriptionSection SSR", () => {
  it("renders without hydration errors", () => {
    const html = renderToString(
      <DescriptionSection>Test content</DescriptionSection>,
    );
    expect(html).toContain("Test content");
    expect(html).toContain("ds description-section");
  });
});
