// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import type { Meta, StoryObj } from "@storybook/react";
import DescriptionSection from "./DescriptionSection.js";
import * as decorators from "../../../storybook/decorators.js";

const meta: Meta<typeof DescriptionSection> = {
  title: "Components/DescriptionSection",
  component: DescriptionSection,
  tags: ["autodocs"],
  parameters: {
    layout: "fullscreen",
  },
  decorators: [decorators.grid()],
};

export default meta;
type Story = StoryObj<typeof DescriptionSection>;

export const Default: Story = {
  args: {
    children: "Hello, DescriptionSection!",
    title: "Fast track",
  },
};

export const WithCustomClass: Story = {
  args: {
    children: "Custom styled",
    className: "custom-class",
  },
};
