<!-- Generated by @canonical/summon-component:svelte v0.1.0 -->

<script lang="ts" module>
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import { SECTION_SPACING } from "./constants.js";
  import Section from "./Section.svelte";

  const { Story } = defineMeta({
    title: "Components/Section",
    component: Section,
    tags: ["autodocs"],
    argTypes: {
      spacing: {
        options: [undefined, ...SECTION_SPACING],
        control: { type: "radio" },
        description: "The spacing variant of the section.",
        table: {
          type: {
            summary: SECTION_SPACING.join(" | "),
          },
        },
      },
    },
    parameters: {
      docs: {
        description: {
          component:
            "The `Section` component groups related content. Sections can have varying visual spacing levels to organize information according to an information hierarchy.",
        },
      },
    },
  });
</script>

<Story name="Default">
  <p>Hello world!</p>
</Story>

<Story
  name="Bordered"
  args={{ bordered: true }}
  parameters={{
    docs: {
      description: {
        story:
          "A section can have a top border to increase its visual separation from preceding content.",
      },
    },
  }}
>
  <p>This section has a top border.</p>
</Story>

<Story
  name="Spacing"
  args={{ bordered: true }}
  parameters={{
    docs: {
      description: {
        story:
          "Sections can have varying visual spacing levels to organize information according to an information hierarchy.<br>Use the `spacing` prop to set the desired spacing level.<br>The example below uses `spacing` with `bordered` to help visually demonstrate the different spacing levels, but `spacing` can be used without `bordered` as well.",
      },
    },
  }}
>
  {#snippet template({ children: _, ...args })}
    {#each SECTION_SPACING as spacingLevel (spacingLevel)}
      <Section {...args} spacing={spacingLevel}>
        <h4>This is a {spacingLevel} section.</h4>
      </Section>
    {/each}
  {/snippet}
</Story>
