<!-- Generated by @canonical/summon-component:svelte v0.1.0 -->

<script lang="ts">
  import type { SectionProps } from "./types.js";
  import "./styles.css";

  const componentCssClassName = "ds section";

  let {
    class: className,
    children,
    spacing,
    bordered = false,
    ...rest
  }: SectionProps = $props();
</script>

<section
  class={[componentCssClassName, bordered && "bordered", spacing, className]}
  {...rest}
>
  {@render children()}
</section>

<!-- @component
The `Section` component groups related content. Sections can have varying visual
spacing levels to organize information according to an information hierarchy.

`import { Section } from "@canonical/svelte-ds-app-wpe";`

## Example Usage
```svelte
<Section spacing="deep" bordered>
  <p>Hello world!</p>
</Section>
```

@implements ds:site.component.section
-->
