import type { TokenEntry } from "./TokenTable/index.js";

export const mockTokens: TokenEntry[] = [
  {
    cssVar: "--color-palette-white",
    id: "color.palette.white",
    type: "color",
    tier: "primitive",
    stability: "wip",
    cssOutputFile: "sets.primitive.css",
    isPaired: false,
    valueLight: "oklch(100% 0 0)",
  },
  {
    cssVar: "--color-palette-gray-20",
    id: "color.palette.gray.20",
    type: "color",
    tier: "primitive",
    stability: "wip",
    cssOutputFile: "sets.primitive.css",
    isPaired: false,
    valueLight: "oklch(98% 0 0)",
  },
  {
    cssVar: "--color-palette-gray-50",
    id: "color.palette.gray.50",
    type: "color",
    tier: "primitive",
    stability: "wip",
    cssOutputFile: "sets.primitive.css",
    isPaired: false,
    valueLight: "oklch(95% 0 0)",
  },
  {
    cssVar: "--color-palette-gray-100",
    id: "color.palette.gray.100",
    type: "color",
    tier: "primitive",
    stability: "wip",
    cssOutputFile: "sets.primitive.css",
    isPaired: false,
    valueLight: "oklch(90% 0 0)",
  },
  {
    cssVar: "--color-palette-gray-200",
    id: "color.palette.gray.200",
    type: "color",
    tier: "primitive",
    stability: "wip",
    cssOutputFile: "sets.primitive.css",
    isPaired: false,
    valueLight: "oklch(80% 0 0)",
  },
  {
    cssVar: "--color-palette-gray-300",
    id: "color.palette.gray.300",
    type: "color",
    tier: "primitive",
    stability: "wip",
    cssOutputFile: "sets.primitive.css",
    isPaired: false,
    valueLight: "oklch(70% 0 0)",
  },
  {
    cssVar: "--color-palette-gray-400",
    id: "color.palette.gray.400",
    type: "color",
    tier: "primitive",
    stability: "wip",
    cssOutputFile: "sets.primitive.css",
    isPaired: false,
    valueLight: "oklch(60% 0 0)",
  },
  {
    cssVar: "--color-palette-gray-500",
    id: "color.palette.gray.500",
    type: "color",
    tier: "primitive",
    stability: "wip",
    cssOutputFile: "sets.primitive.css",
    isPaired: false,
    valueLight: "oklch(50% 0 0)",
  },
  {
    cssVar: "--color-palette-gray-600",
    id: "color.palette.gray.600",
    type: "color",
    tier: "primitive",
    stability: "wip",
    cssOutputFile: "sets.primitive.css",
    isPaired: false,
    valueLight: "oklch(40% 0 0)",
  },
  {
    cssVar: "--color-palette-gray-700",
    id: "color.palette.gray.700",
    type: "color",
    tier: "primitive",
    stability: "wip",
    cssOutputFile: "sets.primitive.css",
    isPaired: false,
    valueLight: "oklch(30% 0 0)",
  },
  {
    cssVar: "--color-palette-gray-800",
    id: "color.palette.gray.800",
    type: "color",
    tier: "primitive",
    stability: "wip",
    cssOutputFile: "sets.primitive.css",
    isPaired: false,
    valueLight: "oklch(20% 0 0)",
  },
  {
    cssVar: "--color-palette-gray-900",
    id: "color.palette.gray.900",
    type: "color",
    tier: "primitive",
    stability: "wip",
    cssOutputFile: "sets.primitive.css",
    isPaired: false,
    valueLight: "oklch(15% 0 0)",
  },
  {
    cssVar: "--color-palette-gray-950",
    id: "color.palette.gray.950",
    type: "color",
    tier: "primitive",
    stability: "wip",
    cssOutputFile: "sets.primitive.css",
    isPaired: false,
    valueLight: "oklch(13% 0 0)",
  },
  {
    cssVar: "--color-palette-gray-960",
    id: "color.palette.gray.960",
    type: "color",
    tier: "primitive",
    stability: "wip",
    cssOutputFile: "sets.primitive.css",
    isPaired: false,
    valueLight: "oklch(13% 0 0)",
  },
  {
    cssVar: "--color-palette-gray-990",
    id: "color.palette.gray.990",
    type: "color",
    tier: "primitive",
    stability: "wip",
    cssOutputFile: "sets.primitive.css",
    isPaired: false,
    valueLight: "oklch(12.21% 0 0)",
  },
  {
    cssVar: "--color-palette-black",
    id: "color.palette.black",
    type: "color",
    tier: "primitive",
    stability: "wip",
    cssOutputFile: "sets.primitive.css",
    isPaired: false,
    valueLight: "oklch(0% 0 0)",
  },
  {
    cssVar: "--dimension-025",
    id: "dimension.025",
    type: "dimension",
    tier: "primitive",
    stability: "wip",
    cssOutputFile: "sets.primitive.css",
    isPaired: false,
    valueLight: "0.125rem",
  },
  {
    cssVar: "--dimension-1",
    id: "dimension.1",
    type: "dimension",
    tier: "primitive",
    stability: "wip",
    cssOutputFile: "sets.primitive.css",
    isPaired: false,
    valueLight: "0.5rem",
  },
  {
    cssVar: "--dimension-2",
    id: "dimension.2",
    type: "dimension",
    tier: "primitive",
    stability: "wip",
    cssOutputFile: "sets.primitive.css",
    isPaired: false,
    valueLight: "1rem",
  },
  {
    cssVar: "--dimension-4",
    id: "dimension.4",
    type: "dimension",
    tier: "primitive",
    stability: "wip",
    cssOutputFile: "sets.primitive.css",
    isPaired: false,
    valueLight: "2rem",
  },
  {
    cssVar: "--color-background",
    id: "color.background",
    type: "color",
    tier: "semantic",
    stability: "wip",
    cssOutputFile: "modifiers.theme.css",
    isPaired: true,
    valueLight: "oklch(100% 0 0)",
    valueDark: "oklch(12.21% 0 0)",
  },
  {
    cssVar: "--color-text",
    id: "color.text",
    type: "color",
    tier: "semantic",
    stability: "wip",
    cssOutputFile: "modifiers.theme.css",
    isPaired: true,
    valueLight: "oklch(12.21% 0 0)",
    valueDark: "oklch(100% 0 0)",
  },
  {
    cssVar: "--color-foreground-primary",
    id: "color.foreground.primary",
    type: "color",
    tier: "semantic",
    stability: "wip",
    cssOutputFile: "modifiers.theme.css",
    isPaired: true,
    valueLight: "oklch(12.21% 0 0)",
    valueDark: "oklch(100% 0 0)",
  },
  {
    cssVar: "--color-border",
    id: "color.border",
    type: "color",
    tier: "semantic",
    stability: "wip",
    cssOutputFile: "modifiers.theme.css",
    isPaired: true,
    valueLight: "oklch(80% 0 0)",
    valueDark: "oklch(30% 0 0)",
  },
  {
    cssVar: "--color-text-muted",
    id: "color.text.muted",
    type: "color",
    tier: "semantic",
    stability: "wip",
    cssOutputFile: "modifiers.theme.css",
    isPaired: true,
    valueLight: "oklch(50% 0 0)",
    valueDark: "oklch(70% 0 0)",
  },
  {
    cssVar: "--color-text-on-foreground",
    id: "color.text.onForeground",
    type: "color",
    tier: "semantic",
    stability: "wip",
    cssOutputFile: "modifiers.theme.css",
    isPaired: true,
    valueLight: "oklch(100% 0 0)",
    valueDark: "oklch(12.21% 0 0)",
  },
  {
    cssVar: "--color-icon-default",
    id: "color.icon.default",
    type: "color",
    tier: "semantic",
    stability: "wip",
    cssOutputFile: "modifiers.theme.css",
    isPaired: true,
    valueLight: "oklch(12.21% 0 0)",
    valueDark: "oklch(100% 0 0)",
  },
  {
    cssVar: "--color-icon-muted",
    id: "color.icon.muted",
    type: "color",
    tier: "semantic",
    stability: "wip",
    cssOutputFile: "modifiers.theme.css",
    isPaired: true,
    valueLight: "oklch(50% 0 0)",
    valueDark: "oklch(70% 0 0)",
  },
  {
    cssVar: "--color-brand",
    id: "color.brand",
    type: "color",
    tier: "semantic",
    stability: "wip",
    cssOutputFile: "modifiers.theme.css",
    isPaired: true,
    valueLight: "oklch(40% 0.15 30)",
    valueDark: "oklch(60% 0.15 30)",
  },
  {
    cssVar: "--color-foreground-secondary",
    id: "color.foreground.secondary",
    type: "color",
    tier: "semantic",
    stability: "wip",
    cssOutputFile: "modifiers.theme.css",
    isPaired: true,
    valueLight: "oklch(30% 0 0)",
    valueDark: "oklch(80% 0 0)",
  },
  {
    cssVar: "--color-foreground-ghost",
    id: "color.foreground.ghost",
    type: "color",
    tier: "semantic",
    stability: "wip",
    cssOutputFile: "modifiers.theme.css",
    isPaired: true,
    valueLight: "oklch(95% 0 0)",
    valueDark: "oklch(20% 0 0)",
  },
  {
    cssVar: "--color-foreground-input",
    id: "color.foreground.input",
    type: "color",
    tier: "semantic",
    stability: "wip",
    cssOutputFile: "modifiers.theme.css",
    isPaired: true,
    valueLight: "oklch(100% 0 0)",
    valueDark: "oklch(15% 0 0)",
  },
  {
    cssVar: "--color-border-subtle",
    id: "color.border.subtle",
    type: "color",
    tier: "semantic",
    stability: "wip",
    cssOutputFile: "modifiers.theme.css",
    isPaired: true,
    valueLight: "oklch(90% 0 0)",
    valueDark: "oklch(20% 0 0)",
  },
  {
    cssVar: "--color-border-strong",
    id: "color.border.strong",
    type: "color",
    tier: "semantic",
    stability: "wip",
    cssOutputFile: "modifiers.theme.css",
    isPaired: true,
    valueLight: "oklch(50% 0 0)",
    valueDark: "oklch(60% 0 0)",
  },
  {
    cssVar: "--color-border-input",
    id: "color.border.input",
    type: "color",
    tier: "semantic",
    stability: "wip",
    cssOutputFile: "modifiers.theme.css",
    isPaired: true,
    valueLight: "oklch(70% 0 0)",
    valueDark: "oklch(40% 0 0)",
  },
  {
    cssVar: "--modifier-color-text",
    id: null,
    type: "color",
    tier: "derived",
    stability: "wip",
    cssOutputFile: "modifiers.criticality.css",
    isPaired: false,
    derivedFrom: "--color-text",
    derivation: "channel-modifier",
  },
  {
    cssVar: "--modifier-color-foreground-primary",
    id: null,
    type: "color",
    tier: "derived",
    stability: "wip",
    cssOutputFile: "modifiers.criticality.css",
    isPaired: false,
    derivedFrom: "--color-foreground-primary",
    derivation: "channel-modifier",
  },
  {
    cssVar: "--surface-color-background",
    id: null,
    type: "color",
    tier: "derived",
    stability: "wip",
    cssOutputFile: "modifiers.surfaces.css",
    isPaired: false,
    derivedFrom: "--color-background",
    derivation: "channel-surface",
  },
  {
    cssVar: "--surface-color-foreground-ghost",
    id: null,
    type: "color",
    tier: "derived",
    stability: "wip",
    cssOutputFile: "modifiers.surfaces.css",
    isPaired: false,
    derivedFrom: "--color-foreground-ghost",
    derivation: "channel-surface",
  },
  {
    cssVar: "--hover--color-foreground-primary",
    id: null,
    type: "color",
    tier: "derived",
    stability: "experimental",
    cssOutputFile: "states.css",
    isPaired: false,
    derivedFrom: "--color-foreground-primary",
    derivation: "hover",
  },
  {
    cssVar: "--active--color-foreground-primary",
    id: null,
    type: "color",
    tier: "derived",
    stability: "experimental",
    cssOutputFile: "states.css",
    isPaired: false,
    derivedFrom: "--color-foreground-primary",
    derivation: "active",
  },
  {
    cssVar: "--disabled--color-foreground-primary",
    id: null,
    type: "color",
    tier: "derived",
    stability: "experimental",
    cssOutputFile: "states.css",
    isPaired: false,
    derivedFrom: "--color-foreground-primary",
    derivation: "disabled",
  },
  {
    cssVar: "--delta-hover-color-foreground-primary",
    id: null,
    type: "number",
    tier: "derived",
    stability: "experimental",
    cssOutputFile: "modifiers.theme.css",
    isPaired: true,
    valueLight: "0.06",
    valueDark: "-0.04",
    derivedFrom: "--color-foreground-primary",
    derivation: "delta",
  },
];
