// Generated by @canonical/summon-component:react v0.1.0

import type React from "react";
import type { JourneyTableProps } from "./types.js";
import "./styles.css";

const componentCssClassName = "ds journey-table";

/**
 * JourneyTable component
 */
const JourneyTable = ({
	className,
	children,
	...props
}: JourneyTableProps): React.ReactElement => {
	return (
		<div
			className={[componentCssClassName, className].filter(Boolean).join(" ")}
			{...props}
		>
			{children}
		</div>
	);
};

export default JourneyTable;
