// Generated by @canonical/summon-component:react v0.1.0

import { describe, expect, it } from "vitest";
import { renderToString } from "react-dom/server";
import JourneyTable from "./JourneyTable.js";

describe("JourneyTable SSR", () => {
	it("renders without hydration errors", () => {
		const html = renderToString(<JourneyTable>Test content</JourneyTable>);
		expect(html).toContain("Test content");
		expect(html).toContain("ds journey-table");
	});
});
