// Generated by @canonical/summon-component:lit v0.1.0

import { html, LitElement } from "lit";
import { customElement, property } from "lit/decorators.js";
import { classMap } from "lit/directives/class-map.js";
import { when } from "lit/directives/when.js";
import styles from "./styles.css";
import type { HeroProps } from "./types.js";

const componentCssClassName = "ds hero";

/**
 * Hero is a prominent full-width banner pattern used at the top of pages to
 * introduce key content and drive user action. It employs a two-column grid
 * layout, a content column on one side and an optional media column on the
 * other.
 *
 * @slot cta - Optional call-to-action content displayed below the description.
 *
 * @implements ds:global.component.hero
 */
@customElement("ds-hero")
export default class Hero extends LitElement implements HeroProps {
  static styles = styles;

  @property({ type: String }) title = "";
  @property({ type: String }) description = "";
  @property({ type: String, reflect: true }) layout: "side" | "stacked" =
    "side";
  @property({ attribute: false }) media?: HeroProps["media"];

  render() {
    const classes = {
      [componentCssClassName]: true,
      "no-media": !this.media,
    };
    return html`
      <section class=${classMap(classes)}>
        <div class="content">
          <div class="header">
            <h1>${this.title}</h1>
          </div>
          <div class="body">
            ${when(this.description, () => html`<p class="description">${this.description}</p>`)}
            <slot name="cta"></slot>
          </div>
        </div>
        <div class="media">
          ${when(
            this.media,
            (media) => html`
              <img
                src=${media.src}
                alt=${media.alt}
                width=${media.width ?? ""}
                height=${media.height ?? ""}
                sizes=${media.sizes ?? ""}
                loading="lazy"
              >
            `,
          )}
        </div>
      </section>
    `;
  }
}
