// Generated by @canonical/summon:component-webcomponents v0.1.0

import { html, LitElement } from "lit";
import { customElement, property, state } from "lit/decorators.js";
import { when } from "lit/directives/when.js";
import styles from "./styles.css";
import type { HeroProps } from "./types.js";

const componentCssClassName = "ds hero";

/**
 * Hero is a prominent full-width banner pattern used at the top of pages to
 * introduce key content and drive user action. It employs a two-column grid
 * layout, a content column on one side and an optional media column on the
 * other.
 *
 * @slot cta - Optional call-to-action content displayed below the description.
 *
 * @implements ds:global.component.hero
 */
@customElement("ds-hero")
export default class Hero extends LitElement implements HeroProps {
  static styles = styles;

  @property({ type: String }) title = "";
  @property({ type: String }) description = "";

  @state() private _hasMedia = false;

  private _onMediaSlotChange(e: Event) {
    const slot = e.target as HTMLSlotElement;
    this._hasMedia = slot.assignedElements().length > 0;
  }

  render() {
    return html`
      <section class=${componentCssClassName + (this._hasMedia ? "" : " no-media")}>
        <div class="content">
          <div class="header">
            <h1>${this.title}</h1>
          </div>
          <div class="body">
            ${when(this.description, () => html`<p class="description">${this.description}</p>`)}
            <slot name="cta"></slot>
          </div>
        </div>
        <div class="media" ?hidden=${!this._hasMedia}>
          <slot name="media" @slotchange=${this._onMediaSlotChange}></slot>
        </div>
      </section>
    `;
  }
}
