// Generated by @canonical/summon-component-lit v0.1.0

import type { Meta, StoryObj } from "@storybook/web-components-vite";
import { html } from "lit";

import "./Hero.js";
import type Hero from "./Hero.js";
import "../SiteLayout/SiteLayout.js";
import "../Button/Button.js";

const meta = {
  title: "Web Components/Hero",
  tags: ["autodocs"],
  parameters: {
    layout: "fullscreen",
  },
  decorators: [
    (story) => html`
			<ds-site-layout>
				${story()}
			</ds-site-layout>
		`,
  ],
} satisfies Meta<Hero>;

export default meta;
type Story = StoryObj<Hero>;

export const Default: Story = {
  render: () =>
    html`
      <ds-hero title="Scale out with Ubuntu Server"
        description="Ubuntu Server brings economic and technical scalability to your enterprise data center, public or private cloud. Whether you want to deploy an OpenStack cloud, a Kubernetes cluster, or a 50,000-node render farm, Ubuntu Server delivers the best value scale-out performance available."
      >
        <div slot="cta">
          <hr/>
          <ds-button class="constructive">Download Ubuntu Server</ds-button>
        </div>
        <img slot="media" src="https://assets.ubuntu.com/v1/a1dd867d-hero.jpg" alt="Canonical data centre">
      </ds-hero>`,
};

export const NoMedia: Story = {
  render: () =>
    html`
      <ds-hero title="Ubuntu leads in hyperscale"
        description="Ubuntu is the hyperscale OS, natively powering scale-out workloads on a new wave of low-cost, ultra-dense hardware based on x86 and ARM processors."
      >
        <div slot="cta">
          <hr/>
          <ds-button class="constructive">Download Ubuntu Server</ds-button>
          <a href="#">Download Ubuntu for ARM ›</a>
        </div>
      </ds-hero>`,
};
