// Generated by @canonical/summon-component:lit v0.1.0

/**
 * Props for the Hero component.
 */
export type HeroProps = {
  /** Heading text for the section. */
  title?: string;
  /** Descriptive text displayed beside the heading. */
  description?: string;
  /** Layout variant when media is present. "side" places media beside content (default), "stacked" places media below content at full width. */
  layout?: "side" | "stacked";
};
