// Generated by @canonical/summon-component:react v0.1.0

import type React from "react";
import type { StandardArticleProps } from "./types.js";
import "./styles.css";

const componentCssClassName = "ds standard-article";

/**
 * StandardArticle component
 */
const StandardArticle = ({
  className,
  children,
  ...props
}: StandardArticleProps): React.ReactElement => {
  return (
    <div
      className={[componentCssClassName, className].filter(Boolean).join(" ")}
      {...props}
    >
      {children}
    </div>
  );
};

export default StandardArticle;
