// Generated by @canonical/summon-component:react v0.1.0

import type { Meta, StoryObj } from "@storybook/react-vite";
import StandardArticle from "./StandardArticle.js";

const meta: Meta<typeof StandardArticle> = {
  title: "Components/StandardArticle",
  component: StandardArticle,
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof StandardArticle>;

export const Default: Story = {
  args: {
    children: "Hello, StandardArticle!",
  },
};

export const WithCustomClass: Story = {
  args: {
    children: "Custom styled",
    className: "custom-class",
  },
};
