<!-- Generated by @canonical/summon-component:svelte v0.1.0 -->

<script lang="ts">
  import type { AnnouncementProps } from "./types.js";
  import "./styles.css";

  const componentCssClassName = "ds announcement";

  let {
    criticality = "information",
    heading,
    children,
    class: className,
    ...rest
  }: AnnouncementProps = $props();
</script>

<div
  class={[componentCssClassName, criticality, className]}
  {...rest}
>
  <span class="icon" aria-hidden="true"></span>
  <span class="text">
    {#if heading != null}
      <span class="heading">{heading}</span>
    {/if}
    <span class="content">
      {@render children()}
    </span>
  </span>
</div>

<!-- @component
The `Announcement` component is a persistent, high-visibility UI block used to
communicate time-sensitive or critical contextual information directly within a
page. It is not triggered by specific system or user events; instead, it is a
non-transient call-out used for broad organisational updates, compliance
warnings, or upcoming deadlines.

`import { Announcement } from "@canonical/svelte-ds-app-wpe";`

## Example Usage
```svelte
<Announcement criticality="information" heading="System Maintenance">
  Maintenance is scheduled for tonight from 11 PM - 2 AM PST.
  Some services may be unavailable.
</Announcement>
```

### Rich content in the heading
For markup inside the heading, fold it into `children` instead — there is
no separate heading snippet. The `heading` prop is intentionally `string`
only so it stays controllable via Storybook args.

@implements ds:global.component.announcement
-->
