import type { ShellId } from "./detectShell.js";

const HOME = process.env.HOME ?? "";

/**
 * Generate the shell-specific completion script content.
 *
 * Each script delegates to `pragma completions <shell>` at runtime
 * so the completion logic stays in the CLI, not in the shell script.
 *
 * @param shell - Target shell identifier.
 * @returns The completion script content as a string.
 */
export function completionScriptContent(shell: ShellId): string {
  switch (shell) {
    case "zsh":
      return [
        "#compdef pragma",
        "# Generated by `pragma setup completions`",
        "",
        "_pragma() {",
        "  local -a completions",
        // biome-ignore lint/suspicious/noTemplateCurlyInString: shell syntax, not JS template
        '  completions=("${(@f)$(pragma completions zsh -- "${words[@]}" 2>/dev/null)}")',
        "  compadd -- $completions",
        "}",
        "",
        "compdef _pragma pragma",
        "",
      ].join("\n");

    case "bash":
      return [
        "# Generated by `pragma setup completions`",
        "",
        "_pragma() {",
        // biome-ignore lint/suspicious/noTemplateCurlyInString: shell syntax, not JS template
        '  local cur="${COMP_WORDS[COMP_CWORD]}"',
        "  local completions",
        // biome-ignore lint/suspicious/noTemplateCurlyInString: shell syntax, not JS template
        '  completions=$(pragma completions bash -- "${COMP_WORDS[@]}" 2>/dev/null)',
        "  # shellcheck disable=SC2207",
        '  COMPREPLY=($(compgen -W "$completions" -- "$cur"))',
        "}",
        "",
        "complete -F _pragma pragma",
        "",
      ].join("\n");

    case "fish":
      return [
        "# Generated by `pragma setup completions`",
        "",
        "complete -c pragma -f -a '(pragma completions fish -- (commandline -cop) 2>/dev/null)'",
        "",
      ].join("\n");
  }
}

/**
 * Return the standard filesystem path where the completion script should be installed.
 *
 * @param shell - Target shell identifier.
 * @returns Absolute path to the completion script location.
 */
export function completionScriptPath(shell: ShellId): string {
  switch (shell) {
    case "zsh":
      return `${HOME}/.zfunc/_pragma`;
    case "bash":
      return `${HOME}/.local/share/bash-completion/completions/pragma`;
    case "fish":
      return `${HOME}/.config/fish/completions/pragma.fish`;
  }
}

/**
 * Return a post-install hint instructing the user how to activate completions.
 *
 * @param shell - Target shell identifier.
 * @returns A human-readable activation hint.
 */
export function postInstallHint(shell: ShellId): string {
  switch (shell) {
    case "zsh":
      return "Run `source ~/.zshrc` or start a new shell to activate.";
    case "bash":
      return "Run `source ~/.bashrc` or start a new shell to activate.";
    case "fish":
      return "Start a new shell to activate.";
  }
}
