/**
 * Font registry – consumed by sidebar.js.
 *
 * Each entry carries the three metric values the baseline engine needs
 * (ascender, descender, unitsPerEm) as extracted by `extractFontData.ts`.
 *
 * `source` tells the loader how to make the font available:
 *   - "local"  → a @font-face is injected pointing at `file`
 *   - "google" → a <link> is injected with the Google Fonts `url`
 *
 * All Ubuntu Sans variants share the same vertical metrics (940 / -260 / 1000).
 * Inter, Roboto, and each Google Font have their own distinct metrics.
 */
export const fonts = [
  // ── Ubuntu Sans family (local) ────────────────────────────────
  {
    name: "Ubuntu Sans Regular",
    family: "Ubuntu Sans",
    source: "local",
    file: "./fonts/UbuntuSans-Regular.woff2",
    weight: 400,
    style: "normal",
    metrics: { ascender: 940, descender: -260, unitsPerEm: 1000 },
  },
  {
    name: "Ubuntu Sans Bold",
    family: "Ubuntu Sans Bold",
    source: "local",
    file: "./fonts/UbuntuSans-Bold.woff2",
    weight: 700,
    style: "normal",
    metrics: { ascender: 940, descender: -260, unitsPerEm: 1000 },
  },
  {
    name: "Ubuntu Sans Italic",
    family: "Ubuntu Sans Italic",
    source: "local",
    file: "./fonts/UbuntuSans-Italic.woff2",
    weight: 400,
    style: "italic",
    metrics: { ascender: 940, descender: -260, unitsPerEm: 1000 },
  },
  {
    name: "Ubuntu Sans Bold Italic",
    family: "Ubuntu Sans Bold Italic",
    source: "local",
    file: "./fonts/UbuntuSans-BoldItalic.woff2",
    weight: 700,
    style: "italic",
    metrics: { ascender: 940, descender: -260, unitsPerEm: 1000 },
  },
  {
    name: "Ubuntu Sans Light",
    family: "Ubuntu Sans Light",
    source: "local",
    file: "./fonts/UbuntuSans-Light.woff2",
    weight: 300,
    style: "normal",
    metrics: { ascender: 940, descender: -260, unitsPerEm: 1000 },
  },
  {
    name: "Ubuntu Sans Medium",
    family: "Ubuntu Sans Medium",
    source: "local",
    file: "./fonts/UbuntuSans-Medium.woff2",
    weight: 500,
    style: "normal",
    metrics: { ascender: 940, descender: -260, unitsPerEm: 1000 },
  },

  // ── Ubuntu Sans Condensed (local) ────────────────────────────
  {
    name: "Ubuntu Sans Condensed",
    family: "Ubuntu Sans Condensed",
    source: "local",
    file: "./fonts/UbuntuSansCondensed-Regular.woff2",
    weight: 400,
    style: "normal",
    metrics: { ascender: 940, descender: -260, unitsPerEm: 1000 },
  },
  {
    name: "Ubuntu Sans Condensed Bold",
    family: "Ubuntu Sans Condensed Bold",
    source: "local",
    file: "./fonts/UbuntuSansCondensed-Bold.woff2",
    weight: 700,
    style: "normal",
    metrics: { ascender: 940, descender: -260, unitsPerEm: 1000 },
  },

  // ── Inter (local) ────────────────────────────────────────────
  {
    name: "Inter",
    family: "Inter",
    source: "local",
    file: "./fonts/Inter-Regular.woff2",
    weight: 400,
    style: "normal",
    metrics: { ascender: 1984, descender: -494, unitsPerEm: 2048 },
  },

  // ── Google Fonts (remote) ────────────────────────────────────
  {
    name: "Open Sans",
    family: "Open Sans",
    source: "google",
    url: "https://fonts.googleapis.com/css2?family=Open+Sans:wght@400&display=swap",
    weight: 400,
    style: "normal",
    metrics: { ascender: 2189, descender: -600, unitsPerEm: 2048 },
  },
  {
    name: "Roboto",
    family: "Roboto",
    source: "google",
    url: "https://fonts.googleapis.com/css2?family=Roboto:wght@400&display=swap",
    weight: 400,
    style: "normal",
    metrics: { ascender: 1900, descender: -500, unitsPerEm: 2048 },
  },
  {
    name: "Lato",
    family: "Lato",
    source: "google",
    url: "https://fonts.googleapis.com/css2?family=Lato:wght@400&display=swap",
    weight: 400,
    style: "normal",
    metrics: { ascender: 940, descender: -260, unitsPerEm: 1000 },
  },
  {
    name: "Montserrat",
    family: "Montserrat",
    source: "google",
    url: "https://fonts.googleapis.com/css2?family=Montserrat:wght@400&display=swap",
    weight: 400,
    style: "normal",
    metrics: { ascender: 968, descender: -251, unitsPerEm: 1000 },
  },
  {
    name: "Poppins",
    family: "Poppins",
    source: "google",
    url: "https://fonts.googleapis.com/css2?family=Poppins:wght@400&display=swap",
    weight: 400,
    style: "normal",
    metrics: { ascender: 1050, descender: -350, unitsPerEm: 1000 },
  },
  {
    name: "Oswald",
    family: "Oswald",
    source: "google",
    url: "https://fonts.googleapis.com/css2?family=Oswald:wght@400&display=swap",
    weight: 400,
    style: "normal",
    metrics: { ascender: 1193, descender: -289, unitsPerEm: 1000 },
  },
  {
    name: "Raleway",
    family: "Raleway",
    source: "google",
    url: "https://fonts.googleapis.com/css2?family=Raleway:wght@400&display=swap",
    weight: 400,
    style: "normal",
    metrics: { ascender: 940, descender: -234, unitsPerEm: 1000 },
  },
  {
    name: "Merriweather",
    family: "Merriweather",
    source: "google",
    url: "https://fonts.googleapis.com/css2?family=Merriweather:wght@400&display=swap",
    weight: 400,
    style: "normal",
    metrics: { ascender: 1968, descender: -546, unitsPerEm: 2000 },
  },
  {
    name: "Nunito",
    family: "Nunito",
    source: "google",
    url: "https://fonts.googleapis.com/css2?family=Nunito:wght@400&display=swap",
    weight: 400,
    style: "normal",
    metrics: { ascender: 1011, descender: -353, unitsPerEm: 1000 },
  },
  {
    name: "Playfair Display",
    family: "Playfair Display",
    source: "google",
    url: "https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400&display=swap",
    weight: 400,
    style: "normal",
    metrics: { ascender: 1082, descender: -251, unitsPerEm: 1000 },
  },
  {
    name: "PT Sans",
    family: "PT Sans",
    source: "google",
    url: "https://fonts.googleapis.com/css2?family=PT+Sans:wght@400&display=swap",
    weight: 400,
    style: "normal",
    metrics: { ascender: 1018, descender: -276, unitsPerEm: 1000 },
  },
  {
    name: "Source Sans 3",
    family: "Source Sans 3",
    source: "google",
    url: "https://fonts.googleapis.com/css2?family=Source+Sans+3:wght@400&display=swap",
    weight: 400,
    style: "normal",
    metrics: { ascender: 1024, descender: -400, unitsPerEm: 1000 },
  },
  {
    name: "Noto Sans",
    family: "Noto Sans",
    source: "google",
    url: "https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400&display=swap",
    weight: 400,
    style: "normal",
    metrics: { ascender: 1069, descender: -293, unitsPerEm: 1000 },
  },
  {
    name: "Mukta",
    family: "Mukta",
    source: "google",
    url: "https://fonts.googleapis.com/css2?family=Mukta:wght@400&display=swap",
    weight: 400,
    style: "normal",
    metrics: { ascender: 1130, descender: -532, unitsPerEm: 1000 },
  },
  {
    name: "Rubik",
    family: "Rubik",
    source: "google",
    url: "https://fonts.googleapis.com/css2?family=Rubik:wght@400&display=swap",
    weight: 400,
    style: "normal",
    metrics: { ascender: 935, descender: -250, unitsPerEm: 1000 },
  },
  {
    name: "Work Sans",
    family: "Work Sans",
    source: "google",
    url: "https://fonts.googleapis.com/css2?family=Work+Sans:wght@400&display=swap",
    weight: 400,
    style: "normal",
    metrics: { ascender: 930, descender: -243, unitsPerEm: 1000 },
  },
  {
    name: "Nunito Sans",
    family: "Nunito Sans",
    source: "google",
    url: "https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400&display=swap",
    weight: 400,
    style: "normal",
    metrics: { ascender: 1011, descender: -353, unitsPerEm: 1000 },
  },
  {
    name: "Fira Sans",
    family: "Fira Sans",
    source: "google",
    url: "https://fonts.googleapis.com/css2?family=Fira+Sans:wght@400&display=swap",
    weight: 400,
    style: "normal",
    metrics: { ascender: 935, descender: -265, unitsPerEm: 1000 },
  },
  {
    name: "Quicksand",
    family: "Quicksand",
    source: "google",
    url: "https://fonts.googleapis.com/css2?family=Quicksand:wght@400&display=swap",
    weight: 400,
    style: "normal",
    metrics: { ascender: 1000, descender: -250, unitsPerEm: 1000 },
  },
  {
    name: "Barlow",
    family: "Barlow",
    source: "google",
    url: "https://fonts.googleapis.com/css2?family=Barlow:wght@400&display=swap",
    weight: 400,
    style: "normal",
    metrics: { ascender: 1000, descender: -200, unitsPerEm: 1000 },
  },
  {
    name: "Mulish",
    family: "Mulish",
    source: "google",
    url: "https://fonts.googleapis.com/css2?family=Mulish:wght@400&display=swap",
    weight: 400,
    style: "normal",
    metrics: { ascender: 1005, descender: -250, unitsPerEm: 1000 },
  },
  {
    name: "Titillium Web",
    family: "Titillium Web",
    source: "google",
    url: "https://fonts.googleapis.com/css2?family=Titillium+Web:wght@400&display=swap",
    weight: 400,
    style: "normal",
    metrics: { ascender: 1133, descender: -388, unitsPerEm: 1000 },
  },

  // ── IBM Plex family (Google Fonts) ─────────────────────────────
  {
    name: "IBM Plex Sans",
    family: "IBM Plex Sans",
    source: "google",
    url: "https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400&display=swap",
    weight: 400,
    style: "normal",
    metrics: { ascender: 1025, descender: -275, unitsPerEm: 1000 },
  },
  {
    name: "IBM Plex Sans Light",
    family: "IBM Plex Sans",
    source: "google",
    url: "https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@300&display=swap",
    weight: 300,
    style: "normal",
    metrics: { ascender: 1025, descender: -275, unitsPerEm: 1000 },
  },
  {
    name: "IBM Plex Sans Medium",
    family: "IBM Plex Sans",
    source: "google",
    url: "https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@500&display=swap",
    weight: 500,
    style: "normal",
    metrics: { ascender: 1025, descender: -275, unitsPerEm: 1000 },
  },
  {
    name: "IBM Plex Sans Bold",
    family: "IBM Plex Sans",
    source: "google",
    url: "https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@700&display=swap",
    weight: 700,
    style: "normal",
    metrics: { ascender: 1025, descender: -275, unitsPerEm: 1000 },
  },
  {
    name: "IBM Plex Sans Italic",
    family: "IBM Plex Sans",
    source: "google",
    url: "https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@1,400&display=swap",
    weight: 400,
    style: "italic",
    metrics: { ascender: 1025, descender: -275, unitsPerEm: 1000 },
  },
  {
    name: "IBM Plex Mono",
    family: "IBM Plex Mono",
    source: "google",
    url: "https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400&display=swap",
    weight: 400,
    style: "normal",
    metrics: { ascender: 1025, descender: -275, unitsPerEm: 1000 },
  },
  {
    name: "IBM Plex Serif",
    family: "IBM Plex Serif",
    source: "google",
    url: "https://fonts.googleapis.com/css2?family=IBM+Plex+Serif:wght@400&display=swap",
    weight: 400,
    style: "normal",
    metrics: { ascender: 1025, descender: -275, unitsPerEm: 1000 },
  },
];
