// Generated by @canonical/summon-component:react v0.1.0

import { describe, expect, it } from "vitest";
import { render, screen } from "@testing-library/react";
import Header from "./Header.js";

describe("Header", () => {
	it("renders children", () => {
		render(<Header>Test content</Header>);
		expect(screen.getByText("Test content")).toBeInTheDocument();
	});

	it("applies custom className", () => {
		render(<Header className="custom-class">Content</Header>);
		const element = screen.getByText("Content");
		expect(element.className).toContain("ds header");
		expect(element.className).toContain("custom-class");
	});

	it("passes through additional props", () => {
		render(<Header data-testid="test-component">Content</Header>);
		expect(screen.getByTestId("test-component")).toBeInTheDocument();
	});
});
