// Generated by @canonical/summon-component:react v0.1.0

import type React from "react";
import { CollapseToggle } from "../CollapseToggle/index.js";
import type { HeaderProps } from "./types.js";
import "./styles.css";

const componentCssClassName = "ds header";

/**
 * SideNavigation.Header — top region holding the brand (children, at the start)
 * and the collapse toggle (at the end). The toggle is omitted when no
 * `onToggle` handler is provided.
 *
 * @implements ds:apps.subcomponent.side-navigation-header
 */
const Header = ({
  className,
  children,
  expanded,
  onToggle,
  collapseControls,
  ...props
}: HeaderProps): React.ReactElement => {
  return (
    <div
      className={[componentCssClassName, className].filter(Boolean).join(" ")}
      {...props}
    >
      <div className="brand">{children}</div>
      {onToggle && (
        <CollapseToggle
          expanded={expanded}
          aria-controls={collapseControls}
          onClick={onToggle}
        />
      )}
    </div>
  );
};

export default Header;
