// Generated by @canonical/summon-component:react v0.1.0

import type { Meta, StoryObj } from "@storybook/react-vite";
import Header from "./Header.js";

const meta: Meta<typeof Header> = {
	title: "Components/SideNavigation/Header",
	component: Header,
	tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof Header>;

export const Default: Story = {
	args: {
		children: "Hello, Header!",
	},
};

export const WithCustomClass: Story = {
	args: {
		children: "Custom styled",
		className: "custom-class",
	},
};
