// Generated by @canonical/summon-component:react v0.1.0

import { renderToString } from "react-dom/server";
import { describe, expect, it } from "vitest";
import Header from "./Header.js";

describe("Header SSR", () => {
  it("renders without hydration errors", () => {
    const html = renderToString(<Header brand="Test content" />);
    expect(html).toContain("Test content");
    expect(html).toContain("ds side-navigation-header");
  });
});
