<script lang="ts" module>
  // Generated by @canonical/summon:component-svelte v0.1.0
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import Chip from "./Chip.svelte";
  import { fn } from "storybook/test";
  import { MODIFIER_FAMILIES } from "../../modifier-families";
  import { ArchiveIcon } from "@canonical/svelte-icons";

  const { Story } = defineMeta({
    title: "Components/Chip",
    component: Chip,
    tags: ["autodocs"],
  });
</script>

<Story
  name="Default interactive chip"
  args={{
    value: "Value",
    onclick: fn(),
  }}
/>

<Story name="Severities">
  {#snippet template(args)}
    {#each MODIFIER_FAMILIES.severity as severity (severity)}
      <Chip
        {...args}
        lead="Severity"
        value={severity}
        {severity}
        onclick={fn()}
      />
      <br />
      <br />
    {/each}
  {/snippet}
</Story>

<Story
  name="With icon and lead"
  args={{
    lead: "Lead",
    value: "Value",
    severity: "caution",
  }}
>
  {#snippet template(args)}
    <Chip {...args}>
      {#snippet icon()}
        <ArchiveIcon />
      {/snippet}
    </Chip>
  {/snippet}
</Story>

<Story
  name="Dismissable chip"
  args={{
    lead: "Owner",
    value: "Bob",
    ondismiss: fn(),
  }}
/>

<Story
  name="With a badge"
  args={{
    lead: "Lead",
    value: "Value",
  }}
>
  {#snippet template(args)}
    <Chip {...args}>
      {#snippet badge()}
        <!-- TODO: uncomment once Badge is upstreamed -->
        <!-- <Badge value={42} /> -->
      {/snippet}
    </Chip>
  {/snippet}
</Story>

<Story name="Read-only">
  {#snippet template(args)}
    {#each [undefined, ...MODIFIER_FAMILIES.severity] as severity (severity)}
      <Chip
        {...args}
        lead="Severity"
        value={severity || "default"}
        readonly
        {severity}
      >
        <!-- TODO: uncomment once Badge is upstreamed -->
        <!-- {#snippet badge()} -->
        <!-- <Badge value={420} /> -->
        <!-- {/snippet} -->
      </Chip>
      <br />
      <br />
    {/each}
  {/snippet}
</Story>

<Story
  name="With all the elements"
  tags={["!autodocs"]}
  args={{
    lead: "Lead",
    value: "Value",
    ondismiss: fn(),
    onclick: fn(),
  }}
>
  {#snippet template(args)}
    <Chip {...args}>
      {#snippet icon()}
        <ArchiveIcon />
      {/snippet}
      <!-- TODO: uncomment once Badge is upstreamed -->
      <!-- {#snippet badge()} -->
      <!-- <Badge value={420} /> -->
      <!-- {/snippet} -->
    </Chip>
  {/snippet}
</Story>
