<!-- Generated by @canonical/summon:component-svelte v0.1.0 -->

<script lang="ts">
  import { CloseIcon } from "@canonical/svelte-icons";
  import type { ChipProps } from "./types";
  import "./styles.css";

  const componentCssClassName = "ds chip";

  const {
    class: className,
    density,
    severity,
    readonly,
    lead,
    value,
    icon,
    badge,
    ondismiss,
    onclick,
    ...rest
  }: ChipProps = $props();

  const dismissible = $derived(ondismiss !== undefined);
  const clickable = $derived(onclick !== undefined);

  const rootElement = $derived(
    dismissible || readonly || !clickable ? "span" : "button",
  );
</script>

<svelte:element
  this={rootElement}
  class={[componentCssClassName, className, density, severity, { readonly }]}
  type={rootElement === "button" ? "button" : undefined}
  {onclick}
  {...rest}
>
  {#if icon}
    <span class="icon">
      {@render icon()}
    </span>
  {/if}
  {#if lead}
    <span class="lead">
      {lead}
    </span>
  {/if}
  <span class="value">
    {value}
  </span>
  {#if badge}
    <span class="badge">
      {@render badge()}
    </span>
  {/if}
  {#if dismissible}
    <button
      class="dismiss"
      onclick={ondismiss}
      aria-label="Dismiss"
      type="button"
    >
      <CloseIcon class="dismiss-icon" />
    </button>
  {/if}
</svelte:element>

<!-- @component
`Chip` displays a small actionable pieces of information.

## Example Usage
```svelte
<Chip value="Value"/>
<Chip lead="Lead" value="Value" />
<Chip lead="Lead" value="Value" severity="caution" />
<Chip
  lead="Lead"
  value="Value"
  readonly
  density="dense"
  severity="caution"
/>
```
-->
