// Generated by @canonical/summon-component:react v0.1.0

import type { Meta, StoryObj } from "@storybook/react-vite";
import TermInspector from "./TermInspector.js";

const meta: Meta<typeof TermInspector> = {
  title: "Components/TermInspector",
  component: TermInspector,
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof TermInspector>;

export const Default: Story = {
  args: {
    children: "Hello, TermInspector!",
  },
};

export const WithCustomClass: Story = {
  args: {
    children: "Custom styled",
    className: "custom-class",
  },
};
