// Generated by @canonical/summon-component:react v0.1.0

import { renderToString } from "react-dom/server";
import { describe, expect, it } from "vitest";
import TermInspector from "./TermInspector.js";

describe("TermInspector SSR", () => {
  it("renders without hydration errors", () => {
    const html = renderToString(<TermInspector>Test content</TermInspector>);
    expect(html).toContain("Test content");
    expect(html).toContain("ds term-inspector");
  });
});
