// Generated by @canonical/summon-component:react v0.1.0

import type React from "react";
import type { JourneysPageProps } from "./types.js";
import "./styles.css";

const componentCssClassName = "ds journeys-page";

/**
 * JourneysPage component
 */
const JourneysPage = ({
  className,
  children,
  ...props
}: JourneysPageProps): React.ReactElement => {
  return (
    <div
      className={[componentCssClassName, className].filter(Boolean).join(" ")}
      {...props}
    >
      {children}
    </div>
  );
};

export default JourneysPage;
