// Generated by @canonical/summon-component:react v0.1.0

import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import JourneysPage from "./JourneysPage.js";

describe("JourneysPage", () => {
  it("renders children", () => {
    render(<JourneysPage>Test content</JourneysPage>);
    expect(screen.getByText("Test content")).toBeInTheDocument();
  });

  it("applies custom className", () => {
    render(<JourneysPage className="custom-class">Content</JourneysPage>);
    const element = screen.getByText("Content");
    expect(element.className).toContain("ds journeys-page");
    expect(element.className).toContain("custom-class");
  });

  it("passes through additional props", () => {
    render(<JourneysPage data-testid="test-component">Content</JourneysPage>);
    expect(screen.getByTestId("test-component")).toBeInTheDocument();
  });
});
