// Generated by @canonical/summon-component:svelte v0.1.0

import type { Snippet } from "svelte";
import type { SvelteHTMLElements } from "svelte/elements";

type BaseProps = SvelteHTMLElements["kbd"];

export interface KeyboardKeysProps extends BaseProps {
  /** The keyboard keys (and any separator text) to group together */
  children?: Snippet;
}
