// Generated by @canonical/summon-component:react v0.1.0

import { renderToString } from "react-dom/server";
import { describe, expect, it } from "vitest";
import Option from "./Option.js";

describe("RichChoices Option SSR", () => {
  it("renders without hydration errors", () => {
    const html = renderToString(
      <Option
        name="group"
        type="radio"
        option={{ value: "a", label: "Option A" }}
        checked={false}
        disabled={false}
        onChange={() => {}}
      />,
    );
    expect(html).toContain("Option A");
    expect(html).toContain("ds option");
  });
});
