// Generated by @canonical/summon-component:react v0.1.0

import type { Meta, StoryObj } from "@storybook/react-vite";
import Option from "./Option.js";

const meta: Meta<typeof Option> = {
  title: "components/RichChoicesField/Option",
  component: Option,
  decorators: [
    (Story) => (
      <fieldset className="ds form-rich-choices" style={{ border: "none" }}>
        <Story />
      </fieldset>
    ),
  ],
};

export default meta;
type Story = StoryObj<typeof Option>;

export const Default: Story = {
  args: {
    name: "rich-choices",
    type: "radio",
    option: { value: "a", label: "Option A" },
    checked: false,
    disabled: false,
    onChange: () => {},
  },
};

export const Checked: Story = {
  args: { ...Default.args, checked: true },
};

export const Disabled: Story = {
  args: { ...Default.args, disabled: true },
};
