// Generated by @canonical/summon-component:react v0.1.0

import { renderToString } from "react-dom/server";
import { describe, expect, it } from "vitest";
import ComponentsCatalogPage from "./ComponentsCatalogPage.js";

describe("ComponentsCatalogPage SSR", () => {
  it("renders without hydration errors", () => {
    const html = renderToString(
      <ComponentsCatalogPage>Test content</ComponentsCatalogPage>,
    );
    expect(html).toContain("Test content");
    expect(html).toContain("ds components-catalog-page");
  });
});
