// Generated by @canonical/summon-component:react v0.1.0

import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import ComponentsCatalogPage from "./ComponentsCatalogPage.js";

describe("ComponentsCatalogPage", () => {
  it("renders children", () => {
    render(<ComponentsCatalogPage>Test content</ComponentsCatalogPage>);
    expect(screen.getByText("Test content")).toBeInTheDocument();
  });

  it("applies custom className", () => {
    render(
      <ComponentsCatalogPage className="custom-class">
        Content
      </ComponentsCatalogPage>,
    );
    const element = screen.getByText("Content");
    expect(element.className).toContain("ds components-catalog-page");
    expect(element.className).toContain("custom-class");
  });

  it("passes through additional props", () => {
    render(
      <ComponentsCatalogPage data-testid="test-component">
        Content
      </ComponentsCatalogPage>,
    );
    expect(screen.getByTestId("test-component")).toBeInTheDocument();
  });
});
