/**
 * Build script for the `pragma` compiled binary.
 *
 * Two steps: (1) codegen the embedded template manifest, then (2) compile the
 * CLI entry (`src/bin.ts`) into a standalone executable with `Bun.build`.
 *
 * COMPILED `create` — every binding runs from the shipped binary.
 * `create.verb.ts` reaches summon-core + the generators through STATIC dynamic
 * imports (behind its lazy boundary), so bun's `--compile` bundler includes
 * them. The generators load their templates from disk
 * (`import.meta`-relative), which does not exist in a standalone binary, so
 * this script inlines EVERY declared root's template tree into
 * `create/templates.embedded.generated.ts` — the same
 * inline-strings-survive-`--compile` technique as
 * `graphpack/embedded/pack.generated.ts` — keyed by summon-core's qualified
 * scheme (`component/react/types.ts.ejs`, `package/tsconfig.json.ejs`,
 * `application/react/src/lib/index.ts.ejs`), so sibling basenames never
 * collide and one manifest serves all three packages. The compiled-binary
 * smoke test (create/compiledCreate.subprocess.test.ts) proves each binding
 * byte-identical to a source run.
 */

import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { generators as applicationGenerators } from "@canonical/summon-application";
import { generators as componentGenerators } from "@canonical/summon-component";
import { buildEmbeddedManifest } from "@canonical/summon-core";
import { projectGenerator } from "@canonical/summon-core/projection";
import { generators as packageGenerators } from "@canonical/summon-package";
import { CREATE_GENERATORS } from "../src/capabilities/create/constants.js";
import { capabilities } from "../src/capabilities/index.js";
import { emitReference } from "../src/kernel/spec/emitReference.js";

const scriptsUrl = new URL(".", import.meta.url);

/**
 * EVERY declared template root — the binary carries all of them, so every
 * `create` binding runs from the compiled binary. Prefixes and relative dirs
 * come from {@link CREATE_GENERATORS}; the walking, keying (one scheme with
 * the reader), and the per-root/UTF-8 fail-louds are summon-core's
 * `buildEmbeddedManifest` — this script keeps only host duties
 * (write-when-changed + the generated-module header).
 *
 * Each root is the declared package's source templates dir — the source of
 * truth, identical to that package's dist copy — reached through this
 * package's own `node_modules`, which bun links to the sibling workspace
 * directory. That is a MONOREPO BUILD path, not npm resolution: the published
 * tarballs ship `dist` only (`"files": ["dist"]`), so only a checkout
 * satisfies it.
 */
const TEMPLATE_ROOTS: ReadonlyArray<{ prefix: string; dir: string }> =
  Object.values(CREATE_GENERATORS).flatMap((binding) =>
    binding.templateRoots.map((root) => ({
      prefix: root.prefix,
      dir: fileURLToPath(
        new URL(`../node_modules/${binding.name}/${root.relDir}`, scriptsUrl),
      ),
    })),
  );

const SURFACE_OUT = fileURLToPath(
  new URL("../src/capabilities/create/createSurface.generated.ts", scriptsUrl),
);

/**
 * Project every declared generator binding onto its serializable surface and
 * write `createSurface.generated.ts` — the static data the create surface's
 * params, CLI mount, completion, and MCP schemas all derive from, so the fast
 * path never imports a generator. Deterministic (sorted keys, JSON values);
 * write-only-when-changed. The projection-fidelity test in `create.test.ts`
 * loads the LIVE generators and fails when this file drifts.
 *
 * @returns The number of projected command paths.
 */
function generateCreateSurface(): number {
  const maps: Record<string, Record<string, unknown>> = {
    component: componentGenerators as never,
    package: packageGenerators as never,
    application: applicationGenerators as never,
  };
  const entries: Record<string, unknown> = {};
  for (const [kind, binding] of Object.entries(CREATE_GENERATORS)) {
    for (const commandPath of binding.paths) {
      const generator = maps[kind]?.[commandPath];
      if (!generator) {
        throw new Error(
          `no generator exported for declared path ${commandPath}`,
        );
      }
      entries[commandPath] = projectGenerator(
        commandPath.split("/"),
        generator as never,
      );
    }
  }

  const body = Object.keys(entries)
    .sort()
    .map(
      (key) =>
        `  ${JSON.stringify(key)}: ${JSON.stringify(entries[key], null, 2)
          .split("\n")
          .join("\n  ")},`,
    )
    .join("\n");

  const module = `// AUTO-GENERATED by scripts/build.ts — do not edit by hand.
// Regenerate: \`bun run scripts/build.ts\`. The serializable projection of
// every declared generator binding (\`projectGenerator\` over the live
// generators, captured at build time): the create surface's params, the CLI
// mount, completion, and the MCP schemas all derive from THIS data, so the
// \`--help\`/\`__complete\` fast path never imports a generator. The
// projection-fidelity test in create.test.ts loads the LIVE generators and
// fails when this file drifts; rerunning the build fixes it.

import type { SurfaceCommand } from "@canonical/summon-core/projection";

/** Declared command path → its projected command surface. */
export const CREATE_SURFACE: Readonly<Record<string, SurfaceCommand>> = {
${body}
};
`;
  if (
    !existsSync(SURFACE_OUT) ||
    readFileSync(SURFACE_OUT, "utf-8") !== module
  ) {
    writeFileSync(SURFACE_OUT, module);
  }
  return Object.keys(entries).length;
}

const MANIFEST_OUT = fileURLToPath(
  new URL(
    "../src/capabilities/create/templates.embedded.generated.ts",
    scriptsUrl,
  ),
);

/**
 * Inline every declared root's template tree into the generated manifest
 * module. Deterministic (summon-core sorts the keys; `JSON.stringify` values)
 * so re-running produces byte-identical output — no working-tree churn.
 *
 * @returns The embedded manifest (for counting/reporting).
 */
function generateTemplateManifest(): Record<string, string> {
  const entries = buildEmbeddedManifest(TEMPLATE_ROOTS);

  const body = Object.keys(entries)
    .map((key) => `  ${JSON.stringify(key)}: ${JSON.stringify(entries[key])},`)
    .join("\n");

  // Each declared generator package's version, captured at build time from
  // the same manifest a source run's disk walk finds. The binary injects it
  // (setEmbeddedPackageVersions) so a generator resolving its OWN version —
  // summon-package's fixed-version-train dependency ranges — gets the value
  // the walk cannot reach under /$bunfs.
  const versions = Object.fromEntries(
    Object.values(CREATE_GENERATORS).map((binding) => {
      const manifestPath = fileURLToPath(
        new URL(`../node_modules/${binding.name}/package.json`, scriptsUrl),
      );
      const manifest = JSON.parse(readFileSync(manifestPath, "utf-8")) as {
        version?: string;
      };
      if (!manifest.version) {
        throw new Error(`no version in ${manifestPath}`);
      }
      return [binding.name, manifest.version];
    }),
  );
  const versionsBody = Object.keys(versions)
    .sort()
    .map((key) => `  ${JSON.stringify(key)}: ${JSON.stringify(versions[key])},`)
    .join("\n");

  const module = `// AUTO-GENERATED by scripts/build.ts — do not edit by hand.
// Regenerate: \`bun run scripts/build.ts\`. Inlines every declared generator
// root's template tree (component, package, application — all files, not just
// .ejs) as strings, so every \`pragma create\` binding works from the
// standalone --compile binary (the template files are absent from the binary's
// virtual filesystem). Keys follow summon-core's qualified-key scheme.
/** Qualified template key (\`<prefix>/<path>\`) → file contents. */
export const TEMPLATES: Record<string, string> = {
${body}
};

/** Declared generator package → version, captured at build time. */
export const PACKAGE_VERSIONS: Record<string, string> = {
${versionsBody}
};
`;
  // Write only when changed: the output is deterministic, so a rebuild is a
  // no-op — no working-tree churn, and no rewrite racing a concurrent import
  // (the compiled-binary smoke test rebuilds while sibling create tests run).
  if (
    !existsSync(MANIFEST_OUT) ||
    readFileSync(MANIFEST_OUT, "utf-8") !== module
  ) {
    writeFileSync(MANIFEST_OUT, module);
  }
  return entries;
}

/** The committed reference tree the generator writes back. */
const REFERENCE_DIR = fileURLToPath(new URL("../docs/reference/", scriptsUrl));

/**
 * Write the generated Markdown reference (`emitReference(capabilities)`) into
 * `docs/reference/`, one file per page. Deterministic, so — like
 * {@link generateTemplateManifest} — a page is written ONLY when its bytes
 * differ, keeping a rebuild a working-tree no-op. Any committed `.md` the
 * emitter no longer produces (a removed noun's page) is pruned, so the tree
 * self-heals instead of leaning on the drift-guard to catch the orphan.
 *
 * @returns The number of pages actually written (changed).
 * @note Impure — reads, writes, and prunes the `docs/reference` tree.
 */
function writeReferenceDocs(): number {
  mkdirSync(REFERENCE_DIR, { recursive: true });
  const emitted = emitReference(capabilities);
  let written = 0;
  for (const [relPath, content] of emitted) {
    const out = join(REFERENCE_DIR, relPath);
    if (!existsSync(out) || readFileSync(out, "utf-8") !== content) {
      writeFileSync(out, content);
      written += 1;
    }
  }
  // Prune orphans deterministically: unlink any top-level `.md` the emitter did
  // not just produce (sorted for a stable order), so a removed page disappears
  // on the next build rather than lingering until the drift-guard flags it.
  for (const name of readdirSync(REFERENCE_DIR).sort()) {
    if (name.endsWith(".md") && !emitted.has(name)) {
      unlinkSync(join(REFERENCE_DIR, name));
    }
  }
  return written;
}

export { writeReferenceDocs };

// Only the actual build (not an `import` of `writeReferenceDocs` from the fast
// `genReference` script) runs codegen and compiles the binary.
if (import.meta.main) {
  const surfaced = generateCreateSurface();
  console.log(
    `Projected ${surfaced} generator binding(s) → createSurface.generated.ts`,
  );

  const manifest = generateTemplateManifest();
  const perRoot = TEMPLATE_ROOTS.map(
    ({ prefix }) =>
      `${prefix}: ${
        Object.keys(manifest).filter((key) => key.startsWith(`${prefix}/`))
          .length
      }`,
  ).join(", ");
  console.log(
    `Embedded ${Object.keys(manifest).length} generator templates (${perRoot}) → templates.embedded.generated.ts`,
  );

  const changedDocs = writeReferenceDocs();
  console.log(
    `Wrote ${changedDocs} changed reference page(s) → docs/reference/`,
  );

  const result = await Bun.build({
    entrypoints: ["src/bin.ts"],
    minify: true,
    // Code-splitting is load-bearing for cold-start: it emits the lazily
    // `import()`ed summon-core + generators (+ Ink/React) as SEPARATE chunks the
    // binary parses on demand, not at startup. Without it, bundling summon adds
    // ~135 ms to every invocation (blowing the __complete/--help budgets); with
    // it, the fast paths stay at/under their budgets while `create` loads summon
    // only when it runs.
    splitting: true,
    compile: {
      target: "bun-linux-x64",
      outfile: "dist/pragma",
    },
  });

  if (!result.success) {
    console.error("Build failed:");
    for (const log of result.logs) {
      console.error(log);
    }
    process.exit(1);
  }

  console.log("Built dist/pragma");
}
