// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import { describe, expect, it } from "vitest";
import { render, screen } from "@testing-library/react";
import { GridCard } from "./GridCard";

describe("GridCard", () => {
	it("renders children", () => {
		render(<GridCard>Test content</GridCard>);
		expect(screen.getByText("Test content")).toBeInTheDocument();
	});

	it("applies custom className", () => {
		render(<GridCard className="custom-class">Content</GridCard>);
		const element = screen.getByText("Content");
		expect(element).toHaveClass("grid-card");
		expect(element).toHaveClass("custom-class");
	});

	it("passes through additional props", () => {
		render(<GridCard data-testid="test-component">Content</GridCard>);
		expect(screen.getByTestId("test-component")).toBeInTheDocument();
	});
});
