// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import type { Meta, StoryObj } from "@storybook/react";
import { GridCard } from "./GridCard";

const meta: Meta<typeof GridCard> = {
	title: "Components/GridCard",
	component: GridCard,
	tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof GridCard>;

export const Default: Story = {
	args: {
		children: "Hello, GridCard!",
	},
};

export const WithCustomClass: Story = {
	args: {
		children: "Custom styled",
		className: "custom-class",
	},
};
