// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import { renderToString } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { GridCard } from "./GridCard.js";

describe("GridCard SSR", () => {
  it("renders without hydration errors", () => {
    const html = renderToString(<GridCard>Test content</GridCard>);
    expect(html).toContain("Test content");
    expect(html).toContain("grid-card");
  });
});
