// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import type { GridCardProps } from "./types";
import "./styles.css";

/**
 * GridCard component
 */
export const GridCard = ({
	className,
	children,
	...props
}: GridCardProps): JSX.Element => {
	return (
		<div className={`grid-card${className ? ` ${className}` : ""}`} {...props}>
			Represents a card within the grid
		</div>
	);
};
