// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import type { HTMLAttributes } from "react";

/**
 * The component renders fixed placeholder copy; it accepts no children.
 */
export type GridCardProps = Omit<HTMLAttributes<HTMLDivElement>, "children">;
