<!-- Generated by @canonical/summon-component:svelte v0.1.0 -->

<script lang="ts">
  import type { DialogContentProps } from "./types.js";
  import "./styles.css";

  const componentCssClassName = "ds dialog-content";

  let { class: className, children, ...rest }: DialogContentProps = $props();
</script>

<section class={[componentCssClassName, className]} {...rest}>
  {@render children?.()}
</section>

<!-- @component
`DialogContent` is a layout component that provides a structured container for dialog-like content.

## Example Usage
```svelte
  <DialogContent>
    <DialogContent.Header>
      Dialog Header
      <DialogContent.Header.CloseButton />
    </DialogContent.Header>
    <DialogContent.Body>
      Main Content
    </DialogContent.Body>
    <DialogContent.Footer>
      <Button>Footer Button</Button>
      <Button>Footer Button</Button>
    </DialogContent.Footer>
  </DialogContent>
```
-->
