// Generated by @canonical/summon-component:svelte v0.1.0

import { Body, Footer, Header } from "./common/index.js";
import { default as DialogContentRoot } from "./DialogContent.svelte";

const DialogContent = DialogContentRoot as typeof DialogContentRoot & {
  /**
   * `DialogContent.Header` represents the header section of a dialog.
   *
   * @example
   * ```svelte
   * <DialogContent.Header>
   *   Header Content
   *   <DialogContent.Header.CloseButton />
   * </DialogContent.Header>
   * ```
   */
  Header: typeof Header;

  /**
   * `DialogContent.Body` represents the main content area of a dialog.
   *
   * @example
   * ```svelte
   * <DialogContent.Body>
   *   Main Content
   * </DialogContent.Body>
   * ```
   */
  Body: typeof Body;

  /**
   * `DialogContent.Footer` represents the footer section of a dialog. Usually contains action buttons.
   *
   * @example
   * ```svelte
   * <DialogContent.Footer>
   *   <Button>Cancel</Button>
   *   <Button>Confirm</Button>
   * </DialogContent.Footer>
   * ```
   */
  Footer: typeof Footer;
};

DialogContent.Header = Header;
DialogContent.Body = Body;
DialogContent.Footer = Footer;

export type {
  BodyProps as DialogContentBodyProps,
  CloseButtonProps as DialogContentCloseButtonProps,
  FooterProps as DialogContentFooterProps,
  HeaderProps as DialogContentHeaderProps,
} from "./common/index.js";
export type { DialogContentProps } from "./types.js";
export { DialogContent };
