// Generated by @canonical/summon-component:react v0.1.0

import type { Meta, StoryObj } from "@storybook/react-vite";
import Rail from "./Rail.js";

const meta: Meta<typeof Rail> = {
  title: "Components/Rail",
  component: Rail,
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof Rail>;

export const Default: Story = {
  args: {
    children: "Hello, Rail!",
  },
};

export const WithCustomClass: Story = {
  args: {
    children: "Custom styled",
    className: "custom-class",
  },
};
