// Generated by @canonical/summon-component:react v0.1.0

import { renderToString } from "react-dom/server";
import { describe, expect, it } from "vitest";
import Rail from "./Rail.js";

describe("Rail SSR", () => {
  it("renders without hydration errors", () => {
    const html = renderToString(<Rail>Test content</Rail>);
    expect(html).toContain("Test content");
    expect(html).toContain("ds rail");
  });
});
