// Generated by @canonical/summon-component:react v0.1.0

import { route } from "@canonical/router-core";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { withRouter } from "../../../.storybook/decorators/index.js";
import Rail from "./Rail.js";

/** Name-compatible bare routes: the rail's links resolve without mounting
 * the app's real pages (whose wrapper would nest a whole Shell here). */
const bareRoutes = {
  home: route({ url: "/", component: () => null }),
  components: route({ url: "/components", component: () => null }),
  definitions: route({ url: "/definitions", component: () => null }),
  standards: route({ url: "/standards", component: () => null }),
  guides: route({ url: "/guides", component: () => null }),
  playground: route({ url: "/playground", component: () => null }),
  account: route({ url: "/account", component: () => null }),
} as const;

const meta: Meta<typeof Rail> = {
  title: "Shell/Rail",
  component: Rail,
  tags: ["autodocs"],
  decorators: [withRouter({ routes: bareRoutes })],
};

export default meta;
type Story = StoryObj<typeof Rail>;

/** The primary rail: brand, the five lenses with keyboard hints, and the
 * non-lens utility cluster. Hover an entry to reveal its digit. */
export const Default: Story = {};
