// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import type { ApplicationLayoutProps } from "./types";
import "./styles.css";

/**
 * ApplicationLayout component
 */
export const ApplicationLayout = ({
  className,
  children,
  ...props
}: ApplicationLayoutProps): JSX.Element => {
  return (
    <div
      className={`ds application-layout${className ? ` ${className}` : ""}`}
      {...props}
    >
      {children}
    </div>
  );
};
