// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import { ApplicationLayout } from "./ApplicationLayout.js";

describe("ApplicationLayout", () => {
  it("renders children", () => {
    render(<ApplicationLayout>Test content</ApplicationLayout>);
    expect(screen.getByText("Test content")).toBeInTheDocument();
  });

  it("applies custom className", () => {
    render(
      <ApplicationLayout className="custom-class">Content</ApplicationLayout>,
    );
    const element = screen.getByText("Content");
    expect(element).toHaveClass("application-layout");
    expect(element).toHaveClass("custom-class");
  });

  it("passes through additional props", () => {
    render(
      <ApplicationLayout data-testid="test-component">
        Content
      </ApplicationLayout>,
    );
    expect(screen.getByTestId("test-component")).toBeInTheDocument();
  });
});
