// Generated by @canonical/summon-component:react v0.1.0

import type { Meta, StoryObj } from "@storybook/react-vite";
import StandardsPage from "./StandardsPage.js";

const meta: Meta<typeof StandardsPage> = {
  title: "Components/StandardsPage",
  component: StandardsPage,
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof StandardsPage>;

export const Default: Story = {
  args: {
    children: "Hello, StandardsPage!",
  },
};

export const WithCustomClass: Story = {
  args: {
    children: "Custom styled",
    className: "custom-class",
  },
};
