// Generated by @canonical/summon-component:react v0.1.0

import type React from "react";
import type { StandardsPageProps } from "./types.js";
import "./styles.css";

const componentCssClassName = "ds standards-page";

/**
 * StandardsPage component
 */
const StandardsPage = ({
  className,
  children,
  ...props
}: StandardsPageProps): React.ReactElement => {
  return (
    <div
      className={[componentCssClassName, className].filter(Boolean).join(" ")}
      {...props}
    >
      {children}
    </div>
  );
};

export default StandardsPage;
