// Generated by @canonical/summon-component:react v0.1.0

import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import StandardsPage from "./StandardsPage.js";

describe("StandardsPage", () => {
  it("renders children", () => {
    render(<StandardsPage>Test content</StandardsPage>);
    expect(screen.getByText("Test content")).toBeInTheDocument();
  });

  it("applies custom className", () => {
    render(<StandardsPage className="custom-class">Content</StandardsPage>);
    const element = screen.getByText("Content");
    expect(element.className).toContain("ds standards-page");
    expect(element.className).toContain("custom-class");
  });

  it("passes through additional props", () => {
    render(<StandardsPage data-testid="test-component">Content</StandardsPage>);
    expect(screen.getByTestId("test-component")).toBeInTheDocument();
  });
});
