// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import type { InnerGridDemoProps } from "./types";
import "./styles.css";
import { GridCard } from "../GridCard/index.js";
import { SettingsView } from "../SettingsView/index.js";

const componentCssClassName = "ds grid-demo";

/**
 * InnerGridDemo component
 */
export const InnerGridDemo = ({
	className,
	children,
	...props
}: InnerGridDemoProps): React.ReactElement => {
	return (
		<div
			className={[componentCssClassName, className].filter(Boolean).join(" ")}
			{...props}
		>
			<p>
				This is a demo of the Grid component. It is used to demonstrate the grid
				layout and its responsiveness.
			</p>
			<p>{children}</p>
			<GridCard />
			<GridCard />
			<GridCard />
			<GridCard />
			<SettingsView title="Settings">
				<p>
					Here you can adjust the settings for the application, the user
					settings, and the system settings.
				</p>
			</SettingsView>
		</div>
	);
};
