// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import { describe, expect, it } from "vitest";
import { render, screen } from "@testing-library/react";
import { InnerGridDemo } from "./InnerGridDemo";

describe("InnerGridDemo", () => {
	it("renders children", () => {
		render(<InnerGridDemo>Test content</InnerGridDemo>);
		expect(screen.getByText("Test content")).toBeInTheDocument();
	});

	it("applies custom className", () => {
		render(<InnerGridDemo className="custom-class">Content</InnerGridDemo>);
		const element = screen.getByText("Content");
		expect(element).toHaveClass("grid-demo");
		expect(element).toHaveClass("custom-class");
	});

	it("passes through additional props", () => {
		render(<InnerGridDemo data-testid="test-component">Content</InnerGridDemo>);
		expect(screen.getByTestId("test-component")).toBeInTheDocument();
	});
});
