// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import { describe, expect, it } from "vitest";
import { renderToString } from "react-dom/server";
import { InnerGridDemo } from "./InnerGridDemo";

describe("InnerGridDemo SSR", () => {
	it("renders without hydration errors", () => {
		const html = renderToString(<InnerGridDemo>Test content</InnerGridDemo>);
		expect(html).toContain("Test content");
		expect(html).toContain("grid-demo");
	});
});
