/**
 * A serialised Relay store snapshot for `DefinitionsExplorerQuery` at
 * { uri: "ds:UIBlock", hasTerm: true } — captured VERBATIM from a dev
 * server's `__INITIAL_DATA__.relay.records` at /definitions/ds%3AUIBlock
 * (the output of the prepare step's `getStore().getSource().toJSON()`).
 * Nothing trimmed: the explorer's one operation carries all three
 * ontologies (rail + well) plus the ds:UIBlock class lookup (inspector),
 * and the hydration/frame certifications replay these exact bytes.
 *
 * Regenerate: boot `dev:bun`, copy `relay.records` out of the
 * `__INITIAL_DATA__` script served at /definitions/ds%3AUIBlock.
 */

import type { RecordMap } from "relay-runtime/store/RelayStoreTypes.js";

const definitionsExplorerRecords = {
  "client:root": {
    __id: "client:root",
    __typename: "__Root",
    ontologies: {
      __refs: [
        "client:root:ontologies:0",
        "client:root:ontologies:1",
        "client:root:ontologies:2",
      ],
    },
    'ontologyClass(uri:"ds:UIBlock")': {
      __ref: 'client:root:ontologyClass(uri:"ds:UIBlock")',
    },
    'ontologyProperty(uri:"ds:UIBlock")': null,
  },
  "client:root:ontologies:0": {
    __id: "client:root:ontologies:0",
    __typename: "Ontology",
    prefix: "ds",
    namespace: "https://ds.canonical.com/",
    label: "ds",
    classes: {
      __refs: [
        "client:root:ontologies:0:classes:0",
        "client:root:ontologies:0:classes:1",
        "client:root:ontologies:0:classes:2",
        "client:root:ontologies:0:classes:3",
        "client:root:ontologies:0:classes:4",
        "client:root:ontologies:0:classes:5",
        "client:root:ontologies:0:classes:6",
        "client:root:ontologies:0:classes:7",
        "client:root:ontologies:0:classes:8",
        "client:root:ontologies:0:classes:9",
        "client:root:ontologies:0:classes:10",
        "client:root:ontologies:0:classes:11",
        "client:root:ontologies:0:classes:12",
        "client:root:ontologies:0:classes:13",
        "client:root:ontologies:0:classes:14",
        "client:root:ontologies:0:classes:15",
        "client:root:ontologies:0:classes:16",
      ],
    },
    properties: {
      __refs: [
        "client:root:ontologies:0:properties:0",
        "client:root:ontologies:0:properties:1",
        "client:root:ontologies:0:properties:2",
        "client:root:ontologies:0:properties:3",
        "client:root:ontologies:0:properties:4",
        "client:root:ontologies:0:properties:5",
        "client:root:ontologies:0:properties:6",
        "client:root:ontologies:0:properties:7",
        "client:root:ontologies:0:properties:8",
        "client:root:ontologies:0:properties:9",
        "client:root:ontologies:0:properties:10",
        "client:root:ontologies:0:properties:11",
        "client:root:ontologies:0:properties:12",
        "client:root:ontologies:0:properties:13",
        "client:root:ontologies:0:properties:14",
        "client:root:ontologies:0:properties:15",
        "client:root:ontologies:0:properties:16",
        "client:root:ontologies:0:properties:17",
        "client:root:ontologies:0:properties:18",
        "client:root:ontologies:0:properties:19",
        "client:root:ontologies:0:properties:20",
        "client:root:ontologies:0:properties:21",
        "client:root:ontologies:0:properties:22",
        "client:root:ontologies:0:properties:23",
        "client:root:ontologies:0:properties:24",
        "client:root:ontologies:0:properties:25",
        "client:root:ontologies:0:properties:26",
        "client:root:ontologies:0:properties:27",
        "client:root:ontologies:0:properties:28",
        "client:root:ontologies:0:properties:29",
        "client:root:ontologies:0:properties:30",
        "client:root:ontologies:0:properties:31",
        "client:root:ontologies:0:properties:32",
        "client:root:ontologies:0:properties:33",
        "client:root:ontologies:0:properties:34",
        "client:root:ontologies:0:properties:35",
        "client:root:ontologies:0:properties:36",
        "client:root:ontologies:0:properties:37",
        "client:root:ontologies:0:properties:38",
        "client:root:ontologies:0:properties:39",
        "client:root:ontologies:0:properties:40",
        "client:root:ontologies:0:properties:41",
        "client:root:ontologies:0:properties:42",
        "client:root:ontologies:0:properties:43",
        "client:root:ontologies:0:properties:44",
        "client:root:ontologies:0:properties:45",
        "client:root:ontologies:0:properties:46",
        "client:root:ontologies:0:properties:47",
        "client:root:ontologies:0:properties:48",
        "client:root:ontologies:0:properties:49",
        "client:root:ontologies:0:properties:50",
        "client:root:ontologies:0:properties:51",
      ],
    },
  },
  "client:root:ontologies:0:classes:0": {
    __id: "client:root:ontologies:0:classes:0",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/ChangeLogEntry",
    label: "Change Log Entry",
    isAbstract: false,
    instanceCount: 0,
    superclass: {
      __ref: "client:root:ontologies:0:classes:0:superclass",
    },
  },
  "client:root:ontologies:0:classes:0:superclass": {
    __id: "client:root:ontologies:0:classes:0:superclass",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Entity",
  },
  "client:root:ontologies:0:classes:1": {
    __id: "client:root:ontologies:0:classes:1",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/TagCategory",
    label: "Tag Category",
    isAbstract: false,
    instanceCount: 8,
    superclass: {
      __ref: "client:root:ontologies:0:classes:1:superclass",
    },
  },
  "client:root:ontologies:0:classes:1:superclass": {
    __id: "client:root:ontologies:0:classes:1:superclass",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Entity",
  },
  "client:root:ontologies:0:classes:2": {
    __id: "client:root:ontologies:0:classes:2",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Tag",
    label: "Tag",
    isAbstract: false,
    instanceCount: 42,
    superclass: {
      __ref: "client:root:ontologies:0:classes:2:superclass",
    },
  },
  "client:root:ontologies:0:classes:2:superclass": {
    __id: "client:root:ontologies:0:classes:2:superclass",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Entity",
  },
  "client:root:ontologies:0:classes:3": {
    __id: "client:root:ontologies:0:classes:3",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/ImplementationLibrary",
    label: "Implementation Library",
    isAbstract: false,
    instanceCount: 0,
    superclass: {
      __ref: "client:root:ontologies:0:classes:3:superclass",
    },
  },
  "client:root:ontologies:0:classes:3:superclass": {
    __id: "client:root:ontologies:0:classes:3:superclass",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Entity",
  },
  "client:root:ontologies:0:classes:4": {
    __id: "client:root:ontologies:0:classes:4",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/ImplementationObject",
    label: "Implementation Object",
    isAbstract: false,
    instanceCount: 0,
    superclass: {
      __ref: "client:root:ontologies:0:classes:4:superclass",
    },
  },
  "client:root:ontologies:0:classes:4:superclass": {
    __id: "client:root:ontologies:0:classes:4:superclass",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Entity",
  },
  "client:root:ontologies:0:classes:5": {
    __id: "client:root:ontologies:0:classes:5",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Tier",
    label: "Tier",
    isAbstract: false,
    instanceCount: 15,
    superclass: {
      __ref: "client:root:ontologies:0:classes:5:superclass",
    },
  },
  "client:root:ontologies:0:classes:5:superclass": {
    __id: "client:root:ontologies:0:classes:5:superclass",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Entity",
  },
  "client:root:ontologies:0:classes:6": {
    __id: "client:root:ontologies:0:classes:6",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Property",
    label: "Property",
    isAbstract: false,
    instanceCount: 0,
    superclass: {
      __ref: "client:root:ontologies:0:classes:6:superclass",
    },
  },
  "client:root:ontologies:0:classes:6:superclass": {
    __id: "client:root:ontologies:0:classes:6:superclass",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Entity",
  },
  "client:root:ontologies:0:classes:7": {
    __id: "client:root:ontologies:0:classes:7",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/ModifierFamily",
    label: "Modifier Family",
    isAbstract: false,
    instanceCount: 9,
    superclass: {
      __ref: "client:root:ontologies:0:classes:7:superclass",
    },
  },
  "client:root:ontologies:0:classes:7:superclass": {
    __id: "client:root:ontologies:0:classes:7:superclass",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/UIElement",
  },
  "client:root:ontologies:0:classes:8": {
    __id: "client:root:ontologies:0:classes:8",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Modifier",
    label: "Modifier",
    isAbstract: false,
    instanceCount: 27,
    superclass: {
      __ref: "client:root:ontologies:0:classes:8:superclass",
    },
  },
  "client:root:ontologies:0:classes:8:superclass": {
    __id: "client:root:ontologies:0:classes:8:superclass",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/UIElement",
  },
  "client:root:ontologies:0:classes:9": {
    __id: "client:root:ontologies:0:classes:9",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Group",
    label: "Group",
    isAbstract: false,
    instanceCount: 9,
    superclass: {
      __ref: "client:root:ontologies:0:classes:9:superclass",
    },
  },
  "client:root:ontologies:0:classes:9:superclass": {
    __id: "client:root:ontologies:0:classes:9:superclass",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/UIBlock",
  },
  "client:root:ontologies:0:classes:10": {
    __id: "client:root:ontologies:0:classes:10",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Subcomponent",
    label: "Subcomponent",
    isAbstract: false,
    instanceCount: 85,
    superclass: {
      __ref: "client:root:ontologies:0:classes:10:superclass",
    },
  },
  "client:root:ontologies:0:classes:10:superclass": {
    __id: "client:root:ontologies:0:classes:10:superclass",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/UIBlock",
  },
  "client:root:ontologies:0:classes:11": {
    __id: "client:root:ontologies:0:classes:11",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Layout",
    label: "Layout",
    isAbstract: false,
    instanceCount: 14,
    superclass: {
      __ref: "client:root:ontologies:0:classes:11:superclass",
    },
  },
  "client:root:ontologies:0:classes:11:superclass": {
    __id: "client:root:ontologies:0:classes:11:superclass",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/UIBlock",
  },
  "client:root:ontologies:0:classes:12": {
    __id: "client:root:ontologies:0:classes:12",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Pattern",
    label: "Pattern",
    isAbstract: false,
    instanceCount: 41,
    superclass: {
      __ref: "client:root:ontologies:0:classes:12:superclass",
    },
  },
  "client:root:ontologies:0:classes:12:superclass": {
    __id: "client:root:ontologies:0:classes:12:superclass",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/UIBlock",
  },
  "client:root:ontologies:0:classes:13": {
    __id: "client:root:ontologies:0:classes:13",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Component",
    label: "Component",
    isAbstract: false,
    instanceCount: 108,
    superclass: {
      __ref: "client:root:ontologies:0:classes:13:superclass",
    },
  },
  "client:root:ontologies:0:classes:13:superclass": {
    __id: "client:root:ontologies:0:classes:13:superclass",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/UIBlock",
  },
  "client:root:ontologies:0:classes:14": {
    __id: "client:root:ontologies:0:classes:14",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/UIBlock",
    label: "UI Block",
    isAbstract: true,
    instanceCount: 0,
    superclass: {
      __ref: "client:root:ontologies:0:classes:14:superclass",
    },
  },
  "client:root:ontologies:0:classes:14:superclass": {
    __id: "client:root:ontologies:0:classes:14:superclass",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/UIElement",
  },
  "client:root:ontologies:0:classes:15": {
    __id: "client:root:ontologies:0:classes:15",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/UIElement",
    label: "UI Element",
    isAbstract: true,
    instanceCount: 0,
    superclass: {
      __ref: "client:root:ontologies:0:classes:15:superclass",
    },
  },
  "client:root:ontologies:0:classes:15:superclass": {
    __id: "client:root:ontologies:0:classes:15:superclass",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Entity",
  },
  "client:root:ontologies:0:classes:16": {
    __id: "client:root:ontologies:0:classes:16",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Entity",
    label: "Entity",
    isAbstract: true,
    instanceCount: 0,
    superclass: null,
  },
  "client:root:ontologies:0:properties:0": {
    __id: "client:root:ontologies:0:properties:0",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/libraryTier",
    label: "libraryTier",
    kind: "OBJECT",
  },
  "client:root:ontologies:0:properties:1": {
    __id: "client:root:ontologies:0:properties:1",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/library",
    label: "library",
    kind: "OBJECT",
  },
  "client:root:ontologies:0:properties:2": {
    __id: "client:root:ontologies:0:properties:2",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/implementsBlock",
    label: "implementsBlock",
    kind: "OBJECT",
  },
  "client:root:ontologies:0:properties:3": {
    __id: "client:root:ontologies:0:properties:3",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/category",
    label: "category",
    kind: "OBJECT",
  },
  "client:root:ontologies:0:properties:4": {
    __id: "client:root:ontologies:0:properties:4",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/hasSubcomponent",
    label: "hasSubcomponent",
    kind: "OBJECT",
  },
  "client:root:ontologies:0:properties:5": {
    __id: "client:root:ontologies:0:properties:5",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/parentComponent",
    label: "parentComponent",
    kind: "OBJECT",
  },
  "client:root:ontologies:0:properties:6": {
    __id: "client:root:ontologies:0:properties:6",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/hasModifier",
    label: "hasModifier",
    kind: "OBJECT",
  },
  "client:root:ontologies:0:properties:7": {
    __id: "client:root:ontologies:0:properties:7",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/modifierFamily",
    label: "modifierFamily",
    kind: "OBJECT",
  },
  "client:root:ontologies:0:properties:8": {
    __id: "client:root:ontologies:0:properties:8",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/hasVariant",
    label: "hasVariant",
    kind: "OBJECT",
  },
  "client:root:ontologies:0:properties:9": {
    __id: "client:root:ontologies:0:properties:9",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/variantOf",
    label: "variantOf",
    kind: "OBJECT",
  },
  "client:root:ontologies:0:properties:10": {
    __id: "client:root:ontologies:0:properties:10",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/specializedBy",
    label: "specializedBy",
    kind: "OBJECT",
  },
  "client:root:ontologies:0:properties:11": {
    __id: "client:root:ontologies:0:properties:11",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/inheritsFrom",
    label: "inheritsFrom",
    kind: "OBJECT",
  },
  "client:root:ontologies:0:properties:12": {
    __id: "client:root:ontologies:0:properties:12",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/changeLog",
    label: "changeLog",
    kind: "OBJECT",
  },
  "client:root:ontologies:0:properties:13": {
    __id: "client:root:ontologies:0:properties:13",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/documentationStage",
    label: "documentationStage",
    kind: "OBJECT",
  },
  "client:root:ontologies:0:properties:14": {
    __id: "client:root:ontologies:0:properties:14",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/hasProperty",
    label: "hasProperty",
    kind: "OBJECT",
  },
  "client:root:ontologies:0:properties:15": {
    __id: "client:root:ontologies:0:properties:15",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/hasModifierFamily",
    label: "hasModifierFamily",
    kind: "OBJECT",
  },
  "client:root:ontologies:0:properties:16": {
    __id: "client:root:ontologies:0:properties:16",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/tier",
    label: "tier",
    kind: "OBJECT",
  },
  "client:root:ontologies:0:properties:17": {
    __id: "client:root:ontologies:0:properties:17",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/documentation",
    label: "documentation",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:18": {
    __id: "client:root:ontologies:0:properties:18",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/link",
    label: "link",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:19": {
    __id: "client:root:ontologies:0:properties:19",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/platform",
    label: "platform",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:20": {
    __id: "client:root:ontologies:0:properties:20",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/libraryName",
    label: "libraryName",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:21": {
    __id: "client:root:ontologies:0:properties:21",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/isDraft",
    label: "isDraft",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:22": {
    __id: "client:root:ontologies:0:properties:22",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/versionedLink",
    label: "versionedLink",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:23": {
    __id: "client:root:ontologies:0:properties:23",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/headLink",
    label: "headLink",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:24": {
    __id: "client:root:ontologies:0:properties:24",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/implementationVersion",
    label: "implementationVersion",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:25": {
    __id: "client:root:ontologies:0:properties:25",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/constraints",
    label: "constraints",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:26": {
    __id: "client:root:ontologies:0:properties:26",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/defaultValue",
    label: "defaultValue",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:27": {
    __id: "client:root:ontologies:0:properties:27",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/optional",
    label: "optional",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:28": {
    __id: "client:root:ontologies:0:properties:28",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/propertyType",
    label: "propertyType",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:29": {
    __id: "client:root:ontologies:0:properties:29",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/targetDevices",
    label: "targetDevices",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:30": {
    __id: "client:root:ontologies:0:properties:30",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/changeType",
    label: "changeType",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:31": {
    __id: "client:root:ontologies:0:properties:31",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/githubLink",
    label: "githubLink",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:32": {
    __id: "client:root:ontologies:0:properties:32",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/owner",
    label: "owner",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:33": {
    __id: "client:root:ontologies:0:properties:33",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/change",
    label: "change",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:34": {
    __id: "client:root:ontologies:0:properties:34",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/timestamp",
    label: "timestamp",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:35": {
    __id: "client:root:ontologies:0:properties:35",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/whenToRemove",
    label: "whenToRemove",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:36": {
    __id: "client:root:ontologies:0:properties:36",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/whenToApply",
    label: "whenToApply",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:37": {
    __id: "client:root:ontologies:0:properties:37",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/gridAreas",
    label: "gridAreas",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:38": {
    __id: "client:root:ontologies:0:properties:38",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/domain",
    label: "domain",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:39": {
    __id: "client:root:ontologies:0:properties:39",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/grid",
    label: "grid",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:40": {
    __id: "client:root:ontologies:0:properties:40",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/standalone",
    label: "standalone",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:41": {
    __id: "client:root:ontologies:0:properties:41",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/guidelines",
    label: "guidelines",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:42": {
    __id: "client:root:ontologies:0:properties:42",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/usage",
    label: "usage",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:43": {
    __id: "client:root:ontologies:0:properties:43",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/anatomyDsl",
    label: "anatomyDsl",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:44": {
    __id: "client:root:ontologies:0:properties:44",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/anatomyClassic",
    label: "anatomyClassic",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:45": {
    __id: "client:root:ontologies:0:properties:45",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/figmaLink",
    label: "figmaLink",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:46": {
    __id: "client:root:ontologies:0:properties:46",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/decisionLog",
    label: "decisionLog",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:47": {
    __id: "client:root:ontologies:0:properties:47",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/version",
    label: "version",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:48": {
    __id: "client:root:ontologies:0:properties:48",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/summary",
    label: "summary",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:49": {
    __id: "client:root:ontologies:0:properties:49",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/name",
    label: "name",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:50": {
    __id: "client:root:ontologies:0:properties:50",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/completionGuidance",
    label: "completionGuidance",
    kind: "ANNOTATION",
  },
  "client:root:ontologies:0:properties:51": {
    __id: "client:root:ontologies:0:properties:51",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/acceptanceCriteria",
    label: "acceptanceCriteria",
    kind: "ANNOTATION",
  },
  "client:root:ontologies:1": {
    __id: "client:root:ontologies:1",
    __typename: "Ontology",
    prefix: "cs",
    namespace: "http://pragma.canonical.com/codestandards#",
    label: "cs",
    classes: {
      __refs: [
        "client:root:ontologies:1:classes:0",
        "client:root:ontologies:1:classes:1",
        "client:root:ontologies:1:classes:2",
      ],
    },
    properties: {
      __refs: [
        "client:root:ontologies:1:properties:0",
        "client:root:ontologies:1:properties:1",
        "client:root:ontologies:1:properties:2",
        "client:root:ontologies:1:properties:3",
        "client:root:ontologies:1:properties:4",
        "client:root:ontologies:1:properties:5",
        "client:root:ontologies:1:properties:6",
        "client:root:ontologies:1:properties:7",
        "client:root:ontologies:1:properties:8",
      ],
    },
  },
  "client:root:ontologies:1:classes:0": {
    __id: "client:root:ontologies:1:classes:0",
    __typename: "OntologyClass",
    uri: "http://pragma.canonical.com/codestandards#Example",
    label: "Example",
    isAbstract: false,
    instanceCount: 0,
    superclass: null,
  },
  "client:root:ontologies:1:classes:1": {
    __id: "client:root:ontologies:1:classes:1",
    __typename: "OntologyClass",
    uri: "http://pragma.canonical.com/codestandards#Category",
    label: "Category",
    isAbstract: false,
    instanceCount: 19,
    superclass: null,
  },
  "client:root:ontologies:1:classes:2": {
    __id: "client:root:ontologies:1:classes:2",
    __typename: "OntologyClass",
    uri: "http://pragma.canonical.com/codestandards#CodeStandard",
    label: "Code Standard",
    isAbstract: false,
    instanceCount: 131,
    superclass: null,
  },
  "client:root:ontologies:1:properties:0": {
    __id: "client:root:ontologies:1:properties:0",
    __typename: "OntologyProperty",
    uri: "http://pragma.canonical.com/codestandards#dont",
    label: "don't",
    kind: "OBJECT",
  },
  "client:root:ontologies:1:properties:1": {
    __id: "client:root:ontologies:1:properties:1",
    __typename: "OntologyProperty",
    uri: "http://pragma.canonical.com/codestandards#do",
    label: "do",
    kind: "OBJECT",
  },
  "client:root:ontologies:1:properties:2": {
    __id: "client:root:ontologies:1:properties:2",
    __typename: "OntologyProperty",
    uri: "http://pragma.canonical.com/codestandards#extends",
    label: "extends",
    kind: "OBJECT",
  },
  "client:root:ontologies:1:properties:3": {
    __id: "client:root:ontologies:1:properties:3",
    __typename: "OntologyProperty",
    uri: "http://pragma.canonical.com/codestandards#hasCategory",
    label: "has category",
    kind: "OBJECT",
  },
  "client:root:ontologies:1:properties:4": {
    __id: "client:root:ontologies:1:properties:4",
    __typename: "OntologyProperty",
    uri: "http://pragma.canonical.com/codestandards#code",
    label: "code",
    kind: "DATATYPE",
  },
  "client:root:ontologies:1:properties:5": {
    __id: "client:root:ontologies:1:properties:5",
    __typename: "OntologyProperty",
    uri: "http://pragma.canonical.com/codestandards#language",
    label: "language",
    kind: "DATATYPE",
  },
  "client:root:ontologies:1:properties:6": {
    __id: "client:root:ontologies:1:properties:6",
    __typename: "OntologyProperty",
    uri: "http://pragma.canonical.com/codestandards#description",
    label: "description",
    kind: "DATATYPE",
  },
  "client:root:ontologies:1:properties:7": {
    __id: "client:root:ontologies:1:properties:7",
    __typename: "OntologyProperty",
    uri: "http://pragma.canonical.com/codestandards#slug",
    label: "slug",
    kind: "DATATYPE",
  },
  "client:root:ontologies:1:properties:8": {
    __id: "client:root:ontologies:1:properties:8",
    __typename: "OntologyProperty",
    uri: "http://pragma.canonical.com/codestandards#name",
    label: "name",
    kind: "DATATYPE",
  },
  "client:root:ontologies:2": {
    __id: "client:root:ontologies:2",
    __typename: "Ontology",
    prefix: "anatomy",
    namespace: "http://anatomy-dsl.example.org/ontology#",
    label: "anatomy",
    classes: {
      __refs: [
        "client:root:ontologies:2:classes:0",
        "client:root:ontologies:2:classes:1",
        "client:root:ontologies:2:classes:2",
        "client:root:ontologies:2:classes:3",
        "client:root:ontologies:2:classes:4",
        "client:root:ontologies:2:classes:5",
        "client:root:ontologies:2:classes:6",
        "client:root:ontologies:2:classes:7",
        "client:root:ontologies:2:classes:8",
      ],
    },
    properties: {
      __refs: [
        "client:root:ontologies:2:properties:0",
        "client:root:ontologies:2:properties:1",
        "client:root:ontologies:2:properties:2",
        "client:root:ontologies:2:properties:3",
        "client:root:ontologies:2:properties:4",
        "client:root:ontologies:2:properties:5",
        "client:root:ontologies:2:properties:6",
        "client:root:ontologies:2:properties:7",
        "client:root:ontologies:2:properties:8",
        "client:root:ontologies:2:properties:9",
        "client:root:ontologies:2:properties:10",
        "client:root:ontologies:2:properties:11",
        "client:root:ontologies:2:properties:12",
        "client:root:ontologies:2:properties:13",
        "client:root:ontologies:2:properties:14",
      ],
    },
  },
  "client:root:ontologies:2:classes:0": {
    __id: "client:root:ontologies:2:classes:0",
    __typename: "OntologyClass",
    uri: "http://anatomy-dsl.example.org/ontology#SwitchCase",
    label: "Switch Case",
    isAbstract: false,
    instanceCount: 0,
    superclass: null,
  },
  "client:root:ontologies:2:classes:1": {
    __id: "client:root:ontologies:2:classes:1",
    __typename: "OntologyClass",
    uri: "http://anatomy-dsl.example.org/ontology#Switch",
    label: "Switch",
    isAbstract: false,
    instanceCount: 0,
    superclass: null,
  },
  "client:root:ontologies:2:classes:2": {
    __id: "client:root:ontologies:2:classes:2",
    __typename: "OntologyClass",
    uri: "http://anatomy-dsl.example.org/ontology#Style",
    label: "Style",
    isAbstract: false,
    instanceCount: 0,
    superclass: null,
  },
  "client:root:ontologies:2:classes:3": {
    __id: "client:root:ontologies:2:classes:3",
    __typename: "OntologyClass",
    uri: "http://anatomy-dsl.example.org/ontology#Relation",
    label: "Relation",
    isAbstract: false,
    instanceCount: 0,
    superclass: null,
  },
  "client:root:ontologies:2:classes:4": {
    __id: "client:root:ontologies:2:classes:4",
    __typename: "OntologyClass",
    uri: "http://anatomy-dsl.example.org/ontology#Edge",
    label: "Edge",
    isAbstract: false,
    instanceCount: 0,
    superclass: null,
  },
  "client:root:ontologies:2:classes:5": {
    __id: "client:root:ontologies:2:classes:5",
    __typename: "OntologyClass",
    uri: "http://anatomy-dsl.example.org/ontology#AnonymousNode",
    label: "Anonymous Node",
    isAbstract: false,
    instanceCount: 0,
    superclass: {
      __ref: "client:root:ontologies:2:classes:5:superclass",
    },
  },
  "client:root:ontologies:2:classes:5:superclass": {
    __id: "client:root:ontologies:2:classes:5:superclass",
    __typename: "OntologyClass",
    uri: "http://anatomy-dsl.example.org/ontology#Node",
  },
  "client:root:ontologies:2:classes:6": {
    __id: "client:root:ontologies:2:classes:6",
    __typename: "OntologyClass",
    uri: "http://anatomy-dsl.example.org/ontology#NamedNode",
    label: "Named Node",
    isAbstract: false,
    instanceCount: 0,
    superclass: {
      __ref: "client:root:ontologies:2:classes:6:superclass",
    },
  },
  "client:root:ontologies:2:classes:6:superclass": {
    __id: "client:root:ontologies:2:classes:6:superclass",
    __typename: "OntologyClass",
    uri: "http://anatomy-dsl.example.org/ontology#Node",
  },
  "client:root:ontologies:2:classes:7": {
    __id: "client:root:ontologies:2:classes:7",
    __typename: "OntologyClass",
    uri: "http://anatomy-dsl.example.org/ontology#Node",
    label: "Node",
    isAbstract: true,
    instanceCount: 0,
    superclass: null,
  },
  "client:root:ontologies:2:classes:8": {
    __id: "client:root:ontologies:2:classes:8",
    __typename: "OntologyClass",
    uri: "http://anatomy-dsl.example.org/ontology#Specification",
    label: "Specification",
    isAbstract: false,
    instanceCount: 0,
    superclass: null,
  },
  "client:root:ontologies:2:properties:0": {
    __id: "client:root:ontologies:2:properties:0",
    __typename: "OntologyProperty",
    uri: "http://anatomy-dsl.example.org/ontology#hasStyle",
    label: "has style",
    kind: "OBJECT",
  },
  "client:root:ontologies:2:properties:1": {
    __id: "client:root:ontologies:2:properties:1",
    __typename: "OntologyProperty",
    uri: "http://anatomy-dsl.example.org/ontology#caseNode",
    label: "case node",
    kind: "OBJECT",
  },
  "client:root:ontologies:2:properties:2": {
    __id: "client:root:ontologies:2:properties:2",
    __typename: "OntologyProperty",
    uri: "http://anatomy-dsl.example.org/ontology#hasCase",
    label: "has case",
    kind: "OBJECT",
  },
  "client:root:ontologies:2:properties:3": {
    __id: "client:root:ontologies:2:properties:3",
    __typename: "OntologyProperty",
    uri: "http://anatomy-dsl.example.org/ontology#edgeSwitch",
    label: "edge switch",
    kind: "OBJECT",
  },
  "client:root:ontologies:2:properties:4": {
    __id: "client:root:ontologies:2:properties:4",
    __typename: "OntologyProperty",
    uri: "http://anatomy-dsl.example.org/ontology#edgeTarget",
    label: "edge target",
    kind: "OBJECT",
  },
  "client:root:ontologies:2:properties:5": {
    __id: "client:root:ontologies:2:properties:5",
    __typename: "OntologyProperty",
    uri: "http://anatomy-dsl.example.org/ontology#hasRelation",
    label: "has relation",
    kind: "OBJECT",
  },
  "client:root:ontologies:2:properties:6": {
    __id: "client:root:ontologies:2:properties:6",
    __typename: "OntologyProperty",
    uri: "http://anatomy-dsl.example.org/ontology#hasEdge",
    label: "has edge",
    kind: "OBJECT",
  },
  "client:root:ontologies:2:properties:7": {
    __id: "client:root:ontologies:2:properties:7",
    __typename: "OntologyProperty",
    uri: "http://anatomy-dsl.example.org/ontology#rootNode",
    label: "root node",
    kind: "OBJECT",
  },
  "client:root:ontologies:2:properties:8": {
    __id: "client:root:ontologies:2:properties:8",
    __typename: "OntologyProperty",
    uri: "http://anatomy-dsl.example.org/ontology#styleValue",
    label: "style value",
    kind: "DATATYPE",
  },
  "client:root:ontologies:2:properties:9": {
    __id: "client:root:ontologies:2:properties:9",
    __typename: "OntologyProperty",
    uri: "http://anatomy-dsl.example.org/ontology#styleKey",
    label: "style key",
    kind: "DATATYPE",
  },
  "client:root:ontologies:2:properties:10": {
    __id: "client:root:ontologies:2:properties:10",
    __typename: "OntologyProperty",
    uri: "http://anatomy-dsl.example.org/ontology#slotName",
    label: "slot name",
    kind: "DATATYPE",
  },
  "client:root:ontologies:2:properties:11": {
    __id: "client:root:ontologies:2:properties:11",
    __typename: "OntologyProperty",
    uri: "http://anatomy-dsl.example.org/ontology#cardinality",
    label: "cardinality",
    kind: "DATATYPE",
  },
  "client:root:ontologies:2:properties:12": {
    __id: "client:root:ontologies:2:properties:12",
    __typename: "OntologyProperty",
    uri: "http://anatomy-dsl.example.org/ontology#discriminator",
    label: "discriminator",
    kind: "DATATYPE",
  },
  "client:root:ontologies:2:properties:13": {
    __id: "client:root:ontologies:2:properties:13",
    __typename: "OntologyProperty",
    uri: "http://anatomy-dsl.example.org/ontology#role",
    label: "role",
    kind: "DATATYPE",
  },
  "client:root:ontologies:2:properties:14": {
    __id: "client:root:ontologies:2:properties:14",
    __typename: "OntologyProperty",
    uri: "http://anatomy-dsl.example.org/ontology#uri",
    label: "uri",
    kind: "DATATYPE",
  },
  'client:root:ontologyClass(uri:"ds:UIBlock")': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock")',
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/UIBlock",
    label: "UI Block",
    definition:
      "A category of visual or abstract entity that fulfills a particular role in composing user interfaces",
    isAbstract: true,
    namespace: "ds",
    instanceCount: 0,
    superclass: {
      __ref: 'client:root:ontologyClass(uri:"ds:UIBlock"):superclass',
    },
    superclasses: {
      __refs: [
        'client:root:ontologyClass(uri:"ds:UIBlock"):superclasses:0',
        'client:root:ontologyClass(uri:"ds:UIBlock"):superclasses:1',
      ],
    },
    subclasses: {
      __refs: [
        'client:root:ontologyClass(uri:"ds:UIBlock"):subclasses:0',
        'client:root:ontologyClass(uri:"ds:UIBlock"):subclasses:1',
        'client:root:ontologyClass(uri:"ds:UIBlock"):subclasses:2',
        'client:root:ontologyClass(uri:"ds:UIBlock"):subclasses:3',
        'client:root:ontologyClass(uri:"ds:UIBlock"):subclasses:4',
      ],
    },
    properties: {
      __refs: [
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:0',
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:1',
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:2',
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:3',
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:4',
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:5',
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:6',
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:7',
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:8',
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:9',
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:10',
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:11',
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:12',
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:13',
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:14',
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:15',
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:16',
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:17',
      ],
    },
    "instances(first:12)": {
      __ref: 'client:root:ontologyClass(uri:"ds:UIBlock"):instances(first:12)',
    },
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):superclass': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):superclass',
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/UIElement",
    label: "UI Element",
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):superclasses:0': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):superclasses:0',
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/UIElement",
    label: "UI Element",
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):superclasses:1': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):superclasses:1',
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Entity",
    label: "Entity",
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):subclasses:0': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):subclasses:0',
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Group",
    label: "Group",
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):subclasses:1': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):subclasses:1',
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Subcomponent",
    label: "Subcomponent",
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):subclasses:2': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):subclasses:2',
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Layout",
    label: "Layout",
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):subclasses:3': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):subclasses:3',
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Pattern",
    label: "Pattern",
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):subclasses:4': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):subclasses:4',
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Component",
    label: "Component",
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:0': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:0',
    __typename: "ClassProperty",
    required: false,
    singular: false,
    inherited: false,
    property: {
      __ref:
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:0:property',
    },
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:0:property': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:0:property',
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/hasVariant",
    label: "hasVariant",
    definition:
      "The variants of this UI Block (inverse of ds:variantOf). E.g. Tooltip has variant Tooltip+Dense.",
    range: "https://ds.canonical.com/UIBlock",
    kind: "OBJECT",
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:1': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:1',
    __typename: "ClassProperty",
    required: false,
    singular: false,
    inherited: false,
    property: {
      __ref:
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:1:property',
    },
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:1:property': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:1:property',
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/variantOf",
    label: "variantOf",
    definition:
      "The base UI Block this block is a variant of, by the '+' naming convention (e.g. Tooltip+Dense is a variant of Tooltip). Distinct from ds:inheritsFrom: a variant is a modifier-style derivative rather than a prefixed specialisation.",
    range: "https://ds.canonical.com/UIBlock",
    kind: "OBJECT",
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:2': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:2',
    __typename: "ClassProperty",
    required: false,
    singular: false,
    inherited: false,
    property: {
      __ref:
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:2:property',
    },
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:2:property': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:2:property',
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/specializedBy",
    label: "specializedBy",
    definition:
      "The UI Blocks that inherit from / specialise this block (inverse of ds:inheritsFrom). E.g. Tooltip is specialised by DataTooltip.",
    range: "https://ds.canonical.com/UIBlock",
    kind: "OBJECT",
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:3': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:3',
    __typename: "ClassProperty",
    required: false,
    singular: false,
    inherited: false,
    property: {
      __ref:
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:3:property',
    },
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:3:property': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:3:property',
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/inheritsFrom",
    label: "inheritsFrom",
    definition:
      "The UI Block this block inherits from / specialises (e.g. a Data tooltip inherits from Tooltip). Distinct from subcomponent containment: inheritance is an is-a-specialisation relationship.",
    range: "https://ds.canonical.com/UIBlock",
    kind: "OBJECT",
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:4': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:4',
    __typename: "ClassProperty",
    required: false,
    singular: false,
    inherited: false,
    property: {
      __ref:
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:4:property',
    },
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:4:property': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:4:property',
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/changeLog",
    label: "changeLog",
    definition: "Links a UI Block to its dated change log entries.",
    range: "https://ds.canonical.com/ChangeLogEntry",
    kind: "OBJECT",
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:5': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:5',
    __typename: "ClassProperty",
    required: false,
    singular: false,
    inherited: false,
    property: {
      __ref:
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:5:property',
    },
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:5:property': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:5:property',
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/documentationStage",
    label: "documentationStage",
    definition:
      "Links a UI Block to the documentation-stage Tag(s) applied to it (e.g. needs:documentation). One facet of the wider Tag vocabulary; the other tag facets are tracked as future work.",
    range: "https://ds.canonical.com/Tag",
    kind: "OBJECT",
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:6': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:6',
    __typename: "ClassProperty",
    required: false,
    singular: false,
    inherited: false,
    property: {
      __ref:
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:6:property',
    },
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:6:property': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:6:property',
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/hasProperty",
    label: "hasProperty",
    definition: "Links a UI Block to its configurable properties",
    range: "https://ds.canonical.com/Property",
    kind: "OBJECT",
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:7': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:7',
    __typename: "ClassProperty",
    required: false,
    singular: false,
    inherited: false,
    property: {
      __ref:
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:7:property',
    },
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:7:property': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:7:property',
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/hasModifierFamily",
    label: "hasModifierFamily",
    definition: "Links a UI Block to applicable modifier families",
    range: "https://ds.canonical.com/ModifierFamily",
    kind: "OBJECT",
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:8': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:8',
    __typename: "ClassProperty",
    required: false,
    singular: true,
    inherited: false,
    property: {
      __ref:
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:8:property',
    },
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:8:property': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:8:property',
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/tier",
    label: "tier",
    definition: "The tier to which the UI block belongs to",
    range: "https://ds.canonical.com/Tier",
    kind: "OBJECT",
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:9': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:9',
    __typename: "ClassProperty",
    required: false,
    singular: true,
    inherited: false,
    property: {
      __ref:
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:9:property',
    },
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:9:property': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:9:property',
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/guidelines",
    label: "guidelines",
    definition:
      "Detailed specification for correctly using and implementing the UI block.",
    range: "http://www.w3.org/2001/XMLSchema#string",
    kind: "DATATYPE",
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:10': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:10',
    __typename: "ClassProperty",
    required: false,
    singular: true,
    inherited: false,
    property: {
      __ref:
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:10:property',
    },
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:10:property': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:10:property',
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/usage",
    label: "usage",
    definition:
      "Free-text (Markdown) usage documentation for the UI block. Subsumes the former whenToUse/whenNotToUse: a usage entry describes the contexts where the component is most appropriate ('When to use'), the contexts where it is NOT appropriate and what to use instead ('When not to use'), and a general description, typically as Markdown sub-sections.",
    range: "http://www.w3.org/2001/XMLSchema#string",
    kind: "DATATYPE",
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:11': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:11',
    __typename: "ClassProperty",
    required: false,
    singular: true,
    inherited: false,
    property: {
      __ref:
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:11:property',
    },
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:11:property': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:11:property',
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/anatomyDsl",
    label: "anatomyDsl",
    definition:
      "YAML specification of component structure using the Anatomy DSL. Describes nodes (named/anonymous), edges with cardinality, slots, and CTI-inspired styles.",
    range: "http://www.w3.org/2001/XMLSchema#string",
    kind: "DATATYPE",
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:12': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:12',
    __typename: "ClassProperty",
    required: false,
    singular: true,
    inherited: false,
    property: {
      __ref:
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:12:property',
    },
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:12:property': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:12:property',
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/anatomyClassic",
    label: "anatomyClassic",
    definition:
      "DEPRECATED. Legacy anatomy field (free-form text). Superseded by ds:anatomyDsl.",
    range: "http://www.w3.org/2001/XMLSchema#string",
    kind: "DATATYPE",
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:13': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:13',
    __typename: "ClassProperty",
    required: false,
    singular: true,
    inherited: false,
    property: {
      __ref:
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:13:property',
    },
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:13:property': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:13:property',
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/figmaLink",
    label: "figmaLink",
    definition: "Link to the Figma design file for this UI block",
    range: "http://www.w3.org/2001/XMLSchema#anyURI",
    kind: "DATATYPE",
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:14': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:14',
    __typename: "ClassProperty",
    required: false,
    singular: true,
    inherited: true,
    property: {
      __ref:
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:14:property',
    },
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:14:property': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:14:property',
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/decisionLog",
    label: "decisionLog",
    definition: "Log of decisions with [date][author][content]",
    range: "http://www.w3.org/2001/XMLSchema#string",
    kind: "DATATYPE",
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:15': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:15',
    __typename: "ClassProperty",
    required: false,
    singular: true,
    inherited: true,
    property: {
      __ref:
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:15:property',
    },
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:15:property': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:15:property',
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/version",
    label: "version",
    definition: "Semantic version of the entity following semver specification",
    range: "https://ds.canonical.com/SemverString",
    kind: "DATATYPE",
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:16': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:16',
    __typename: "ClassProperty",
    required: false,
    singular: true,
    inherited: true,
    property: {
      __ref:
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:16:property',
    },
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:16:property': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:16:property',
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/summary",
    label: "summary",
    definition:
      "A comprehensive paragraph of text that states the singular purpose of the entity.",
    range: "http://www.w3.org/2001/XMLSchema#string",
    kind: "DATATYPE",
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:17': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:17',
    __typename: "ClassProperty",
    required: false,
    singular: true,
    inherited: true,
    property: {
      __ref:
        'client:root:ontologyClass(uri:"ds:UIBlock"):properties:17:property',
    },
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):properties:17:property': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):properties:17:property',
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/name",
    label: "name",
    definition:
      "A human-readable text for the entity. The primary identifier, used for referencing and display purposes.",
    range: "http://www.w3.org/2001/XMLSchema#string",
    kind: "DATATYPE",
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):instances(first:12)': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):instances(first:12)',
    __typename: "NodeConnection",
    edges: {
      __refs: [],
    },
    pageInfo: {
      __ref:
        'client:root:ontologyClass(uri:"ds:UIBlock"):instances(first:12):pageInfo',
    },
  },
  'client:root:ontologyClass(uri:"ds:UIBlock"):instances(first:12):pageInfo': {
    __id: 'client:root:ontologyClass(uri:"ds:UIBlock"):instances(first:12):pageInfo',
    __typename: "PageInfo",
    hasNextPage: false,
  },
} as unknown as RecordMap;

export default definitionsExplorerRecords;
