/**
 * A serialised Relay store snapshot for `DefinitionsExplorerQuery` at
 * { uri: "ds:hasSubcomponent", hasTerm: true } — captured VERBATIM from a
 * dev server's `__INITIAL_DATA__.relay.records` at
 * /definitions/ds%3AhasSubcomponent (`getStore().getSource().toJSON()`).
 * The property-term twin of `definitionsExplorerRecords`: the class
 * lookup is null and `ontologyProperty` carries the record — the
 * inspector's property view renders from exactly this shape.
 *
 * Regenerate: boot `dev:bun`, copy `relay.records` out of the
 * `__INITIAL_DATA__` script served at /definitions/ds%3AhasSubcomponent.
 */

import type { RecordMap } from "relay-runtime/store/RelayStoreTypes.js";

const definitionsExplorerRecordsProperty = {
  "client:root": {
    __id: "client:root",
    __typename: "__Root",
    ontologies: {
      __refs: [
        "client:root:ontologies:0",
        "client:root:ontologies:1",
        "client:root:ontologies:2",
      ],
    },
    'ontologyClass(uri:"ds:hasSubcomponent")': null,
    'ontologyProperty(uri:"ds:hasSubcomponent")': {
      __ref: 'client:root:ontologyProperty(uri:"ds:hasSubcomponent")',
    },
  },
  "client:root:ontologies:0": {
    __id: "client:root:ontologies:0",
    __typename: "Ontology",
    prefix: "ds",
    namespace: "https://ds.canonical.com/",
    label: "ds",
    classes: {
      __refs: [
        "client:root:ontologies:0:classes:0",
        "client:root:ontologies:0:classes:1",
        "client:root:ontologies:0:classes:2",
        "client:root:ontologies:0:classes:3",
        "client:root:ontologies:0:classes:4",
        "client:root:ontologies:0:classes:5",
        "client:root:ontologies:0:classes:6",
        "client:root:ontologies:0:classes:7",
        "client:root:ontologies:0:classes:8",
        "client:root:ontologies:0:classes:9",
        "client:root:ontologies:0:classes:10",
        "client:root:ontologies:0:classes:11",
        "client:root:ontologies:0:classes:12",
        "client:root:ontologies:0:classes:13",
        "client:root:ontologies:0:classes:14",
        "client:root:ontologies:0:classes:15",
        "client:root:ontologies:0:classes:16",
      ],
    },
    properties: {
      __refs: [
        "client:root:ontologies:0:properties:0",
        "client:root:ontologies:0:properties:1",
        "client:root:ontologies:0:properties:2",
        "client:root:ontologies:0:properties:3",
        "client:root:ontologies:0:properties:4",
        "client:root:ontologies:0:properties:5",
        "client:root:ontologies:0:properties:6",
        "client:root:ontologies:0:properties:7",
        "client:root:ontologies:0:properties:8",
        "client:root:ontologies:0:properties:9",
        "client:root:ontologies:0:properties:10",
        "client:root:ontologies:0:properties:11",
        "client:root:ontologies:0:properties:12",
        "client:root:ontologies:0:properties:13",
        "client:root:ontologies:0:properties:14",
        "client:root:ontologies:0:properties:15",
        "client:root:ontologies:0:properties:16",
        "client:root:ontologies:0:properties:17",
        "client:root:ontologies:0:properties:18",
        "client:root:ontologies:0:properties:19",
        "client:root:ontologies:0:properties:20",
        "client:root:ontologies:0:properties:21",
        "client:root:ontologies:0:properties:22",
        "client:root:ontologies:0:properties:23",
        "client:root:ontologies:0:properties:24",
        "client:root:ontologies:0:properties:25",
        "client:root:ontologies:0:properties:26",
        "client:root:ontologies:0:properties:27",
        "client:root:ontologies:0:properties:28",
        "client:root:ontologies:0:properties:29",
        "client:root:ontologies:0:properties:30",
        "client:root:ontologies:0:properties:31",
        "client:root:ontologies:0:properties:32",
        "client:root:ontologies:0:properties:33",
        "client:root:ontologies:0:properties:34",
        "client:root:ontologies:0:properties:35",
        "client:root:ontologies:0:properties:36",
        "client:root:ontologies:0:properties:37",
        "client:root:ontologies:0:properties:38",
        "client:root:ontologies:0:properties:39",
        "client:root:ontologies:0:properties:40",
        "client:root:ontologies:0:properties:41",
        "client:root:ontologies:0:properties:42",
        "client:root:ontologies:0:properties:43",
        "client:root:ontologies:0:properties:44",
        "client:root:ontologies:0:properties:45",
        "client:root:ontologies:0:properties:46",
        "client:root:ontologies:0:properties:47",
        "client:root:ontologies:0:properties:48",
        "client:root:ontologies:0:properties:49",
        "client:root:ontologies:0:properties:50",
        "client:root:ontologies:0:properties:51",
      ],
    },
  },
  "client:root:ontologies:0:classes:0": {
    __id: "client:root:ontologies:0:classes:0",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/ChangeLogEntry",
    label: "Change Log Entry",
    isAbstract: false,
    instanceCount: 0,
    superclass: {
      __ref: "client:root:ontologies:0:classes:0:superclass",
    },
  },
  "client:root:ontologies:0:classes:0:superclass": {
    __id: "client:root:ontologies:0:classes:0:superclass",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Entity",
  },
  "client:root:ontologies:0:classes:1": {
    __id: "client:root:ontologies:0:classes:1",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/TagCategory",
    label: "Tag Category",
    isAbstract: false,
    instanceCount: 8,
    superclass: {
      __ref: "client:root:ontologies:0:classes:1:superclass",
    },
  },
  "client:root:ontologies:0:classes:1:superclass": {
    __id: "client:root:ontologies:0:classes:1:superclass",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Entity",
  },
  "client:root:ontologies:0:classes:2": {
    __id: "client:root:ontologies:0:classes:2",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Tag",
    label: "Tag",
    isAbstract: false,
    instanceCount: 42,
    superclass: {
      __ref: "client:root:ontologies:0:classes:2:superclass",
    },
  },
  "client:root:ontologies:0:classes:2:superclass": {
    __id: "client:root:ontologies:0:classes:2:superclass",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Entity",
  },
  "client:root:ontologies:0:classes:3": {
    __id: "client:root:ontologies:0:classes:3",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/ImplementationLibrary",
    label: "Implementation Library",
    isAbstract: false,
    instanceCount: 0,
    superclass: {
      __ref: "client:root:ontologies:0:classes:3:superclass",
    },
  },
  "client:root:ontologies:0:classes:3:superclass": {
    __id: "client:root:ontologies:0:classes:3:superclass",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Entity",
  },
  "client:root:ontologies:0:classes:4": {
    __id: "client:root:ontologies:0:classes:4",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/ImplementationObject",
    label: "Implementation Object",
    isAbstract: false,
    instanceCount: 0,
    superclass: {
      __ref: "client:root:ontologies:0:classes:4:superclass",
    },
  },
  "client:root:ontologies:0:classes:4:superclass": {
    __id: "client:root:ontologies:0:classes:4:superclass",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Entity",
  },
  "client:root:ontologies:0:classes:5": {
    __id: "client:root:ontologies:0:classes:5",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Tier",
    label: "Tier",
    isAbstract: false,
    instanceCount: 15,
    superclass: {
      __ref: "client:root:ontologies:0:classes:5:superclass",
    },
  },
  "client:root:ontologies:0:classes:5:superclass": {
    __id: "client:root:ontologies:0:classes:5:superclass",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Entity",
  },
  "client:root:ontologies:0:classes:6": {
    __id: "client:root:ontologies:0:classes:6",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Property",
    label: "Property",
    isAbstract: false,
    instanceCount: 0,
    superclass: {
      __ref: "client:root:ontologies:0:classes:6:superclass",
    },
  },
  "client:root:ontologies:0:classes:6:superclass": {
    __id: "client:root:ontologies:0:classes:6:superclass",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Entity",
  },
  "client:root:ontologies:0:classes:7": {
    __id: "client:root:ontologies:0:classes:7",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/ModifierFamily",
    label: "Modifier Family",
    isAbstract: false,
    instanceCount: 9,
    superclass: {
      __ref: "client:root:ontologies:0:classes:7:superclass",
    },
  },
  "client:root:ontologies:0:classes:7:superclass": {
    __id: "client:root:ontologies:0:classes:7:superclass",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/UIElement",
  },
  "client:root:ontologies:0:classes:8": {
    __id: "client:root:ontologies:0:classes:8",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Modifier",
    label: "Modifier",
    isAbstract: false,
    instanceCount: 27,
    superclass: {
      __ref: "client:root:ontologies:0:classes:8:superclass",
    },
  },
  "client:root:ontologies:0:classes:8:superclass": {
    __id: "client:root:ontologies:0:classes:8:superclass",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/UIElement",
  },
  "client:root:ontologies:0:classes:9": {
    __id: "client:root:ontologies:0:classes:9",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Group",
    label: "Group",
    isAbstract: false,
    instanceCount: 9,
    superclass: {
      __ref: "client:root:ontologies:0:classes:9:superclass",
    },
  },
  "client:root:ontologies:0:classes:9:superclass": {
    __id: "client:root:ontologies:0:classes:9:superclass",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/UIBlock",
  },
  "client:root:ontologies:0:classes:10": {
    __id: "client:root:ontologies:0:classes:10",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Subcomponent",
    label: "Subcomponent",
    isAbstract: false,
    instanceCount: 85,
    superclass: {
      __ref: "client:root:ontologies:0:classes:10:superclass",
    },
  },
  "client:root:ontologies:0:classes:10:superclass": {
    __id: "client:root:ontologies:0:classes:10:superclass",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/UIBlock",
  },
  "client:root:ontologies:0:classes:11": {
    __id: "client:root:ontologies:0:classes:11",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Layout",
    label: "Layout",
    isAbstract: false,
    instanceCount: 14,
    superclass: {
      __ref: "client:root:ontologies:0:classes:11:superclass",
    },
  },
  "client:root:ontologies:0:classes:11:superclass": {
    __id: "client:root:ontologies:0:classes:11:superclass",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/UIBlock",
  },
  "client:root:ontologies:0:classes:12": {
    __id: "client:root:ontologies:0:classes:12",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Pattern",
    label: "Pattern",
    isAbstract: false,
    instanceCount: 41,
    superclass: {
      __ref: "client:root:ontologies:0:classes:12:superclass",
    },
  },
  "client:root:ontologies:0:classes:12:superclass": {
    __id: "client:root:ontologies:0:classes:12:superclass",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/UIBlock",
  },
  "client:root:ontologies:0:classes:13": {
    __id: "client:root:ontologies:0:classes:13",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Component",
    label: "Component",
    isAbstract: false,
    instanceCount: 108,
    superclass: {
      __ref: "client:root:ontologies:0:classes:13:superclass",
    },
  },
  "client:root:ontologies:0:classes:13:superclass": {
    __id: "client:root:ontologies:0:classes:13:superclass",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/UIBlock",
  },
  "client:root:ontologies:0:classes:14": {
    __id: "client:root:ontologies:0:classes:14",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/UIBlock",
    label: "UI Block",
    isAbstract: true,
    instanceCount: 0,
    superclass: {
      __ref: "client:root:ontologies:0:classes:14:superclass",
    },
  },
  "client:root:ontologies:0:classes:14:superclass": {
    __id: "client:root:ontologies:0:classes:14:superclass",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/UIElement",
  },
  "client:root:ontologies:0:classes:15": {
    __id: "client:root:ontologies:0:classes:15",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/UIElement",
    label: "UI Element",
    isAbstract: true,
    instanceCount: 0,
    superclass: {
      __ref: "client:root:ontologies:0:classes:15:superclass",
    },
  },
  "client:root:ontologies:0:classes:15:superclass": {
    __id: "client:root:ontologies:0:classes:15:superclass",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Entity",
  },
  "client:root:ontologies:0:classes:16": {
    __id: "client:root:ontologies:0:classes:16",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Entity",
    label: "Entity",
    isAbstract: true,
    instanceCount: 0,
    superclass: null,
  },
  "client:root:ontologies:0:properties:0": {
    __id: "client:root:ontologies:0:properties:0",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/libraryTier",
    label: "libraryTier",
    kind: "OBJECT",
  },
  "client:root:ontologies:0:properties:1": {
    __id: "client:root:ontologies:0:properties:1",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/library",
    label: "library",
    kind: "OBJECT",
  },
  "client:root:ontologies:0:properties:2": {
    __id: "client:root:ontologies:0:properties:2",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/implementsBlock",
    label: "implementsBlock",
    kind: "OBJECT",
  },
  "client:root:ontologies:0:properties:3": {
    __id: "client:root:ontologies:0:properties:3",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/category",
    label: "category",
    kind: "OBJECT",
  },
  "client:root:ontologies:0:properties:4": {
    __id: "client:root:ontologies:0:properties:4",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/hasSubcomponent",
    label: "hasSubcomponent",
    kind: "OBJECT",
  },
  "client:root:ontologies:0:properties:5": {
    __id: "client:root:ontologies:0:properties:5",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/parentComponent",
    label: "parentComponent",
    kind: "OBJECT",
  },
  "client:root:ontologies:0:properties:6": {
    __id: "client:root:ontologies:0:properties:6",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/hasModifier",
    label: "hasModifier",
    kind: "OBJECT",
  },
  "client:root:ontologies:0:properties:7": {
    __id: "client:root:ontologies:0:properties:7",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/modifierFamily",
    label: "modifierFamily",
    kind: "OBJECT",
  },
  "client:root:ontologies:0:properties:8": {
    __id: "client:root:ontologies:0:properties:8",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/hasVariant",
    label: "hasVariant",
    kind: "OBJECT",
  },
  "client:root:ontologies:0:properties:9": {
    __id: "client:root:ontologies:0:properties:9",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/variantOf",
    label: "variantOf",
    kind: "OBJECT",
  },
  "client:root:ontologies:0:properties:10": {
    __id: "client:root:ontologies:0:properties:10",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/specializedBy",
    label: "specializedBy",
    kind: "OBJECT",
  },
  "client:root:ontologies:0:properties:11": {
    __id: "client:root:ontologies:0:properties:11",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/inheritsFrom",
    label: "inheritsFrom",
    kind: "OBJECT",
  },
  "client:root:ontologies:0:properties:12": {
    __id: "client:root:ontologies:0:properties:12",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/changeLog",
    label: "changeLog",
    kind: "OBJECT",
  },
  "client:root:ontologies:0:properties:13": {
    __id: "client:root:ontologies:0:properties:13",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/documentationStage",
    label: "documentationStage",
    kind: "OBJECT",
  },
  "client:root:ontologies:0:properties:14": {
    __id: "client:root:ontologies:0:properties:14",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/hasProperty",
    label: "hasProperty",
    kind: "OBJECT",
  },
  "client:root:ontologies:0:properties:15": {
    __id: "client:root:ontologies:0:properties:15",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/hasModifierFamily",
    label: "hasModifierFamily",
    kind: "OBJECT",
  },
  "client:root:ontologies:0:properties:16": {
    __id: "client:root:ontologies:0:properties:16",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/tier",
    label: "tier",
    kind: "OBJECT",
  },
  "client:root:ontologies:0:properties:17": {
    __id: "client:root:ontologies:0:properties:17",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/documentation",
    label: "documentation",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:18": {
    __id: "client:root:ontologies:0:properties:18",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/link",
    label: "link",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:19": {
    __id: "client:root:ontologies:0:properties:19",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/platform",
    label: "platform",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:20": {
    __id: "client:root:ontologies:0:properties:20",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/libraryName",
    label: "libraryName",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:21": {
    __id: "client:root:ontologies:0:properties:21",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/isDraft",
    label: "isDraft",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:22": {
    __id: "client:root:ontologies:0:properties:22",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/versionedLink",
    label: "versionedLink",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:23": {
    __id: "client:root:ontologies:0:properties:23",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/headLink",
    label: "headLink",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:24": {
    __id: "client:root:ontologies:0:properties:24",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/implementationVersion",
    label: "implementationVersion",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:25": {
    __id: "client:root:ontologies:0:properties:25",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/constraints",
    label: "constraints",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:26": {
    __id: "client:root:ontologies:0:properties:26",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/defaultValue",
    label: "defaultValue",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:27": {
    __id: "client:root:ontologies:0:properties:27",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/optional",
    label: "optional",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:28": {
    __id: "client:root:ontologies:0:properties:28",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/propertyType",
    label: "propertyType",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:29": {
    __id: "client:root:ontologies:0:properties:29",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/targetDevices",
    label: "targetDevices",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:30": {
    __id: "client:root:ontologies:0:properties:30",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/changeType",
    label: "changeType",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:31": {
    __id: "client:root:ontologies:0:properties:31",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/githubLink",
    label: "githubLink",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:32": {
    __id: "client:root:ontologies:0:properties:32",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/owner",
    label: "owner",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:33": {
    __id: "client:root:ontologies:0:properties:33",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/change",
    label: "change",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:34": {
    __id: "client:root:ontologies:0:properties:34",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/timestamp",
    label: "timestamp",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:35": {
    __id: "client:root:ontologies:0:properties:35",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/whenToRemove",
    label: "whenToRemove",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:36": {
    __id: "client:root:ontologies:0:properties:36",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/whenToApply",
    label: "whenToApply",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:37": {
    __id: "client:root:ontologies:0:properties:37",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/gridAreas",
    label: "gridAreas",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:38": {
    __id: "client:root:ontologies:0:properties:38",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/domain",
    label: "domain",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:39": {
    __id: "client:root:ontologies:0:properties:39",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/grid",
    label: "grid",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:40": {
    __id: "client:root:ontologies:0:properties:40",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/standalone",
    label: "standalone",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:41": {
    __id: "client:root:ontologies:0:properties:41",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/guidelines",
    label: "guidelines",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:42": {
    __id: "client:root:ontologies:0:properties:42",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/usage",
    label: "usage",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:43": {
    __id: "client:root:ontologies:0:properties:43",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/anatomyDsl",
    label: "anatomyDsl",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:44": {
    __id: "client:root:ontologies:0:properties:44",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/anatomyClassic",
    label: "anatomyClassic",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:45": {
    __id: "client:root:ontologies:0:properties:45",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/figmaLink",
    label: "figmaLink",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:46": {
    __id: "client:root:ontologies:0:properties:46",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/decisionLog",
    label: "decisionLog",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:47": {
    __id: "client:root:ontologies:0:properties:47",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/version",
    label: "version",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:48": {
    __id: "client:root:ontologies:0:properties:48",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/summary",
    label: "summary",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:49": {
    __id: "client:root:ontologies:0:properties:49",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/name",
    label: "name",
    kind: "DATATYPE",
  },
  "client:root:ontologies:0:properties:50": {
    __id: "client:root:ontologies:0:properties:50",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/completionGuidance",
    label: "completionGuidance",
    kind: "ANNOTATION",
  },
  "client:root:ontologies:0:properties:51": {
    __id: "client:root:ontologies:0:properties:51",
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/acceptanceCriteria",
    label: "acceptanceCriteria",
    kind: "ANNOTATION",
  },
  "client:root:ontologies:1": {
    __id: "client:root:ontologies:1",
    __typename: "Ontology",
    prefix: "cs",
    namespace: "http://pragma.canonical.com/codestandards#",
    label: "cs",
    classes: {
      __refs: [
        "client:root:ontologies:1:classes:0",
        "client:root:ontologies:1:classes:1",
        "client:root:ontologies:1:classes:2",
      ],
    },
    properties: {
      __refs: [
        "client:root:ontologies:1:properties:0",
        "client:root:ontologies:1:properties:1",
        "client:root:ontologies:1:properties:2",
        "client:root:ontologies:1:properties:3",
        "client:root:ontologies:1:properties:4",
        "client:root:ontologies:1:properties:5",
        "client:root:ontologies:1:properties:6",
        "client:root:ontologies:1:properties:7",
        "client:root:ontologies:1:properties:8",
      ],
    },
  },
  "client:root:ontologies:1:classes:0": {
    __id: "client:root:ontologies:1:classes:0",
    __typename: "OntologyClass",
    uri: "http://pragma.canonical.com/codestandards#Example",
    label: "Example",
    isAbstract: false,
    instanceCount: 0,
    superclass: null,
  },
  "client:root:ontologies:1:classes:1": {
    __id: "client:root:ontologies:1:classes:1",
    __typename: "OntologyClass",
    uri: "http://pragma.canonical.com/codestandards#Category",
    label: "Category",
    isAbstract: false,
    instanceCount: 19,
    superclass: null,
  },
  "client:root:ontologies:1:classes:2": {
    __id: "client:root:ontologies:1:classes:2",
    __typename: "OntologyClass",
    uri: "http://pragma.canonical.com/codestandards#CodeStandard",
    label: "Code Standard",
    isAbstract: false,
    instanceCount: 131,
    superclass: null,
  },
  "client:root:ontologies:1:properties:0": {
    __id: "client:root:ontologies:1:properties:0",
    __typename: "OntologyProperty",
    uri: "http://pragma.canonical.com/codestandards#dont",
    label: "don't",
    kind: "OBJECT",
  },
  "client:root:ontologies:1:properties:1": {
    __id: "client:root:ontologies:1:properties:1",
    __typename: "OntologyProperty",
    uri: "http://pragma.canonical.com/codestandards#do",
    label: "do",
    kind: "OBJECT",
  },
  "client:root:ontologies:1:properties:2": {
    __id: "client:root:ontologies:1:properties:2",
    __typename: "OntologyProperty",
    uri: "http://pragma.canonical.com/codestandards#extends",
    label: "extends",
    kind: "OBJECT",
  },
  "client:root:ontologies:1:properties:3": {
    __id: "client:root:ontologies:1:properties:3",
    __typename: "OntologyProperty",
    uri: "http://pragma.canonical.com/codestandards#hasCategory",
    label: "has category",
    kind: "OBJECT",
  },
  "client:root:ontologies:1:properties:4": {
    __id: "client:root:ontologies:1:properties:4",
    __typename: "OntologyProperty",
    uri: "http://pragma.canonical.com/codestandards#code",
    label: "code",
    kind: "DATATYPE",
  },
  "client:root:ontologies:1:properties:5": {
    __id: "client:root:ontologies:1:properties:5",
    __typename: "OntologyProperty",
    uri: "http://pragma.canonical.com/codestandards#language",
    label: "language",
    kind: "DATATYPE",
  },
  "client:root:ontologies:1:properties:6": {
    __id: "client:root:ontologies:1:properties:6",
    __typename: "OntologyProperty",
    uri: "http://pragma.canonical.com/codestandards#description",
    label: "description",
    kind: "DATATYPE",
  },
  "client:root:ontologies:1:properties:7": {
    __id: "client:root:ontologies:1:properties:7",
    __typename: "OntologyProperty",
    uri: "http://pragma.canonical.com/codestandards#slug",
    label: "slug",
    kind: "DATATYPE",
  },
  "client:root:ontologies:1:properties:8": {
    __id: "client:root:ontologies:1:properties:8",
    __typename: "OntologyProperty",
    uri: "http://pragma.canonical.com/codestandards#name",
    label: "name",
    kind: "DATATYPE",
  },
  "client:root:ontologies:2": {
    __id: "client:root:ontologies:2",
    __typename: "Ontology",
    prefix: "anatomy",
    namespace: "http://anatomy-dsl.example.org/ontology#",
    label: "anatomy",
    classes: {
      __refs: [
        "client:root:ontologies:2:classes:0",
        "client:root:ontologies:2:classes:1",
        "client:root:ontologies:2:classes:2",
        "client:root:ontologies:2:classes:3",
        "client:root:ontologies:2:classes:4",
        "client:root:ontologies:2:classes:5",
        "client:root:ontologies:2:classes:6",
        "client:root:ontologies:2:classes:7",
        "client:root:ontologies:2:classes:8",
      ],
    },
    properties: {
      __refs: [
        "client:root:ontologies:2:properties:0",
        "client:root:ontologies:2:properties:1",
        "client:root:ontologies:2:properties:2",
        "client:root:ontologies:2:properties:3",
        "client:root:ontologies:2:properties:4",
        "client:root:ontologies:2:properties:5",
        "client:root:ontologies:2:properties:6",
        "client:root:ontologies:2:properties:7",
        "client:root:ontologies:2:properties:8",
        "client:root:ontologies:2:properties:9",
        "client:root:ontologies:2:properties:10",
        "client:root:ontologies:2:properties:11",
        "client:root:ontologies:2:properties:12",
        "client:root:ontologies:2:properties:13",
        "client:root:ontologies:2:properties:14",
      ],
    },
  },
  "client:root:ontologies:2:classes:0": {
    __id: "client:root:ontologies:2:classes:0",
    __typename: "OntologyClass",
    uri: "http://anatomy-dsl.example.org/ontology#SwitchCase",
    label: "Switch Case",
    isAbstract: false,
    instanceCount: 0,
    superclass: null,
  },
  "client:root:ontologies:2:classes:1": {
    __id: "client:root:ontologies:2:classes:1",
    __typename: "OntologyClass",
    uri: "http://anatomy-dsl.example.org/ontology#Switch",
    label: "Switch",
    isAbstract: false,
    instanceCount: 0,
    superclass: null,
  },
  "client:root:ontologies:2:classes:2": {
    __id: "client:root:ontologies:2:classes:2",
    __typename: "OntologyClass",
    uri: "http://anatomy-dsl.example.org/ontology#Style",
    label: "Style",
    isAbstract: false,
    instanceCount: 0,
    superclass: null,
  },
  "client:root:ontologies:2:classes:3": {
    __id: "client:root:ontologies:2:classes:3",
    __typename: "OntologyClass",
    uri: "http://anatomy-dsl.example.org/ontology#Relation",
    label: "Relation",
    isAbstract: false,
    instanceCount: 0,
    superclass: null,
  },
  "client:root:ontologies:2:classes:4": {
    __id: "client:root:ontologies:2:classes:4",
    __typename: "OntologyClass",
    uri: "http://anatomy-dsl.example.org/ontology#Edge",
    label: "Edge",
    isAbstract: false,
    instanceCount: 0,
    superclass: null,
  },
  "client:root:ontologies:2:classes:5": {
    __id: "client:root:ontologies:2:classes:5",
    __typename: "OntologyClass",
    uri: "http://anatomy-dsl.example.org/ontology#AnonymousNode",
    label: "Anonymous Node",
    isAbstract: false,
    instanceCount: 0,
    superclass: {
      __ref: "client:root:ontologies:2:classes:5:superclass",
    },
  },
  "client:root:ontologies:2:classes:5:superclass": {
    __id: "client:root:ontologies:2:classes:5:superclass",
    __typename: "OntologyClass",
    uri: "http://anatomy-dsl.example.org/ontology#Node",
  },
  "client:root:ontologies:2:classes:6": {
    __id: "client:root:ontologies:2:classes:6",
    __typename: "OntologyClass",
    uri: "http://anatomy-dsl.example.org/ontology#NamedNode",
    label: "Named Node",
    isAbstract: false,
    instanceCount: 0,
    superclass: {
      __ref: "client:root:ontologies:2:classes:6:superclass",
    },
  },
  "client:root:ontologies:2:classes:6:superclass": {
    __id: "client:root:ontologies:2:classes:6:superclass",
    __typename: "OntologyClass",
    uri: "http://anatomy-dsl.example.org/ontology#Node",
  },
  "client:root:ontologies:2:classes:7": {
    __id: "client:root:ontologies:2:classes:7",
    __typename: "OntologyClass",
    uri: "http://anatomy-dsl.example.org/ontology#Node",
    label: "Node",
    isAbstract: true,
    instanceCount: 0,
    superclass: null,
  },
  "client:root:ontologies:2:classes:8": {
    __id: "client:root:ontologies:2:classes:8",
    __typename: "OntologyClass",
    uri: "http://anatomy-dsl.example.org/ontology#Specification",
    label: "Specification",
    isAbstract: false,
    instanceCount: 0,
    superclass: null,
  },
  "client:root:ontologies:2:properties:0": {
    __id: "client:root:ontologies:2:properties:0",
    __typename: "OntologyProperty",
    uri: "http://anatomy-dsl.example.org/ontology#hasStyle",
    label: "has style",
    kind: "OBJECT",
  },
  "client:root:ontologies:2:properties:1": {
    __id: "client:root:ontologies:2:properties:1",
    __typename: "OntologyProperty",
    uri: "http://anatomy-dsl.example.org/ontology#caseNode",
    label: "case node",
    kind: "OBJECT",
  },
  "client:root:ontologies:2:properties:2": {
    __id: "client:root:ontologies:2:properties:2",
    __typename: "OntologyProperty",
    uri: "http://anatomy-dsl.example.org/ontology#hasCase",
    label: "has case",
    kind: "OBJECT",
  },
  "client:root:ontologies:2:properties:3": {
    __id: "client:root:ontologies:2:properties:3",
    __typename: "OntologyProperty",
    uri: "http://anatomy-dsl.example.org/ontology#edgeSwitch",
    label: "edge switch",
    kind: "OBJECT",
  },
  "client:root:ontologies:2:properties:4": {
    __id: "client:root:ontologies:2:properties:4",
    __typename: "OntologyProperty",
    uri: "http://anatomy-dsl.example.org/ontology#edgeTarget",
    label: "edge target",
    kind: "OBJECT",
  },
  "client:root:ontologies:2:properties:5": {
    __id: "client:root:ontologies:2:properties:5",
    __typename: "OntologyProperty",
    uri: "http://anatomy-dsl.example.org/ontology#hasRelation",
    label: "has relation",
    kind: "OBJECT",
  },
  "client:root:ontologies:2:properties:6": {
    __id: "client:root:ontologies:2:properties:6",
    __typename: "OntologyProperty",
    uri: "http://anatomy-dsl.example.org/ontology#hasEdge",
    label: "has edge",
    kind: "OBJECT",
  },
  "client:root:ontologies:2:properties:7": {
    __id: "client:root:ontologies:2:properties:7",
    __typename: "OntologyProperty",
    uri: "http://anatomy-dsl.example.org/ontology#rootNode",
    label: "root node",
    kind: "OBJECT",
  },
  "client:root:ontologies:2:properties:8": {
    __id: "client:root:ontologies:2:properties:8",
    __typename: "OntologyProperty",
    uri: "http://anatomy-dsl.example.org/ontology#styleValue",
    label: "style value",
    kind: "DATATYPE",
  },
  "client:root:ontologies:2:properties:9": {
    __id: "client:root:ontologies:2:properties:9",
    __typename: "OntologyProperty",
    uri: "http://anatomy-dsl.example.org/ontology#styleKey",
    label: "style key",
    kind: "DATATYPE",
  },
  "client:root:ontologies:2:properties:10": {
    __id: "client:root:ontologies:2:properties:10",
    __typename: "OntologyProperty",
    uri: "http://anatomy-dsl.example.org/ontology#slotName",
    label: "slot name",
    kind: "DATATYPE",
  },
  "client:root:ontologies:2:properties:11": {
    __id: "client:root:ontologies:2:properties:11",
    __typename: "OntologyProperty",
    uri: "http://anatomy-dsl.example.org/ontology#cardinality",
    label: "cardinality",
    kind: "DATATYPE",
  },
  "client:root:ontologies:2:properties:12": {
    __id: "client:root:ontologies:2:properties:12",
    __typename: "OntologyProperty",
    uri: "http://anatomy-dsl.example.org/ontology#discriminator",
    label: "discriminator",
    kind: "DATATYPE",
  },
  "client:root:ontologies:2:properties:13": {
    __id: "client:root:ontologies:2:properties:13",
    __typename: "OntologyProperty",
    uri: "http://anatomy-dsl.example.org/ontology#role",
    label: "role",
    kind: "DATATYPE",
  },
  "client:root:ontologies:2:properties:14": {
    __id: "client:root:ontologies:2:properties:14",
    __typename: "OntologyProperty",
    uri: "http://anatomy-dsl.example.org/ontology#uri",
    label: "uri",
    kind: "DATATYPE",
  },
  'client:root:ontologyProperty(uri:"ds:hasSubcomponent")': {
    __id: 'client:root:ontologyProperty(uri:"ds:hasSubcomponent")',
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/hasSubcomponent",
    label: "hasSubcomponent",
    definition: "Subcomponents that are structural parts of this component",
    kind: "OBJECT",
    functional: false,
    range: "https://ds.canonical.com/Subcomponent",
    namespace: "ds",
    domain: {
      __ref: 'client:root:ontologyProperty(uri:"ds:hasSubcomponent"):domain',
    },
    inverse: {
      __ref: 'client:root:ontologyProperty(uri:"ds:hasSubcomponent"):inverse',
    },
    acceptanceCriteria:
      "Inverse of ds:parentComponent. Each referenced entity must be a ds:Subcomponent.",
    completionGuidance: null,
  },
  'client:root:ontologyProperty(uri:"ds:hasSubcomponent"):domain': {
    __id: 'client:root:ontologyProperty(uri:"ds:hasSubcomponent"):domain',
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Component",
    label: "Component",
  },
  'client:root:ontologyProperty(uri:"ds:hasSubcomponent"):inverse': {
    __id: 'client:root:ontologyProperty(uri:"ds:hasSubcomponent"):inverse',
    __typename: "OntologyProperty",
    uri: "https://ds.canonical.com/parentComponent",
    label: "parentComponent",
  },
} as unknown as RecordMap;

export default definitionsExplorerRecordsProperty;
