// Generated by @canonical/summon-component:react v0.1.0

import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import RelationsSection from "./RelationsSection.js";

describe("RelationsSection", () => {
  it("renders children", () => {
    render(<RelationsSection>Test content</RelationsSection>);
    expect(screen.getByText("Test content")).toBeInTheDocument();
  });

  it("applies custom className", () => {
    render(
      <RelationsSection className="custom-class">Content</RelationsSection>,
    );
    const element = screen.getByText("Content");
    expect(element.className).toContain("ds relations-section");
    expect(element.className).toContain("custom-class");
  });

  it("passes through additional props", () => {
    render(
      <RelationsSection data-testid="test-component">Content</RelationsSection>,
    );
    expect(screen.getByTestId("test-component")).toBeInTheDocument();
  });
});
