// Generated by @canonical/summon-component:react v0.1.0

import type { Meta, StoryObj } from "@storybook/react-vite";
import RelationsSection from "./RelationsSection.js";

const meta: Meta<typeof RelationsSection> = {
  title: "Components/RelationsSection",
  component: RelationsSection,
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof RelationsSection>;

export const Default: Story = {
  args: {
    children: "Hello, RelationsSection!",
  },
};

export const WithCustomClass: Story = {
  args: {
    children: "Custom styled",
    className: "custom-class",
  },
};
