// Generated by @canonical/summon-component:lit v0.1.0

import { afterEach, beforeEach, describe, expect, it } from "vitest";
import "./BasicSection.js";
import type BasicSection from "./BasicSection.js";

describe("BasicSection component", () => {
  let elem: BasicSection;

  beforeEach(() => {
    elem = document.createElement("ds-basic-section") as BasicSection;
    document.body.appendChild(elem);
  });

  afterEach(() => {
    elem.remove();
  });

  it("should render component", async () => {
    await customElements.whenDefined("ds-basic-section");

    const container = elem.shadowRoot?.querySelector(".ds.basic-section");
    expect(container).toBeTruthy();
  });

  it("should have correct tag name", () => {
    expect(elem.tagName.toLowerCase()).toBe("ds-basic-section");
  });
});
