// Generated by @canonical/summon-component:lit v0.1.0

import { html, LitElement } from "lit";
import { customElement, property } from "lit/decorators.js";
import { classMap } from "lit/directives/class-map.js";
import styles from "./styles.css";
import type { BasicSectionProps } from "./types.js";

const componentCssClassName = "ds basic-section";

/**
 * BasicSection web component.
 *
 * @implements ds:global.component.basic-section
 */
@customElement("ds-basic-section")
export default class BasicSection
  extends LitElement
  implements BasicSectionProps
{
  static styles = styles;

  @property({ type: Object }) sectionTitle = {
    text: "",
    linkAttrs: {
      href: "",
    },
  };
  @property({ type: Object }) subtitle = {
    text: "",
    headingLevel: 4,
  };
  @property({ type: String }) label = "";
  @property({ type: String })
  padding: "deep" | "shallow" | "default" = "default";
  @property({ type: String })
  topRule: "highlighted" | "muted" | "none" | "default" = "default";
  @property({ type: Boolean })
  isSplitOnMedium = false;

  renderTitle() {
    const titleContent =
      this.sectionTitle.linkAttrs?.href?.length > 0
        ? html`<a href="${this.sectionTitle.linkAttrs.href}">${this.sectionTitle.text}</a>`
        : html`${this.sectionTitle.text}`;

    return html`<h2 class="title">${titleContent}</h2>`;
  }

  renderSubtitle() {
    const headingLevel = this.subtitle?.headingLevel ?? 4;
    return html`<p class="subtitle heading-${headingLevel}">${this.subtitle.text}</p>`;
  }

  render() {
    const sectionClasses = {
      [componentCssClassName]: true,
      [`is-${this.padding}`]: this.padding !== "default",
      ["is-split-on-medium"]: this.isSplitOnMedium,
    };

    return html`
      <div class=${classMap(sectionClasses)}>
        <hr class="${this.topRule}" />
        <div class="header">
          <h3 class="label">${this.label}</h3>
          ${this.renderTitle()}
        </div>
        <div class="content">
          ${this.renderSubtitle()}
        </div>
      </div>
    `;
  }
}
