// Generated by component/react v0.1.0
// Generated by @canonical/summon:component-react v0.1.0

import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import TSection from "./TSection.js";

describe("TSection", () => {
  it("renders children", () => {
    render(<TSection>Test content</TSection>);
    expect(screen.getByText("Test content")).toBeInTheDocument();
  });

  it("applies custom className", () => {
    const { container } = render(<TSection className="custom-class" />);
    expect(container.firstChild).toHaveClass("ds", "section", "custom-class");
  });

  it("passes through additional props", () => {
    render(<TSection data-testid="test-component">Content</TSection>);
    expect(screen.getByTestId("test-component")).toBeInTheDocument();
  });
});
