// Generated by @canonical/summon-component:react v0.1.0

import { renderToString } from "react-dom/server";
import { describe, expect, it } from "vitest";
import DefinitionsExplorer from "./DefinitionsExplorer.js";

describe("DefinitionsExplorer SSR", () => {
  it("renders without hydration errors", () => {
    const html = renderToString(
      <DefinitionsExplorer>Test content</DefinitionsExplorer>,
    );
    expect(html).toContain("Test content");
    expect(html).toContain("ds definitions-explorer");
  });
});
