// Generated by @canonical/summon-component:react v0.1.0

import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import DefinitionsExplorer from "./DefinitionsExplorer.js";

describe("DefinitionsExplorer", () => {
  it("renders children", () => {
    render(<DefinitionsExplorer>Test content</DefinitionsExplorer>);
    expect(screen.getByText("Test content")).toBeInTheDocument();
  });

  it("applies custom className", () => {
    render(
      <DefinitionsExplorer className="custom-class">
        Content
      </DefinitionsExplorer>,
    );
    const element = screen.getByText("Content");
    expect(element.className).toContain("ds definitions-explorer");
    expect(element.className).toContain("custom-class");
  });

  it("passes through additional props", () => {
    render(
      <DefinitionsExplorer data-testid="test-component">
        Content
      </DefinitionsExplorer>,
    );
    expect(screen.getByTestId("test-component")).toBeInTheDocument();
  });
});
