// Generated by @canonical/summon-component:react v0.1.0

import type { Meta, StoryObj } from "@storybook/react-vite";
import ModeStrip from "./ModeStrip.js";

const meta: Meta<typeof ModeStrip> = {
  title: "Components/ModeStrip",
  component: ModeStrip,
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof ModeStrip>;

export const Default: Story = {
  args: {
    children: "Hello, ModeStrip!",
  },
};

export const WithCustomClass: Story = {
  args: {
    children: "Custom styled",
    className: "custom-class",
  },
};
