// Generated by @canonical/summon-component:react v0.1.0

import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import ModeStrip from "./ModeStrip.js";

describe("ModeStrip", () => {
  it("renders children", () => {
    render(<ModeStrip>Test content</ModeStrip>);
    expect(screen.getByText("Test content")).toBeInTheDocument();
  });

  it("applies custom className", () => {
    render(<ModeStrip className="custom-class">Content</ModeStrip>);
    const element = screen.getByText("Content");
    expect(element.className).toContain("ds mode-strip");
    expect(element.className).toContain("custom-class");
  });

  it("passes through additional props", () => {
    render(<ModeStrip data-testid="test-component">Content</ModeStrip>);
    expect(screen.getByTestId("test-component")).toBeInTheDocument();
  });
});
