// Generated by @canonical/summon-component:react v0.1.0

import { renderToString } from "react-dom/server";
import { describe, expect, it } from "vitest";
import ModeStrip from "./ModeStrip.js";

describe("ModeStrip SSR", () => {
  it("renders without hydration errors", () => {
    const html = renderToString(<ModeStrip>Test content</ModeStrip>);
    expect(html).toContain("Test content");
    expect(html).toContain("ds mode-strip");
  });
});
