// Generated by @canonical/summon-component:react v0.1.0

import type { HTMLAttributes, ReactNode } from "react";

export interface ModeStripProps
  extends Omit<HTMLAttributes<HTMLElement>, "children"> {
  /** The mode's context/title, west slot. Empty until a layout claims it. */
  context?: string;
  /** The composed layout's controls region content (`ControlsRegion`). */
  controls?: ReactNode;
  /** The composed layout's status region content (`StatusRegion`). */
  status?: ReactNode;
}
