name: "react-ds-app/chromatic"
on:
  pull_request:
    paths:
      - configs/storybook/**
      - packages/tokens/**
      - packages/styles/**
      - packages/utils/**
      - packages/react/ds-core/**
      - packages/react/ds-app/**
  push:
    branches:
      - main
    paths:
      - configs/storybook/**
      - packages/tokens/**
      - packages/styles/**
      - packages/utils/**
      - packages/react/ds-core/**
      - packages/react/ds-app/**
jobs:
  test-compile:
    uses: ./.github/workflows/chromatic._template.yml
    secrets:
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_TOKEN_CANONICAL_REACT_DS_APP }}
    with:
      working-directory: packages/react/ds-app
      externals: '[
        "configs/storybook/**",
        "packages/tokens/**",
        "packages/styles/**",
        "packages/utils/**",
        "packages/react/ds-core/**"
      ]'
