name: Main branch update

on:
  push:
    branches:
      - main

env:
  NX_SELF_HOSTED_REMOTE_CACHE_SERVER: "http://localhost:9876"
  NX_SELF_HOSTED_REMOTE_CACHE_ACCESS_TOKEN: "local"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          build-target: build:all

  check:
    name: Code quality checks
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          build-target: build:all

      - name: Code quality checks
        run: bun run check

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          build-target: build:all

      - name: Test
        run: bun run test
