name: Main branch update

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Code quality checks
        run: bun run check

        # TODO we could also upload the current coverage results to GH pages like MAAS does
        # https://github.com/canonical/maas-ui/blob/b69e5401cca09d6c6b6e0ade75b16727e701ab0d/.github/workflows/coverage.yaml#L97-L107
        # https://canonical.github.io/maas-ui/
      - name: Test with coverage
        uses: ./.github/actions/coverage
