// Generated by @canonical/summon-component:react v0.1.0

import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import EntityHeader from "./EntityHeader.js";

describe("EntityHeader", () => {
  it("renders children", () => {
    render(<EntityHeader>Test content</EntityHeader>);
    expect(screen.getByText("Test content")).toBeInTheDocument();
  });

  it("applies custom className", () => {
    render(<EntityHeader className="custom-class">Content</EntityHeader>);
    const element = screen.getByText("Content");
    expect(element.className).toContain("ds entity-header");
    expect(element.className).toContain("custom-class");
  });

  it("passes through additional props", () => {
    render(<EntityHeader data-testid="test-component">Content</EntityHeader>);
    expect(screen.getByTestId("test-component")).toBeInTheDocument();
  });
});
