// Generated by @canonical/summon-component:react v0.1.0

import type React from "react";
import type { EntityHeaderProps } from "./types.js";
import "./styles.css";

const componentCssClassName = "ds entity-header";

/**
 * EntityHeader component
 */
const EntityHeader = ({
  className,
  children,
  ...props
}: EntityHeaderProps): React.ReactElement => {
  return (
    <div
      className={[componentCssClassName, className].filter(Boolean).join(" ")}
      {...props}
    >
      {children}
    </div>
  );
};

export default EntityHeader;
