// Generated by @canonical/summon-component:react v0.1.0

import type { Meta, StoryObj } from "@storybook/react-vite";
import EntityHeader from "./EntityHeader.js";

const meta: Meta<typeof EntityHeader> = {
  title: "Components/EntityHeader",
  component: EntityHeader,
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof EntityHeader>;

export const Default: Story = {
  args: {
    children: "Hello, EntityHeader!",
  },
};

export const WithCustomClass: Story = {
  args: {
    children: "Custom styled",
    className: "custom-class",
  },
};
