// Generated by @canonical/summon-application:application/react v0.1.0

import { HeadProvider } from "@canonical/react-head";
import { createBrowserRouter } from "@canonical/router-core";
import { Outlet, RouterProvider } from "@canonical/router-react";
import { hydrateRoot } from "react-dom/client";
import { RelayEnvironmentProvider } from "react-relay";
import { createEnvironment } from "#relay/environment.js";
import { appRoutes, middleware, notFoundRoute } from "../routes.js";
import type { InitialData } from "../server/entry.js";
import "#styles/index.css";

const router = createBrowserRouter(appRoutes, {
  middleware: [...middleware],
  notFound: notFoundRoute,
});

// The SSR servers embed `__INITIAL_DATA__` via the renderer's bootstrap
// script, which executes before this module (module scripts are deferred).
// The two SPA cells have no such global at all — hence every step of the
// chain below is optional.
const initialData = (
  window as Window & { readonly __INITIAL_DATA__?: InitialData }
).__INITIAL_DATA__;

// One Relay environment (network + normalized store) for the whole browser
// session — module scope, so client-side navigations share the cache. Seeded
// from the server-serialised records, so the hydration render reads the same
// bytes the server rendered from and nothing refetches.
const relayEnvironment = createEnvironment({
  records: initialData?.relay?.records,
});

const root = document.getElementById("root");
if (!root) {
  throw new Error('Root element "#root" not found');
}

hydrateRoot(
  root,
  <HeadProvider>
    <RelayEnvironmentProvider environment={relayEnvironment}>
      <RouterProvider router={router}>
        <Outlet fallback={<p>Loading…</p>} />
      </RouterProvider>
    </RelayEnvironmentProvider>
  </HeadProvider>,
);
